import { Prisma, type PrismaClient } from "@prisma/client";
import type { AdminAnalyticsQuery, AdminAuditQuery, AdminBannerInput, AdminCampaignInput, AdminCategoryAttributesInput, AdminCategoryInput, AdminCategoryRequestReview, AdminCouponInput, AdminFlashSaleInput, AdminInventoryBulkUpdate, AdminInventoryUpdate, AdminKycReviewInput, AdminOrderAddressInput, AdminOrderCourierInput, AdminOrderReturnWindowInput, AdminOrderStatusOverride, AdminUserRolesInput, AdminUserStatusInput, AdminVendorStatusInput, AdminVoucherInput, PaymentVerificationReview, PlatformSettingsInput, Session, TrustCaseActionInput, UpdateAdminCampaign, UpdateAdminCoupon } from "@amiyo/contracts";
import { ApiProblem } from "../../middleware/api-problem.js";

function requireAdmin(session: Session, write = false) {
  const permission = write ? "admin:manage" : "admin:read";
  if (session.status !== "ACTIVE" || !session.permissions.includes(permission)) throw new ApiProblem(403, "ADMIN_ACCESS_REQUIRED", `${permission} access is required`);
}
function json(value: unknown) { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }
function mediaUrl(key: string | null) { if (!key) return null; if (/^https?:\/\//.test(key)) return key; const base = process.env.OBJECT_STORAGE_PUBLIC_URL?.replace(/\/$/, ""); return base ? `${base}/${key}` : null; }
function money(amountMinor: bigint, currency = "BDT") { return { amountMinor: amountMinor.toString(), currency }; }
function bannerStatus(active: boolean, startsAt: Date, endsAt: Date) { const now = new Date(); return !active ? "inactive" as const : startsAt > now ? "scheduled" as const : endsAt <= now ? "expired" as const : "active" as const; }
function couponStatus(active: boolean, startsAt: Date, endsAt: Date) { const now = new Date(); return !active ? "disabled" as const : startsAt > now ? "scheduled" as const : endsAt <= now ? "expired" as const : "active" as const; }
type CampaignMetadata = { description?: string; discountType?: "PERCENT" | "FIXED"; discountValue?: number; imageUrl?: string | null; showAsPopup?: boolean; priority?: number; couponCode?: string | null; buttonText?: string; buttonLink?: string };
function campaignMetadata(value: Prisma.JsonValue | null): CampaignMetadata { return value && typeof value === "object" && !Array.isArray(value) ? value as CampaignMetadata : {}; }
const auditModules = { finance: ["payout_request", "payment", "payment_verification", "commission_rule", "refund"], logistics: ["shipment", "delivery_dispatch", "delivery_settings", "logistics_assignment", "courier_partner"], products: ["product", "category", "inventory_item", "promotion", "campaign", "voucher", "flash_sale"], vendors: ["vendor", "vendor_member", "vendor_kyc_submission", "vendor_category_request", "vendor_order"] } as const;
function auditModule(resourceType: string) { return (Object.entries(auditModules).find(([, resources]) => (resources as readonly string[]).includes(resourceType))?.[0] ?? "platform"); }
function auditSeverity(action: string): "critical" | "warning" | "ok" { const value = action.toLowerCase(); if (["failed", "rejected", "deleted", "suspended", "cancelled", "anonymized"].some((token) => value.includes(token))) return "critical"; if (["refund", "override", "updated", "changed", "review", "retried", "moderated"].some((token) => value.includes(token))) return "warning"; return "ok"; }
function sensitiveAudit(resourceType: string, action: string) { return ["payout_request", "payment", "payment_verification", "commission_rule", "user", "role", "delivery_settings"].includes(resourceType) || /access|role|permission|kyc/.test(action.toLowerCase()); }
const defaultPlatformSettings = { featureFlags: { sellerRegistration: true, reviews: true, questions: true, flashSales: true, loyalty: true, voiceSearch: true, googleLogin: true }, paymentMethods: { cod: { enabled: true }, sslcommerz: { enabled: true }, bkashManual: { enabled: true } }, maintenanceMode: { enabled: false, message: "Amiyo-Go is being improved. Please try again shortly." }, returnPolicy: { windowDays: 7, restockingFeePercent: 0, requireEvidence: true }, tax: { enabled: false, rateBps: 0, pricesIncludeTax: true }, seo: { title: "Amiyo-Go Marketplace", description: "Shop trusted products from verified sellers across Bangladesh." }, notificationControls: { orderUpdates: true, promotions: true, sellerAlerts: true, adminAlerts: true } };
const assignableRoles = ["SUPPORT_AGENT", "FINANCE_ADMIN", "OPERATIONS_ADMIN", "SUPER_ADMIN"] as const;

export class AdminService {
  constructor(private readonly client: PrismaClient) {}
  async workspace(session: Session) {
    requireAdmin(session);
    const [users, vendors, kyc, trustCases] = await Promise.all([
      this.client.user.findMany({ include: { profile: true, roles: { include: { role: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
      this.client.vendor.findMany({ include: { _count: { select: { members: true, shops: true } }, kycSubmissions: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { createdAt: "desc" }, take: 100 }),
      this.client.vendorKycSubmission.findMany({ where: { status: { in: ["SUBMITTED", "REVIEWING"] } }, include: { vendor: true, documents: true }, orderBy: { createdAt: "asc" }, take: 100 }),
      this.client.trustCase.findMany({ include: { actions: { orderBy: { createdAt: "asc" } } }, orderBy: [{ severity: "desc" }, { createdAt: "asc" }], take: 100 })
    ]);
    return {
      users: users.map((user) => ({ id: user.id, email: user.normalizedEmail, phone: user.normalizedPhone, displayName: user.profile?.displayName ?? null, status: user.status, roles: user.roles.map(({ role }) => role.name), createdAt: user.createdAt.toISOString() })),
      vendors: vendors.map((vendor) => ({ id: vendor.id, legalName: vendor.legalName, displayName: vendor.displayName, status: vendor.status, version: vendor.version, memberCount: vendor._count.members, shopCount: vendor._count.shops, latestKycStatus: vendor.kycSubmissions[0]?.status ?? null, createdAt: vendor.createdAt.toISOString() })),
      kyc: kyc.map((submission) => ({ id: submission.id, vendorId: submission.vendorId, vendorName: submission.vendor.displayName, status: submission.status, submittedAt: submission.submittedAt?.toISOString() ?? null, rejectionReason: submission.rejectionReason, documents: submission.documents.map((document) => ({ id: document.id, documentType: document.documentType, storageKey: document.storageKey, mimeType: document.mimeType })) })),
      trustCases: trustCases.map((trustCase) => ({ id: trustCase.id, subjectType: trustCase.subjectType, subjectId: trustCase.subjectId, caseType: trustCase.caseType, severity: trustCase.severity, status: trustCase.status, assignedTo: trustCase.assignedTo, summary: trustCase.summary, createdAt: trustCase.createdAt.toISOString(), actions: trustCase.actions.map((action) => ({ id: action.id, actionType: action.actionType, actorUserId: action.actorUserId, reason: action.reason, createdAt: action.createdAt.toISOString() })) }))
    };
  }
  async customerDetail(session: Session, userId: string) {
    requireAdmin(session);
    const user = await this.client.user.findUnique({ where: { id: userId }, include: { profile: true, addresses: { orderBy: [{ isDefault: "desc" }, { createdAt: "desc" }] }, roles: { include: { role: true } }, orders: { include: { vendorOrders: { include: { vendor: true } }, payments: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { createdAt: "desc" }, take: 30 }, returnRequests: { orderBy: { createdAt: "desc" }, take: 20 }, supportTickets: { orderBy: { createdAt: "desc" }, take: 20 }, reviews: { include: { product: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 20 }, notifications: { orderBy: { createdAt: "desc" }, take: 20 } } });
    if (!user) throw new ApiProblem(404, "USER_NOT_FOUND", "Customer not found");
    return { id: user.id, email: user.normalizedEmail, phone: user.normalizedPhone, status: user.status, roles: user.roles.map(({ role }) => role.name), createdAt: user.createdAt.toISOString(), lastLoginAt: user.lastLoginAt?.toISOString() ?? null, profile: { firstName: user.profile?.firstName ?? null, lastName: user.profile?.lastName ?? null, displayName: user.profile?.displayName ?? null, locale: user.profile?.locale ?? "en", currency: user.profile?.currency ?? "BDT" }, addresses: user.addresses.map((address) => ({ id: address.id, label: address.label, recipientName: address.recipientName, phone: address.phone, line1: address.line1, line2: address.line2, division: address.division, district: address.district, upazila: address.upazila, unionName: address.unionName, postalCode: address.postalCode, isDefault: address.isDefault })), orders: user.orders.map((order) => ({ id: order.id, orderNumber: order.orderNumber, status: order.status, total: money(order.totalMinor, order.currency), vendors: order.vendorOrders.map((vendorOrder) => vendorOrder.vendor.displayName), paymentStatus: order.payments[0]?.status ?? null, createdAt: order.createdAt.toISOString() })), returns: user.returnRequests.map((item) => ({ id: item.id, orderId: item.orderId, status: item.status, reasonCode: item.reasonCode, requested: money(item.requestedMinor, item.currency), createdAt: item.createdAt.toISOString() })), support: user.supportTickets.map((ticket) => ({ id: ticket.id, subject: ticket.subject, category: ticket.category, priority: ticket.priority, status: ticket.status, createdAt: ticket.createdAt.toISOString() })), reviews: user.reviews.map((review) => ({ id: review.id, product: review.product.name, rating: review.rating, status: review.status, body: review.body, createdAt: review.createdAt.toISOString() })), notifications: user.notifications.map((notification) => ({ id: notification.id, title: notification.title, body: notification.body, readAt: notification.readAt?.toISOString() ?? null, createdAt: notification.createdAt.toISOString() })), summary: { orders: user.orders.length, spendMinor: user.orders.reduce((sum, order) => sum + order.totalMinor, 0n).toString(), returns: user.returnRequests.length, tickets: user.supportTickets.length, reviews: user.reviews.length } };
  }
  async updateUser(session: Session, userId: string, input: AdminUserStatusInput) {
    requireAdmin(session, true); if (userId === session.principal.userId) throw new ApiProblem(409, "SELF_STATUS_CHANGE_FORBIDDEN", "You cannot change your own account status");
    const before = await this.client.user.findUnique({ where: { id: userId } }); if (!before) throw new ApiProblem(404, "USER_NOT_FOUND", "User not found");
    await this.client.$transaction([this.client.user.update({ where: { id: userId }, data: { status: input.status } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.user.status_changed", resourceType: "user", resourceId: userId, before: json({ status: before.status }), after: json(input) } })]);
    return this.workspace(session);
  }
  async paymentVerifications(session: Session) {
    requireAdmin(session);
    const rows = await this.client.paymentVerification.findMany({ include: { payment: { include: { order: { include: { user: { include: { profile: true } } } } } } }, orderBy: [{ status: "asc" }, { createdAt: "asc" }], take: 150 });
    return rows.map((item) => ({ id: item.id, paymentId: item.paymentId, orderId: item.payment.orderId, orderNumber: item.payment.order.orderNumber, customer: item.payment.order.user?.profile?.displayName ?? item.payment.order.user?.normalizedEmail ?? "Guest customer", provider: item.payment.provider, method: item.payment.method, amount: money(item.payment.amountMinor, item.payment.currency), paymentStatus: item.payment.status, status: item.status, transactionRef: item.transactionRef, senderMasked: item.senderMasked, evidenceStorageKey: item.evidenceStorageKey, reviewedAt: item.reviewedAt?.toISOString() ?? null, createdAt: item.createdAt.toISOString() }));
  }
  async marketing(session: Session) {
    requireAdmin(session);
    const [vouchers, flashSales, products] = await Promise.all([
      this.client.voucher.findMany({ orderBy: { startsAt: "desc" }, take: 200 }),
      this.client.flashSale.findMany({ include: { products: { include: { product: { include: { variants: { where: { active: true }, orderBy: { createdAt: "asc" }, take: 1 } } } } } }, orderBy: { startsAt: "desc" }, take: 100 }),
      this.client.product.findMany({ where: { status: "APPROVED", variants: { some: { active: true } } }, include: { variants: { where: { active: true }, orderBy: { createdAt: "asc" }, take: 1 } }, orderBy: { name: "asc" }, take: 500 })
    ]);
    return {
      vouchers: vouchers.map((item) => ({ id: item.id, code: item.code, ownerType: item.ownerType, ownerId: item.ownerId, rules: item.rules, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), active: item.active, version: item.version })),
      flashSales: flashSales.map((item) => ({ id: item.id, name: item.name, status: item.status, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), version: item.version, products: item.products.map((entry) => ({ productId: entry.productId, productName: entry.product.name, regularPriceMinor: entry.product.variants[0]?.priceMinor.toString() ?? "0", priceMinor: entry.priceMinor.toString(), quantityLimit: entry.quantityLimit, soldCount: entry.soldCount })) })),
      products: products.map((item) => ({ id: item.id, name: item.name, slug: item.slug, priceMinor: item.variants[0]?.priceMinor.toString() ?? "0", currency: item.variants[0]?.currency ?? "BDT" }))
    };
  }
  async audit(session: Session, query: AdminAuditQuery) {
    requireAdmin(session);
    if (!session.permissions.includes("audit:read") && !session.permissions.includes("admin:manage")) throw new ApiProblem(403, "AUDIT_ACCESS_REQUIRED", "audit:read access is required");
    const actorMatches = query.search ? await this.client.user.findMany({ where: { OR: [{ normalizedEmail: { contains: query.search, mode: "insensitive" } }, { profile: { displayName: { contains: query.search, mode: "insensitive" } } }] }, select: { id: true }, take: 100 }) : [];
    const severityPatterns = query.severity === "critical" ? ["failed", "rejected", "deleted", "suspended", "cancelled", "anonymized"] : query.severity === "warning" ? ["refund", "override", "updated", "changed", "review", "retried", "moderated"] : [];
    const moduleResources = query.module !== "all" && query.module !== "platform" ? [...auditModules[query.module]] : null;
    const classifiedResources = Object.values(auditModules).flatMap((resources) => [...resources]);
    const where: Prisma.AuditLogWhereInput = { AND: [query.actorType === "all" ? {} : { actorType: query.actorType }, query.resourceType === "all" ? {} : { resourceType: query.resourceType }, moduleResources ? { resourceType: { in: moduleResources } } : query.module === "platform" ? { resourceType: { notIn: classifiedResources } } : {}, query.action ? { action: { contains: query.action, mode: "insensitive" } } : {}, query.from || query.to ? { createdAt: { ...(query.from ? { gte: query.from } : {}), ...(query.to ? { lte: new Date(query.to.getTime() + 86_399_999) } : {}) } } : {}, query.search ? { OR: [{ action: { contains: query.search, mode: "insensitive" } }, { resourceType: { contains: query.search, mode: "insensitive" } }, { resourceId: { contains: query.search, mode: "insensitive" } }, { correlationId: { contains: query.search, mode: "insensitive" } }, { actorUserId: { in: actorMatches.map((item) => item.id) } }] } : {}, severityPatterns.length ? { OR: severityPatterns.map((pattern) => ({ action: { contains: pattern, mode: "insensitive" as const } })) } : query.severity === "ok" ? { NOT: ["failed", "rejected", "deleted", "suspended", "cancelled", "anonymized", "refund", "override", "updated", "changed", "review", "retried", "moderated"].map((pattern) => ({ action: { contains: pattern, mode: "insensitive" as const } })) } : {}] };
    const [rows, total, grouped, actorFacets, resourceFacets] = await Promise.all([this.client.auditLog.findMany({ where, orderBy: { createdAt: "desc" }, skip: (query.page - 1) * query.limit, take: query.limit }), this.client.auditLog.count({ where }), this.client.auditLog.groupBy({ by: ["action", "resourceType"], where, _count: { _all: true } }), this.client.auditLog.groupBy({ by: ["actorType"], _count: { _all: true }, orderBy: { actorType: "asc" } }), this.client.auditLog.groupBy({ by: ["resourceType"], _count: { _all: true }, orderBy: { resourceType: "asc" } })]);
    const actorIds = [...new Set(rows.flatMap((item) => item.actorUserId ? [item.actorUserId] : []))];
    const actors = await this.client.user.findMany({ where: { id: { in: actorIds } }, include: { profile: true } }); const actorById = new Map(actors.map((actor) => [actor.id, actor]));
    const summary = grouped.reduce((result, item) => { const count = item._count._all; const severity = auditSeverity(item.action); return { total: result.total + count, critical: result.critical + (severity === "critical" ? count : 0), warning: result.warning + (severity === "warning" ? count : 0), sensitive: result.sensitive + (sensitiveAudit(item.resourceType, item.action) ? count : 0) }; }, { total: 0, critical: 0, warning: 0, sensitive: 0 });
    const totalPages = Math.max(1, Math.ceil(total / query.limit));
    return { logs: rows.map((item) => { const actor = item.actorUserId ? actorById.get(item.actorUserId) : null; return { id: item.id, actor: { id: item.actorUserId, type: item.actorType, email: actor?.normalizedEmail ?? null, name: actor?.profile?.displayName ?? null }, action: item.action, resource: { type: item.resourceType, id: item.resourceId }, module: auditModule(item.resourceType), severity: auditSeverity(item.action), correlationId: item.correlationId, ipHash: item.ipHash, before: item.before, after: item.after, metadata: item.metadata, createdAt: item.createdAt.toISOString() }; }), summary, pagination: { page: query.page, limit: query.limit, total, totalPages, hasPreviousPage: query.page > 1, hasNextPage: query.page < totalPages }, facets: { actorTypes: actorFacets.map((item) => item.actorType), resourceTypes: resourceFacets.map((item) => item.resourceType) } };
  }
  async settings(session: Session) {
    requireAdmin(session);
    const row = await this.client.platformConfiguration.upsert({ where: { key: "default" }, update: {}, create: { key: "default", featureFlags: json(defaultPlatformSettings.featureFlags), paymentMethods: json(defaultPlatformSettings.paymentMethods), maintenanceMode: json(defaultPlatformSettings.maintenanceMode), returnPolicy: json(defaultPlatformSettings.returnPolicy), tax: json(defaultPlatformSettings.tax), seo: json(defaultPlatformSettings.seo), notificationControls: json(defaultPlatformSettings.notificationControls), updatedBy: session.principal.userId } });
    const failedJobs = await this.client.outboxEvent.count({ where: { status: "failed" } });
    const paymentConfigured = Boolean(process.env.SSLCOMMERZ_STORE_ID && process.env.SSLCOMMERZ_STORE_PASSWORD);
    const storageConfigured = Boolean(process.env.OBJECT_STORAGE_PUBLIC_URL);
    const services = [{ key: "api", label: "API", status: "healthy" as const, detail: "Authenticated admin API is responding" }, { key: "database", label: "PostgreSQL", status: "healthy" as const, detail: "Configuration and queue queries succeeded" }, { key: "queue", label: "Outbox queue", status: failedJobs ? "degraded" as const : "healthy" as const, detail: failedJobs ? `${failedJobs} failed event(s) require review` : "No failed outbox events" }, { key: "payment", label: "SSLCommerz", status: paymentConfigured ? "healthy" as const : "degraded" as const, detail: paymentConfigured ? "Sandbox/merchant credentials configured" : "Merchant credentials are not configured" }, { key: "storage", label: "Object storage", status: storageConfigured ? "healthy" as const : "degraded" as const, detail: storageConfigured ? "Public media base URL configured" : "Public media base URL is not configured" }];
    return { key: row.key, featureFlags: row.featureFlags, paymentMethods: row.paymentMethods, maintenanceMode: row.maintenanceMode, returnPolicy: row.returnPolicy, tax: row.tax, seo: row.seo, notificationControls: row.notificationControls, version: row.version, updatedBy: row.updatedBy, updatedAt: row.updatedAt.toISOString(), health: { overall: services.some((service) => service.status === "degraded") ? "degraded" as const : "healthy" as const, checkedAt: new Date().toISOString(), environment: process.env.NODE_ENV || "development", services } };
  }
  async updateSettings(session: Session, input: PlatformSettingsInput) { requireAdmin(session, true); if (!session.permissions.includes("settings:manage")) throw new ApiProblem(403, "SETTINGS_ACCESS_REQUIRED", "settings:manage access is required"); const before = await this.client.platformConfiguration.upsert({ where: { key: "default" }, update: {}, create: { key: "default", featureFlags: json(defaultPlatformSettings.featureFlags), paymentMethods: json(defaultPlatformSettings.paymentMethods), maintenanceMode: json(defaultPlatformSettings.maintenanceMode), returnPolicy: json(defaultPlatformSettings.returnPolicy), tax: json(defaultPlatformSettings.tax), seo: json(defaultPlatformSettings.seo), notificationControls: json(defaultPlatformSettings.notificationControls), updatedBy: session.principal.userId } }); const changed = await this.client.platformConfiguration.updateMany({ where: { key: "default", version: input.expectedVersion }, data: { featureFlags: json(input.featureFlags), paymentMethods: json(input.paymentMethods), maintenanceMode: json(input.maintenanceMode), returnPolicy: json(input.returnPolicy), tax: json(input.tax), seo: json(input.seo), notificationControls: json(input.notificationControls), updatedBy: session.principal.userId, version: { increment: 1 } } }); if (!changed.count) throw new ApiProblem(409, "SETTINGS_VERSION_CONFLICT", "Platform settings changed; refresh and try again"); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "platform.settings.updated", resourceType: "platform_settings", resourceId: "default", before: json({ version: before.version, featureFlags: before.featureFlags, paymentMethods: before.paymentMethods, maintenanceMode: before.maintenanceMode }), after: json(input) } }); return this.settings(session); }
  async createVoucher(session: Session, input: AdminVoucherInput) { requireAdmin(session, true); const row = await this.client.voucher.create({ data: { code: input.code, ownerType: "platform", ownerId: "marketplace", rules: json({ discountType: input.discountType, value: input.value, minimumSpendMinor: input.minimumSpendMinor, usageLimit: input.usageLimit }), startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), active: input.active } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "voucher.created", resourceType: "voucher", resourceId: row.id, after: json(input) } }); return this.marketing(session); }
  async updateVoucher(session: Session, id: string, input: AdminVoucherInput) { requireAdmin(session, true); const before = await this.client.voucher.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "VOUCHER_NOT_FOUND", "Voucher not found"); await this.client.$transaction([this.client.voucher.update({ where: { id }, data: { code: input.code, rules: json({ discountType: input.discountType, value: input.value, minimumSpendMinor: input.minimumSpendMinor, usageLimit: input.usageLimit }), startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), active: input.active, version: { increment: 1 } } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "voucher.updated", resourceType: "voucher", resourceId: id, before: json(before), after: json(input) } })]); return this.marketing(session); }
  async deleteVoucher(session: Session, id: string) { requireAdmin(session, true); const before = await this.client.voucher.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "VOUCHER_NOT_FOUND", "Voucher not found"); await this.client.$transaction([this.client.voucher.delete({ where: { id } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "voucher.deleted", resourceType: "voucher", resourceId: id, before: json(before) } })]); return this.marketing(session); }
  private async validateFlashProducts(products: AdminFlashSaleInput["products"]) { const rows = await this.client.product.findMany({ where: { id: { in: products.map((item) => item.productId) }, status: "APPROVED" }, include: { variants: { where: { active: true }, orderBy: { createdAt: "asc" }, take: 1 } } }); if (rows.length !== products.length) throw new ApiProblem(400, "FLASH_SALE_PRODUCT_INVALID", "Every flash-sale product must be approved"); const priceById = new Map(rows.map((row) => [row.id, row.variants[0]?.priceMinor])); for (const item of products) { const regular = priceById.get(item.productId); if (!regular || BigInt(item.priceMinor) >= regular) throw new ApiProblem(400, "FLASH_PRICE_INVALID", "Flash price must be lower than the regular product price"); } }
  async createFlashSale(session: Session, input: AdminFlashSaleInput) { requireAdmin(session, true); await this.validateFlashProducts(input.products); const row = await this.client.flashSale.create({ data: { name: input.name, status: input.status, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), products: { create: input.products.map((product) => ({ productId: product.productId, priceMinor: BigInt(product.priceMinor), quantityLimit: product.quantityLimit })) } } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "flash_sale.created", resourceType: "flash_sale", resourceId: row.id, after: json(input) } }); return this.marketing(session); }
  async updateFlashSale(session: Session, id: string, input: AdminFlashSaleInput) { requireAdmin(session, true); await this.validateFlashProducts(input.products); const before = await this.client.flashSale.findUnique({ where: { id }, include: { products: true } }); if (!before) throw new ApiProblem(404, "FLASH_SALE_NOT_FOUND", "Flash sale not found"); const beforeSnapshot = { ...before, products: before.products.map((item) => ({ ...item, priceMinor: item.priceMinor.toString() })) }; const soldByProduct = new Map(before.products.map((item) => [item.productId, item.soldCount])); await this.client.$transaction(async (transaction) => { await transaction.flashSaleProduct.deleteMany({ where: { flashSaleId: id } }); await transaction.flashSale.update({ where: { id }, data: { name: input.name, status: input.status, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), version: { increment: 1 }, products: { create: input.products.map((product) => ({ productId: product.productId, priceMinor: BigInt(product.priceMinor), quantityLimit: product.quantityLimit, soldCount: soldByProduct.get(product.productId) ?? 0 })) } } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "flash_sale.updated", resourceType: "flash_sale", resourceId: id, before: json(beforeSnapshot), after: json(input) } }); }); return this.marketing(session); }
  async deleteFlashSale(session: Session, id: string) { requireAdmin(session, true); const before = await this.client.flashSale.findUnique({ where: { id }, include: { products: true } }); if (!before) throw new ApiProblem(404, "FLASH_SALE_NOT_FOUND", "Flash sale not found"); if (before.products.some((item) => item.soldCount > 0)) throw new ApiProblem(409, "FLASH_SALE_HAS_SALES", "A flash sale with completed sales cannot be deleted; pause it instead"); const beforeSnapshot = { ...before, products: before.products.map((item) => ({ ...item, priceMinor: item.priceMinor.toString() })) }; await this.client.$transaction([this.client.flashSale.delete({ where: { id } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "flash_sale.deleted", resourceType: "flash_sale", resourceId: id, before: json(beforeSnapshot) } })]); return this.marketing(session); }
  async updateUserRoles(session: Session, userId: string, input: AdminUserRolesInput) {
    requireAdmin(session, true);
    if (userId === session.principal.userId) throw new ApiProblem(409, "SELF_ROLE_CHANGE_FORBIDDEN", "You cannot change your own platform roles");
    const user = await this.client.user.findUnique({ where: { id: userId }, include: { roles: { include: { role: true } } } });
    if (!user) throw new ApiProblem(404, "USER_NOT_FOUND", "User not found");
    const before = user.roles.map(({ role }) => role.name);
    if (before.includes("SUPER_ADMIN") && !input.roles.includes("SUPER_ADMIN")) {
      const superAdminCount = await this.client.userRole.count({ where: { role: { name: "SUPER_ADMIN" }, user: { status: "ACTIVE" } } });
      if (superAdminCount <= 1) throw new ApiProblem(409, "LAST_SUPER_ADMIN_REQUIRED", "At least one active super admin must remain");
    }
    const roles = await this.client.role.findMany({ where: { name: { in: input.roles } } });
    if (roles.length !== input.roles.length) throw new ApiProblem(503, "ROLE_CONFIGURATION_INCOMPLETE", "One or more platform roles have not been seeded");
    await this.client.$transaction(async (transaction) => {
      await transaction.userRole.deleteMany({ where: { userId, role: { name: { in: [...assignableRoles] } } } });
      if (roles.length) await transaction.userRole.createMany({ data: roles.map((role) => ({ userId, roleId: role.id })) });
      await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.user.roles_changed", resourceType: "user", resourceId: userId, before: json({ roles: before }), after: json(input) } });
    });
    return this.workspace(session);
  }
  async updateVendor(session: Session, vendorId: string, input: AdminVendorStatusInput) {
    requireAdmin(session, true); const before = await this.client.vendor.findUnique({ where: { id: vendorId } }); if (!before) throw new ApiProblem(404, "VENDOR_NOT_FOUND", "Vendor not found");
    await this.client.$transaction([this.client.vendor.update({ where: { id: vendorId }, data: { status: input.status, approvedAt: input.status === "APPROVED" ? new Date() : before.approvedAt, version: { increment: 1 } } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.vendor.status_changed", resourceType: "vendor", resourceId: vendorId, before: json({ status: before.status }), after: json(input) } })]);
    return this.workspace(session);
  }
  async reviewKyc(session: Session, id: string, input: AdminKycReviewInput) {
    requireAdmin(session, true); const before = await this.client.vendorKycSubmission.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "KYC_NOT_FOUND", "KYC submission not found");
    if (!(["SUBMITTED", "REVIEWING"] as const).includes(before.status as "SUBMITTED" | "REVIEWING")) throw new ApiProblem(409, "KYC_NOT_REVIEWABLE", "KYC submission is no longer reviewable");
    await this.client.$transaction(async (transaction) => { await transaction.vendorKycSubmission.update({ where: { id }, data: { status: input.status, reviewedBy: session.principal.userId, reviewedAt: input.status === "REVIEWING" ? null : new Date(), rejectionReason: input.status === "REJECTED" ? input.reason ?? null : null } }); if (input.status === "APPROVED") await transaction.vendor.update({ where: { id: before.vendorId }, data: { status: "APPROVED", approvedAt: new Date(), version: { increment: 1 } } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.vendor_kyc.reviewed", resourceType: "vendor_kyc_submission", resourceId: id, before: json({ status: before.status }), after: json(input) } }); });
    return this.workspace(session);
  }
  async actOnTrustCase(session: Session, id: string, input: TrustCaseActionInput) {
    requireAdmin(session, true); const trustCase = await this.client.trustCase.findUnique({ where: { id } }); if (!trustCase) throw new ApiProblem(404, "TRUST_CASE_NOT_FOUND", "Trust case not found"); const status = input.action === "INVESTIGATE" ? "investigating" : input.action.toLowerCase();
    await this.client.$transaction([this.client.trustCase.update({ where: { id }, data: { status, assignedTo: trustCase.assignedTo ?? session.principal.userId, actions: { create: { actionType: input.action, actorUserId: session.principal.userId, reason: input.reason } } } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.trust_case.action", resourceType: "trust_case", resourceId: id, after: json(input) } })]);
    return this.workspace(session);
  }
  async commerce(session: Session) {
    requireAdmin(session);
    const [orders, inventory, coupons, campaigns, chats, codCollections, codReconciliations, vendorActivity] = await Promise.all([
      this.client.order.findMany({ include: { user: { include: { profile: true } }, vendorOrders: { include: { vendor: true, shop: true } }, payments: { orderBy: { createdAt: "desc" }, take: 1 }, _count: { select: { items: true } } }, orderBy: { createdAt: "desc" }, take: 200 }),
      this.client.inventoryItem.findMany({ include: { variant: { include: { product: { include: { vendor: true, shop: true } } } } }, orderBy: { updatedAt: "desc" }, take: 300 }),
      this.client.coupon.findMany({ include: { _count: { select: { redemptions: true } } }, orderBy: { startsAt: "desc" }, take: 100 }),
      this.client.campaign.findMany({ include: { _count: { select: { products: true, events: true } } }, orderBy: { startsAt: "desc" }, take: 100 }),
      this.client.chatThread.findMany({ include: { vendor: true, messages: { orderBy: { createdAt: "desc" }, take: 1 }, _count: { select: { participants: true, messages: true } } }, orderBy: { updatedAt: "desc" }, take: 100 }),
      this.client.codCollection.findMany({ include: { payment: { include: { order: true } } }, orderBy: { collectedAt: "desc" }, take: 100 }),
      this.client.codReconciliation.findMany({ include: { _count: { select: { items: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
      this.client.vendor.findMany({ include: { _count: { select: { products: true, vendorOrders: true, chatThreads: true, payoutRequests: true } }, vendorOrders: { select: { totalMinor: true, commissionMinor: true } } }, orderBy: { updatedAt: "desc" }, take: 100 })
    ]);
    return {
      orders: orders.map((item) => ({ id: item.id, orderNumber: item.orderNumber, customer: item.user?.profile?.displayName ?? item.user?.normalizedEmail ?? "Guest customer", status: item.status, totalMinor: item.totalMinor.toString(), currency: item.currency, itemCount: item._count.items, vendorCount: item.vendorOrders.length, vendorOrders: item.vendorOrders.map((vendorOrder) => ({ id: vendorOrder.id, vendorId: vendorOrder.vendorId, vendor: vendorOrder.vendor.displayName, shop: vendorOrder.shop.name, status: vendorOrder.status, version: vendorOrder.version })), paymentMethod: item.payments[0]?.method ?? null, paymentStatus: item.payments[0]?.status ?? null, createdAt: item.createdAt.toISOString() })),
      inventory: inventory.map((item) => ({ id: item.id, version: item.version, sku: item.variant.sku, variant: item.variant.title, product: item.variant.product.name, vendor: item.variant.product.vendor.displayName, shop: item.variant.product.shop.name, onHand: item.onHand, reserved: item.reserved, available: Math.max(0, item.onHand - item.reserved), reorderLevel: item.reorderLevel, updatedAt: item.updatedAt.toISOString() })),
      coupons: coupons.map((item) => ({ id: item.id, code: item.code, discountType: item.discountType, value: item.value, minimumSpendMinor: item.minimumSpendMinor.toString(), usageLimit: item.usageLimit, redemptions: item._count.redemptions, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), active: item.active, version: item.version })),
      campaigns: campaigns.map((item) => ({ id: item.id, name: item.name, slug: item.slug, status: item.status, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), productCount: item._count.products, eventCount: item._count.events, version: item.version })),
      chats: chats.map((item) => ({ id: item.id, vendorId: item.vendorId, vendor: item.vendor?.displayName ?? "Customer support", subject: item.subject ?? "Conversation", status: item.status, participants: item._count.participants, messageCount: item._count.messages, lastMessage: item.messages[0]?.body ?? null, updatedAt: item.updatedAt.toISOString() })),
      codCollections: codCollections.map((item) => ({ id: item.id, orderNumber: item.payment.order.orderNumber, expectedMinor: item.payment.amountMinor.toString(), collectedMinor: item.collectedMinor.toString(), currency: item.currency, collectorRef: item.collectorRef, collectedAt: item.collectedAt.toISOString() })),
      codReconciliations: codReconciliations.map((item) => ({ id: item.id, periodStart: item.periodStart.toISOString(), periodEnd: item.periodEnd.toISOString(), expectedMinor: item.expectedMinor.toString(), receivedMinor: item.receivedMinor.toString(), currency: item.currency, status: item.status, itemCount: item._count.items, createdAt: item.createdAt.toISOString() })),
      vendorActivity: vendorActivity.map((item) => ({ id: item.id, vendor: item.displayName, status: item.status, products: item._count.products, orders: item._count.vendorOrders, chats: item._count.chatThreads, payoutRequests: item._count.payoutRequests, gmvMinor: item.vendorOrders.reduce((sum, row) => sum + row.totalMinor, 0n).toString(), commissionMinor: item.vendorOrders.reduce((sum, row) => sum + row.commissionMinor, 0n).toString(), updatedAt: item.updatedAt.toISOString() }))
    };
  }
  async coupons(session: Session) { requireAdmin(session); const rows = await this.client.coupon.findMany({ include: { redemptions: { select: { amountMinor: true } }, _count: { select: { redemptions: true } } }, orderBy: { startsAt: "desc" }, take: 250 }); return rows.map((item) => ({ id: item.id, code: item.code, discountType: item.discountType as "PERCENT" | "FIXED", value: item.value, maxDiscountMinor: item.maxDiscountMinor?.toString() ?? null, minimumSpendMinor: item.minimumSpendMinor.toString(), currency: item.currency, usageLimit: item.usageLimit, perUserLimit: item.perUserLimit, redemptions: item._count.redemptions, redeemedMinor: item.redemptions.reduce((sum, redemption) => sum + redemption.amountMinor, 0n).toString(), startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), active: item.active, status: couponStatus(item.active, item.startsAt, item.endsAt), version: item.version })); }
  async campaigns(session: Session) { requireAdmin(session); const [campaigns, products, coupons] = await Promise.all([this.client.campaign.findMany({ include: { products: { include: { product: { select: { id: true, name: true, slug: true, media: { orderBy: { displayOrder: "asc" }, take: 1 }, variants: { select: { priceMinor: true }, orderBy: { priceMinor: "asc" }, take: 1 } } } }, orderBy: { displayOrder: "asc" } }, _count: { select: { events: true } } }, orderBy: [{ startsAt: "desc" }, { name: "asc" }], take: 250 }), this.client.product.findMany({ where: { status: "APPROVED" }, select: { id: true, name: true, slug: true, media: { orderBy: { displayOrder: "asc" }, take: 1 }, variants: { select: { priceMinor: true }, orderBy: { priceMinor: "asc" }, take: 1 } }, orderBy: { name: "asc" }, take: 500 }), this.client.coupon.findMany({ select: { code: true, active: true }, orderBy: { code: "asc" }, take: 250 })]); const productDto = (product: typeof products[number]) => ({ id: product.id, name: product.name, slug: product.slug, priceMinor: (product.variants[0]?.priceMinor ?? 0n).toString(), imageUrl: mediaUrl(product.media[0]?.storageKey ?? null) }); return { campaigns: campaigns.map((item) => { const metadata = campaignMetadata(item.metadata); return { id: item.id, name: item.name, slug: item.slug, description: metadata.description ?? "Marketplace promotional campaign", discountType: metadata.discountType ?? "PERCENT" as const, discountValue: metadata.discountValue ?? 1, imageUrl: metadata.imageUrl ?? null, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), status: (["draft", "active", "paused"] as const).find((status) => status === item.status) ?? "paused", showAsPopup: metadata.showAsPopup ?? false, priority: metadata.priority ?? 0, couponCode: metadata.couponCode ?? null, buttonText: metadata.buttonText ?? "Shop now", buttonLink: metadata.buttonLink ?? `/campaign/${item.slug}`, products: item.products.map((row) => ({ ...productDto(row.product), displayOrder: row.displayOrder })), eventCount: item._count.events, version: item.version }; }), products: products.map(productDto), coupons }; }
  async chats(session: Session) { requireAdmin(session); const rows = await this.client.chatThread.findMany({ include: { vendor: true, participants: { where: { userId: session.principal.userId }, take: 1 }, messages: { include: { sender: { include: { profile: true } } }, orderBy: { createdAt: "desc" }, take: 1 }, _count: { select: { messages: true } } }, orderBy: { updatedAt: "desc" }, take: 250 }); const threads = await Promise.all(rows.map(async (item) => { const admin = item.participants[0]; const unreadCount = await this.client.chatMessage.count({ where: { threadId: item.id, senderId: { not: session.principal.userId }, createdAt: { gt: admin?.lastReadAt ?? admin?.joinedAt ?? item.createdAt } } }); const message = item.messages[0]; return { id: item.id, vendorId: item.vendorId, vendorName: item.vendor?.displayName ?? "Marketplace conversation", vendorStatus: item.vendor?.status ?? null, subject: item.subject ?? "Seller support", status: item.status, unreadCount, messageCount: item._count.messages, lastMessage: message ? { body: message.body, senderId: message.senderId, senderName: message.sender.profile?.displayName ?? message.sender.normalizedEmail ?? "User", createdAt: message.createdAt.toISOString() } : null, updatedAt: item.updatedAt.toISOString() }; })); return { threads, summary: { total: threads.length, unread: threads.filter((item) => item.unreadCount > 0).length, open: threads.filter((item) => item.status === "open").length } }; }
  async chatDetail(session: Session, id: string) { requireAdmin(session); const thread = await this.client.chatThread.findUnique({ where: { id }, include: { vendor: true, participants: { include: { user: { include: { profile: true } } }, orderBy: { joinedAt: "asc" } }, messages: { include: { sender: { include: { profile: true } } }, orderBy: { createdAt: "asc" }, take: 500 } } }); if (!thread) throw new ApiProblem(404, "CHAT_THREAD_NOT_FOUND", "Chat thread not found"); const roles = new Map(thread.participants.map((item) => [item.userId, item.role])); return { id: thread.id, vendorId: thread.vendorId, vendorName: thread.vendor?.displayName ?? "Marketplace conversation", vendorStatus: thread.vendor?.status ?? null, subject: thread.subject ?? "Seller support", status: thread.status, participants: thread.participants.map((item) => ({ userId: item.userId, role: item.role, displayName: item.user.profile?.displayName ?? item.user.normalizedEmail ?? "User" })), messages: thread.messages.map((item) => ({ id: item.id, senderId: item.senderId, senderName: item.sender.profile?.displayName ?? item.sender.normalizedEmail ?? "User", senderRole: roles.get(item.senderId) ?? (item.senderId === session.principal.userId ? "admin" : "participant"), body: item.body, attachments: item.attachments ?? null, createdAt: item.createdAt.toISOString() })), createdAt: thread.createdAt.toISOString(), updatedAt: thread.updatedAt.toISOString() }; }
  async orderDetail(session: Session, id: string) {
    requireAdmin(session);
    const order = await this.client.order.findUnique({ where: { id }, include: { user: { include: { profile: true } }, addresses: true, payments: { orderBy: { createdAt: "desc" }, take: 1 }, invoice: true, statusEvents: { orderBy: { createdAt: "asc" } }, vendorOrders: { include: { vendor: true, shop: true, items: true, shipments: { orderBy: { createdAt: "desc" }, take: 1 } } } } });
    if (!order) throw new ApiProblem(404, "ORDER_NOT_FOUND", "Order not found");
    const payment = order.payments[0];
    const deliveryAddress = order.addresses.find((address) => address.type === "delivery") ?? null;
    return {
      id: order.id, orderNumber: order.orderNumber, status: order.status, version: order.version, createdAt: order.createdAt.toISOString(), placedAt: order.placedAt?.toISOString() ?? null, returnWindowUntil: order.returnWindowUntil?.toISOString() ?? null,
      customer: { id: order.userId, displayName: order.user?.profile?.displayName ?? order.user?.normalizedEmail ?? "Guest customer", email: order.user?.normalizedEmail ?? null, phone: order.user?.normalizedPhone ?? null },
      deliveryAddress: deliveryAddress ? { recipientName: deliveryAddress.recipientName, phone: deliveryAddress.phone, line1: deliveryAddress.line1, line2: deliveryAddress.line2, division: deliveryAddress.division, district: deliveryAddress.district, upazila: deliveryAddress.upazila, unionName: deliveryAddress.unionName, postalCode: deliveryAddress.postalCode } : null,
      payment: payment ? { id: payment.id, provider: payment.provider, method: payment.method, status: payment.status, amount: money(payment.amountMinor, payment.currency), refunded: money(payment.refundedMinor, payment.currency), transactionId: payment.providerTransactionId, createdAt: payment.createdAt.toISOString() } : null,
      invoice: order.invoice ? { id: order.invoice.id, number: order.invoice.number, issuedAt: order.invoice.issuedAt.toISOString(), storageUrl: mediaUrl(order.invoice.storageKey) } : null,
      subtotal: money(order.subtotalMinor, order.currency), discount: money(order.discountMinor, order.currency), delivery: money(order.deliveryMinor, order.currency), tax: money(order.taxMinor, order.currency), total: money(order.totalMinor, order.currency),
      events: order.statusEvents.map((event) => ({ id: event.id, fromStatus: event.fromStatus, toStatus: event.toStatus, actorType: event.actorType, reason: event.reason, createdAt: event.createdAt.toISOString() })),
      vendorOrders: order.vendorOrders.map((vendorOrder) => ({ id: vendorOrder.id, vendorId: vendorOrder.vendorId, vendorName: vendorOrder.vendor.displayName, shopName: vendorOrder.shop.name, status: vendorOrder.status, version: vendorOrder.version, subtotal: money(vendorOrder.subtotalMinor, order.currency), discount: money(vendorOrder.discountMinor, order.currency), delivery: money(vendorOrder.deliveryMinor, order.currency), total: money(vendorOrder.totalMinor, order.currency), commission: money(vendorOrder.commissionMinor, order.currency), shipment: vendorOrder.shipments[0] ? { status: vendorOrder.shipments[0].status, provider: vendorOrder.shipments[0].provider, trackingNumber: vendorOrder.shipments[0].trackingNumber } : null, items: vendorOrder.items.map((item) => ({ id: item.id, productName: item.productNameSnapshot, sku: item.skuSnapshot, quantity: item.quantity, unitPrice: money(item.unitPriceMinor, item.currency), lineTotal: money(item.lineTotalMinor, item.currency) })) }))
    };
  }
  async overrideOrderStatus(session: Session, id: string, input: AdminOrderStatusOverride) { requireAdmin(session, true); const before = await this.client.order.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "ORDER_NOT_FOUND", "Order not found"); await this.client.$transaction(async (transaction) => { const changed = await transaction.order.updateMany({ where: { id, version: input.expectedVersion }, data: { status: input.status, version: { increment: 1 } } }); if (!changed.count) throw new ApiProblem(409, "ORDER_VERSION_CONFLICT", "Order changed; refresh and try again"); await transaction.orderStatusEvent.create({ data: { orderId: id, fromStatus: before.status, toStatus: input.status, actorType: "admin", actorId: session.principal.userId, reason: input.reason, metadata: json({ override: true }) } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "order.status_overridden", resourceType: "order", resourceId: id, before: json({ status: before.status, version: before.version }), after: json(input) } }); }); return this.orderDetail(session, id); }
  async correctOrderAddress(session: Session, id: string, input: AdminOrderAddressInput) { requireAdmin(session, true); const before = await this.client.orderAddress.findUnique({ where: { orderId_type: { orderId: id, type: "delivery" } } }); if (!before) throw new ApiProblem(404, "ORDER_ADDRESS_NOT_FOUND", "Delivery address not found"); const { reason, ...address } = input; await this.client.$transaction([this.client.orderAddress.update({ where: { orderId_type: { orderId: id, type: "delivery" } }, data: address }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "order.delivery_address_corrected", resourceType: "order", resourceId: id, before: json(before), after: json({ ...address, reason }) } })]); return this.orderDetail(session, id); }
  async reassignOrderCourier(session: Session, id: string, input: AdminOrderCourierInput) { requireAdmin(session, true); const vendorOrder = await this.client.vendorOrder.findFirst({ where: { id: input.vendorOrderId, orderId: id }, include: { shipments: { take: 1 } } }); if (!vendorOrder) throw new ApiProblem(404, "VENDOR_ORDER_NOT_FOUND", "Seller fulfillment not found"); await this.client.$transaction(async (transaction) => { const changed = await transaction.vendorOrder.updateMany({ where: { id: input.vendorOrderId, version: input.expectedVersion }, data: { version: { increment: 1 } } }); if (!changed.count) throw new ApiProblem(409, "VENDOR_ORDER_VERSION_CONFLICT", "Seller fulfillment changed; refresh and try again"); const occurredAt = new Date(); await transaction.shipment.upsert({ where: { vendorOrderId: input.vendorOrderId }, create: { vendorOrderId: input.vendorOrderId, provider: input.provider, trackingNumber: input.trackingNumber, events: { create: { status: "PENDING", description: input.reason, occurredAt } } }, update: { provider: input.provider, trackingNumber: input.trackingNumber, events: { create: { status: vendorOrder.shipments[0]?.status ?? "PENDING", description: input.reason, occurredAt } } } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "order.courier_reassigned", resourceType: "order", resourceId: id, before: json({ provider: vendorOrder.shipments[0]?.provider, trackingNumber: vendorOrder.shipments[0]?.trackingNumber }), after: json(input) } }); }); return this.orderDetail(session, id); }
  async extendOrderReturnWindow(session: Session, id: string, input: AdminOrderReturnWindowInput) { requireAdmin(session, true); const before = await this.client.order.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "ORDER_NOT_FOUND", "Order not found"); await this.client.$transaction(async (transaction) => { const changed = await transaction.order.updateMany({ where: { id, version: input.expectedVersion }, data: { returnWindowUntil: new Date(input.returnWindowUntil), version: { increment: 1 } } }); if (!changed.count) throw new ApiProblem(409, "ORDER_VERSION_CONFLICT", "Order changed; refresh and try again"); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "order.return_window_extended", resourceType: "order", resourceId: id, before: json({ returnWindowUntil: before.returnWindowUntil, version: before.version }), after: json(input) } }); }); return this.orderDetail(session, id); }
  async inventory(session: Session) {
    requireAdmin(session);
    const items = await this.client.inventoryItem.findMany({ include: { variant: { include: { product: { include: { vendor: true, shop: true } } } }, movements: { orderBy: { createdAt: "desc" }, take: 8 } }, orderBy: { updatedAt: "desc" }, take: 500 });
    const movementRows = await this.client.inventoryMovement.findMany({ include: { inventory: { include: { variant: { include: { product: true } } } } }, orderBy: { createdAt: "desc" }, take: 250 });
    const movement = (item: typeof movementRows[number] | typeof items[number]["movements"][number]) => { const metadata = item.metadata && typeof item.metadata === "object" && !Array.isArray(item.metadata) ? item.metadata as Record<string, unknown> : {}; return { id: item.id, inventoryId: item.inventoryId, type: item.type, quantity: item.quantity, referenceType: item.referenceType, referenceId: item.referenceId, reason: typeof metadata.reason === "string" ? metadata.reason : null, createdAt: item.createdAt.toISOString() }; };
    const mapped = items.map((item) => { const available = Math.max(0, item.onHand - item.reserved); const status = item.onHand === 0 ? "out_of_stock" as const : available <= item.reorderLevel ? "low_stock" as const : "in_stock" as const; return { id: item.id, version: item.version, productId: item.variant.productId, product: item.variant.product.name, productStatus: item.variant.product.status, sku: item.variant.sku, variant: item.variant.title, vendor: item.variant.product.vendor.displayName, shop: item.variant.product.shop.name, priceMinor: item.variant.priceMinor.toString(), currency: item.variant.currency, onHand: item.onHand, reserved: item.reserved, available, reorderLevel: item.reorderLevel, stockValueMinor: (item.variant.priceMinor * BigInt(item.onHand)).toString(), status, updatedAt: item.updatedAt.toISOString(), movements: item.movements.map(movement) }; });
    return { items: mapped, movements: movementRows.map((item) => ({ ...movement(item), product: item.inventory.variant.product.name, sku: item.inventory.variant.sku })), summary: { totalVariants: mapped.length, inStock: mapped.filter((item) => item.status === "in_stock").length, lowStock: mapped.filter((item) => item.status === "low_stock").length, outOfStock: mapped.filter((item) => item.status === "out_of_stock").length, stockUnits: mapped.reduce((sum, item) => sum + item.onHand, 0), reservedUnits: mapped.reduce((sum, item) => sum + item.reserved, 0), valueMinor: mapped.reduce((sum, item) => sum + BigInt(item.stockValueMinor), 0n).toString(), currency: "BDT" } };
  }
  async updateInventory(session: Session, id: string, input: AdminInventoryUpdate) {
    requireAdmin(session, true);
    await this.client.$transaction(async (transaction) => { const before = await transaction.inventoryItem.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "INVENTORY_NOT_FOUND", "Inventory item not found"); if (input.onHand < before.reserved) throw new ApiProblem(400, "INVENTORY_BELOW_RESERVED", `On-hand stock cannot be lower than ${before.reserved} reserved units`); const updated = await transaction.inventoryItem.updateMany({ where: { id, version: input.expectedVersion }, data: { onHand: input.onHand, reorderLevel: input.reorderLevel, version: { increment: 1 } } }); if (!updated.count) throw new ApiProblem(409, "INVENTORY_VERSION_CONFLICT", "Inventory changed; refresh and try again"); const quantity = input.onHand - before.onHand; if (quantity !== 0) await transaction.inventoryMovement.create({ data: { inventoryId: id, type: "ADJUSTMENT", quantity, referenceType: "admin", referenceId: session.principal.userId, idempotencyKey: `admin-adjust:${id}:${input.expectedVersion}`, metadata: json({ reason: input.reason, previousOnHand: before.onHand, reorderLevel: input.reorderLevel }) } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "inventory.admin_adjusted", resourceType: "inventory_item", resourceId: id, before: json({ onHand: before.onHand, reorderLevel: before.reorderLevel, version: before.version }), after: json(input) } }); });
    return this.inventory(session);
  }
  async bulkUpdateInventory(session: Session, input: AdminInventoryBulkUpdate) {
    requireAdmin(session, true);
    await this.client.$transaction(async (transaction) => { const current = await transaction.inventoryItem.findMany({ where: { id: { in: input.items.map((item) => item.id) } } }); if (current.length !== input.items.length) throw new ApiProblem(404, "INVENTORY_NOT_FOUND", "One or more inventory items were not found"); const byId = new Map(current.map((item) => [item.id, item])); for (const change of input.items) { const before = byId.get(change.id)!; if (change.onHand < before.reserved) throw new ApiProblem(400, "INVENTORY_BELOW_RESERVED", `${change.id} cannot be lower than ${before.reserved} reserved units`); const updated = await transaction.inventoryItem.updateMany({ where: { id: change.id, version: change.expectedVersion }, data: { onHand: change.onHand, reorderLevel: change.reorderLevel, version: { increment: 1 } } }); if (!updated.count) throw new ApiProblem(409, "INVENTORY_VERSION_CONFLICT", "Inventory changed; refresh and try again"); const quantity = change.onHand - before.onHand; if (quantity !== 0) await transaction.inventoryMovement.create({ data: { inventoryId: change.id, type: "ADJUSTMENT", quantity, referenceType: "admin_bulk", referenceId: session.principal.userId, idempotencyKey: `admin-bulk:${change.id}:${change.expectedVersion}`, metadata: json({ reason: input.reason, previousOnHand: before.onHand, reorderLevel: change.reorderLevel }) } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "inventory.admin_bulk_adjusted", resourceType: "inventory_item", resourceId: change.id, before: json({ onHand: before.onHand, reorderLevel: before.reorderLevel, version: before.version }), after: json({ ...change, reason: input.reason }) } }); } });
    return this.inventory(session);
  }
  async toggleCoupon(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.coupon.update({ where: { id }, data: { active, version: { increment: 1 } } }); await this.auditToggle(session, "coupon", id, active); return this.commerce(session); }
  async createCoupon(session: Session, input: AdminCouponInput) { requireAdmin(session, true); const row = await this.client.coupon.create({ data: { code: input.code, discountType: input.discountType, value: input.value, maxDiscountMinor: input.maxDiscountMinor === null ? null : BigInt(input.maxDiscountMinor), minimumSpendMinor: BigInt(input.minimumSpendMinor), usageLimit: input.usageLimit, perUserLimit: input.perUserLimit, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), active: input.active } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "coupon.created", resourceType: "coupon", resourceId: row.id, after: json(input) } }); return this.coupons(session); }
  async updateCoupon(session: Session, id: string, input: UpdateAdminCoupon) { requireAdmin(session, true); const before = await this.client.coupon.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "COUPON_NOT_FOUND", "Coupon not found"); const changed = await this.client.coupon.updateMany({ where: { id, version: input.expectedVersion }, data: { code: input.code, discountType: input.discountType, value: input.value, maxDiscountMinor: input.maxDiscountMinor === null ? null : BigInt(input.maxDiscountMinor), minimumSpendMinor: BigInt(input.minimumSpendMinor), usageLimit: input.usageLimit, perUserLimit: input.perUserLimit, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), active: input.active, version: { increment: 1 } } }); if (!changed.count) throw new ApiProblem(409, "COUPON_VERSION_CONFLICT", "Coupon changed; refresh and try again"); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "coupon.updated", resourceType: "coupon", resourceId: id, before: json({ code: before.code, version: before.version, active: before.active }), after: json(input) } }); return this.coupons(session); }
  async deleteCoupon(session: Session, id: string) { requireAdmin(session, true); const before = await this.client.coupon.findUnique({ where: { id }, include: { _count: { select: { redemptions: true } } } }); if (!before) throw new ApiProblem(404, "COUPON_NOT_FOUND", "Coupon not found"); if (before._count.redemptions) throw new ApiProblem(409, "COUPON_HAS_REDEMPTIONS", "Redeemed coupons cannot be deleted; disable this coupon instead"); await this.client.$transaction([this.client.coupon.delete({ where: { id } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "coupon.deleted", resourceType: "coupon", resourceId: id, before: json({ code: before.code, version: before.version }) } })]); return this.coupons(session); }
  async validateCampaignProducts(productIds: string[]) { if (!productIds.length) return; const count = await this.client.product.count({ where: { id: { in: productIds }, status: "APPROVED" } }); if (count !== productIds.length) throw new ApiProblem(400, "INVALID_CAMPAIGN_PRODUCTS", "Every campaign product must exist and be published"); }
  campaignData(input: AdminCampaignInput | UpdateAdminCampaign) { return { name: input.name, slug: input.slug, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), status: input.status, metadata: json({ description: input.description, discountType: input.discountType, discountValue: input.discountValue, imageUrl: input.imageUrl, showAsPopup: input.showAsPopup, priority: input.priority, couponCode: input.couponCode, buttonText: input.buttonText, buttonLink: input.buttonLink }) }; }
  async createCampaign(session: Session, input: AdminCampaignInput) { requireAdmin(session, true); await this.validateCampaignProducts(input.productIds); const row = await this.client.campaign.create({ data: { ...this.campaignData(input), products: { create: input.productIds.map((productId, displayOrder) => ({ productId, displayOrder })) } } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "campaign.created", resourceType: "campaign", resourceId: row.id, after: json(input) } }); return this.campaigns(session); }
  async updateCampaign(session: Session, id: string, input: UpdateAdminCampaign) { requireAdmin(session, true); await this.validateCampaignProducts(input.productIds); const before = await this.client.campaign.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "CAMPAIGN_NOT_FOUND", "Campaign not found"); await this.client.$transaction(async (transaction) => { const changed = await transaction.campaign.updateMany({ where: { id, version: input.expectedVersion }, data: { ...this.campaignData(input), version: { increment: 1 } } }); if (!changed.count) throw new ApiProblem(409, "CAMPAIGN_VERSION_CONFLICT", "Campaign changed; refresh and try again"); await transaction.campaignProduct.deleteMany({ where: { campaignId: id } }); if (input.productIds.length) await transaction.campaignProduct.createMany({ data: input.productIds.map((productId, displayOrder) => ({ campaignId: id, productId, displayOrder })) }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "campaign.updated", resourceType: "campaign", resourceId: id, before: json({ name: before.name, status: before.status, version: before.version }), after: json(input) } }); }); return this.campaigns(session); }
  async toggleCampaign(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.campaign.update({ where: { id }, data: { status: active ? "active" : "paused", version: { increment: 1 } } }); await this.auditToggle(session, "campaign", id, active); return this.commerce(session); }
  async deleteCampaign(session: Session, id: string) { requireAdmin(session, true); const before = await this.client.campaign.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "CAMPAIGN_NOT_FOUND", "Campaign not found"); await this.client.$transaction([this.client.campaign.delete({ where: { id } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "campaign.deleted", resourceType: "campaign", resourceId: id, before: json({ name: before.name, slug: before.slug, version: before.version }) } })]); return this.campaigns(session); }
  async sendAdminChat(session: Session, id: string, body: string) {
    requireAdmin(session, true); const thread = await this.client.chatThread.findUnique({ where: { id } }); if (!thread) throw new ApiProblem(404, "CHAT_THREAD_NOT_FOUND", "Chat thread not found");
    await this.client.$transaction([this.client.chatParticipant.upsert({ where: { threadId_userId: { threadId: id, userId: session.principal.userId } }, create: { threadId: id, userId: session.principal.userId, role: "admin", lastReadAt: new Date() }, update: { lastReadAt: new Date() } }), this.client.chatMessage.create({ data: { threadId: id, senderId: session.principal.userId, body } }), this.client.chatThread.update({ where: { id }, data: { updatedAt: new Date() } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "chat.admin_message_sent", resourceType: "chat_thread", resourceId: id, after: json({ bodyLength: body.length }) } })]); return this.chatDetail(session, id);
  }
  async readAdminChat(session: Session, id: string) { requireAdmin(session, true); const thread = await this.client.chatThread.findUnique({ where: { id }, select: { id: true } }); if (!thread) throw new ApiProblem(404, "CHAT_THREAD_NOT_FOUND", "Chat thread not found"); await this.client.chatParticipant.upsert({ where: { threadId_userId: { threadId: id, userId: session.principal.userId } }, create: { threadId: id, userId: session.principal.userId, role: "admin", lastReadAt: new Date() }, update: { lastReadAt: new Date() } }); return this.chatDetail(session, id); }
  async platform(session: Session) {
    requireAdmin(session);
    const [paymentVerifications, categories, banners, vouchers, flashSales, audit] = await Promise.all([this.client.paymentVerification.findMany({ include: { payment: { include: { order: true } } }, orderBy: { createdAt: "asc" }, take: 100 }), this.client.category.findMany({ include: { attributes: { include: { options: { orderBy: { displayOrder: "asc" } } }, orderBy: { displayOrder: "asc" } }, _count: { select: { products: true } } }, orderBy: { displayOrder: "asc" }, take: 200 }), this.client.banner.findMany({ orderBy: [{ placement: "asc" }, { displayOrder: "asc" }], take: 100 }), this.client.voucher.findMany({ orderBy: { startsAt: "desc" }, take: 100 }), this.client.flashSale.findMany({ include: { _count: { select: { products: true } } }, orderBy: { startsAt: "desc" }, take: 100 }), this.client.auditLog.findMany({ orderBy: { createdAt: "desc" }, take: 100 })]);
    return { paymentVerifications: paymentVerifications.map((item) => ({ id: item.id, paymentId: item.paymentId, orderId: item.payment.orderId, orderNumber: item.payment.order.orderNumber, provider: item.payment.provider, amountMinor: item.payment.amountMinor.toString(), currency: item.payment.currency, status: item.status, transactionRef: item.transactionRef, senderMasked: item.senderMasked, evidenceStorageKey: item.evidenceStorageKey, createdAt: item.createdAt.toISOString() })), categories: categories.map((item) => ({ id: item.id, parentId: item.parentId, name: item.name, slug: item.slug, status: item.status, displayOrder: item.displayOrder, productCount: item._count.products, attributes: item.attributes.map((attribute) => ({ ...attribute, options: attribute.options })) })), banners: banners.map((item) => ({ ...item, imageUrl: mediaUrl(item.storageKey), mobileImageUrl: mediaUrl(item.mobileStorageKey), startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), status: bannerStatus(item.active, item.startsAt, item.endsAt) })), vouchers: vouchers.map((item) => ({ id: item.id, code: item.code, ownerType: item.ownerType, active: item.active, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString() })), flashSales: flashSales.map((item) => ({ id: item.id, name: item.name, status: item.status, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), productCount: item._count.products })), audit: audit.map((item) => ({ id: item.id, actorType: item.actorType, action: item.action, resourceType: item.resourceType, resourceId: item.resourceId, createdAt: item.createdAt.toISOString() })) };
  }
  async reviewPayment(session: Session, id: string, input: PaymentVerificationReview) { requireAdmin(session, true); const current = await this.client.paymentVerification.findUnique({ where: { id }, include: { payment: true } }); if (!current) throw new ApiProblem(404, "PAYMENT_VERIFICATION_NOT_FOUND", "Payment verification not found"); if (current.status !== "pending") throw new ApiProblem(409, "PAYMENT_VERIFICATION_REVIEWED", "Payment verification has already been reviewed"); await this.client.$transaction(async (transaction) => { await transaction.paymentVerification.update({ where: { id }, data: { status: input.status, reviewedBy: session.principal.userId, reviewedAt: new Date() } }); if (input.status === "approved") { await transaction.payment.update({ where: { id: current.paymentId }, data: { status: "CAPTURED", version: { increment: 1 } } }); await transaction.order.update({ where: { id: current.payment.orderId }, data: { status: "CONFIRMED", version: { increment: 1 } } }); } await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "payment.verification.reviewed", resourceType: "payment_verification", resourceId: id, after: json(input) } }); }); return this.platform(session); }
  async createCategory(session: Session, input: AdminCategoryInput) { requireAdmin(session, true); if (input.parentId && !(await this.client.category.findUnique({ where: { id: input.parentId } }))) throw new ApiProblem(404, "PARENT_CATEGORY_NOT_FOUND", "Parent category not found"); const row = await this.client.category.create({ data: { parentId: input.parentId ?? null, name: input.name, slug: input.slug, description: input.description ?? null, displayOrder: input.displayOrder } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "catalog.category.created", resourceType: "category", resourceId: row.id, after: json(input) } }); return this.platform(session); }
  async updateCategory(session: Session, id: string, input: { status?: "active" | "inactive" | undefined; displayOrder?: number | undefined }) {
    requireAdmin(session, true); const before = await this.client.category.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "CATEGORY_NOT_FOUND", "Category not found");
    const changes = { ...(input.status === undefined ? {} : { status: input.status }), ...(input.displayOrder === undefined ? {} : { displayOrder: input.displayOrder }), version: { increment: 1 } };
    await this.client.$transaction([this.client.category.update({ where: { id }, data: changes }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "catalog.category.updated", resourceType: "category", resourceId: id, before: json({ status: before.status, displayOrder: before.displayOrder }), after: json(input) } })]); return this.platform(session);
  }
  async analytics(session: Session, input: AdminAnalyticsQuery) {
    requireAdmin(session); const days = input.range === "7d" ? 7 : input.range === "90d" ? 90 : 30; const endsAt = new Date(); const startsAt = new Date(endsAt.getTime() - days * 86_400_000); const activeOrderWhere = { createdAt: { gte: startsAt, lte: endsAt }, status: { not: "CANCELLED" as const } };
    const [totalCustomers, newCustomers, orderAggregate, customers, productGroups, vendorGroups, trend] = await Promise.all([
      this.client.user.count(), this.client.user.count({ where: { createdAt: { gte: startsAt, lte: endsAt } } }), this.client.order.aggregate({ where: activeOrderWhere, _count: { _all: true }, _sum: { totalMinor: true } }),
      this.client.order.groupBy({ by: ["userId"], where: { ...activeOrderWhere, userId: { not: null } }, _count: { _all: true }, _sum: { totalMinor: true } }),
      this.client.orderItem.groupBy({ by: ["productId"], where: { order: activeOrderWhere }, _sum: { quantity: true, lineTotalMinor: true }, orderBy: { _sum: { lineTotalMinor: "desc" } }, take: 5 }),
      this.client.vendorOrder.groupBy({ by: ["vendorId"], where: { order: activeOrderWhere }, _count: { _all: true }, _sum: { totalMinor: true }, orderBy: { _sum: { totalMinor: "desc" } }, take: 5 }),
      this.client.$queryRaw<Array<{ date: Date; orders: bigint; revenue: bigint }>>(Prisma.sql`SELECT DATE_TRUNC('day', created_at) AS date, COUNT(*)::bigint AS orders, COALESCE(SUM(total_minor), 0)::bigint AS revenue FROM orders WHERE created_at >= ${startsAt} AND created_at <= ${endsAt} AND status <> 'CANCELLED' GROUP BY 1 ORDER BY 1 ASC`)
    ]);
    const [products, vendors] = await Promise.all([this.client.product.findMany({ where: { id: { in: productGroups.map((item) => item.productId) } }, select: { id: true, name: true } }), this.client.vendor.findMany({ where: { id: { in: vendorGroups.map((item) => item.vendorId) } }, select: { id: true, displayName: true } })]); const productNames = new Map(products.map((item) => [item.id, item.name])); const vendorNames = new Map(vendors.map((item) => [item.id, item.displayName])); type SegmentKey = "new" | "regular" | "vip"; type SegmentAccumulator = { key: SegmentKey; customers: number; orders: number; revenue: bigint }; const segmentMap = new Map<SegmentKey, SegmentAccumulator>(["new", "regular", "vip"].map((key) => [key as SegmentKey, { key: key as SegmentKey, customers: 0, orders: 0, revenue: 0n }])); for (const customer of customers) { const key: SegmentKey = customer._count._all >= 5 ? "vip" : customer._count._all >= 2 ? "regular" : "new"; const segment = segmentMap.get(key)!; segment.customers += 1; segment.orders += customer._count._all; segment.revenue += customer._sum.totalMinor ?? 0n; } const gmv = orderAggregate._sum.totalMinor ?? 0n; const orderCount = orderAggregate._count._all; const repeatCustomers = customers.filter((customer) => customer._count._all > 1).length; const amount = (amountMinor: bigint) => ({ amountMinor: amountMinor.toString(), currency: "BDT" as const });
    return { range: { key: input.range, startsAt: startsAt.toISOString(), endsAt: endsAt.toISOString() }, summary: { totalCustomers, newCustomers, purchasingCustomers: customers.length, orders: orderCount, gmv: amount(gmv), averageOrderValue: amount(orderCount ? gmv / BigInt(orderCount) : 0n), repeatPurchaseRate: customers.length ? Math.round((repeatCustomers / customers.length) * 1000) / 10 : 0 }, trend: trend.map((item) => ({ date: item.date.toISOString().slice(0, 10), orders: Number(item.orders), revenue: amount(item.revenue) })), segments: [...segmentMap.values()].map((item) => ({ ...item, revenue: amount(item.revenue) })), topProducts: productGroups.map((item) => ({ id: item.productId, name: productNames.get(item.productId) ?? "Unknown product", quantity: item._sum.quantity ?? 0, revenue: amount(item._sum.lineTotalMinor ?? 0n) })), topVendors: vendorGroups.map((item) => ({ id: item.vendorId, name: vendorNames.get(item.vendorId) ?? "Unknown vendor", orders: item._count._all, revenue: amount(item._sum.totalMinor ?? 0n) })) };
  }
  async replaceCategoryAttributes(session: Session, categoryId: string, input: AdminCategoryAttributesInput) { requireAdmin(session, true); const category = await this.client.category.findUnique({ where: { id: categoryId }, include: { attributes: { include: { options: true } } } }); if (!category) throw new ApiProblem(404, "CATEGORY_NOT_FOUND", "Category not found"); await this.client.$transaction(async (transaction) => { await transaction.categoryAttribute.deleteMany({ where: { categoryId } }); for (const attribute of input.attributes) await transaction.categoryAttribute.create({ data: { categoryId, key: attribute.key, label: attribute.label, dataType: attribute.dataType, required: attribute.required, filterable: attribute.filterable, displayOrder: attribute.displayOrder, options: { create: attribute.options.map((option, displayOrder) => ({ value: option.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), label: option, displayOrder })) } } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "catalog.category_attributes.replaced", resourceType: "category", resourceId: categoryId, before: json(category.attributes), after: json(input.attributes) } }); }); return this.platform(session); }
  async createBanner(session: Session, input: AdminBannerInput) { requireAdmin(session, true); const row = await this.client.banner.create({ data: { ...input, subtitle: input.subtitle ?? null, mobileStorageKey: input.mobileStorageKey ?? null, ctaLabel: input.ctaLabel ?? null, badgeText: input.badgeText ?? null, targetType: input.targetType ?? null, targetValue: input.targetValue ?? null, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt) } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "banner.created", resourceType: "banner", resourceId: row.id, after: json(input) } }); return this.platform(session); }
  async updateBanner(session: Session, id: string, input: AdminBannerInput) { requireAdmin(session, true); const before = await this.client.banner.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "BANNER_NOT_FOUND", "Banner not found"); await this.client.$transaction([this.client.banner.update({ where: { id }, data: { ...input, subtitle: input.subtitle ?? null, mobileStorageKey: input.mobileStorageKey ?? null, ctaLabel: input.ctaLabel ?? null, badgeText: input.badgeText ?? null, targetType: input.targetType ?? null, targetValue: input.targetValue ?? null, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt) } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "banner.updated", resourceType: "banner", resourceId: id, before: json(before), after: json(input) } })]); return this.platform(session); }
  async deleteBanner(session: Session, id: string) { requireAdmin(session, true); const before = await this.client.banner.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "BANNER_NOT_FOUND", "Banner not found"); await this.client.$transaction([this.client.banner.delete({ where: { id } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "banner.deleted", resourceType: "banner", resourceId: id, before: json(before) } })]); return this.platform(session); }
  async toggleBanner(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.banner.update({ where: { id }, data: { active } }); await this.auditToggle(session, "banner", id, active); return this.platform(session); }
  async toggleVoucher(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.voucher.update({ where: { id }, data: { active, version: { increment: 1 } } }); await this.auditToggle(session, "voucher", id, active); return this.platform(session); }
  async toggleFlashSale(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.flashSale.update({ where: { id }, data: { status: active ? "active" : "paused", version: { increment: 1 } } }); await this.auditToggle(session, "flash_sale", id, active); return this.platform(session); }
  async categoryRequests(session: Session) { requireAdmin(session); const rows = await this.client.vendorCategoryRequest.findMany({ include: { vendor: true, category: { include: { parent: true } } }, orderBy: { createdAt: "asc" }, take: 100 }); return rows.map((item) => ({ id: item.id, vendorId: item.vendorId, vendorName: item.vendor.displayName, categoryId: item.categoryId, categoryName: item.category.name, categoryPath: item.category.parent ? `${item.category.parent.name} > ${item.category.name}` : item.category.name, status: item.status, reason: item.reason, description: item.description, reviewReason: item.reviewReason, reviewedAt: item.reviewedAt?.toISOString() ?? null, createdAt: item.createdAt.toISOString() })); }
  async reviewCategoryRequest(session: Session, id: string, input: AdminCategoryRequestReview) { requireAdmin(session, true); const current = await this.client.vendorCategoryRequest.findUnique({ where: { id } }); if (!current) throw new ApiProblem(404, "CATEGORY_REQUEST_NOT_FOUND", "Category request not found"); if (current.status !== "pending") throw new ApiProblem(409, "CATEGORY_REQUEST_REVIEWED", "Category request has already been reviewed"); await this.client.$transaction([this.client.vendorCategoryRequest.update({ where: { id }, data: { status: input.status, reviewReason: input.reason, reviewedBy: session.principal.userId, reviewedAt: new Date() } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: `vendor.category_request.${input.status}`, resourceType: "vendor_category_request", resourceId: id, before: json({ status: current.status }), after: json(input) } })]); return this.categoryRequests(session); }
  private async auditToggle(session: Session, resourceType: string, resourceId: string, active: boolean) { await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: `${resourceType}.toggled`, resourceType, resourceId, after: json({ active }) } }); }
}
