import { adminAnalyticsQuerySchema, adminAuditQuerySchema, adminBannerInputSchema, adminCategoryAttributesInputSchema, adminCategoryInputSchema, adminCategoryRequestReviewSchema, adminFlashSaleInputSchema, adminKycReviewInputSchema, adminToggleInputSchema, adminUserRolesInputSchema, adminUserStatusInputSchema, adminVendorStatusInputSchema, adminVoucherInputSchema, commissionRuleInputSchema, endCommissionRuleSchema, paymentVerificationReviewSchema, platformSettingsInputSchema, trustCaseActionInputSchema, updateCommissionRuleSchema } from "@amiyo/contracts";
import { Router } from "express";
import { rateLimit } from "express-rate-limit";
import { z } from "zod";
import { prisma } from "../../infrastructure/database/prisma.js";
import { FirebaseTokenVerifier } from "../identity/firebase-token.verifier.js";
import { createAuthenticationMiddleware, requireSession } from "../identity/identity.middleware.js";
import { IdentityService } from "../identity/identity.service.js";
import { CommissionService } from "../finance/commission.service.js";
import { AdminSearchService, type AdminSearchType } from "./admin-search.service.js";
import { AdminService } from "./admin.service.js";

const idSchema = z.object({ id: z.string().uuid() });
const inventoryInputSchema = z.object({ expectedVersion: z.number().int().positive(), onHand: z.number().int().nonnegative(), reorderLevel: z.number().int().nonnegative() });
const adminChatInputSchema = z.object({ body: z.string().trim().min(1).max(4000) });
const couponInputSchema = z.object({ code: z.string().trim().min(3).max(40).transform((value) => value.toUpperCase()), discountType: z.enum(["PERCENT", "FIXED"]), value: z.number().int().positive(), minimumSpendMinor: z.string().regex(/^\d+$/).default("0"), usageLimit: z.number().int().positive().nullable().default(null), startsAt: z.string().datetime(), endsAt: z.string().datetime() }).refine((value) => value.startsAt < value.endsAt, "startsAt must precede endsAt");
const campaignInputSchema = z.object({ name: z.string().trim().min(3).max(120), slug: z.string().trim().min(3).max(120).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), startsAt: z.string().datetime(), endsAt: z.string().datetime() }).refine((value) => value.startsAt < value.endsAt, "startsAt must precede endsAt");
const categoryControlSchema = z.object({ status: z.enum(["active", "inactive"]).optional(), displayOrder: z.number().int().nonnegative().optional() }).refine((value) => value.status !== undefined || value.displayOrder !== undefined, "A category change is required");
const adminSearchTypeSchema = z.enum(["order", "vendor", "product", "customer", "return", "support"]);

export function createAdminRouter() {
  const router = Router();
  const service = new AdminService(prisma);
  const search = new AdminSearchService(prisma);
  const commissions = new CommissionService(prisma);
  const authenticate = createAuthenticationMiddleware(new FirebaseTokenVerifier(), new IdentityService(prisma));
  const writes = rateLimit({ windowMs: 60_000, limit: 30, standardHeaders: "draft-7", legacyHeaders: false, message: { title: "Too many admin requests", status: 429, code: "ADMIN_RATE_LIMITED" } });
  router.use("/api/v2/admin/workspace", authenticate);
  router.get("/api/v2/admin/workspace/search", async (req, res, next) => { try {
    const query = z.string().trim().max(200).catch("").parse(req.query.q);
    const typesValue = z.string().optional().parse(req.query.types);
    const requestedTypes = typesValue ? typesValue.split(",").map((type) => adminSearchTypeSchema.parse(type)) as AdminSearchType[] : undefined;
    const limit = z.coerce.number().int().min(1).max(10).catch(5).parse(req.query.limit);
    const totalLimit = z.coerce.number().int().min(1).max(50).catch(24).parse(req.query.totalLimit);
    res.json(await search.search(requireSession(req), query, requestedTypes, limit, totalLimit));
  } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/search/:type/:id", async (req, res, next) => { try {
    const type = adminSearchTypeSchema.parse(req.params.type);
    const id = idSchema.parse(req.params).id;
    res.json(await search.detail(requireSession(req), type, id));
  } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace", async (req, res, next) => { try { res.json(await service.workspace(requireSession(req))); } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/customers/:id", async (req, res, next) => { try { res.json(await service.customerDetail(requireSession(req), idSchema.parse(req.params).id)); } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/payment-verifications", async (req, res, next) => { try { res.json(await service.paymentVerifications(requireSession(req))); } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/marketing", async (req, res, next) => { try { res.json(await service.marketing(requireSession(req))); } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/audit", async (req, res, next) => { try { res.json(await service.audit(requireSession(req), adminAuditQuerySchema.parse(req.query))); } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/settings", async (req, res, next) => { try { res.json(await service.settings(requireSession(req))); } catch (error) { next(error); } });
  router.put("/api/v2/admin/workspace/settings", writes, async (req, res, next) => { try { res.json(await service.updateSettings(requireSession(req), platformSettingsInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/commerce", async (req, res, next) => { try { res.json(await service.commerce(requireSession(req))); } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/orders/:id", async (req, res, next) => { try { res.json(await service.orderDetail(requireSession(req), idSchema.parse(req.params).id)); } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/commission-rules", async (req, res, next) => { try { res.json(await commissions.list(requireSession(req))); } catch (error) { next(error); } });
  router.post("/api/v2/admin/workspace/commission-rules", writes, async (req, res, next) => { try { res.status(201).json(await commissions.create(requireSession(req), commissionRuleInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.put("/api/v2/admin/workspace/commission-rules/:id", writes, async (req, res, next) => { try { res.json(await commissions.update(requireSession(req), idSchema.parse(req.params).id, updateCommissionRuleSchema.parse(req.body))); } catch (error) { next(error); } });
  router.delete("/api/v2/admin/workspace/commission-rules/:id", writes, async (req, res, next) => { try { res.json(await commissions.end(requireSession(req), idSchema.parse(req.params).id, endCommissionRuleSchema.parse(req.body).expectedVersion)); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/inventory/:id", writes, async (req, res, next) => { try { res.json(await service.updateInventory(requireSession(req), idSchema.parse(req.params).id, inventoryInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/coupons/:id", writes, async (req, res, next) => { try { res.json(await service.toggleCoupon(requireSession(req), idSchema.parse(req.params).id, adminToggleInputSchema.parse(req.body).active)); } catch (error) { next(error); } });
  router.post("/api/v2/admin/workspace/coupons", writes, async (req, res, next) => { try { res.status(201).json(await service.createCoupon(requireSession(req), couponInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.post("/api/v2/admin/workspace/campaigns", writes, async (req, res, next) => { try { res.status(201).json(await service.createCampaign(requireSession(req), campaignInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.put("/api/v2/admin/workspace/campaigns/:id", writes, async (req, res, next) => { try { res.json(await service.updateCampaign(requireSession(req), idSchema.parse(req.params).id, campaignInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/campaigns/:id", writes, async (req, res, next) => { try { res.json(await service.toggleCampaign(requireSession(req), idSchema.parse(req.params).id, adminToggleInputSchema.parse(req.body).active)); } catch (error) { next(error); } });
  router.post("/api/v2/admin/workspace/chats/:id/messages", writes, async (req, res, next) => { try { res.json(await service.sendAdminChat(requireSession(req), idSchema.parse(req.params).id, adminChatInputSchema.parse(req.body).body)); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/users/:id/status", writes, async (req, res, next) => { try { res.json(await service.updateUser(requireSession(req), idSchema.parse(req.params).id, adminUserStatusInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.put("/api/v2/admin/workspace/users/:id/roles", writes, async (req, res, next) => { try { res.json(await service.updateUserRoles(requireSession(req), idSchema.parse(req.params).id, adminUserRolesInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/vendors/:id/status", writes, async (req, res, next) => { try { res.json(await service.updateVendor(requireSession(req), idSchema.parse(req.params).id, adminVendorStatusInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/kyc/:id", writes, async (req, res, next) => { try { res.json(await service.reviewKyc(requireSession(req), idSchema.parse(req.params).id, adminKycReviewInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.post("/api/v2/admin/workspace/trust-cases/:id/actions", writes, async (req, res, next) => { try { res.json(await service.actOnTrustCase(requireSession(req), idSchema.parse(req.params).id, trustCaseActionInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/platform", async (req, res, next) => { try { res.json(await service.platform(requireSession(req))); } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/analytics", async (req, res, next) => { try { res.json(await service.analytics(requireSession(req), adminAnalyticsQuerySchema.parse(req.query))); } catch (error) { next(error); } });
  router.get("/api/v2/admin/workspace/category-requests", async (req, res, next) => { try { res.json(await service.categoryRequests(requireSession(req))); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/category-requests/:id", writes, async (req, res, next) => { try { res.json(await service.reviewCategoryRequest(requireSession(req), idSchema.parse(req.params).id, adminCategoryRequestReviewSchema.parse(req.body))); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/payment-verifications/:id", writes, async (req, res, next) => { try { res.json(await service.reviewPayment(requireSession(req), idSchema.parse(req.params).id, paymentVerificationReviewSchema.parse(req.body))); } catch (error) { next(error); } });
  router.post("/api/v2/admin/workspace/categories", writes, async (req, res, next) => { try { res.status(201).json(await service.createCategory(requireSession(req), adminCategoryInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/categories/:id", writes, async (req, res, next) => { try { res.json(await service.updateCategory(requireSession(req), idSchema.parse(req.params).id, categoryControlSchema.parse(req.body))); } catch (error) { next(error); } });
  router.put("/api/v2/admin/workspace/categories/:id/attributes", writes, async (req, res, next) => { try { res.json(await service.replaceCategoryAttributes(requireSession(req), idSchema.parse(req.params).id, adminCategoryAttributesInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.post("/api/v2/admin/workspace/banners", writes, async (req, res, next) => { try { res.status(201).json(await service.createBanner(requireSession(req), adminBannerInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.put("/api/v2/admin/workspace/banners/:id", writes, async (req, res, next) => { try { res.json(await service.updateBanner(requireSession(req), idSchema.parse(req.params).id, adminBannerInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.delete("/api/v2/admin/workspace/banners/:id", writes, async (req, res, next) => { try { res.json(await service.deleteBanner(requireSession(req), idSchema.parse(req.params).id)); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/banners/:id", writes, async (req, res, next) => { try { res.json(await service.toggleBanner(requireSession(req), idSchema.parse(req.params).id, adminToggleInputSchema.parse(req.body).active)); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/vouchers/:id", writes, async (req, res, next) => { try { res.json(await service.toggleVoucher(requireSession(req), idSchema.parse(req.params).id, adminToggleInputSchema.parse(req.body).active)); } catch (error) { next(error); } });
  router.patch("/api/v2/admin/workspace/flash-sales/:id", writes, async (req, res, next) => { try { res.json(await service.toggleFlashSale(requireSession(req), idSchema.parse(req.params).id, adminToggleInputSchema.parse(req.body).active)); } catch (error) { next(error); } });
  router.post("/api/v2/admin/workspace/vouchers", writes, async (req, res, next) => { try { res.status(201).json(await service.createVoucher(requireSession(req), adminVoucherInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.put("/api/v2/admin/workspace/vouchers/:id", writes, async (req, res, next) => { try { res.json(await service.updateVoucher(requireSession(req), idSchema.parse(req.params).id, adminVoucherInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.delete("/api/v2/admin/workspace/vouchers/:id", writes, async (req, res, next) => { try { res.json(await service.deleteVoucher(requireSession(req), idSchema.parse(req.params).id)); } catch (error) { next(error); } });
  router.post("/api/v2/admin/workspace/flash-sales", writes, async (req, res, next) => { try { res.status(201).json(await service.createFlashSale(requireSession(req), adminFlashSaleInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.put("/api/v2/admin/workspace/flash-sales/:id", writes, async (req, res, next) => { try { res.json(await service.updateFlashSale(requireSession(req), idSchema.parse(req.params).id, adminFlashSaleInputSchema.parse(req.body))); } catch (error) { next(error); } });
  router.delete("/api/v2/admin/workspace/flash-sales/:id", writes, async (req, res, next) => { try { res.json(await service.deleteFlashSale(requireSession(req), idSchema.parse(req.params).id)); } catch (error) { next(error); } });
  return router;
}
