import { Prisma, type PrismaClient } from "@prisma/client";
import type { AdminCategoryInput, AdminKycReviewInput, AdminUserStatusInput, AdminVendorStatusInput, PaymentVerificationReview, Session, TrustCaseActionInput } from "@amiyo/contracts";
import { ApiProblem } from "../../middleware/api-problem.js";

function requireAdmin(session: Session, write = false) {
  const permission = write ? "admin:manage" : "admin:read";
  if (session.status !== "ACTIVE" || !session.permissions.includes(permission)) throw new ApiProblem(403, "ADMIN_ACCESS_REQUIRED", `${permission} access is required`);
}
function json(value: unknown) { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }

export class AdminService {
  constructor(private readonly client: PrismaClient) {}
  async workspace(session: Session) {
    requireAdmin(session);
    const [users, vendors, kyc, trustCases] = await Promise.all([
      this.client.user.findMany({ include: { profile: true, roles: { include: { role: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
      this.client.vendor.findMany({ include: { _count: { select: { members: true, shops: true } }, kycSubmissions: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { createdAt: "desc" }, take: 100 }),
      this.client.vendorKycSubmission.findMany({ where: { status: { in: ["SUBMITTED", "REVIEWING"] } }, include: { vendor: true, documents: true }, orderBy: { createdAt: "asc" }, take: 100 }),
      this.client.trustCase.findMany({ include: { actions: { orderBy: { createdAt: "asc" } } }, orderBy: [{ severity: "desc" }, { createdAt: "asc" }], take: 100 })
    ]);
    return {
      users: users.map((user) => ({ id: user.id, email: user.normalizedEmail, phone: user.normalizedPhone, displayName: user.profile?.displayName ?? null, status: user.status, roles: user.roles.map(({ role }) => role.name), createdAt: user.createdAt.toISOString() })),
      vendors: vendors.map((vendor) => ({ id: vendor.id, legalName: vendor.legalName, displayName: vendor.displayName, status: vendor.status, version: vendor.version, memberCount: vendor._count.members, shopCount: vendor._count.shops, latestKycStatus: vendor.kycSubmissions[0]?.status ?? null, createdAt: vendor.createdAt.toISOString() })),
      kyc: kyc.map((submission) => ({ id: submission.id, vendorId: submission.vendorId, vendorName: submission.vendor.displayName, status: submission.status, submittedAt: submission.submittedAt?.toISOString() ?? null, rejectionReason: submission.rejectionReason, documents: submission.documents.map((document) => ({ id: document.id, documentType: document.documentType, storageKey: document.storageKey, mimeType: document.mimeType })) })),
      trustCases: trustCases.map((trustCase) => ({ id: trustCase.id, subjectType: trustCase.subjectType, subjectId: trustCase.subjectId, caseType: trustCase.caseType, severity: trustCase.severity, status: trustCase.status, assignedTo: trustCase.assignedTo, summary: trustCase.summary, createdAt: trustCase.createdAt.toISOString(), actions: trustCase.actions.map((action) => ({ id: action.id, actionType: action.actionType, actorUserId: action.actorUserId, reason: action.reason, createdAt: action.createdAt.toISOString() })) }))
    };
  }
  async updateUser(session: Session, userId: string, input: AdminUserStatusInput) {
    requireAdmin(session, true); if (userId === session.principal.userId) throw new ApiProblem(409, "SELF_STATUS_CHANGE_FORBIDDEN", "You cannot change your own account status");
    const before = await this.client.user.findUnique({ where: { id: userId } }); if (!before) throw new ApiProblem(404, "USER_NOT_FOUND", "User not found");
    await this.client.$transaction([this.client.user.update({ where: { id: userId }, data: { status: input.status } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.user.status_changed", resourceType: "user", resourceId: userId, before: json({ status: before.status }), after: json(input) } })]);
    return this.workspace(session);
  }
  async updateVendor(session: Session, vendorId: string, input: AdminVendorStatusInput) {
    requireAdmin(session, true); const before = await this.client.vendor.findUnique({ where: { id: vendorId } }); if (!before) throw new ApiProblem(404, "VENDOR_NOT_FOUND", "Vendor not found");
    await this.client.$transaction([this.client.vendor.update({ where: { id: vendorId }, data: { status: input.status, approvedAt: input.status === "APPROVED" ? new Date() : before.approvedAt, version: { increment: 1 } } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.vendor.status_changed", resourceType: "vendor", resourceId: vendorId, before: json({ status: before.status }), after: json(input) } })]);
    return this.workspace(session);
  }
  async reviewKyc(session: Session, id: string, input: AdminKycReviewInput) {
    requireAdmin(session, true); const before = await this.client.vendorKycSubmission.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "KYC_NOT_FOUND", "KYC submission not found");
    if (!(["SUBMITTED", "REVIEWING"] as const).includes(before.status as "SUBMITTED" | "REVIEWING")) throw new ApiProblem(409, "KYC_NOT_REVIEWABLE", "KYC submission is no longer reviewable");
    await this.client.$transaction(async (transaction) => { await transaction.vendorKycSubmission.update({ where: { id }, data: { status: input.status, reviewedBy: session.principal.userId, reviewedAt: input.status === "REVIEWING" ? null : new Date(), rejectionReason: input.status === "REJECTED" ? input.reason ?? null : null } }); if (input.status === "APPROVED") await transaction.vendor.update({ where: { id: before.vendorId }, data: { status: "APPROVED", approvedAt: new Date(), version: { increment: 1 } } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.vendor_kyc.reviewed", resourceType: "vendor_kyc_submission", resourceId: id, before: json({ status: before.status }), after: json(input) } }); });
    return this.workspace(session);
  }
  async actOnTrustCase(session: Session, id: string, input: TrustCaseActionInput) {
    requireAdmin(session, true); const trustCase = await this.client.trustCase.findUnique({ where: { id } }); if (!trustCase) throw new ApiProblem(404, "TRUST_CASE_NOT_FOUND", "Trust case not found"); const status = input.action === "INVESTIGATE" ? "investigating" : input.action.toLowerCase();
    await this.client.$transaction([this.client.trustCase.update({ where: { id }, data: { status, assignedTo: trustCase.assignedTo ?? session.principal.userId, actions: { create: { actionType: input.action, actorUserId: session.principal.userId, reason: input.reason } } } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.trust_case.action", resourceType: "trust_case", resourceId: id, after: json(input) } })]);
    return this.workspace(session);
  }
  async platform(session: Session) {
    requireAdmin(session);
    const [paymentVerifications, categories, banners, vouchers, flashSales, audit] = await Promise.all([this.client.paymentVerification.findMany({ include: { payment: { include: { order: true } } }, orderBy: { createdAt: "asc" }, take: 100 }), this.client.category.findMany({ include: { _count: { select: { products: true } } }, orderBy: { displayOrder: "asc" }, take: 200 }), this.client.banner.findMany({ orderBy: [{ placement: "asc" }, { displayOrder: "asc" }], take: 100 }), this.client.voucher.findMany({ orderBy: { startsAt: "desc" }, take: 100 }), this.client.flashSale.findMany({ include: { _count: { select: { products: true } } }, orderBy: { startsAt: "desc" }, take: 100 }), this.client.auditLog.findMany({ orderBy: { createdAt: "desc" }, take: 100 })]);
    return { paymentVerifications: paymentVerifications.map((item) => ({ id: item.id, paymentId: item.paymentId, orderId: item.payment.orderId, orderNumber: item.payment.order.orderNumber, provider: item.payment.provider, amountMinor: item.payment.amountMinor.toString(), currency: item.payment.currency, status: item.status, transactionRef: item.transactionRef, senderMasked: item.senderMasked, evidenceStorageKey: item.evidenceStorageKey, createdAt: item.createdAt.toISOString() })), categories: categories.map((item) => ({ id: item.id, name: item.name, slug: item.slug, status: item.status, displayOrder: item.displayOrder, productCount: item._count.products })), banners: banners.map((item) => ({ id: item.id, title: item.title, placement: item.placement, active: item.active, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString() })), vouchers: vouchers.map((item) => ({ id: item.id, code: item.code, ownerType: item.ownerType, active: item.active, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString() })), flashSales: flashSales.map((item) => ({ id: item.id, name: item.name, status: item.status, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), productCount: item._count.products })), audit: audit.map((item) => ({ id: item.id, actorType: item.actorType, action: item.action, resourceType: item.resourceType, resourceId: item.resourceId, createdAt: item.createdAt.toISOString() })) };
  }
  async reviewPayment(session: Session, id: string, input: PaymentVerificationReview) { requireAdmin(session, true); const current = await this.client.paymentVerification.findUnique({ where: { id }, include: { payment: true } }); if (!current) throw new ApiProblem(404, "PAYMENT_VERIFICATION_NOT_FOUND", "Payment verification not found"); if (current.status !== "pending") throw new ApiProblem(409, "PAYMENT_VERIFICATION_REVIEWED", "Payment verification has already been reviewed"); await this.client.$transaction(async (transaction) => { await transaction.paymentVerification.update({ where: { id }, data: { status: input.status, reviewedBy: session.principal.userId, reviewedAt: new Date() } }); if (input.status === "approved") { await transaction.payment.update({ where: { id: current.paymentId }, data: { status: "CAPTURED", version: { increment: 1 } } }); await transaction.order.update({ where: { id: current.payment.orderId }, data: { status: "CONFIRMED", version: { increment: 1 } } }); } await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "payment.verification.reviewed", resourceType: "payment_verification", resourceId: id, after: json(input) } }); }); return this.platform(session); }
  async createCategory(session: Session, input: AdminCategoryInput) { requireAdmin(session, true); const row = await this.client.category.create({ data: { name: input.name, slug: input.slug, description: input.description ?? null, displayOrder: input.displayOrder } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "catalog.category.created", resourceType: "category", resourceId: row.id, after: json(input) } }); return this.platform(session); }
  async toggleBanner(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.banner.update({ where: { id }, data: { active } }); await this.auditToggle(session, "banner", id, active); return this.platform(session); }
  async toggleVoucher(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.voucher.update({ where: { id }, data: { active, version: { increment: 1 } } }); await this.auditToggle(session, "voucher", id, active); return this.platform(session); }
  async toggleFlashSale(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.flashSale.update({ where: { id }, data: { status: active ? "active" : "paused", version: { increment: 1 } } }); await this.auditToggle(session, "flash_sale", id, active); return this.platform(session); }
  private async auditToggle(session: Session, resourceType: string, resourceId: string, active: boolean) { await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: `${resourceType}.toggled`, resourceType, resourceId, after: json({ active }) } }); }
}
