import assert from "node:assert/strict"; import test from "node:test"; import type { PrismaClient } from "@prisma/client"; import type { Session } from "@amiyo/contracts"; import { AdminService } from "./admin.service.js";
const userId = "11111111-1111-4111-8111-111111111111"; const customer: Session = { principal: { userId, roles: ["CUSTOMER"], vendorIds: [] }, status: "ACTIVE", email: null, phone: null, profile: { firstName: null, lastName: null, displayName: "Customer", avatarStorageKey: null, locale: "en", currency: "BDT" }, permissions: ["catalog:read"], vendorMemberships: [] }; const admin: Session = { ...customer, principal: { ...customer.principal, roles: ["SUPER_ADMIN"] }, permissions: ["admin:read", "admin:manage"] };
test("customer cannot read admin trust queues", async () => { await assert.rejects(() => new AdminService({} as PrismaClient).workspace(customer), /admin:read access is required/); });
test("admin cannot suspend their own account", async () => { await assert.rejects(() => new AdminService({} as PrismaClient).updateUser(admin, userId, { status: "SUSPENDED", reason: "Security review" }), /cannot change your own account status/); });
test("admin cannot change their own platform roles", async () => { await assert.rejects(() => new AdminService({} as PrismaClient).updateUserRoles(admin, userId, { roles: [], reason: "Access review" }), /cannot change your own platform roles/); });
test("customer cannot read marketplace analytics", async () => { await assert.rejects(() => new AdminService({} as PrismaClient).analytics(customer, { range: "30d" }), /admin:read access is required/); });
test("customer cannot read admin commerce workspaces", async () => { await assert.rejects(() => new AdminService({} as PrismaClient).commerce(customer), /admin:read access is required/); });
test("admin analytics derives bigint-safe metrics and customer segments", async () => {
  let userCountCall = 0;
  const client = {
    user: { count: async () => ++userCountCall === 1 ? 20 : 3 },
    order: { aggregate: async () => ({ _count: { _all: 3 }, _sum: { totalMinor: 90000n } }), groupBy: async () => [{ userId: "customer-1", _count: { _all: 2 }, _sum: { totalMinor: 60000n } }, { userId: "customer-2", _count: { _all: 1 }, _sum: { totalMinor: 30000n } }] },
    orderItem: { groupBy: async () => [{ productId: "product-1", _sum: { quantity: 4, lineTotalMinor: 70000n } }] },
    vendorOrder: { groupBy: async () => [{ vendorId: "vendor-1", _count: { _all: 3 }, _sum: { totalMinor: 90000n } }] },
    product: { findMany: async () => [{ id: "product-1", name: "Top product" }] },
    vendor: { findMany: async () => [{ id: "vendor-1", displayName: "Top vendor" }] },
    $queryRaw: async () => [{ date: new Date("2026-08-01T00:00:00.000Z"), orders: 3n, revenue: 90000n }]
  } as unknown as PrismaClient;
  const result = await new AdminService(client).analytics(admin, { range: "30d" });
  assert.equal(result.summary.gmv.amountMinor, "90000");
  assert.equal(result.summary.averageOrderValue.amountMinor, "30000");
  assert.equal(result.summary.repeatPurchaseRate, 50);
  assert.equal(result.segments.find((segment) => segment.key === "regular")?.customers, 1);
  assert.equal(result.topProducts[0]?.name, "Top product");
});
test("coupon updates reject stale versions", async () => { const client = { coupon: { findUnique: async () => ({ id: "coupon-1", code: "SAVE10", version: 3, active: true }), updateMany: async () => ({ count: 0 }) } } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).updateCoupon(admin, "coupon-1", { code: "SAVE20", discountType: "PERCENT", value: 20, maxDiscountMinor: null, minimumSpendMinor: "0", usageLimit: null, perUserLimit: 1, startsAt: "2026-08-15T00:00:00.000Z", endsAt: "2026-08-30T00:00:00.000Z", active: true, expectedVersion: 2 }), /Coupon changed; refresh and try again/); });
test("redeemed coupons cannot be deleted", async () => { const client = { coupon: { findUnique: async () => ({ id: "coupon-1", code: "USED10", version: 1, _count: { redemptions: 2 } }) } } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).deleteCoupon(admin, "coupon-1"), /Redeemed coupons cannot be deleted/); });
test("campaigns reject unpublished target products", async () => { const client = { product: { count: async () => 1 } } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).createCampaign(admin, { name: "Targeted campaign", slug: "targeted-campaign", description: "A targeted product campaign.", discountType: "PERCENT", discountValue: 10, imageUrl: null, startsAt: "2026-08-15T00:00:00.000Z", endsAt: "2026-08-30T00:00:00.000Z", status: "draft", showAsPopup: true, priority: 0, couponCode: null, productIds: ["00000000-0000-4000-8000-000000000401", "00000000-0000-4000-8000-000000000402"], buttonText: "Shop now", buttonLink: "/products" }), /Every campaign product must exist and be published/); });
test("campaign updates reject stale versions", async () => { const transaction = { campaign: { updateMany: async () => ({ count: 0 }) } }; const client = { product: { count: async () => 0 }, campaign: { findUnique: async () => ({ id: "campaign-1", name: "Campaign", slug: "campaign", status: "draft", version: 2 }) }, $transaction: async (operation: (client: typeof transaction) => unknown) => operation(transaction) } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).updateCampaign(admin, "campaign-1", { name: "Updated campaign", slug: "updated-campaign", description: "Updated campaign details.", discountType: "FIXED", discountValue: 500, imageUrl: null, startsAt: "2026-08-15T00:00:00.000Z", endsAt: "2026-08-30T00:00:00.000Z", status: "active", showAsPopup: false, priority: 2, couponCode: null, productIds: [], buttonText: "View offer", buttonLink: "/products", expectedVersion: 1 }), /Campaign changed; refresh and try again/); });
test("admin chat inbox computes participant-scoped unread messages", async () => { const createdAt = new Date("2026-08-14T09:00:00.000Z"); const client = { chatThread: { findMany: async () => [{ id: "00000000-0000-4000-8000-000000000901", vendorId: null, vendor: null, subject: "Seller support", status: "open", createdAt, updatedAt: createdAt, participants: [], messages: [], _count: { messages: 3 } }] }, chatMessage: { count: async () => 2 } } as unknown as PrismaClient; const result = await new AdminService(client).chats(admin); assert.equal(result.summary.unread, 1); assert.equal(result.threads[0]?.unreadCount, 2); });
test("inventory cannot be adjusted below reserved stock", async () => { const transaction = { inventoryItem: { findUnique: async () => ({ id: "inventory-1", version: 2, onHand: 8, reserved: 5, reorderLevel: 2 }) } }; const client = { $transaction: async (operation: (client: typeof transaction) => unknown) => operation(transaction) } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).updateInventory(admin, "inventory-1", { expectedVersion: 2, onHand: 4, reorderLevel: 2, reason: "Cycle count correction" }), /cannot be lower than 5 reserved units/); });
test("inventory adjustments reject stale versions before recording evidence", async () => { let movementCreated = false; const transaction = { inventoryItem: { findUnique: async () => ({ id: "inventory-1", version: 3, onHand: 8, reserved: 1, reorderLevel: 2 }), updateMany: async () => ({ count: 0 }) }, inventoryMovement: { create: async () => { movementCreated = true; } } }; const client = { $transaction: async (operation: (client: typeof transaction) => unknown) => operation(transaction) } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).updateInventory(admin, "inventory-1", { expectedVersion: 2, onHand: 9, reorderLevel: 2, reason: "Warehouse receipt" }), /Inventory changed; refresh and try again/); assert.equal(movementCreated, false); });
test("bulk inventory changes execute inside one transaction", async () => { let transactions = 0; let updates = 0; const current = [{ id: "inventory-1", version: 1, onHand: 4, reserved: 0, reorderLevel: 1 }, { id: "inventory-2", version: 2, onHand: 7, reserved: 2, reorderLevel: 2 }]; const transaction = { inventoryItem: { findMany: async () => current, updateMany: async () => { updates += 1; return { count: 1 }; } }, inventoryMovement: { create: async () => undefined }, auditLog: { create: async () => undefined } }; const client = { $transaction: async (operation: (client: typeof transaction) => unknown) => { transactions += 1; return operation(transaction); } } as unknown as PrismaClient; const service = new AdminService(client); service.inventory = async () => ({ items: [], movements: [], summary: { totalVariants: 0, inStock: 0, lowStock: 0, outOfStock: 0, stockUnits: 0, reservedUnits: 0, valueMinor: "0", currency: "BDT" } }); await service.bulkUpdateInventory(admin, { items: [{ id: "inventory-1", expectedVersion: 1, onHand: 5, reorderLevel: 1 }, { id: "inventory-2", expectedVersion: 2, onHand: 9, reorderLevel: 3 }], reason: "Warehouse shipment received" }); assert.equal(transactions, 1); assert.equal(updates, 2); });
test("order status overrides reject stale versions before audit evidence", async () => { let audited = false; const transaction = { order: { updateMany: async () => ({ count: 0 }) }, orderStatusEvent: { create: async () => undefined }, auditLog: { create: async () => { audited = true; } } }; const client = { order: { findUnique: async () => ({ id: "order-1", status: "CONFIRMED", version: 3 }) }, $transaction: async (operation: (client: typeof transaction) => unknown) => operation(transaction) } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).overrideOrderStatus(admin, "order-1", { expectedVersion: 2, status: "PROCESSING", reason: "Manual operations correction" }), /Order changed; refresh and try again/); assert.equal(audited, false); });
test("order address correction requires an existing delivery snapshot", async () => { const client = { orderAddress: { findUnique: async () => null } } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).correctOrderAddress(admin, "order-1", { recipientName: "Buyer", phone: "01700000000", line1: "Road 1", line2: null, division: "Dhaka", district: "Dhaka", upazila: null, unionName: null, postalCode: null, reason: "Customer verified correction" }), /Delivery address not found/); });
test("return-window extensions reject stale order versions", async () => { let audited = false; const transaction = { order: { updateMany: async () => ({ count: 0 }) }, auditLog: { create: async () => { audited = true; } } }; const client = { order: { findUnique: async () => ({ id: "order-1", version: 3, returnWindowUntil: null }) }, $transaction: async (operation: (client: typeof transaction) => unknown) => operation(transaction) } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).extendOrderReturnWindow(admin, "order-1", { expectedVersion: 2, returnWindowUntil: "2099-09-01T23:59:59.000Z", reason: "Approved customer exception" }), /Order changed; refresh and try again/); assert.equal(audited, false); });
test("order SLA monitor identifies overdue processing", async () => { const createdAt = new Date(Date.now() - 72 * 60 * 60_000); const client = { order: { findMany: async () => [{ id: "00000000-0000-4000-8000-000000000801", orderNumber: "AGO-1001", status: "PROCESSING", totalMinor: 250000n, currency: "BDT", createdAt, user: { normalizedEmail: "buyer@amiyo.test", profile: { displayName: "Buyer" } }, vendorOrders: [{ vendor: { displayName: "Vendor" }, shipments: [] }] }] } } as unknown as PrismaClient; const result = await new AdminService(client).orderSlaBreaches(admin); assert.equal(result.summary.processing, 1); assert.equal(result.breaches[0]?.breachType, "processing"); });
test("order fraud queue exposes gateway risk holds", async () => { const createdAt = new Date(); const client = { order: { findMany: async () => [{ id: "00000000-0000-4000-8000-000000000801", orderNumber: "AGO-1001", userId: "00000000-0000-4000-8000-000000000802", status: "PENDING_PAYMENT", totalMinor: 250000n, currency: "BDT", createdAt, user: { normalizedPhone: "01700000000", profile: { displayName: "Buyer" } }, addresses: [], vendorOrders: [{ vendor: { displayName: "Vendor" } }], payments: [{ method: "SSLCOMMERZ", verifications: [{ status: "risk_hold" }] }] }] } } as unknown as PrismaClient; const result = await new AdminService(client).orderFraudQueue(admin); assert.equal(result.summary.totalFlagged, 1); assert.equal(result.orders[0]?.signals[0]?.type, "payment_risk_hold"); });
