import assert from "node:assert/strict"; import test from "node:test"; import type { PrismaClient } from "@prisma/client"; import type { Session } from "@amiyo/contracts"; import { AdminService } from "./admin.service.js";
const userId = "11111111-1111-4111-8111-111111111111"; const customer: Session = { principal: { userId, roles: ["CUSTOMER"], vendorIds: [] }, status: "ACTIVE", email: null, phone: null, profile: { firstName: null, lastName: null, displayName: "Customer", avatarStorageKey: null, locale: "en", currency: "BDT" }, permissions: ["catalog:read"], vendorMemberships: [] }; const admin: Session = { ...customer, principal: { ...customer.principal, roles: ["SUPER_ADMIN"] }, permissions: ["admin:read", "admin:manage"] };
test("customer cannot read admin trust queues", async () => { await assert.rejects(() => new AdminService({} as PrismaClient).workspace(customer), /admin:read access is required/); });
test("admin cannot suspend their own account", async () => { await assert.rejects(() => new AdminService({} as PrismaClient).updateUser(admin, userId, { status: "SUSPENDED", reason: "Security review" }), /cannot change your own account status/); });
test("admin cannot change their own platform roles", async () => { await assert.rejects(() => new AdminService({} as PrismaClient).updateUserRoles(admin, userId, { roles: [], reason: "Access review" }), /cannot change your own platform roles/); });
test("customer cannot read marketplace analytics", async () => { await assert.rejects(() => new AdminService({} as PrismaClient).analytics(customer, { range: "30d" }), /admin:read access is required/); });
test("customer cannot read admin commerce workspaces", async () => { await assert.rejects(() => new AdminService({} as PrismaClient).commerce(customer), /admin:read access is required/); });
test("admin analytics derives bigint-safe metrics and customer segments", async () => {
  let userCountCall = 0;
  const client = {
    user: { count: async () => ++userCountCall === 1 ? 20 : 3 },
    order: { aggregate: async () => ({ _count: { _all: 3 }, _sum: { totalMinor: 90000n } }), groupBy: async () => [{ userId: "customer-1", _count: { _all: 2 }, _sum: { totalMinor: 60000n } }, { userId: "customer-2", _count: { _all: 1 }, _sum: { totalMinor: 30000n } }] },
    orderItem: { groupBy: async () => [{ productId: "product-1", _sum: { quantity: 4, lineTotalMinor: 70000n } }] },
    vendorOrder: { groupBy: async () => [{ vendorId: "vendor-1", _count: { _all: 3 }, _sum: { totalMinor: 90000n } }] },
    product: { findMany: async () => [{ id: "product-1", name: "Top product" }] },
    vendor: { findMany: async () => [{ id: "vendor-1", displayName: "Top vendor" }] },
    $queryRaw: async () => [{ date: new Date("2026-08-01T00:00:00.000Z"), orders: 3n, revenue: 90000n }]
  } as unknown as PrismaClient;
  const result = await new AdminService(client).analytics(admin, { range: "30d" });
  assert.equal(result.summary.gmv.amountMinor, "90000");
  assert.equal(result.summary.averageOrderValue.amountMinor, "30000");
  assert.equal(result.summary.repeatPurchaseRate, 50);
  assert.equal(result.segments.find((segment) => segment.key === "regular")?.customers, 1);
  assert.equal(result.topProducts[0]?.name, "Top product");
});
test("coupon updates reject stale versions", async () => { const client = { coupon: { findUnique: async () => ({ id: "coupon-1", code: "SAVE10", version: 3, active: true }), updateMany: async () => ({ count: 0 }) } } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).updateCoupon(admin, "coupon-1", { code: "SAVE20", discountType: "PERCENT", value: 20, maxDiscountMinor: null, minimumSpendMinor: "0", usageLimit: null, perUserLimit: 1, startsAt: "2026-08-15T00:00:00.000Z", endsAt: "2026-08-30T00:00:00.000Z", active: true, expectedVersion: 2 }), /Coupon changed; refresh and try again/); });
test("redeemed coupons cannot be deleted", async () => { const client = { coupon: { findUnique: async () => ({ id: "coupon-1", code: "USED10", version: 1, _count: { redemptions: 2 } }) } } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).deleteCoupon(admin, "coupon-1"), /Redeemed coupons cannot be deleted/); });
test("campaigns reject unpublished target products", async () => { const client = { product: { count: async () => 1 } } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).createCampaign(admin, { name: "Targeted campaign", slug: "targeted-campaign", description: "A targeted product campaign.", discountType: "PERCENT", discountValue: 10, imageUrl: null, startsAt: "2026-08-15T00:00:00.000Z", endsAt: "2026-08-30T00:00:00.000Z", status: "draft", showAsPopup: true, priority: 0, couponCode: null, productIds: ["00000000-0000-4000-8000-000000000401", "00000000-0000-4000-8000-000000000402"], buttonText: "Shop now", buttonLink: "/products" }), /Every campaign product must exist and be published/); });
test("campaign updates reject stale versions", async () => { const transaction = { campaign: { updateMany: async () => ({ count: 0 }) } }; const client = { product: { count: async () => 0 }, campaign: { findUnique: async () => ({ id: "campaign-1", name: "Campaign", slug: "campaign", status: "draft", version: 2 }) }, $transaction: async (operation: (client: typeof transaction) => unknown) => operation(transaction) } as unknown as PrismaClient; await assert.rejects(() => new AdminService(client).updateCampaign(admin, "campaign-1", { name: "Updated campaign", slug: "updated-campaign", description: "Updated campaign details.", discountType: "FIXED", discountValue: 500, imageUrl: null, startsAt: "2026-08-15T00:00:00.000Z", endsAt: "2026-08-30T00:00:00.000Z", status: "active", showAsPopup: false, priority: 2, couponCode: null, productIds: [], buttonText: "View offer", buttonLink: "/products", expectedVersion: 1 }), /Campaign changed; refresh and try again/); });
