import { Prisma, type PrismaClient } from "@prisma/client";
import type { AdminAnalyticsQuery, AdminBannerInput, AdminCategoryAttributesInput, AdminCategoryInput, AdminCategoryRequestReview, AdminKycReviewInput, AdminUserRolesInput, AdminUserStatusInput, AdminVendorStatusInput, PaymentVerificationReview, Session, TrustCaseActionInput } from "@amiyo/contracts";
import { ApiProblem } from "../../middleware/api-problem.js";

function requireAdmin(session: Session, write = false) {
  const permission = write ? "admin:manage" : "admin:read";
  if (session.status !== "ACTIVE" || !session.permissions.includes(permission)) throw new ApiProblem(403, "ADMIN_ACCESS_REQUIRED", `${permission} access is required`);
}
function json(value: unknown) { return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue; }
function mediaUrl(key: string | null) { if (!key) return null; if (/^https?:\/\//.test(key)) return key; const base = process.env.OBJECT_STORAGE_PUBLIC_URL?.replace(/\/$/, ""); return base ? `${base}/${key}` : null; }
function bannerStatus(active: boolean, startsAt: Date, endsAt: Date) { const now = new Date(); return !active ? "inactive" as const : startsAt > now ? "scheduled" as const : endsAt <= now ? "expired" as const : "active" as const; }
const assignableRoles = ["SUPPORT_AGENT", "FINANCE_ADMIN", "OPERATIONS_ADMIN", "SUPER_ADMIN"] as const;

export class AdminService {
  constructor(private readonly client: PrismaClient) {}
  async workspace(session: Session) {
    requireAdmin(session);
    const [users, vendors, kyc, trustCases] = await Promise.all([
      this.client.user.findMany({ include: { profile: true, roles: { include: { role: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
      this.client.vendor.findMany({ include: { _count: { select: { members: true, shops: true } }, kycSubmissions: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { createdAt: "desc" }, take: 100 }),
      this.client.vendorKycSubmission.findMany({ where: { status: { in: ["SUBMITTED", "REVIEWING"] } }, include: { vendor: true, documents: true }, orderBy: { createdAt: "asc" }, take: 100 }),
      this.client.trustCase.findMany({ include: { actions: { orderBy: { createdAt: "asc" } } }, orderBy: [{ severity: "desc" }, { createdAt: "asc" }], take: 100 })
    ]);
    return {
      users: users.map((user) => ({ id: user.id, email: user.normalizedEmail, phone: user.normalizedPhone, displayName: user.profile?.displayName ?? null, status: user.status, roles: user.roles.map(({ role }) => role.name), createdAt: user.createdAt.toISOString() })),
      vendors: vendors.map((vendor) => ({ id: vendor.id, legalName: vendor.legalName, displayName: vendor.displayName, status: vendor.status, version: vendor.version, memberCount: vendor._count.members, shopCount: vendor._count.shops, latestKycStatus: vendor.kycSubmissions[0]?.status ?? null, createdAt: vendor.createdAt.toISOString() })),
      kyc: kyc.map((submission) => ({ id: submission.id, vendorId: submission.vendorId, vendorName: submission.vendor.displayName, status: submission.status, submittedAt: submission.submittedAt?.toISOString() ?? null, rejectionReason: submission.rejectionReason, documents: submission.documents.map((document) => ({ id: document.id, documentType: document.documentType, storageKey: document.storageKey, mimeType: document.mimeType })) })),
      trustCases: trustCases.map((trustCase) => ({ id: trustCase.id, subjectType: trustCase.subjectType, subjectId: trustCase.subjectId, caseType: trustCase.caseType, severity: trustCase.severity, status: trustCase.status, assignedTo: trustCase.assignedTo, summary: trustCase.summary, createdAt: trustCase.createdAt.toISOString(), actions: trustCase.actions.map((action) => ({ id: action.id, actionType: action.actionType, actorUserId: action.actorUserId, reason: action.reason, createdAt: action.createdAt.toISOString() })) }))
    };
  }
  async updateUser(session: Session, userId: string, input: AdminUserStatusInput) {
    requireAdmin(session, true); if (userId === session.principal.userId) throw new ApiProblem(409, "SELF_STATUS_CHANGE_FORBIDDEN", "You cannot change your own account status");
    const before = await this.client.user.findUnique({ where: { id: userId } }); if (!before) throw new ApiProblem(404, "USER_NOT_FOUND", "User not found");
    await this.client.$transaction([this.client.user.update({ where: { id: userId }, data: { status: input.status } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.user.status_changed", resourceType: "user", resourceId: userId, before: json({ status: before.status }), after: json(input) } })]);
    return this.workspace(session);
  }
  async updateUserRoles(session: Session, userId: string, input: AdminUserRolesInput) {
    requireAdmin(session, true);
    if (userId === session.principal.userId) throw new ApiProblem(409, "SELF_ROLE_CHANGE_FORBIDDEN", "You cannot change your own platform roles");
    const user = await this.client.user.findUnique({ where: { id: userId }, include: { roles: { include: { role: true } } } });
    if (!user) throw new ApiProblem(404, "USER_NOT_FOUND", "User not found");
    const before = user.roles.map(({ role }) => role.name);
    if (before.includes("SUPER_ADMIN") && !input.roles.includes("SUPER_ADMIN")) {
      const superAdminCount = await this.client.userRole.count({ where: { role: { name: "SUPER_ADMIN" }, user: { status: "ACTIVE" } } });
      if (superAdminCount <= 1) throw new ApiProblem(409, "LAST_SUPER_ADMIN_REQUIRED", "At least one active super admin must remain");
    }
    const roles = await this.client.role.findMany({ where: { name: { in: input.roles } } });
    if (roles.length !== input.roles.length) throw new ApiProblem(503, "ROLE_CONFIGURATION_INCOMPLETE", "One or more platform roles have not been seeded");
    await this.client.$transaction(async (transaction) => {
      await transaction.userRole.deleteMany({ where: { userId, role: { name: { in: [...assignableRoles] } } } });
      if (roles.length) await transaction.userRole.createMany({ data: roles.map((role) => ({ userId, roleId: role.id })) });
      await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.user.roles_changed", resourceType: "user", resourceId: userId, before: json({ roles: before }), after: json(input) } });
    });
    return this.workspace(session);
  }
  async updateVendor(session: Session, vendorId: string, input: AdminVendorStatusInput) {
    requireAdmin(session, true); const before = await this.client.vendor.findUnique({ where: { id: vendorId } }); if (!before) throw new ApiProblem(404, "VENDOR_NOT_FOUND", "Vendor not found");
    await this.client.$transaction([this.client.vendor.update({ where: { id: vendorId }, data: { status: input.status, approvedAt: input.status === "APPROVED" ? new Date() : before.approvedAt, version: { increment: 1 } } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.vendor.status_changed", resourceType: "vendor", resourceId: vendorId, before: json({ status: before.status }), after: json(input) } })]);
    return this.workspace(session);
  }
  async reviewKyc(session: Session, id: string, input: AdminKycReviewInput) {
    requireAdmin(session, true); const before = await this.client.vendorKycSubmission.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "KYC_NOT_FOUND", "KYC submission not found");
    if (!(["SUBMITTED", "REVIEWING"] as const).includes(before.status as "SUBMITTED" | "REVIEWING")) throw new ApiProblem(409, "KYC_NOT_REVIEWABLE", "KYC submission is no longer reviewable");
    await this.client.$transaction(async (transaction) => { await transaction.vendorKycSubmission.update({ where: { id }, data: { status: input.status, reviewedBy: session.principal.userId, reviewedAt: input.status === "REVIEWING" ? null : new Date(), rejectionReason: input.status === "REJECTED" ? input.reason ?? null : null } }); if (input.status === "APPROVED") await transaction.vendor.update({ where: { id: before.vendorId }, data: { status: "APPROVED", approvedAt: new Date(), version: { increment: 1 } } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.vendor_kyc.reviewed", resourceType: "vendor_kyc_submission", resourceId: id, before: json({ status: before.status }), after: json(input) } }); });
    return this.workspace(session);
  }
  async actOnTrustCase(session: Session, id: string, input: TrustCaseActionInput) {
    requireAdmin(session, true); const trustCase = await this.client.trustCase.findUnique({ where: { id } }); if (!trustCase) throw new ApiProblem(404, "TRUST_CASE_NOT_FOUND", "Trust case not found"); const status = input.action === "INVESTIGATE" ? "investigating" : input.action.toLowerCase();
    await this.client.$transaction([this.client.trustCase.update({ where: { id }, data: { status, assignedTo: trustCase.assignedTo ?? session.principal.userId, actions: { create: { actionType: input.action, actorUserId: session.principal.userId, reason: input.reason } } } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "admin.trust_case.action", resourceType: "trust_case", resourceId: id, after: json(input) } })]);
    return this.workspace(session);
  }
  async commerce(session: Session) {
    requireAdmin(session);
    const [orders, inventory, coupons, campaigns, chats, codCollections, codReconciliations, vendorActivity] = await Promise.all([
      this.client.order.findMany({ include: { user: { include: { profile: true } }, vendorOrders: { include: { vendor: true, shop: true } }, payments: { orderBy: { createdAt: "desc" }, take: 1 }, _count: { select: { items: true } } }, orderBy: { createdAt: "desc" }, take: 200 }),
      this.client.inventoryItem.findMany({ include: { variant: { include: { product: { include: { vendor: true, shop: true } } } } }, orderBy: { updatedAt: "desc" }, take: 300 }),
      this.client.coupon.findMany({ include: { _count: { select: { redemptions: true } } }, orderBy: { startsAt: "desc" }, take: 100 }),
      this.client.campaign.findMany({ include: { _count: { select: { products: true, events: true } } }, orderBy: { startsAt: "desc" }, take: 100 }),
      this.client.chatThread.findMany({ include: { vendor: true, messages: { orderBy: { createdAt: "desc" }, take: 1 }, _count: { select: { participants: true, messages: true } } }, orderBy: { updatedAt: "desc" }, take: 100 }),
      this.client.codCollection.findMany({ include: { payment: { include: { order: true } } }, orderBy: { collectedAt: "desc" }, take: 100 }),
      this.client.codReconciliation.findMany({ include: { _count: { select: { items: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
      this.client.vendor.findMany({ include: { _count: { select: { products: true, vendorOrders: true, chatThreads: true, payoutRequests: true } }, vendorOrders: { select: { totalMinor: true, commissionMinor: true } } }, orderBy: { updatedAt: "desc" }, take: 100 })
    ]);
    return {
      orders: orders.map((item) => ({ id: item.id, orderNumber: item.orderNumber, customer: item.user?.profile?.displayName ?? item.user?.normalizedEmail ?? "Guest customer", status: item.status, totalMinor: item.totalMinor.toString(), currency: item.currency, itemCount: item._count.items, vendorCount: item.vendorOrders.length, paymentMethod: item.payments[0]?.method ?? null, paymentStatus: item.payments[0]?.status ?? null, createdAt: item.createdAt.toISOString() })),
      inventory: inventory.map((item) => ({ id: item.id, version: item.version, sku: item.variant.sku, variant: item.variant.title, product: item.variant.product.name, vendor: item.variant.product.vendor.displayName, shop: item.variant.product.shop.name, onHand: item.onHand, reserved: item.reserved, available: Math.max(0, item.onHand - item.reserved), reorderLevel: item.reorderLevel, updatedAt: item.updatedAt.toISOString() })),
      coupons: coupons.map((item) => ({ id: item.id, code: item.code, discountType: item.discountType, value: item.value, minimumSpendMinor: item.minimumSpendMinor.toString(), usageLimit: item.usageLimit, redemptions: item._count.redemptions, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), active: item.active, version: item.version })),
      campaigns: campaigns.map((item) => ({ id: item.id, name: item.name, slug: item.slug, status: item.status, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), productCount: item._count.products, eventCount: item._count.events, version: item.version })),
      chats: chats.map((item) => ({ id: item.id, vendor: item.vendor?.displayName ?? "Customer support", subject: item.subject ?? "Conversation", status: item.status, participants: item._count.participants, messageCount: item._count.messages, lastMessage: item.messages[0]?.body ?? null, updatedAt: item.updatedAt.toISOString() })),
      codCollections: codCollections.map((item) => ({ id: item.id, orderNumber: item.payment.order.orderNumber, expectedMinor: item.payment.amountMinor.toString(), collectedMinor: item.collectedMinor.toString(), currency: item.currency, collectorRef: item.collectorRef, collectedAt: item.collectedAt.toISOString() })),
      codReconciliations: codReconciliations.map((item) => ({ id: item.id, periodStart: item.periodStart.toISOString(), periodEnd: item.periodEnd.toISOString(), expectedMinor: item.expectedMinor.toString(), receivedMinor: item.receivedMinor.toString(), currency: item.currency, status: item.status, itemCount: item._count.items, createdAt: item.createdAt.toISOString() })),
      vendorActivity: vendorActivity.map((item) => ({ id: item.id, vendor: item.displayName, status: item.status, products: item._count.products, orders: item._count.vendorOrders, chats: item._count.chatThreads, payoutRequests: item._count.payoutRequests, gmvMinor: item.vendorOrders.reduce((sum, row) => sum + row.totalMinor, 0n).toString(), commissionMinor: item.vendorOrders.reduce((sum, row) => sum + row.commissionMinor, 0n).toString(), updatedAt: item.updatedAt.toISOString() }))
    };
  }
  async updateInventory(session: Session, id: string, input: { expectedVersion: number; onHand: number; reorderLevel: number }) {
    requireAdmin(session, true); const before = await this.client.inventoryItem.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "INVENTORY_NOT_FOUND", "Inventory item not found");
    const updated = await this.client.inventoryItem.updateMany({ where: { id, version: input.expectedVersion }, data: { onHand: input.onHand, reorderLevel: input.reorderLevel, version: { increment: 1 } } }); if (!updated.count) throw new ApiProblem(409, "INVENTORY_VERSION_CONFLICT", "Inventory changed; refresh and try again");
    await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "inventory.admin_adjusted", resourceType: "inventory_item", resourceId: id, before: json({ onHand: before.onHand, reorderLevel: before.reorderLevel }), after: json(input) } }); return this.commerce(session);
  }
  async toggleCoupon(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.coupon.update({ where: { id }, data: { active, version: { increment: 1 } } }); await this.auditToggle(session, "coupon", id, active); return this.commerce(session); }
  async sendAdminChat(session: Session, id: string, body: string) {
    requireAdmin(session, true); const thread = await this.client.chatThread.findUnique({ where: { id } }); if (!thread) throw new ApiProblem(404, "CHAT_THREAD_NOT_FOUND", "Chat thread not found");
    await this.client.$transaction([this.client.chatParticipant.upsert({ where: { threadId_userId: { threadId: id, userId: session.principal.userId } }, create: { threadId: id, userId: session.principal.userId, role: "admin" }, update: {} }), this.client.chatMessage.create({ data: { threadId: id, senderId: session.principal.userId, body } }), this.client.chatThread.update({ where: { id }, data: { updatedAt: new Date() } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "chat.admin_message_sent", resourceType: "chat_thread", resourceId: id, after: json({ bodyLength: body.length }) } })]); return this.commerce(session);
  }
  async platform(session: Session) {
    requireAdmin(session);
    const [paymentVerifications, categories, banners, vouchers, flashSales, audit] = await Promise.all([this.client.paymentVerification.findMany({ include: { payment: { include: { order: true } } }, orderBy: { createdAt: "asc" }, take: 100 }), this.client.category.findMany({ include: { attributes: { include: { options: { orderBy: { displayOrder: "asc" } } }, orderBy: { displayOrder: "asc" } }, _count: { select: { products: true } } }, orderBy: { displayOrder: "asc" }, take: 200 }), this.client.banner.findMany({ orderBy: [{ placement: "asc" }, { displayOrder: "asc" }], take: 100 }), this.client.voucher.findMany({ orderBy: { startsAt: "desc" }, take: 100 }), this.client.flashSale.findMany({ include: { _count: { select: { products: true } } }, orderBy: { startsAt: "desc" }, take: 100 }), this.client.auditLog.findMany({ orderBy: { createdAt: "desc" }, take: 100 })]);
    return { paymentVerifications: paymentVerifications.map((item) => ({ id: item.id, paymentId: item.paymentId, orderId: item.payment.orderId, orderNumber: item.payment.order.orderNumber, provider: item.payment.provider, amountMinor: item.payment.amountMinor.toString(), currency: item.payment.currency, status: item.status, transactionRef: item.transactionRef, senderMasked: item.senderMasked, evidenceStorageKey: item.evidenceStorageKey, createdAt: item.createdAt.toISOString() })), categories: categories.map((item) => ({ id: item.id, parentId: item.parentId, name: item.name, slug: item.slug, status: item.status, displayOrder: item.displayOrder, productCount: item._count.products, attributes: item.attributes.map((attribute) => ({ ...attribute, options: attribute.options })) })), banners: banners.map((item) => ({ ...item, imageUrl: mediaUrl(item.storageKey), mobileImageUrl: mediaUrl(item.mobileStorageKey), startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), status: bannerStatus(item.active, item.startsAt, item.endsAt) })), vouchers: vouchers.map((item) => ({ id: item.id, code: item.code, ownerType: item.ownerType, active: item.active, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString() })), flashSales: flashSales.map((item) => ({ id: item.id, name: item.name, status: item.status, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), productCount: item._count.products })), audit: audit.map((item) => ({ id: item.id, actorType: item.actorType, action: item.action, resourceType: item.resourceType, resourceId: item.resourceId, createdAt: item.createdAt.toISOString() })) };
  }
  async reviewPayment(session: Session, id: string, input: PaymentVerificationReview) { requireAdmin(session, true); const current = await this.client.paymentVerification.findUnique({ where: { id }, include: { payment: true } }); if (!current) throw new ApiProblem(404, "PAYMENT_VERIFICATION_NOT_FOUND", "Payment verification not found"); if (current.status !== "pending") throw new ApiProblem(409, "PAYMENT_VERIFICATION_REVIEWED", "Payment verification has already been reviewed"); await this.client.$transaction(async (transaction) => { await transaction.paymentVerification.update({ where: { id }, data: { status: input.status, reviewedBy: session.principal.userId, reviewedAt: new Date() } }); if (input.status === "approved") { await transaction.payment.update({ where: { id: current.paymentId }, data: { status: "CAPTURED", version: { increment: 1 } } }); await transaction.order.update({ where: { id: current.payment.orderId }, data: { status: "CONFIRMED", version: { increment: 1 } } }); } await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "payment.verification.reviewed", resourceType: "payment_verification", resourceId: id, after: json(input) } }); }); return this.platform(session); }
  async createCategory(session: Session, input: AdminCategoryInput) { requireAdmin(session, true); if (input.parentId && !(await this.client.category.findUnique({ where: { id: input.parentId } }))) throw new ApiProblem(404, "PARENT_CATEGORY_NOT_FOUND", "Parent category not found"); const row = await this.client.category.create({ data: { parentId: input.parentId ?? null, name: input.name, slug: input.slug, description: input.description ?? null, displayOrder: input.displayOrder } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "catalog.category.created", resourceType: "category", resourceId: row.id, after: json(input) } }); return this.platform(session); }
  async analytics(session: Session, input: AdminAnalyticsQuery) {
    requireAdmin(session); const days = input.range === "7d" ? 7 : input.range === "90d" ? 90 : 30; const endsAt = new Date(); const startsAt = new Date(endsAt.getTime() - days * 86_400_000); const activeOrderWhere = { createdAt: { gte: startsAt, lte: endsAt }, status: { not: "CANCELLED" as const } };
    const [totalCustomers, newCustomers, orderAggregate, customers, productGroups, vendorGroups, trend] = await Promise.all([
      this.client.user.count(), this.client.user.count({ where: { createdAt: { gte: startsAt, lte: endsAt } } }), this.client.order.aggregate({ where: activeOrderWhere, _count: { _all: true }, _sum: { totalMinor: true } }),
      this.client.order.groupBy({ by: ["userId"], where: { ...activeOrderWhere, userId: { not: null } }, _count: { _all: true }, _sum: { totalMinor: true } }),
      this.client.orderItem.groupBy({ by: ["productId"], where: { order: activeOrderWhere }, _sum: { quantity: true, lineTotalMinor: true }, orderBy: { _sum: { lineTotalMinor: "desc" } }, take: 5 }),
      this.client.vendorOrder.groupBy({ by: ["vendorId"], where: { order: activeOrderWhere }, _count: { _all: true }, _sum: { totalMinor: true }, orderBy: { _sum: { totalMinor: "desc" } }, take: 5 }),
      this.client.$queryRaw<Array<{ date: Date; orders: bigint; revenue: bigint }>>(Prisma.sql`SELECT DATE_TRUNC('day', created_at) AS date, COUNT(*)::bigint AS orders, COALESCE(SUM(total_minor), 0)::bigint AS revenue FROM orders WHERE created_at >= ${startsAt} AND created_at <= ${endsAt} AND status <> 'CANCELLED' GROUP BY 1 ORDER BY 1 ASC`)
    ]);
    const [products, vendors] = await Promise.all([this.client.product.findMany({ where: { id: { in: productGroups.map((item) => item.productId) } }, select: { id: true, name: true } }), this.client.vendor.findMany({ where: { id: { in: vendorGroups.map((item) => item.vendorId) } }, select: { id: true, displayName: true } })]); const productNames = new Map(products.map((item) => [item.id, item.name])); const vendorNames = new Map(vendors.map((item) => [item.id, item.displayName])); type SegmentKey = "new" | "regular" | "vip"; type SegmentAccumulator = { key: SegmentKey; customers: number; orders: number; revenue: bigint }; const segmentMap = new Map<SegmentKey, SegmentAccumulator>(["new", "regular", "vip"].map((key) => [key as SegmentKey, { key: key as SegmentKey, customers: 0, orders: 0, revenue: 0n }])); for (const customer of customers) { const key: SegmentKey = customer._count._all >= 5 ? "vip" : customer._count._all >= 2 ? "regular" : "new"; const segment = segmentMap.get(key)!; segment.customers += 1; segment.orders += customer._count._all; segment.revenue += customer._sum.totalMinor ?? 0n; } const gmv = orderAggregate._sum.totalMinor ?? 0n; const orderCount = orderAggregate._count._all; const repeatCustomers = customers.filter((customer) => customer._count._all > 1).length; const amount = (amountMinor: bigint) => ({ amountMinor: amountMinor.toString(), currency: "BDT" as const });
    return { range: { key: input.range, startsAt: startsAt.toISOString(), endsAt: endsAt.toISOString() }, summary: { totalCustomers, newCustomers, purchasingCustomers: customers.length, orders: orderCount, gmv: amount(gmv), averageOrderValue: amount(orderCount ? gmv / BigInt(orderCount) : 0n), repeatPurchaseRate: customers.length ? Math.round((repeatCustomers / customers.length) * 1000) / 10 : 0 }, trend: trend.map((item) => ({ date: item.date.toISOString().slice(0, 10), orders: Number(item.orders), revenue: amount(item.revenue) })), segments: [...segmentMap.values()].map((item) => ({ ...item, revenue: amount(item.revenue) })), topProducts: productGroups.map((item) => ({ id: item.productId, name: productNames.get(item.productId) ?? "Unknown product", quantity: item._sum.quantity ?? 0, revenue: amount(item._sum.lineTotalMinor ?? 0n) })), topVendors: vendorGroups.map((item) => ({ id: item.vendorId, name: vendorNames.get(item.vendorId) ?? "Unknown vendor", orders: item._count._all, revenue: amount(item._sum.totalMinor ?? 0n) })) };
  }
  async replaceCategoryAttributes(session: Session, categoryId: string, input: AdminCategoryAttributesInput) { requireAdmin(session, true); const category = await this.client.category.findUnique({ where: { id: categoryId }, include: { attributes: { include: { options: true } } } }); if (!category) throw new ApiProblem(404, "CATEGORY_NOT_FOUND", "Category not found"); await this.client.$transaction(async (transaction) => { await transaction.categoryAttribute.deleteMany({ where: { categoryId } }); for (const attribute of input.attributes) await transaction.categoryAttribute.create({ data: { categoryId, key: attribute.key, label: attribute.label, dataType: attribute.dataType, required: attribute.required, filterable: attribute.filterable, displayOrder: attribute.displayOrder, options: { create: attribute.options.map((option, displayOrder) => ({ value: option.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), label: option, displayOrder })) } } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "catalog.category_attributes.replaced", resourceType: "category", resourceId: categoryId, before: json(category.attributes), after: json(input.attributes) } }); }); return this.platform(session); }
  async createBanner(session: Session, input: AdminBannerInput) { requireAdmin(session, true); const row = await this.client.banner.create({ data: { ...input, subtitle: input.subtitle ?? null, mobileStorageKey: input.mobileStorageKey ?? null, ctaLabel: input.ctaLabel ?? null, badgeText: input.badgeText ?? null, targetType: input.targetType ?? null, targetValue: input.targetValue ?? null, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt) } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "banner.created", resourceType: "banner", resourceId: row.id, after: json(input) } }); return this.platform(session); }
  async updateBanner(session: Session, id: string, input: AdminBannerInput) { requireAdmin(session, true); const before = await this.client.banner.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "BANNER_NOT_FOUND", "Banner not found"); await this.client.$transaction([this.client.banner.update({ where: { id }, data: { ...input, subtitle: input.subtitle ?? null, mobileStorageKey: input.mobileStorageKey ?? null, ctaLabel: input.ctaLabel ?? null, badgeText: input.badgeText ?? null, targetType: input.targetType ?? null, targetValue: input.targetValue ?? null, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt) } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "banner.updated", resourceType: "banner", resourceId: id, before: json(before), after: json(input) } })]); return this.platform(session); }
  async deleteBanner(session: Session, id: string) { requireAdmin(session, true); const before = await this.client.banner.findUnique({ where: { id } }); if (!before) throw new ApiProblem(404, "BANNER_NOT_FOUND", "Banner not found"); await this.client.$transaction([this.client.banner.delete({ where: { id } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "banner.deleted", resourceType: "banner", resourceId: id, before: json(before) } })]); return this.platform(session); }
  async toggleBanner(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.banner.update({ where: { id }, data: { active } }); await this.auditToggle(session, "banner", id, active); return this.platform(session); }
  async toggleVoucher(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.voucher.update({ where: { id }, data: { active, version: { increment: 1 } } }); await this.auditToggle(session, "voucher", id, active); return this.platform(session); }
  async toggleFlashSale(session: Session, id: string, active: boolean) { requireAdmin(session, true); await this.client.flashSale.update({ where: { id }, data: { status: active ? "active" : "paused", version: { increment: 1 } } }); await this.auditToggle(session, "flash_sale", id, active); return this.platform(session); }
  async categoryRequests(session: Session) { requireAdmin(session); const rows = await this.client.vendorCategoryRequest.findMany({ include: { vendor: true, category: { include: { parent: true } } }, orderBy: { createdAt: "asc" }, take: 100 }); return rows.map((item) => ({ id: item.id, vendorId: item.vendorId, vendorName: item.vendor.displayName, categoryId: item.categoryId, categoryName: item.category.name, categoryPath: item.category.parent ? `${item.category.parent.name} > ${item.category.name}` : item.category.name, status: item.status, reason: item.reason, description: item.description, reviewReason: item.reviewReason, reviewedAt: item.reviewedAt?.toISOString() ?? null, createdAt: item.createdAt.toISOString() })); }
  async reviewCategoryRequest(session: Session, id: string, input: AdminCategoryRequestReview) { requireAdmin(session, true); const current = await this.client.vendorCategoryRequest.findUnique({ where: { id } }); if (!current) throw new ApiProblem(404, "CATEGORY_REQUEST_NOT_FOUND", "Category request not found"); if (current.status !== "pending") throw new ApiProblem(409, "CATEGORY_REQUEST_REVIEWED", "Category request has already been reviewed"); await this.client.$transaction([this.client.vendorCategoryRequest.update({ where: { id }, data: { status: input.status, reviewReason: input.reason, reviewedBy: session.principal.userId, reviewedAt: new Date() } }), this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: `vendor.category_request.${input.status}`, resourceType: "vendor_category_request", resourceId: id, before: json({ status: current.status }), after: json(input) } })]); return this.categoryRequests(session); }
  private async auditToggle(session: Session, resourceType: string, resourceId: string, active: boolean) { await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: `${resourceType}.toggled`, resourceType, resourceId, after: json({ active }) } }); }
}
