import { useMutation } from "@tanstack/react-query";
import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { colors, radius, spacing } from "../../../ui/tokens";
import { checkServiceability } from "../../operations/delivery-settings.api";

export function DeliveryAvailability({ subtotalMinor = "0" }: { subtotalMinor?: string }) {
  const [location, setLocation] = useState({ division: "Chattogram", district: "Cox's Bazar", upazila: "Teknaf", union: "Hnila" });
  const check = useMutation({ mutationFn: () => checkServiceability({ ...location, subtotalMinor }) });
  return <View style={styles.card}><Text style={styles.eyebrow}>DELIVERY CHECK</Text><Text style={styles.title}>Is delivery available in your area?</Text><View style={styles.fields}>{Object.entries(location).map(([key, value]) => <TextInput accessibilityLabel={key} key={key} onChangeText={(next) => setLocation({ ...location, [key]: next })} placeholder={key} placeholderTextColor={colors.muted} style={styles.input} value={value} />)}</View><Pressable disabled={check.isPending} onPress={() => check.mutate()} style={styles.button}><Text style={styles.buttonText}>{check.isPending ? "Checking…" : "Check availability"}</Text></Pressable>{check.data ? <View style={styles.result}><Text style={styles.resultTitle}>{check.data.serviceable ? "Delivery available" : "Not serviceable"}</Text><Text style={styles.resultText}>৳{(Number(check.data.charge.amountMinor) / 100).toLocaleString("en-BD")} · {check.data.estimatedDays.min}–{check.data.estimatedDays.max} days · {check.data.zone.replaceAll("_", " ")}</Text>{check.data.freeDelivery ? <Text style={styles.free}>Free delivery applies to this selection.</Text> : null}</View> : null}{check.error ? <Text style={styles.error}>{check.error.message}</Text> : null}</View>;
}

const styles = StyleSheet.create({ card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.xl, borderWidth: 1, padding: spacing.lg }, eyebrow: { color: colors.primary, fontSize: 10, fontWeight: "700", letterSpacing: 1 }, title: { color: colors.text, fontSize: 21, fontWeight: "700", marginBottom: spacing.md, marginTop: spacing.xs }, fields: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, input: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, flex: 1, minWidth: 150, padding: spacing.md }, button: { alignItems: "center", alignSelf: "flex-start", backgroundColor: colors.primary, borderRadius: radius.md, marginTop: spacing.md, paddingHorizontal: spacing.lg, paddingVertical: 13 }, buttonText: { color: colors.surface, fontWeight: "700" }, result: { backgroundColor: colors.primarySoft, borderRadius: radius.md, marginTop: spacing.md, padding: spacing.md }, resultTitle: { color: colors.success, fontWeight: "700" }, resultText: { color: colors.text, marginTop: spacing.xs }, free: { color: colors.success, fontSize: 11, fontWeight: "600", marginTop: spacing.xs }, error: { color: colors.danger, marginTop: spacing.sm } });
