import { randomUUID } from "expo-crypto";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { cancelCustomerOrder, createCustomerReturn } from "../operations/operations.api";
import { getCustomerOrder } from "./orders.api";

const money = (minor: string) => `৳${(Number(minor) / 100).toLocaleString("en-BD")}`;

export function CustomerOrderDetailScreen({ id }: { id: string }) {
  const router = useRouter(); const cache = useQueryClient(); const user = firebaseAuth?.currentUser ?? null; const [returnReasons, setReturnReasons] = useState<Record<string, string>>({});
  const order = useQuery({ queryKey: ["orders", "customer", id], queryFn: () => getCustomerOrder(user!, id), enabled: Boolean(user) });
  const refresh = async () => { await cache.invalidateQueries({ queryKey: ["orders"] }); await order.refetch(); };
  const cancel = useMutation({ mutationFn: () => cancelCustomerOrder(user!, id, { reason: "Customer requested cancellation", expectedVersion: order.data!.version }, randomUUID()), onSuccess: refresh });
  const createReturn = useMutation({ mutationFn: (vendorOrderId: string) => { const vendorOrder = order.data!.vendorOrders.find((entry) => entry.id === vendorOrderId)!; return createCustomerReturn(user!, { vendorOrderId, reasonCode: "CUSTOMER_RETURN", reasonDetail: returnReasons[vendorOrderId]?.trim() || null, refundMethod: "ORIGINAL_PAYMENT", items: vendorOrder.items.map((item) => ({ orderItemId: item.id, quantity: item.quantity })) }, randomUUID()); }, onSuccess: async () => { await cache.invalidateQueries({ queryKey: ["returns"] }); router.push("/returns"); } });
  if (!user) return <Screen title="Order details"><Text style={styles.error}>Sign in to view this order.</Text></Screen>;
  if (order.isLoading) return <Screen title="Order details"><ActivityIndicator color={colors.primary} /></Screen>;
  if (!order.data) return <Screen title="Order details"><Text style={styles.error}>{order.error?.message || "Order not found"}</Text></Screen>;
  const cancellable = ["PENDING_PAYMENT", "CONFIRMED", "PROCESSING"].includes(order.data.status) && order.data.vendorOrders.every((entry) => ["PLACED", "ACCEPTED", "PROCESSING"].includes(entry.status));
  return <Screen eyebrow="MY ORDER" title={order.data.orderNumber} description={`Placed ${new Date(order.data.createdAt).toLocaleString()}`}><ModuleCard title={money(order.data.total.amountMinor)} meta={order.data.status.replaceAll("_", " ")}><Text style={styles.muted}>Subtotal {money(order.data.subtotal.amountMinor)} · Delivery {money(order.data.delivery.amountMinor)} · Discount {money(order.data.discount.amountMinor)}</Text><View style={styles.actions}><Pressable onPress={() => router.push(`/order/${id}/tracking` as never)} style={styles.secondary}><Text style={styles.secondaryText}>Track order</Text></Pressable><Pressable onPress={() => router.push(`/order/${id}/invoice` as never)} style={styles.secondary}><Text style={styles.secondaryText}>Invoice</Text></Pressable>{cancellable ? <Pressable disabled={cancel.isPending} onPress={() => cancel.mutate()} style={styles.danger}><Text style={styles.dangerText}>{cancel.isPending ? "Cancelling…" : "Cancel order"}</Text></Pressable> : null}</View>{cancel.error ? <Text style={styles.error}>{cancel.error.message}</Text> : null}</ModuleCard>{order.data.vendorOrders.map((vendorOrder) => <ModuleCard key={vendorOrder.id} title={`${vendorOrder.items.length} item(s)`} meta={vendorOrder.status.replaceAll("_", " ")}>{vendorOrder.items.map((item) => <View key={item.id} style={styles.item}><View style={styles.itemCopy}><Text style={styles.itemName}>{item.productName}</Text><Text style={styles.muted}>{item.sku} · Qty {item.quantity}</Text></View><Text style={styles.itemPrice}>{money(item.lineTotal.amountMinor)}</Text></View>)}{vendorOrder.status === "DELIVERED" ? <View style={styles.returnBox}><Text style={styles.returnTitle}>Need to return these items?</Text><TextInput multiline onChangeText={(reason) => setReturnReasons((current) => ({ ...current, [vendorOrder.id]: reason }))} placeholder="Describe the issue (optional)" placeholderTextColor={colors.muted} style={styles.input} value={returnReasons[vendorOrder.id] ?? ""} /><Pressable disabled={createReturn.isPending} onPress={() => createReturn.mutate(vendorOrder.id)} style={styles.primary}><Text style={styles.primaryText}>{createReturn.isPending ? "Submitting…" : "Request return for all items"}</Text></Pressable></View> : null}</ModuleCard>)}{createReturn.error ? <Text style={styles.error}>{createReturn.error.message}</Text> : null}</Screen>;
}

const styles = StyleSheet.create({ muted: { color: colors.muted, lineHeight: 20 }, actions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, secondary: { borderColor: colors.primary, borderRadius: radius.md, borderWidth: 1, padding: spacing.sm }, secondaryText: { color: colors.primary, fontWeight: "900" }, danger: { borderColor: colors.danger, borderRadius: radius.md, borderWidth: 1, padding: spacing.sm }, dangerText: { color: colors.danger, fontWeight: "900" }, error: { color: colors.danger }, item: { alignItems: "center", borderTopColor: colors.border, borderTopWidth: 1, flexDirection: "row", gap: spacing.sm, paddingVertical: spacing.sm }, itemCopy: { flex: 1 }, itemName: { color: colors.text, fontWeight: "900" }, itemPrice: { color: colors.accent, fontWeight: "900" }, returnBox: { backgroundColor: colors.primarySoft, borderRadius: radius.md, gap: spacing.sm, marginTop: spacing.sm, padding: spacing.md }, returnTitle: { color: colors.text, fontWeight: "900" }, input: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, minHeight: 80, padding: spacing.md, textAlignVertical: "top" }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, padding: spacing.md }, primaryText: { color: "#fff", fontWeight: "900" } });
