import { Ionicons } from "@expo/vector-icons";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getCustomerOrders } from "./orders.api";

export function CustomerOrdersScreen() {
  const router = useRouter(); const user = firebaseAuth?.currentUser ?? null;
  const orders = useQuery({ queryKey: ["orders", "customer"], queryFn: () => getCustomerOrders(user!), enabled: Boolean(user) });
  if (!user) return <Center title="Sign in to see orders" action="Sign in" onPress={() => router.replace("/auth")} />;
  if (orders.isLoading) return <Center loading title="Loading orders" />;
  if (orders.error) return <Center title={orders.error instanceof Error ? orders.error.message : "Could not load orders"} action="Try again" onPress={() => orders.refetch()} />;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.replace("/")}><Text style={styles.link}>‹ Shop</Text></Pressable><Text accessibilityRole="header" style={styles.title}>My orders</Text>{orders.data?.length ? orders.data.map((order) => <Pressable accessibilityRole="button" key={order.id} onPress={() => router.push(`/order/${order.id}/tracking` as never)} style={styles.card}><View style={styles.row}><View><Text style={styles.order}>{order.orderNumber}</Text><Text style={styles.muted}>{new Date(order.createdAt).toLocaleDateString()} · {order.vendorOrderCount} seller{order.vendorOrderCount === 1 ? "" : "s"}</Text></View><Text style={styles.status}>{order.status.replaceAll("_", " ")}</Text></View><View style={styles.row}><Text style={styles.total}>৳{(Number(order.total.amountMinor) / 100).toLocaleString("en-BD")}</Text><View style={styles.track}><Text style={styles.link}>Track order</Text><Ionicons name="chevron-forward" size={18} color={colors.primary} /></View></View></Pressable>) : <Center title="No orders yet" action="Start shopping" onPress={() => router.replace("/")} />}</ScrollView></SafeAreaView>;
}
function Center({ action, loading, onPress, title }: { action?: string; loading?: boolean; onPress?: () => void; title: string }) { return <View style={styles.center}>{loading ? <ActivityIndicator color={colors.primary} size="large" /> : <Ionicons name="bag-handle-outline" size={48} color={colors.primary} />}<Text style={styles.centerTitle}>{title}</Text>{action && onPress ? <Pressable onPress={onPress} style={styles.primary}><Text style={styles.primaryText}>{action}</Text></Pressable> : null}</View>; }
const styles = StyleSheet.create({ safe: { backgroundColor: colors.background, flex: 1 }, page: { alignSelf: "center", gap: spacing.md, maxWidth: 850, padding: spacing.lg, width: "100%" }, title: { color: colors.text, fontSize: 30, fontWeight: "900", marginBottom: spacing.sm }, link: { color: colors.primary, fontWeight: "900" }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, gap: spacing.lg, padding: spacing.lg }, row: { alignItems: "center", flexDirection: "row", gap: spacing.md, justifyContent: "space-between" }, order: { color: colors.text, fontSize: 17, fontWeight: "900" }, muted: { color: colors.muted, marginTop: 4 }, status: { backgroundColor: colors.primarySoft, borderRadius: radius.pill, color: colors.primary, fontSize: 10, fontWeight: "900", overflow: "hidden", paddingHorizontal: 10, paddingVertical: 6 }, total: { color: colors.accent, fontSize: 18, fontWeight: "900" }, track: { alignItems: "center", flexDirection: "row" }, center: { alignItems: "center", flex: 1, gap: spacing.md, justifyContent: "center", minHeight: 360, padding: spacing.xl }, centerTitle: { color: colors.text, fontSize: 24, fontWeight: "900", textAlign: "center" }, primary: { backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: spacing.lg, paddingVertical: 13 }, primaryText: { color: "#fff", fontWeight: "900" } });
