import { Ionicons } from "@expo/vector-icons";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getOrderTracking } from "./orders.api";

export function OrderTrackingScreen({ id }: { id: string }) {
  const router = useRouter(); const user = firebaseAuth?.currentUser ?? null;
  const tracking = useQuery({ queryKey: ["orders", id, "tracking"], queryFn: () => getOrderTracking(user!, id), enabled: Boolean(user), refetchInterval: 30_000 });
  if (!user) return <View style={styles.center}><Text style={styles.error}>Sign in to view tracking.</Text><Pressable onPress={() => router.replace("/auth")}><Text style={styles.link}>Sign in</Text></Pressable></View>;
  if (tracking.isLoading) return <View style={styles.center}><ActivityIndicator color={colors.primary} size="large" /><Text style={styles.muted}>Loading tracking…</Text></View>;
  if (!tracking.data) return <View style={styles.center}><Text style={styles.error}>{tracking.error instanceof Error ? tracking.error.message : "Tracking unavailable"}</Text><Pressable onPress={() => tracking.refetch()}><Text style={styles.link}>Try again</Text></Pressable></View>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.link}>‹ Orders</Text></Pressable><Text accessibilityRole="header" style={styles.title}>{tracking.data.orderNumber}</Text><Text style={styles.subtitle}>Overall status: {tracking.data.status.replaceAll("_", " ")}</Text>{tracking.data.shipments.map((entry) => <View key={entry.vendorOrderId} style={styles.card}><Text style={styles.shop}>{entry.shopName}</Text>{entry.shipment ? <><View style={styles.trackingRow}><Ionicons name="navigate-circle" size={26} color={colors.primary} /><View><Text style={styles.current}>{entry.shipment.status.replaceAll("_", " ")}</Text><Text style={styles.muted}>{entry.shipment.trackingNumber || "Tracking number pending"}</Text></View></View><View>{entry.shipment.events.map((event, index) => <View key={event.id} style={styles.event}><View style={styles.rail}><View style={styles.dot} />{index < entry.shipment!.events.length - 1 ? <View style={styles.line} /> : null}</View><View style={styles.eventCopy}><Text style={styles.eventTitle}>{event.status.replaceAll("_", " ")}</Text><Text style={styles.muted}>{event.description || "Shipment updated"}</Text><Text style={styles.time}>{new Date(event.occurredAt).toLocaleString()}{event.location ? ` · ${event.location}` : ""}</Text></View></View>)}</View></> : <Text style={styles.muted}>Shipment appears when the seller prepares your package.</Text>}</View>)}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { backgroundColor: colors.background, flex: 1 }, page: { alignSelf: "center", gap: spacing.md, maxWidth: 800, padding: spacing.lg, width: "100%" }, title: { color: colors.text, fontSize: 30, fontWeight: "900" }, subtitle: { color: colors.muted, marginBottom: spacing.md }, link: { color: colors.primary, fontWeight: "900" }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, gap: spacing.md, padding: spacing.lg }, shop: { color: colors.text, fontSize: 19, fontWeight: "900" }, trackingRow: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: radius.md, flexDirection: "row", gap: spacing.sm, padding: spacing.md }, current: { color: colors.primaryDark, fontWeight: "900" }, event: { flexDirection: "row", gap: spacing.md, minHeight: 78 }, rail: { alignItems: "center", width: 18 }, dot: { backgroundColor: colors.primary, borderRadius: radius.pill, height: 13, width: 13 }, line: { backgroundColor: colors.border, flex: 1, width: 2 }, eventCopy: { flex: 1 }, eventTitle: { color: colors.text, fontWeight: "900" }, muted: { color: colors.muted, marginTop: 3 }, time: { color: colors.muted, fontSize: 11, marginTop: 5 }, center: { alignItems: "center", backgroundColor: colors.background, flex: 1, gap: spacing.md, justifyContent: "center", padding: spacing.xl }, error: { color: colors.danger } });
