import { Ionicons } from "@expo/vector-icons";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import type { VendorOrderStatus } from "@amiyo/contracts";
import * as Crypto from "expo-crypto";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getVendorOrder, transitionVendorOrder } from "./orders.api";

const actions: Partial<Record<VendorOrderStatus, Array<{ status: VendorOrderStatus; label: string; danger?: boolean }>>> = { PLACED: [{ status: "ACCEPTED", label: "Accept order" }, { status: "REJECTED", label: "Reject", danger: true }], ACCEPTED: [{ status: "PROCESSING", label: "Start processing" }], PROCESSING: [{ status: "READY_TO_SHIP", label: "Ready for pickup" }] };

export function VendorOrderDetailScreen({ id }: { id: string }) {
  const router = useRouter(); const queryClient = useQueryClient(); const user = firebaseAuth?.currentUser ?? null; const [busy, setBusy] = useState<VendorOrderStatus | null>(null); const [error, setError] = useState<string | null>(null);
  const order = useQuery({ queryKey: ["orders", "vendor", id], queryFn: () => getVendorOrder(user!, id), enabled: Boolean(user) });
  async function transition(status: VendorOrderStatus) { if (!user || !order.data) return; setBusy(status); setError(null); try { const updated = await transitionVendorOrder(user, id, { status, expectedVersion: order.data.version }, Crypto.randomUUID()); queryClient.setQueryData(["orders", "vendor", id], updated); await queryClient.invalidateQueries({ queryKey: ["orders", "vendor"] }); } catch (caught) { setError(caught instanceof Error ? caught.message : "Order update failed"); } finally { setBusy(null); } }
  if (order.isLoading) return <View style={styles.center}><ActivityIndicator color={colors.primary} size="large" /></View>;
  if (!order.data) return <View style={styles.center}><Text style={styles.error}>{order.error instanceof Error ? order.error.message : "Order not found"}</Text><Pressable onPress={() => router.back()}><Text style={styles.link}>Go back</Text></Pressable></View>;
  const item = order.data;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.link}>‹ Vendor orders</Text></Pressable><View style={styles.heading}><View><Text accessibilityRole="header" style={styles.title}>{item.orderNumber}</Text><Text style={styles.muted}>{item.shopName}</Text></View><Text style={styles.status}>{item.status.replaceAll("_", " ")}</Text></View>{error ? <Text style={styles.error}>{error}</Text> : null}<View style={styles.card}><Text style={styles.sectionTitle}>Items</Text>{item.items.map((line) => <View key={line.id} style={styles.line}><View style={styles.lineCopy}><Text style={styles.itemName}>{line.productName}</Text><Text style={styles.muted}>{line.sku} · Qty {line.quantity}</Text></View><Text style={styles.amount}>৳{(Number(line.lineTotal.amountMinor) / 100).toLocaleString("en-BD")}</Text></View>)}</View><View style={styles.card}><Text style={styles.sectionTitle}>Fulfillment</Text><Detail label="Dispatch" value={item.dispatchStatus || "Not requested"} /><Detail label="Shipment" value={item.shipment?.status || "Not created"} /><Detail label="Tracking" value={item.shipment?.trackingNumber || "Pending"} /></View><View style={styles.card}><Detail label="Subtotal" value={`৳${(Number(item.subtotal.amountMinor) / 100).toLocaleString("en-BD")}`} /><Detail label="Delivery" value={`৳${(Number(item.delivery.amountMinor) / 100).toLocaleString("en-BD")}`} /><Detail label="Total" value={`৳${(Number(item.total.amountMinor) / 100).toLocaleString("en-BD")}`} strong /></View>{actions[item.status]?.length ? <View style={styles.actions}>{actions[item.status]!.map((action) => <Pressable disabled={Boolean(busy)} key={action.status} onPress={() => transition(action.status)} style={[styles.primary, action.danger && styles.danger, busy && styles.disabled]}>{busy === action.status ? <ActivityIndicator color="#fff" /> : <><Ionicons name={action.status === "READY_TO_SHIP" ? "cube-outline" : "checkmark-circle-outline"} size={19} color="#fff" /><Text style={styles.primaryText}>{action.label}</Text></>}</Pressable>)}</View> : <Text style={styles.notice}>No vendor action is required at this stage.</Text>}</ScrollView></SafeAreaView>;
}
function Detail({ label, strong, value }: { label: string; strong?: boolean; value: string }) { return <View style={styles.detail}><Text style={styles.muted}>{label}</Text><Text style={[styles.value, strong && styles.strong]}>{value}</Text></View>; }
const styles = StyleSheet.create({ safe: { backgroundColor: colors.background, flex: 1 }, page: { alignSelf: "center", gap: spacing.md, maxWidth: 850, padding: spacing.lg, width: "100%" }, link: { color: colors.primary, fontWeight: "900" }, heading: { alignItems: "flex-start", flexDirection: "row", gap: spacing.md, justifyContent: "space-between" }, title: { color: colors.text, fontSize: 29, fontWeight: "900" }, muted: { color: colors.muted, marginTop: 3 }, status: { backgroundColor: colors.primarySoft, borderRadius: radius.pill, color: colors.primary, fontSize: 10, fontWeight: "900", overflow: "hidden", paddingHorizontal: 10, paddingVertical: 6 }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, gap: spacing.md, padding: spacing.lg }, sectionTitle: { color: colors.text, fontSize: 18, fontWeight: "900" }, line: { alignItems: "center", borderTopColor: colors.border, borderTopWidth: 1, flexDirection: "row", gap: spacing.md, justifyContent: "space-between", paddingTop: spacing.md }, lineCopy: { flex: 1 }, itemName: { color: colors.text, fontWeight: "900" }, amount: { color: colors.text, fontWeight: "900" }, detail: { flexDirection: "row", gap: spacing.md, justifyContent: "space-between" }, value: { color: colors.text, fontWeight: "800", textAlign: "right" }, strong: { color: colors.accent, fontSize: 18, fontWeight: "900" }, actions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, flexDirection: "row", gap: spacing.sm, justifyContent: "center", minHeight: 48, paddingHorizontal: spacing.lg }, danger: { backgroundColor: colors.danger }, disabled: { opacity: 0.5 }, primaryText: { color: "#fff", fontWeight: "900" }, notice: { backgroundColor: colors.primarySoft, borderRadius: radius.md, color: colors.primaryDark, padding: spacing.md }, error: { backgroundColor: "#fef2f2", borderRadius: radius.md, color: colors.danger, padding: spacing.md }, center: { alignItems: "center", backgroundColor: colors.background, flex: 1, gap: spacing.md, justifyContent: "center", padding: spacing.xl } });
