import { Ionicons } from "@expo/vector-icons";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { colors, radius, spacing } from "../../ui/tokens";
import { useAuthStore } from "../auth/auth.store";
import { firebaseAuth } from "../auth/firebase";
import { getVendorOrders } from "./orders.api";

export function VendorOrdersScreen() {
  const router = useRouter(); const user = firebaseAuth?.currentUser ?? null; const session = useAuthStore((state) => state.session);
  const allowed = Boolean(session?.permissions.includes("orders:read") && session.principal.vendorIds.length);
  const orders = useQuery({ queryKey: ["orders", "vendor"], queryFn: () => getVendorOrders(user!), enabled: Boolean(user && allowed) });
  if (!user || !allowed) return <View style={styles.center}><Ionicons name="lock-closed-outline" size={48} color={colors.primary} /><Text style={styles.centerTitle}>Vendor order access required</Text><Pressable onPress={() => router.replace("/account")}><Text style={styles.link}>Open account</Text></Pressable></View>;
  if (orders.isLoading) return <View style={styles.center}><ActivityIndicator color={colors.primary} size="large" /></View>;
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.link}>‹ Dashboard</Text></Pressable><Text accessibilityRole="header" style={styles.title}>Vendor orders</Text>{orders.error ? <Text style={styles.error}>{orders.error instanceof Error ? orders.error.message : "Could not load vendor orders"}</Text> : null}{orders.data?.map((order) => <Pressable accessibilityRole="button" key={order.id} onPress={() => router.push(`/vendor/order/${order.id}` as never)} style={styles.card}><View style={styles.row}><View><Text style={styles.order}>{order.orderNumber}</Text><Text style={styles.muted}>{order.shopName} · {order.items.length} lines</Text></View><Text style={styles.status}>{order.status.replaceAll("_", " ")}</Text></View><View style={styles.row}><Text style={styles.total}>৳{(Number(order.total.amountMinor) / 100).toLocaleString("en-BD")}</Text><Ionicons name="chevron-forward" size={20} color={colors.primary} /></View></Pressable>)}{orders.data?.length === 0 ? <Text style={styles.muted}>No vendor orders are assigned yet.</Text> : null}</ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { backgroundColor: colors.background, flex: 1 }, page: { alignSelf: "center", gap: spacing.md, maxWidth: 900, padding: spacing.lg, width: "100%" }, title: { color: colors.text, fontSize: 30, fontWeight: "900", marginBottom: spacing.sm }, link: { color: colors.primary, fontWeight: "900" }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, gap: spacing.lg, padding: spacing.lg }, row: { alignItems: "center", flexDirection: "row", gap: spacing.md, justifyContent: "space-between" }, order: { color: colors.text, fontSize: 17, fontWeight: "900" }, muted: { color: colors.muted, marginTop: 4 }, status: { backgroundColor: colors.accentSoft, borderRadius: radius.pill, color: colors.accent, fontSize: 10, fontWeight: "900", overflow: "hidden", paddingHorizontal: 9, paddingVertical: 6 }, total: { color: colors.text, fontSize: 17, fontWeight: "900" }, error: { backgroundColor: "#fef2f2", borderRadius: radius.md, color: colors.danger, padding: spacing.md }, center: { alignItems: "center", backgroundColor: colors.background, flex: 1, gap: spacing.md, justifyContent: "center", padding: spacing.xl }, centerTitle: { color: colors.text, fontSize: 24, fontWeight: "900", textAlign: "center" } });
