import { CryptoDigestAlgorithm, digest } from "expo-crypto";
import * as DocumentPicker from "expo-document-picker";
import * as ImagePicker from "expo-image-picker";
import type { MediaUploadInput } from "@amiyo/contracts";
import { mediaUploadResultSchema, mediaUploadTicketSchema } from "@amiyo/contracts";
import type { User } from "firebase/auth";

const apiUrl = (process.env.EXPO_PUBLIC_API_URL || "http://localhost:4000").replace(/\/$/, "");
type PickedFile = { fileName: string; mimeType: MediaUploadInput["mimeType"]; size: number; uri: string };
async function authenticated(user: User, path: string, init: RequestInit) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init.headers } }); if (!response.ok) { const problem = await response.json().catch(() => null) as { detail?: string; title?: string } | null; throw new Error(problem?.detail || problem?.title || `Media request failed (${response.status})`); } return response.json(); }
function supportedMime(value: string | null | undefined): MediaUploadInput["mimeType"] { if (["image/jpeg", "image/png", "image/webp", "application/pdf"].includes(value || "")) return value as MediaUploadInput["mimeType"]; throw new Error("Choose a JPEG, PNG, WebP or PDF file"); }
function toHex(buffer: ArrayBuffer) { return Array.from(new Uint8Array(buffer), (byte) => byte.toString(16).padStart(2, "0")).join(""); }
async function upload(user: User, purpose: MediaUploadInput["purpose"], file: PickedFile) { const blob = await (await fetch(file.uri)).blob(); const checksum = toHex(await digest(CryptoDigestAlgorithm.SHA256, await blob.arrayBuffer())); const ticket = mediaUploadTicketSchema.parse(await authenticated(user, "/api/v2/media/uploads", { method: "POST", body: JSON.stringify({ purpose, fileName: file.fileName, mimeType: file.mimeType, size: file.size, checksum }) })); const uploaded = await fetch(ticket.uploadUrl, { method: ticket.method, headers: ticket.headers, body: blob }); if (!uploaded.ok) throw new Error(`Storage upload failed (${uploaded.status})`); const result = mediaUploadResultSchema.parse(await authenticated(user, `/api/v2/media/uploads/${ticket.id}/complete`, { method: "POST" })); return { ...result, checksum, mimeType: file.mimeType, localUri: file.uri }; }

export async function pickAndUploadImage(user: User, purpose: Extract<MediaUploadInput["purpose"], "avatar" | "product" | "shop" | "banner" | "review" | "payment_evidence" | "return_evidence">) { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) throw new Error("Photo library permission is required"); const picked = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], allowsEditing: false, quality: 0.9 }); if (picked.canceled) return null; const asset = picked.assets[0]!; const blob = await (await fetch(asset.uri)).blob(); return upload(user, purpose, { uri: asset.uri, fileName: asset.fileName || `upload-${Date.now()}.jpg`, mimeType: supportedMime(asset.mimeType || blob.type || "image/jpeg"), size: asset.fileSize || blob.size }); }
export async function pickAndUploadDocument(user: User, purpose: Extract<MediaUploadInput["purpose"], "kyc" | "payment_evidence" | "return_evidence" | "support">) { const picked = await DocumentPicker.getDocumentAsync({ type: ["application/pdf", "image/jpeg", "image/png", "image/webp"], copyToCacheDirectory: true }); if (picked.canceled) return null; const asset = picked.assets[0]!; const blob = asset.size ? null : await (await fetch(asset.uri)).blob(); return { ...(await upload(user, purpose, { uri: asset.uri, fileName: asset.name, mimeType: supportedMime(asset.mimeType || blob?.type), size: asset.size || blob!.size })), originalName: asset.name }; }
