import { Ionicons } from "@expo/vector-icons";
import { useQueries } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { ActivityIndicator, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { colors, radius, spacing } from "../../ui/tokens";
import { StoreHeader } from "../home/components/StoreHeader";
import { getProduct } from "./catalog.api";
import { fallbackProductImage } from "./catalog.view-model";
import { useComparisonStore } from "./comparison.store";

const money = (minor?: string) => minor ? `৳${(Number(minor) / 100).toLocaleString("en-BD")}` : "Unavailable";
const attributeText = (value: unknown) => Array.isArray(value) ? value.join(", ") : typeof value === "object" && value !== null ? JSON.stringify(value) : String(value ?? "—");

export function ComparisonScreen() {
  const router = useRouter();
  const { width } = useWindowDimensions();
  const productIds = useComparisonStore((state) => state.productIds);
  const removeProduct = useComparisonStore((state) => state.removeProduct);
  const clearProducts = useComparisonStore((state) => state.clearProducts);
  const queries = useQueries({ queries: productIds.map((id) => ({ queryKey: ["catalog", "product", id], queryFn: () => getProduct(id) })) });
  const products = queries.flatMap((query) => query.data ? [query.data] : []);
  const attributes = [...new Set(products.flatMap((product) => Object.keys(product.dynamicAttributes || {})))].sort();
  const cardWidth = width >= 1000 ? 280 : width >= 700 ? 260 : Math.max(250, width - 64);

  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><StoreHeader desktop={width >= 900} viewportWidth={width} /><View style={styles.content}><View style={styles.headingRow}><View><Text accessibilityRole="header" style={styles.title}>Compare products</Text><Text style={styles.subtitle}>Review price, rating, stock, seller, and specifications side by side.</Text></View>{productIds.length ? <Pressable accessibilityRole="button" onPress={clearProducts} style={styles.clear}><Text style={styles.clearText}>Clear all</Text></Pressable> : null}</View>{queries.some((query) => query.isLoading) ? <ActivityIndicator color={colors.primary} size="large" /> : null}{queries.some((query) => query.error) ? <Text style={styles.error}>Some products could not be loaded. Remove them and try again.</Text> : null}{!productIds.length ? <View style={styles.empty}><Ionicons color={colors.primary} name="git-compare-outline" size={48} /><Text style={styles.emptyTitle}>No products selected</Text><Text style={styles.subtitle}>Open a product and tap Compare. You can compare up to four products.</Text><Pressable onPress={() => router.push("/search")} style={styles.primary}><Text style={styles.primaryText}>Browse products</Text></Pressable></View> : <ScrollView horizontal showsHorizontalScrollIndicator><View style={styles.cards}>{products.map((product) => { const variant = product.variants[0]; return <View key={product.id} style={[styles.card, { width: cardWidth }]}><Pressable accessibilityLabel={`Remove ${product.name}`} onPress={() => removeProduct(product.id)} style={styles.remove}><Ionicons color={colors.danger} name="close-circle" size={24} /></Pressable><Pressable onPress={() => router.push(`/product/${product.slug}` as never)}><Image source={{ uri: product.media[0]?.url || product.thumbnailUrl || fallbackProductImage }} style={styles.image} /><Text numberOfLines={2} style={styles.productName}>{product.name}</Text></Pressable><ComparisonRow label="Price" value={money(variant?.price.amountMinor)} highlight /><ComparisonRow label="Brand" value={product.brand || "Not specified"} /><ComparisonRow label="Seller" value={product.shopName} /><ComparisonRow label="Rating" value={`${product.rating.toFixed(1)} / 5 (${product.reviewCount})`} /><ComparisonRow label="Stock" value={variant ? `${variant.availableQuantity} available` : "Unavailable"} /><ComparisonRow label="Variants" value={String(product.variants.length)} />{attributes.map((key) => <ComparisonRow key={key} label={key.replace(/[_-]+/g, " ")} value={attributeText(product.dynamicAttributes?.[key])} />)}<Pressable onPress={() => router.push(`/product/${product.slug}` as never)} style={styles.primary}><Text style={styles.primaryText}>View product</Text></Pressable></View>; })}</View></ScrollView>}<Text style={styles.count}>{productIds.length} of 4 products selected</Text></View></ScrollView></SafeAreaView>;
}

function ComparisonRow({ highlight, label, value }: { highlight?: boolean; label: string; value: string }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={[styles.value, highlight && styles.highlight]}>{value}</Text></View>; }

const styles = StyleSheet.create({ safe: { backgroundColor: colors.background, flex: 1 }, page: { minHeight: "100%" }, content: { alignSelf: "center", maxWidth: 1208, padding: spacing.lg, width: "100%" }, headingRow: { alignItems: "flex-start", flexDirection: "row", flexWrap: "wrap", gap: spacing.md, justifyContent: "space-between", marginBottom: spacing.xl }, title: { color: colors.text, fontSize: 30, fontWeight: "700" }, subtitle: { color: colors.muted, lineHeight: 21, marginTop: spacing.xs, maxWidth: 620 }, clear: { borderColor: colors.danger, borderRadius: radius.md, borderWidth: 1, paddingHorizontal: spacing.md, paddingVertical: spacing.sm }, clearText: { color: colors.danger, fontWeight: "600" }, error: { color: colors.danger, marginBottom: spacing.md }, empty: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.xl, borderWidth: 1, gap: spacing.sm, padding: spacing.xl }, emptyTitle: { color: colors.text, fontSize: 21, fontWeight: "700" }, cards: { alignItems: "stretch", flexDirection: "row", gap: spacing.md, paddingBottom: spacing.md }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.xl, borderWidth: 1, overflow: "hidden", padding: spacing.md }, remove: { alignSelf: "flex-end", marginBottom: spacing.xs }, image: { aspectRatio: 1.2, backgroundColor: colors.primarySoft, borderRadius: radius.lg, width: "100%" }, productName: { color: colors.text, fontSize: 18, fontWeight: "700", marginBottom: spacing.md, marginTop: spacing.md, minHeight: 44 }, row: { borderTopColor: colors.border, borderTopWidth: 1, gap: 3, minHeight: 65, paddingVertical: spacing.sm }, label: { color: colors.muted, fontSize: 11, fontWeight: "600", textTransform: "capitalize" }, value: { color: colors.text, fontWeight: "700" }, highlight: { color: colors.accent, fontSize: 20, fontWeight: "700" }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, marginTop: spacing.md, padding: spacing.md }, primaryText: { color: "#fff", fontWeight: "700" }, count: { color: colors.muted, marginTop: spacing.md, textAlign: "center" } });
