import { randomUUID } from "node:crypto";
import { Prisma, type PrismaClient } from "@prisma/client";
import type { AnswerInput, ChatMessageInput, ChatThreadInput, ContentModerationInput, CreatePromotion, NewsletterBroadcastInput, NewsletterSubscribeInput, ProductReportInput, QuestionInput, ReviewInput, Session, VendorReviewReplyInput } from "@amiyo/contracts";
import { notificationChannels } from "@amiyo/domain";
import { ApiProblem } from "../../middleware/api-problem.js";

const money = (amountMinor: bigint, currency = "BDT") => ({ amountMinor: amountMinor.toString(), currency });
const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
const profileName = (profile: { displayName: string | null; firstName: string | null } | null) => profile?.displayName || profile?.firstName || "Amiyo customer";
function mediaUrl(key: string | undefined) { if (!key) return null; if (/^https?:\/\//.test(key)) return key; const base = process.env.OBJECT_STORAGE_PUBLIC_URL?.replace(/\/$/, ""); return base ? `${base}/${key}` : null; }

export class EngagementService {
  constructor(private readonly client: PrismaClient) {}

  private async queueNewsletter(transaction: Prisma.TransactionClient, broadcastId: string, availableAt: Date, status: "queued" | "scheduled") {
    const subscribers = await transaction.newsletterSubscriber.findMany({ where: { active: true }, select: { id: true, email: true } });
    await transaction.newsletterDelivery.createMany({ data: subscribers.map((subscriber) => ({ broadcastId, subscriberId: subscriber.id, email: subscriber.email })), skipDuplicates: true });
    const deliveries = await transaction.newsletterDelivery.findMany({ where: { broadcastId }, select: { id: true } });
    await transaction.outboxEvent.createMany({ data: deliveries.map((delivery) => ({ aggregateType: "newsletter_delivery", aggregateId: delivery.id, eventType: "newsletter.delivery.requested", idempotencyKey: `newsletter-delivery:${delivery.id}`, payload: { newsletterDeliveryId: delivery.id }, availableAt })), skipDuplicates: true });
    await transaction.newsletterBroadcast.update({ where: { id: broadcastId }, data: { status: deliveries.length ? status : "sent", recipientCount: deliveries.length } });
  }

  private async notify(userId: string, eventType: keyof typeof import("@amiyo/domain").notificationMatrix, title: string, body: string, href: string, key: string) {
    const channels = notificationChannels(eventType); return this.client.$transaction(async (transaction) => { const notification = await transaction.notification.upsert({ where: { idempotencyKey: key }, update: {}, create: { userId, type: eventType, title, body, data: { href }, idempotencyKey: key, deliveries: { create: channels.map((channel) => ({ channel: channel.toLowerCase(), status: channel === "IN_APP" ? "DELIVERED" : "PENDING", ...(channel === "IN_APP" ? { deliveredAt: new Date() } : {}) })) } }, include: { deliveries: true } }); for (const delivery of notification.deliveries.filter((item) => item.status === "PENDING")) await transaction.outboxEvent.upsert({ where: { idempotencyKey: `notification-delivery:${delivery.id}` }, create: { aggregateType: "notification_delivery", aggregateId: delivery.id, eventType: "notification.delivery.requested", idempotencyKey: `notification-delivery:${delivery.id}`, payload: { notificationDeliveryId: delivery.id } }, update: {} }); return notification; });
  }

  private async defaultWishlist(userId: string) {
    const existing = await this.client.wishlist.findFirst({ where: { userId, isDefault: true } }); if (existing) return existing;
    try { return await this.client.wishlist.create({ data: { userId, isDefault: true } }); } catch { return this.client.wishlist.findFirstOrThrow({ where: { userId, isDefault: true } }); }
  }

  async wishlist(userId: string) {
    const list = await this.defaultWishlist(userId); const loaded = await this.client.wishlist.findUniqueOrThrow({ where: { id: list.id }, include: { share: true, items: { orderBy: { createdAt: "desc" }, include: { product: { include: { media: { orderBy: { displayOrder: "asc" }, take: 1 }, variants: { where: { active: true }, orderBy: { priceMinor: "asc" }, take: 1 } } } } } } });
    return { id: loaded.id, name: loaded.name, isDefault: loaded.isDefault, shareUrl: loaded.share && (!loaded.share.expiresAt || loaded.share.expiresAt > new Date()) ? `${process.env.APP_PUBLIC_URL || "http://localhost:8081"}/wishlist/shared/${loaded.share.shareToken}` : null, items: loaded.items.map((item) => ({ productId: item.productId, name: item.product.name, slug: item.product.slug, thumbnailUrl: mediaUrl(item.product.media[0]?.storageKey), price: item.product.variants[0] ? money(item.product.variants[0].priceMinor, item.product.variants[0].currency) : null, addedAt: item.createdAt.toISOString() })) };
  }

  async addWishlistItem(userId: string, productId: string) { const list = await this.defaultWishlist(userId); const product = await this.client.product.findFirst({ where: { id: productId, status: "APPROVED" } }); if (!product) throw new ApiProblem(404, "PRODUCT_NOT_FOUND", "Product not found"); await this.client.wishlistItem.upsert({ where: { wishlistId_productId: { wishlistId: list.id, productId } }, create: { wishlistId: list.id, productId }, update: {} }); return this.wishlist(userId); }
  async removeWishlistItem(userId: string, productId: string) { const list = await this.defaultWishlist(userId); await this.client.wishlistItem.deleteMany({ where: { wishlistId: list.id, productId } }); return this.wishlist(userId); }
  async shareWishlist(userId: string) { const list = await this.defaultWishlist(userId); await this.client.sharedWishlist.upsert({ where: { wishlistId: list.id }, create: { wishlistId: list.id, shareToken: randomUUID(), expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60_000) }, update: { shareToken: randomUUID(), expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60_000) } }); return this.wishlist(userId); }
  async unshareWishlist(userId: string) { const list = await this.defaultWishlist(userId); await this.client.sharedWishlist.deleteMany({ where: { wishlistId: list.id } }); return this.wishlist(userId); }
  async sharedWishlist(token: string) { const shared = await this.client.sharedWishlist.findFirst({ where: { shareToken: token, OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }] }, include: { wishlist: { include: { items: { include: { product: { include: { variants: { where: { active: true }, take: 1 } } } } } } } } }); if (!shared) throw new ApiProblem(404, "WISHLIST_SHARE_NOT_FOUND", "Shared wishlist not found"); return { name: shared.wishlist.name, items: shared.wishlist.items.map((item) => ({ productId: item.productId, name: item.product.name, slug: item.product.slug, price: item.product.variants[0] ? money(item.product.variants[0].priceMinor, item.product.variants[0].currency) : null })) }; }

  async alerts(userId: string) { const rows = await this.client.stockAlert.findMany({ where: { userId, active: true }, include: { product: true }, orderBy: { createdAt: "desc" } }); return rows.map((row) => ({ id: row.id, productId: row.productId, productName: row.product.name, target: row.targetMinor === null ? null : money(row.targetMinor), createdAt: row.createdAt.toISOString() })); }
  async saveAlert(userId: string, productId: string, targetMinor?: string | null) { const product = await this.client.product.findFirst({ where: { id: productId, status: "APPROVED" } }); if (!product) throw new ApiProblem(404, "PRODUCT_NOT_FOUND", "Product not found"); await this.client.stockAlert.upsert({ where: { userId_productId: { userId, productId } }, create: { userId, productId, targetMinor: targetMinor ? BigInt(targetMinor) : null }, update: { targetMinor: targetMinor ? BigInt(targetMinor) : null, active: true } }); return this.alerts(userId); }
  async removeAlert(userId: string, productId: string) { await this.client.stockAlert.updateMany({ where: { userId, productId }, data: { active: false } }); return this.alerts(userId); }

  async productReviews(productId: string) { const rows = await this.client.review.findMany({ where: { productId, status: "published" }, include: { user: { include: { profile: true } } }, orderBy: { createdAt: "desc" }, take: 100 }); return rows.map((row) => ({ id: row.id, productId: row.productId, rating: row.rating, title: row.title, body: row.body, verifiedPurchase: Boolean(row.orderItemId), authorName: profileName(row.user.profile), createdAt: row.createdAt.toISOString() })); }
  async myReviews(session: Session) { if (!session.permissions.includes("reviews:manage")) throw new ApiProblem(403, "REVIEW_FORBIDDEN", "Review access is not allowed"); const rows = await this.client.review.findMany({ where: { userId: session.principal.userId }, include: { product: true }, orderBy: { createdAt: "desc" }, take: 100 }); return rows.map((row) => ({ id: row.id, productId: row.productId, productName: row.product.name, productSlug: row.product.slug, rating: row.rating, title: row.title, body: row.body, verifiedPurchase: Boolean(row.orderItemId), authorName: session.profile.displayName || "Amiyo customer", createdAt: row.createdAt.toISOString() })); }
  async createReview(session: Session, input: ReviewInput) { if (!session.permissions.includes("reviews:manage")) throw new ApiProblem(403, "REVIEW_FORBIDDEN", "Review access is not allowed"); const item = await this.client.orderItem.findFirst({ where: { id: input.orderItemId, order: { userId: session.principal.userId, status: "DELIVERED" } } }); if (!item) throw new ApiProblem(409, "VERIFIED_PURCHASE_REQUIRED", "A delivered order item is required"); if (await this.client.review.findUnique({ where: { orderItemId: item.id } })) throw new ApiProblem(409, "REVIEW_ALREADY_EXISTS", "This order item has already been reviewed"); const created = await this.client.review.create({ data: { userId: session.principal.userId, productId: item.productId, orderItemId: item.id, rating: input.rating, title: input.title ?? null, body: input.body ?? null } }); return { id: created.id, productId: created.productId, rating: created.rating, title: created.title, body: created.body, verifiedPurchase: true, authorName: session.profile.displayName || "Amiyo customer", createdAt: created.createdAt.toISOString() }; }

  async questions(productId: string) { const rows = await this.client.question.findMany({ where: { productId, status: { not: "hidden" } }, include: { user: { include: { profile: true } }, answers: { include: { user: { include: { profile: true } } }, orderBy: { createdAt: "asc" } } }, orderBy: { createdAt: "desc" }, take: 100 }); return rows.map((row) => ({ id: row.id, productId: row.productId, body: row.body, status: row.status, authorName: profileName(row.user.profile), createdAt: row.createdAt.toISOString(), answers: row.answers.map((answer) => ({ id: answer.id, body: answer.body, accepted: answer.accepted, authorName: profileName(answer.user.profile), createdAt: answer.createdAt.toISOString() })) })); }
  async createQuestion(session: Session, productId: string, input: QuestionInput) { const product = await this.client.product.findFirst({ where: { id: productId, status: "APPROVED" } }); if (!product) throw new ApiProblem(404, "PRODUCT_NOT_FOUND", "Product not found"); const row = await this.client.question.create({ data: { userId: session.principal.userId, productId, body: input.body } }); return { id: row.id, productId, body: row.body, status: row.status, authorName: session.profile.displayName || "Amiyo customer", createdAt: row.createdAt.toISOString(), answers: [] }; }
  async reportProduct(session: Session, productId: string, input: ProductReportInput) { const product = await this.client.product.findFirst({ where: { id: productId, status: "APPROVED" } }); if (!product) throw new ApiProblem(404, "PRODUCT_NOT_FOUND", "Product not found"); const row = await this.client.$transaction(async (transaction) => { const trustCase = await transaction.trustCase.create({ data: { subjectType: "product", subjectId: productId, caseType: `product_report:${input.reason}`, severity: ["counterfeit", "unsafe_product", "prohibited_content"].includes(input.reason) ? "high" : "medium", summary: input.details, metadata: json({ reporterUserId: session.principal.userId, productName: product.name }), actions: { create: { actionType: "REPORT_RECEIVED", actorUserId: session.principal.userId, reason: input.details, metadata: json({ reason: input.reason }) } } } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "customer", action: "catalog.product.reported", resourceType: "product", resourceId: productId, after: json({ trustCaseId: trustCase.id, reason: input.reason }) } }); return trustCase; }); return { id: row.id, status: row.status }; }
  async answerQuestion(session: Session, questionId: string, input: AnswerInput) { const question = await this.client.question.findUnique({ where: { id: questionId }, include: { product: true } }); if (!question) throw new ApiProblem(404, "QUESTION_NOT_FOUND", "Question not found"); if (!session.principal.vendorIds.includes(question.product.vendorId) && !session.principal.roles.some((role) => ["OPERATIONS_ADMIN", "SUPER_ADMIN"].includes(role))) throw new ApiProblem(403, "QUESTION_ANSWER_FORBIDDEN", "Only this product vendor can answer"); const answer = await this.client.answer.create({ data: { questionId, userId: session.principal.userId, body: input.body } }); await this.client.question.update({ where: { id: questionId }, data: { status: "answered" } }); await this.notify(question.userId, "question.answered", "Your question was answered", input.body.slice(0, 160), `/product/${question.productId}`, `question-answer:${answer.id}`); return answer; }
  async vendorReviews(session: Session) { const vendorId = session.principal.vendorIds[0]; if (!vendorId || !session.permissions.includes("vendor:read")) throw new ApiProblem(403, "VENDOR_REQUIRED", "Vendor access is required"); const rows = await this.client.review.findMany({ where: { product: { vendorId } }, include: { product: true, user: { include: { profile: true } } }, orderBy: { createdAt: "desc" }, take: 100 }); return rows.map((row) => ({ id: row.id, productId: row.productId, productName: row.product.name, productSlug: row.product.slug, rating: row.rating, title: row.title, body: row.body, status: row.status, verifiedPurchase: Boolean(row.orderItemId), authorName: profileName(row.user.profile), vendorReply: row.vendorReply, vendorRepliedAt: row.vendorRepliedAt?.toISOString() ?? null, createdAt: row.createdAt.toISOString() })); }
  async replyToReview(session: Session, reviewId: string, input: VendorReviewReplyInput) { const vendorId = session.principal.vendorIds[0]; if (!vendorId || !session.permissions.includes("support:manage")) throw new ApiProblem(403, "VENDOR_SUPPORT_REQUIRED", "Vendor support access is required"); const review = await this.client.review.findFirst({ where: { id: reviewId, product: { vendorId } } }); if (!review) throw new ApiProblem(404, "REVIEW_NOT_FOUND", "Review not found for this seller"); await this.client.$transaction(async (transaction) => { await transaction.review.update({ where: { id: reviewId }, data: { vendorReply: input.body, vendorRepliedAt: new Date(), version: { increment: 1 } } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "vendor", action: "engagement.review.replied", resourceType: "review", resourceId: reviewId, after: { replyLength: input.body.length } } }); }); return this.vendorReviews(session); }
  async vendorQuestions(session: Session) { const vendorId = session.principal.vendorIds[0]; if (!vendorId || !session.permissions.includes("support:manage")) throw new ApiProblem(403, "VENDOR_REQUIRED", "Vendor support access is required"); const rows = await this.client.question.findMany({ where: { product: { vendorId } }, include: { product: true, user: { include: { profile: true } }, answers: { include: { user: { include: { profile: true } } }, orderBy: { createdAt: "asc" } } }, orderBy: { createdAt: "desc" }, take: 100 }); return rows.map((row) => ({ id: row.id, productId: row.productId, productName: row.product.name, body: row.body, status: row.status, authorName: profileName(row.user.profile), createdAt: row.createdAt.toISOString(), answers: row.answers.map((answer) => ({ id: answer.id, body: answer.body, accepted: answer.accepted, authorName: profileName(answer.user.profile), createdAt: answer.createdAt.toISOString() })) })); }
  async adminReviews(session: Session) { if (!session.permissions.includes("admin:read")) throw new ApiProblem(403, "ADMIN_REQUIRED", "Admin access is required"); const rows = await this.client.review.findMany({ include: { product: true, user: { include: { profile: true } } }, orderBy: { createdAt: "desc" }, take: 100 }); return rows.map((row) => ({ id: row.id, productId: row.productId, productName: row.product.name, productSlug: row.product.slug, rating: row.rating, title: row.title, body: row.body, status: row.status, verifiedPurchase: Boolean(row.orderItemId), authorName: profileName(row.user.profile), createdAt: row.createdAt.toISOString() })); }
  async moderateReview(session: Session, id: string, input: ContentModerationInput) { if (!session.permissions.includes("admin:manage")) throw new ApiProblem(403, "ADMIN_REQUIRED", "Admin management access is required"); const row = await this.client.review.update({ where: { id }, data: { status: input.status, version: { increment: 1 } } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "content.review.moderated", resourceType: "review", resourceId: id, after: { status: input.status, reason: input.reason } } }); return row; }
  async adminQuestions(session: Session) { if (!session.permissions.includes("admin:read")) throw new ApiProblem(403, "ADMIN_REQUIRED", "Admin access is required"); const rows = await this.client.question.findMany({ include: { product: true, user: { include: { profile: true } }, answers: { include: { user: { include: { profile: true } } }, orderBy: { createdAt: "asc" } } }, orderBy: { createdAt: "desc" }, take: 100 }); return rows.map((row) => ({ id: row.id, productId: row.productId, productName: row.product.name, body: row.body, status: row.status, authorName: profileName(row.user.profile), createdAt: row.createdAt.toISOString(), answers: row.answers.map((answer) => ({ id: answer.id, body: answer.body, accepted: answer.accepted, authorName: profileName(answer.user.profile), createdAt: answer.createdAt.toISOString() })) })); }
  async moderateQuestion(session: Session, id: string, input: ContentModerationInput) { if (!session.permissions.includes("admin:manage")) throw new ApiProblem(403, "ADMIN_REQUIRED", "Admin management access is required"); const row = await this.client.question.update({ where: { id }, data: { status: input.status } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "content.question.moderated", resourceType: "question", resourceId: id, after: { status: input.status, reason: input.reason } } }); return row; }

  async notifications(userId: string) { const rows = await this.client.notification.findMany({ where: { userId }, orderBy: { createdAt: "desc" }, take: 100 }); return rows.map((row) => { const data = row.data && typeof row.data === "object" && !Array.isArray(row.data) ? row.data as Record<string, unknown> : {}; return { id: row.id, type: row.type, title: row.title, body: row.body, href: typeof data.href === "string" ? data.href : null, readAt: row.readAt?.toISOString() ?? null, createdAt: row.createdAt.toISOString() }; }); }
  async readNotification(userId: string, id: string) { const result = await this.client.notification.updateMany({ where: { id, userId }, data: { readAt: new Date() } }); if (!result.count) throw new ApiProblem(404, "NOTIFICATION_NOT_FOUND", "Notification not found"); return this.notifications(userId); }

  async createThread(session: Session, input: ChatThreadInput) { const existing = await this.client.chatThread.findFirst({ where: { vendorId: input.vendorId, status: "open", participants: { some: { userId: session.principal.userId } } }, orderBy: { updatedAt: "desc" }, select: { id: true } }); if (existing) return existing; const vendor = await this.client.vendor.findFirst({ where: { id: input.vendorId, status: "APPROVED" }, include: { members: { where: { status: "active" } } } }); if (!vendor) throw new ApiProblem(404, "VENDOR_NOT_FOUND", "Vendor not found"); const recipients = vendor.members.filter((member) => member.userId !== session.principal.userId); if (!recipients.length) throw new ApiProblem(409, "VENDOR_CHAT_UNAVAILABLE", "This seller is not available for chat"); const thread = await this.client.chatThread.create({ data: { vendorId: vendor.id, subject: input.subject, participants: { create: [{ userId: session.principal.userId, role: "customer" }, ...recipients.map((member) => ({ userId: member.userId, role: "vendor" }))] } }, select: { id: true } }); return thread; }
  async threads(userId: string) { const rows = await this.client.chatThread.findMany({ where: { participants: { some: { userId } } }, include: { participants: { where: { userId }, select: { joinedAt: true, lastReadAt: true } }, messages: { orderBy: { createdAt: "desc" }, take: 30 } }, orderBy: { updatedAt: "desc" }, take: 100 }); return Promise.all(rows.map(async (row) => { const participant = row.participants[0]; const unreadCount = participant ? await this.client.chatMessage.count({ where: { threadId: row.id, senderId: { not: userId }, createdAt: { gt: participant.lastReadAt ?? participant.joinedAt } } }) : 0; return { id: row.id, vendorId: row.vendorId, subject: row.subject, status: row.status, updatedAt: row.updatedAt.toISOString(), lastReadAt: participant?.lastReadAt?.toISOString() ?? null, unreadCount, messages: [...row.messages].reverse().map((message) => ({ id: message.id, senderId: message.senderId, body: message.body, createdAt: message.createdAt.toISOString() })) }; })); }
  async readThread(userId: string, threadId: string) { const result = await this.client.chatParticipant.updateMany({ where: { threadId, userId }, data: { lastReadAt: new Date() } }); if (!result.count) throw new ApiProblem(404, "CHAT_THREAD_NOT_FOUND", "Chat thread not found"); }
  async message(session: Session, threadId: string, input: ChatMessageInput) { const participant = await this.client.chatParticipant.findUnique({ where: { threadId_userId: { threadId, userId: session.principal.userId } } }); if (!participant) throw new ApiProblem(403, "CHAT_FORBIDDEN", "You are not a participant in this chat"); const message = await this.client.chatMessage.create({ data: { threadId, senderId: session.principal.userId, body: input.body } }); await this.client.chatThread.update({ where: { id: threadId }, data: { updatedAt: new Date() } }); const recipients = await this.client.chatParticipant.findMany({ where: { threadId, userId: { not: session.principal.userId } } }); await Promise.all(recipients.map((recipient) => this.notify(recipient.userId, "chat.message.created", "New message", input.body.slice(0, 160), `/messages/${threadId}`, `chat-message:${message.id}:${recipient.userId}`))); return message; }

  async loyalty(userId: string) { const account = await this.client.loyaltyAccount.upsert({ where: { userId }, create: { userId }, update: {}, include: { transactions: { orderBy: { createdAt: "desc" }, take: 100 } } }); return { id: account.id, pointsBalance: account.pointsBalance.toString(), version: account.version, transactions: account.transactions.map((row) => ({ id: row.id, points: row.points.toString(), entryType: row.entryType, referenceType: row.referenceType, referenceId: row.referenceId, createdAt: row.createdAt.toISOString() })) }; }

  async growthFeed() { const now = new Date(); const [banners, coupons, campaigns, flashSales] = await Promise.all([this.client.banner.findMany({ where: { active: true, startsAt: { lte: now }, endsAt: { gt: now } }, orderBy: [{ placement: "asc" }, { displayOrder: "asc" }], take: 30 }), this.client.coupon.findMany({ where: { active: true, startsAt: { lte: now }, endsAt: { gt: now } }, orderBy: { startsAt: "desc" }, take: 20 }), this.client.campaign.findMany({ where: { status: "active", startsAt: { lte: now }, endsAt: { gt: now } }, orderBy: { startsAt: "desc" }, take: 20 }), this.client.flashSale.findMany({ where: { status: "active", startsAt: { lte: now }, endsAt: { gt: now } }, include: { products: true }, orderBy: { startsAt: "asc" }, take: 10 })]); return { banners: banners.map((row) => ({ id: row.id, placement: row.placement, title: row.title, subtitle: row.subtitle, imageUrl: mediaUrl(row.storageKey), mobileImageUrl: mediaUrl(row.mobileStorageKey ?? undefined), ctaLabel: row.ctaLabel, badgeText: row.badgeText, targetType: row.targetType, targetValue: row.targetValue, startsAt: row.startsAt.toISOString(), endsAt: row.endsAt.toISOString() })), coupons: coupons.map((row) => ({ id: row.id, code: row.code, discountType: row.discountType, value: row.value, minimumSpend: money(row.minimumSpendMinor, row.currency), startsAt: row.startsAt.toISOString(), endsAt: row.endsAt.toISOString() })), campaigns: campaigns.map((row) => ({ id: row.id, name: row.name, slug: row.slug, href: `/campaign/${row.slug}`, startsAt: row.startsAt.toISOString(), endsAt: row.endsAt.toISOString() })), flashSales: flashSales.map((row) => ({ id: row.id, name: row.name, href: `/flash-sale/${row.id}`, startsAt: row.startsAt.toISOString(), endsAt: row.endsAt.toISOString(), products: row.products.map((product) => ({ productId: product.productId, price: money(product.priceMinor), quantityRemaining: product.quantityLimit === null ? null : Math.max(0, product.quantityLimit - product.soldCount) })) })) };
  }

  async promotions(session: Session) { if (!session.permissions.includes("admin:manage")) throw new ApiProblem(403, "PROMOTION_FORBIDDEN", "Promotion management is not allowed"); return this.client.promotion.findMany({ include: { rules: true }, orderBy: [{ priority: "desc" }, { id: "asc" }], take: 100 }); }
  async createPromotion(session: Session, input: CreatePromotion) { if (!session.permissions.includes("admin:manage")) throw new ApiProblem(403, "PROMOTION_FORBIDDEN", "Promotion management is not allowed"); const promotion = await this.client.promotion.create({ data: { name: input.name, priority: input.priority, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), rules: { create: { ruleType: "ORDER_DISCOUNT", conditions: json({ minimumSubtotalMinor: input.candidate.minimumSubtotalMinor }), effects: json(input.candidate.effect) } } }, include: { rules: true } }); await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "promotion.created", resourceType: "promotion", resourceId: promotion.id, after: json(input) } }); return promotion; }
  async subscribeNewsletter(input: NewsletterSubscribeInput) { const row = await this.client.newsletterSubscriber.upsert({ where: { email: input.email }, create: { email: input.email, source: input.source, unsubscribeToken: randomUUID() }, update: { active: true, unsubscribedAt: null, source: input.source } }); return { id: row.id, email: row.email, active: row.active }; }
  async unsubscribeNewsletter(token: string) { const result = await this.client.newsletterSubscriber.updateMany({ where: { unsubscribeToken: token }, data: { active: false, unsubscribedAt: new Date() } }); if (!result.count) throw new ApiProblem(404, "NEWSLETTER_SUBSCRIBER_NOT_FOUND", "Newsletter subscription not found"); return { unsubscribed: true }; }
  async newsletterWorkspace(session: Session) { if (!session.permissions.includes("admin:read")) throw new ApiProblem(403, "ADMIN_REQUIRED", "Admin access is required"); const [subscribers, broadcasts, activeSubscriberCount] = await Promise.all([this.client.newsletterSubscriber.findMany({ orderBy: { createdAt: "desc" }, take: 200 }), this.client.newsletterBroadcast.findMany({ orderBy: { createdAt: "desc" }, take: 100 }), this.client.newsletterSubscriber.count({ where: { active: true } })]); return { activeSubscriberCount, subscribers: subscribers.map((row) => ({ id: row.id, email: row.email, source: row.source, active: row.active, createdAt: row.createdAt.toISOString(), unsubscribedAt: row.unsubscribedAt?.toISOString() ?? null })), broadcasts: broadcasts.map((row) => ({ id: row.id, subject: row.subject, previewText: row.previewText, body: row.body, status: row.status, scheduledAt: row.scheduledAt?.toISOString() ?? null, recipientCount: row.recipientCount, sentCount: row.sentCount, failedCount: row.failedCount, openCount: row.openCount, createdAt: row.createdAt.toISOString() })) }; }
  async createNewsletterBroadcast(session: Session, input: NewsletterBroadcastInput) { if (!session.permissions.includes("admin:manage")) throw new ApiProblem(403, "ADMIN_REQUIRED", "Admin management access is required"); await this.client.$transaction(async (transaction) => { const scheduledAt = input.scheduledAt ? new Date(input.scheduledAt) : null; const row = await transaction.newsletterBroadcast.create({ data: { subject: input.subject, previewText: input.previewText ?? null, body: input.body, status: scheduledAt ? "scheduled" : "draft", scheduledAt, createdBy: session.principal.userId } }); if (scheduledAt) await this.queueNewsletter(transaction, row.id, scheduledAt, "scheduled"); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "newsletter.broadcast.created", resourceType: "newsletter_broadcast", resourceId: row.id, after: json({ subject: input.subject, scheduledAt: input.scheduledAt ?? null }) } }); }); return this.newsletterWorkspace(session); }
  async sendNewsletterBroadcast(session: Session, id: string) { if (!session.permissions.includes("admin:manage")) throw new ApiProblem(403, "ADMIN_REQUIRED", "Admin management access is required"); await this.client.$transaction(async (transaction) => { const broadcast = await transaction.newsletterBroadcast.findUnique({ where: { id } }); if (!broadcast) throw new ApiProblem(404, "NEWSLETTER_BROADCAST_NOT_FOUND", "Newsletter broadcast not found"); if (["queued", "sending", "sent", "partial"].includes(broadcast.status)) throw new ApiProblem(409, "NEWSLETTER_BROADCAST_ALREADY_SENT", "Newsletter broadcast is already queued or sent"); await this.queueNewsletter(transaction, id, new Date(), "queued"); await transaction.outboxEvent.updateMany({ where: { aggregateType: "newsletter_delivery", eventType: "newsletter.delivery.requested", aggregateId: { in: (await transaction.newsletterDelivery.findMany({ where: { broadcastId: id }, select: { id: true } })).map((delivery) => delivery.id) }, status: "pending" }, data: { availableAt: new Date() } }); await transaction.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action: "newsletter.broadcast.queued", resourceType: "newsletter_broadcast", resourceId: id } }); }); return this.newsletterWorkspace(session); }
}
