import { Ionicons } from "@expo/vector-icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useMemo, useState, type ReactNode } from "react";
import { ActivityIndicator, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from "react-native";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getLogisticsOverview, saveLogisticsResource, type LogisticsOverview, type LogisticsShipment } from "./logistics.api";

const tabs = [
  ["work", "My Orders", "clipboard-outline"], ["zones", "Zones", "location-outline"], ["couriers", "Couriers", "car-outline"], ["ready", "Ready to Ship", "cube-outline"],
  ["manifest", "Manifest", "document-text-outline"], ["parcels", "Parcels", "cube-outline"], ["staff", "Pickup Staff", "people-outline"], ["rules", "Fee Rules", "calculator-outline"],
  ["cod", "COD Float", "cash-outline"], ["failed", "Failed Delivery", "warning-outline"]
] as const;
type Tab = typeof tabs[number][0];
const money = (minor: string) => `৳${(Number(minor) / 100).toLocaleString("en-BD")}`;

export function AdminLogisticsScreen() {
  const user = firebaseAuth?.currentUser ?? null;
  const router = useRouter(); const params = useLocalSearchParams<{ tab?: string }>(); const width = useWindowDimensions().width; const compact = width < 720;
  const selected = tabs.some(([key]) => key === params.tab) ? params.tab as Tab : "work";
  const cache = useQueryClient(); const query = useQuery({ queryKey: ["admin", "logistics"], queryFn: () => getLogisticsOverview(user!), enabled: Boolean(user), refetchInterval: selected === "work" ? 15_000 : false });
  const write = useMutation({ mutationFn: ({ path, body }: { path: string; body: unknown }) => saveLogisticsResource(user!, path, body), onSuccess: () => cache.invalidateQueries({ queryKey: ["admin", "logistics"] }) });
  const setTab = (tab: Tab) => router.replace({ pathname: "/admin/logistics", params: { tab } });
  return <Screen eyebrow="LOGISTICS CONTROL" title="Logistics workspace" description="Zones, courier allocation, manifests, parcel state, COD float and failed delivery operations.">
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.tabs}>{tabs.map(([key, label, icon]) => <Pressable key={key} onPress={() => setTab(key)} style={[styles.tab, selected === key && styles.tabActive]}><Ionicons color={selected === key ? "#fff" : colors.muted} name={icon} size={17} /><Text style={[styles.tabText, selected === key && styles.tabTextActive]}>{label}</Text></Pressable>)}</ScrollView>
    {query.isLoading ? <ActivityIndicator color={colors.primary} /> : null}{query.error ? <Message error text={query.error.message} /> : null}{write.error ? <Message error text={write.error.message} /> : null}
    {query.data ? <Workspace compact={compact} data={query.data} selected={selected} busy={write.isPending} write={(path, body) => write.mutate({ path, body })} /> : null}
  </Screen>;
}

function Workspace({ busy, compact, data, selected, write }: { busy: boolean; compact: boolean; data: LogisticsOverview; selected: Tab; write(path: string, body: unknown): void }) {
  if (selected === "work") return <><View style={styles.metrics}><Metric label="Total shipments" value={data.summary.totalShipments} /><Metric label="Ready to ship" value={data.summary.readyToShip} /><Metric label="Active parcels" value={data.summary.activeParcels} /><Metric label="Failed" value={data.summary.failedDeliveries} danger={data.summary.failedDeliveries > 0} /><Metric label="COD outstanding" value={money(data.summary.codOutstandingMinor)} /></View><ShipmentList compact={compact} rows={data.shipments} write={write} /></>;
  if (selected === "zones") return <ResourceSection title="Delivery zones" rows={data.zones.map((row) => ({ id: row.id, title: row.name, subtitle: `${row.code} · ${row.districts.join(", ") || "No districts"}`, meta: `${row.slaHours}h SLA · COD ${row.codAvailable ? "enabled" : "disabled"}` }))}><CreateZone busy={busy} write={write} /></ResourceSection>;
  if (selected === "couriers") return <ResourceSection title="Courier partners" rows={data.couriers.map((row) => ({ id: row.id, title: row.name, subtitle: `${row.code} · ${row.provider}`, meta: `${money(row.baseDeliveryCostMinor)} base · COD ${row.codSupported ? "yes" : "no"}` }))}><CreateCourier busy={busy} write={write} /></ResourceSection>;
  if (selected === "ready") return <ShipmentList compact={compact} rows={data.shipments.filter((row) => row.status === "READY_TO_SHIP")} write={write} />;
  if (selected === "manifest") return <Manifest rows={data.shipments.filter((row) => ["READY_TO_SHIP", "PICKED_UP"].includes(row.status))} />;
  if (selected === "parcels") return <ShipmentList compact={compact} rows={data.shipments} write={write} />;
  if (selected === "staff") return <ResourceSection title="Pickup staff" rows={data.pickupStaff.map((row) => ({ id: row.id, title: row.name, subtitle: row.routeName || "No route assigned", meta: `${row.vehicleType} · capacity ${row.capacityOrders}` }))}><CreateStaff busy={busy} write={write} /></ResourceSection>;
  if (selected === "rules") return <ResourceSection title="Delivery fee rules" rows={data.feeRules.map((row) => ({ id: row.id, title: row.name, subtitle: `${row.ruleType} · ${row.zoneCode || "All zones"}`, meta: `${money(row.baseFeeMinor)} base · ${money(row.codFeeMinor)} COD` }))}><CreateRule busy={busy} write={write} /></ResourceSection>;
  if (selected === "cod") return <><View style={styles.metrics}><Metric label="Outstanding" value={money(data.summary.codOutstandingMinor)} /></View><ResourceSection title="COD remittances" rows={data.remittances.map((row) => ({ id: row.id, title: row.courierName, subtitle: row.reference || new Date(row.createdAt).toLocaleDateString("en-BD"), meta: `${money(row.collectedAmountMinor)} collected · ${money(row.remittedAmountMinor)} remitted` }))}><CreateCod busy={busy} courierId={data.couriers[0]?.id} write={write} /></ResourceSection></>;
  return <ShipmentList compact={compact} rows={data.shipments.filter((row) => row.status === "FAILED")} write={write} failed />;
}

function ShipmentList({ compact, failed = false, rows, write }: { compact: boolean; failed?: boolean; rows: LogisticsShipment[]; write(path: string, body: unknown): void }) {
  if (!rows.length) return <Message text="No matching shipments in this queue." />;
  return <View style={styles.list}>{rows.map((row) => <View key={row.id} style={styles.card}><View style={[styles.cardTop, compact && styles.stack]}><View style={styles.grow}><Text style={styles.cardTitle}>{row.orderNumber}</Text><Text style={styles.muted}>{row.vendorName} · {row.shopName}</Text></View><Status value={row.status} /></View><View style={styles.details}><Info label="Total" value={money(row.totalMinor)} /><Info label="Courier" value={row.assignment?.courierPartner?.name || row.provider || "Unassigned"} /><Info label="Tracking" value={row.trackingNumber || "Not generated"} /><Info label="Updated" value={new Date(row.updatedAt).toLocaleString("en-BD")} /></View>{row.failedDelivery ? <Text style={styles.dangerText}>{row.failedDelivery.reason} · attempt {row.failedDelivery.attemptCount}</Text> : null}<View style={styles.actions}>{row.status === "READY_TO_SHIP" ? <Action label="Mark picked up" onPress={() => write(`/shipments/${row.id}/state`, { status: "PICKED_UP", note: "Pickup confirmed from logistics workspace" })} /> : null}{row.status === "PICKED_UP" ? <Action label="Start transit" onPress={() => write(`/shipments/${row.id}/state`, { status: "IN_TRANSIT", note: "Parcel entered transit" })} /> : null}{row.status === "IN_TRANSIT" ? <><Action label="Delivered" onPress={() => write(`/shipments/${row.id}/delivery-attempt`, { outcome: "delivered", receiverName: "Customer", reason: null, notes: "Delivered from logistics workspace", codCollected: Number(row.codAmountMinor) > 0 })} /><Action danger label="Failed" onPress={() => write(`/shipments/${row.id}/delivery-attempt`, { outcome: "failed", receiverName: null, reason: "Customer unavailable", notes: "Delivery attempt recorded by operations", codCollected: false })} /></> : null}{failed ? <><Action label="Reattempt" onPress={() => write(`/failed-deliveries/${row.id}/reattempt`, { nextAttemptAt: new Date(Date.now() + 86_400_000).toISOString(), redeliveryFeeMinor: "0", reason: "Scheduled by operations", note: null })} /><Action danger label="Return to seller" onPress={() => write(`/failed-deliveries/${row.id}/return-to-seller`, { returnFeeMinor: "0", reason: "Delivery attempts exhausted", note: null })} /></> : null}</View></View>)}</View>;
}

function ResourceSection({ children, rows, title }: { children: ReactNode; rows: Array<{ id: string; title: string; subtitle: string; meta: string }>; title: string }) { return <View style={styles.section}><View style={styles.sectionHeading}><Text style={styles.sectionTitle}>{title}</Text><Text style={styles.muted}>{rows.length} records</Text></View>{children}<View style={styles.list}>{rows.map((row) => <View key={row.id} style={styles.resource}><View style={styles.grow}><Text style={styles.cardTitle}>{row.title}</Text><Text style={styles.muted}>{row.subtitle}</Text></View><Text style={styles.meta}>{row.meta}</Text></View>)}</View></View>; }
function CreateZone({ busy, write }: FormProps) { const [name, setName] = useState(""); const [code, setCode] = useState(""); const [district, setDistrict] = useState(""); return <Create title="Add delivery zone" fields={[["Zone name", name, setName], ["Code", code, setCode], ["District", district, setDistrict]]} busy={busy} submit={() => write("/delivery-zones", { name, code, districts: district ? [district] : [], courierPartnerIds: [], defaultCourierName: null, codAvailable: true, status: "active", slaHours: 48, sortOrder: 100, notes: null })} />; }
function CreateCourier({ busy, write }: FormProps) { const [name, setName] = useState(""); const [code, setCode] = useState(""); return <Create title="Add courier partner" fields={[["Courier name", name, setName], ["Code", code, setCode]]} busy={busy} submit={() => write("/courier-partners", { name, code, status: "active", provider: "manual", bookingMode: "manual", coverageType: "outside_district", outsideDistrict: true, localArea: false, instantDelivery: false, trackingUrlPattern: null, contactName: null, phone: null, email: null, serviceZones: [], codSupported: true, baseDeliveryCostMinor: "8000", codCollectionFeeMinor: "1000", defaultSlaHours: 72, slaZoneCode: null, slaProcessingHours: 24, slaDeliveryDaysMin: 1, slaDeliveryDaysMax: 3, notes: null })} />; }
function CreateStaff({ busy, write }: FormProps) { const [name, setName] = useState(""); const [phone, setPhone] = useState(""); return <Create title="Add pickup staff" fields={[["Name", name, setName], ["Phone", phone, setPhone]]} busy={busy} submit={() => write("/pickup-staff", { name, phone: phone || null, email: null, userId: null, status: "active", routeName: null, assignedZones: [], assignedLocations: [], assignedVendorIds: [], vehicleType: "bike", capacityOrders: 25, shiftStart: "09:00", shiftEnd: "18:00", notes: null })} />; }
function CreateRule({ busy, write }: FormProps) { const [name, setName] = useState(""); const [fee, setFee] = useState("80"); return <Create title="Add fee rule" fields={[["Rule name", name, setName], ["Base fee (BDT)", fee, setFee]]} busy={busy} submit={() => write("/fee-rules", { name, ruleType: "zone_rate", status: "active", priority: 100, zoneCode: null, minOrderAmountMinor: "0", maxOrderAmountMinor: "0", minWeightGrams: 0, maxWeightGrams: 0, baseFeeMinor: String(Number(fee) * 100), perItemFeeMinor: "0", feePerKgMinor: "1000", codFeeMinor: "0", redeliveryFeeMinor: "0", freeShippingThresholdMinor: "0", paymentMethods: [], notes: null })} />; }
function CreateCod({ busy, courierId, write }: FormProps & { courierId?: string }) { const [courier, setCourier] = useState("Amiyo Delivery"); const [collected, setCollected] = useState("0"); const [remitted, setRemitted] = useState("0"); return <Create title="Record COD remittance" fields={[["Courier", courier, setCourier], ["Collected BDT", collected, setCollected], ["Remitted BDT", remitted, setRemitted]]} busy={busy} submit={() => write("/cod-remittances", { courierPartnerId: courierId || null, courierName: courier, collectedAmountMinor: String(Number(collected) * 100), remittedAmountMinor: String(Number(remitted) * 100), forwardedToVendorMinor: "0", reference: `COD-${Date.now()}`, notes: null, orderIds: [] })} />; }

type FormProps = { busy: boolean; write(path: string, body: unknown): void };
type Field = [string, string, (value: string) => void];
function Create({ busy, fields, submit, title }: { busy: boolean; fields: Field[]; submit(): void; title: string }) { const valid = fields.every(([, value]) => value.trim()); return <View style={styles.create}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.formRow}>{fields.map(([label, value, setValue]) => <TextInput key={label} accessibilityLabel={label} placeholder={label} placeholderTextColor="#94a3b8" value={value} onChangeText={setValue} style={styles.input} />)}<Pressable disabled={busy || !valid} onPress={submit} style={[styles.primary, (busy || !valid) && styles.disabled]}><Ionicons color="#fff" name="add" size={17} /><Text style={styles.primaryText}>{busy ? "Saving…" : "Save"}</Text></Pressable></View></View>; }
function Manifest({ rows }: { rows: LogisticsShipment[] }) { const groups = useMemo(() => rows.reduce((result, row) => { const courier = row.assignment?.courierPartner?.name || row.provider || "Unassigned"; const current = result.get(courier) ?? []; current.push(row); result.set(courier, current); return result; }, new Map<string, LogisticsShipment[]>()), [rows]); const exportCsv = () => { if (Platform.OS !== "web") return; const csv = ["Order,Courier,Status,Tracking,Amount", ...rows.map((row) => [row.orderNumber, row.assignment?.courierPartner?.name || row.provider || "Unassigned", row.status, row.trackingNumber || "", money(row.totalMinor)].map((value) => `"${String(value).replaceAll('"', '""')}"`).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = "dispatch-manifest.csv"; link.click(); URL.revokeObjectURL(url); }; return <View style={styles.section}><View style={styles.sectionHeading}><Text style={styles.sectionTitle}>Dispatch manifest</Text>{Platform.OS === "web" ? <Action label="Export CSV" onPress={exportCsv} /> : null}</View>{[...groups].map(([courier, items]) => <View key={courier} style={styles.card}><Text style={styles.cardTitle}>{courier}</Text><Text style={styles.muted}>{items.length} parcels · {money(String(items.reduce((sum, row) => sum + Number(row.codAmountMinor), 0)))} COD</Text>{items.map((row) => <Text key={row.id} style={styles.manifestLine}>{row.orderNumber} · {row.status} · {row.trackingNumber || "No tracking"}</Text>)}</View>)}</View>; }
function Metric({ danger, label, value }: { danger?: boolean; label: string; value: number | string }) { return <View style={styles.metric}><Text style={[styles.metricValue, danger && styles.dangerText]}>{typeof value === "number" ? value.toLocaleString("en-BD") : value}</Text><Text style={styles.muted}>{label}</Text></View>; }
function Info({ label, value }: { label: string; value: string }) { return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text numberOfLines={2} style={styles.infoValue}>{value}</Text></View>; }
function Status({ value }: { value: string }) { return <Text style={[styles.status, ["DELIVERED", "READY_TO_SHIP"].includes(value) && styles.statusGood, value === "FAILED" && styles.statusBad]}>{value.replaceAll("_", " ")}</Text>; }
function Action({ danger, label, onPress }: { danger?: boolean; label: string; onPress(): void }) { return <Pressable onPress={onPress} style={[styles.action, danger && styles.actionDanger]}><Text style={[styles.actionText, danger && styles.dangerText]}>{label}</Text></Pressable>; }
function Message({ error, text }: { error?: boolean; text: string }) { return <View style={[styles.message, error && styles.messageError]}><Ionicons color={error ? colors.danger : colors.muted} name={error ? "warning-outline" : "file-tray-outline"} size={20} /><Text style={[styles.muted, error && styles.dangerText]}>{text}</Text></View>; }

const styles = StyleSheet.create({
  tabs: { gap: 6, paddingBottom: spacing.sm }, tab: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flexDirection: "row", gap: 6, minHeight: 40, paddingHorizontal: 12 }, tabActive: { backgroundColor: colors.primary, borderColor: colors.primary }, tabText: { color: colors.muted, fontSize: 11, fontWeight: "800" }, tabTextActive: { color: "#fff" },
  metrics: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, metric: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, flex: 1, minWidth: 145, padding: spacing.md }, metricValue: { color: colors.text, fontSize: 22, fontWeight: "900" },
  list: { gap: spacing.sm }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, cardTop: { alignItems: "center", flexDirection: "row", gap: spacing.sm, justifyContent: "space-between" }, stack: { alignItems: "flex-start", flexDirection: "column" }, grow: { flex: 1, minWidth: 0 }, cardTitle: { color: colors.text, fontSize: 14, fontWeight: "900" }, muted: { color: colors.muted, fontSize: 11, lineHeight: 17 }, meta: { color: colors.text, fontSize: 11, fontWeight: "700" }, dangerText: { color: colors.danger },
  details: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, info: { backgroundColor: colors.background, borderRadius: radius.md, flex: 1, minWidth: 135, padding: spacing.sm }, infoLabel: { color: colors.muted, fontSize: 9, fontWeight: "800", textTransform: "uppercase" }, infoValue: { color: colors.text, fontSize: 11, fontWeight: "800", marginTop: 3 }, status: { backgroundColor: "#fff7ed", borderRadius: radius.pill, color: colors.warning, fontSize: 9, fontWeight: "900", overflow: "hidden", paddingHorizontal: 9, paddingVertical: 5 }, statusGood: { backgroundColor: "#ecfdf5", color: colors.success }, statusBad: { backgroundColor: "#fef2f2", color: colors.danger },
  actions: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, action: { backgroundColor: colors.primarySoft, borderRadius: radius.sm, paddingHorizontal: 10, paddingVertical: 8 }, actionDanger: { backgroundColor: "#fef2f2" }, actionText: { color: colors.primary, fontSize: 10, fontWeight: "900" },
  section: { gap: spacing.md }, sectionHeading: { alignItems: "center", flexDirection: "row", gap: spacing.sm, justifyContent: "space-between" }, sectionTitle: { color: colors.text, fontSize: 16, fontWeight: "900" }, resource: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, padding: spacing.md }, create: { backgroundColor: colors.surface, borderColor: colors.primary, borderRadius: radius.lg, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, formRow: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, input: { backgroundColor: colors.background, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, flex: 1, minHeight: 42, minWidth: 180, paddingHorizontal: 12 }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, flexDirection: "row", gap: 6, minHeight: 42, paddingHorizontal: spacing.md }, primaryText: { color: "#fff", fontSize: 11, fontWeight: "900" }, disabled: { opacity: .45 },
  manifestLine: { borderTopColor: colors.border, borderTopWidth: 1, color: colors.text, fontSize: 11, paddingTop: 7 }, message: { alignItems: "center", backgroundColor: colors.surface, borderRadius: radius.md, flexDirection: "row", gap: spacing.sm, padding: spacing.md }, messageError: { backgroundColor: "#fef2f2" }
});
