import { deliveryQueueItemSchema, deliveryRetryResultSchema, returnSchema, vendorFinanceSchema, type DeliveryRetryInput } from "@amiyo/contracts";
import type { User } from "firebase/auth";

const apiUrl = (process.env.EXPO_PUBLIC_API_URL || "http://localhost:4000").replace(/\/$/, "");
async function request(user: User, path: string, init?: RequestInit) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) { const problem = await response.json().catch(() => null) as { title?: string; detail?: string } | null; throw new Error(problem?.detail || problem?.title || `Operations request failed (${response.status})`); } return response.json() as Promise<unknown>; }
export async function getReturns(user: User) { return returnSchema.array().parse(await request(user, "/api/v2/returns")); }
export async function getVendorFinance(user: User) { return vendorFinanceSchema.parse(await request(user, "/api/v2/vendor/finance")); }
export async function getAdminQueues(user: User) { const safe = (path: string) => request(user, path).catch(() => []); const [returns, payouts, audit] = await Promise.all([safe("/api/v2/admin/returns"), safe("/api/v2/admin/payouts"), safe("/api/v2/admin/audit")]); return { returns: returns as Array<{ id: string; status: string; reasonCode: string }>, payouts: payouts as Array<{ id: string; status: string; amount: { amountMinor: string; currency: string }; vendor: { legalName: string } }>, audit: audit as Array<{ id: string; action: string; resourceType: string; createdAt: string }> }; }
export async function getDeliveryQueue(user: User) { return deliveryQueueItemSchema.array().parse(await request(user, "/api/v2/admin/delivery-queue")); }
export async function retryDelivery(user: User, id: string, input: DeliveryRetryInput, idempotencyKey: string) { return deliveryRetryResultSchema.parse(await request(user, `/api/v2/admin/delivery-queue/${id}/retry`, { method: "POST", headers: { "Idempotency-Key": idempotencyKey }, body: JSON.stringify(input) })); }
