import { adminCodWorkspaceSchema, deliveryQueueItemSchema, deliveryRetryResultSchema, returnSchema, vendorFinanceSchema, type AdminCodConfirmationInput, type AdminCodDeliveryInput, type CancelOrder, type CreateReturn, type DeliveryRetryInput, type SellerReturnReceipt, type SellerReturnResponse } from "@amiyo/contracts";
import type { User } from "firebase/auth";
import * as Crypto from "expo-crypto";

const apiUrl = (process.env.EXPO_PUBLIC_API_URL || "http://localhost:4000").replace(/\/$/, "");
async function request(user: User, path: string, init?: RequestInit) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) { const problem = await response.json().catch(() => null) as { title?: string; detail?: string } | null; throw new Error(problem?.detail || problem?.title || `Operations request failed (${response.status})`); } return response.json() as Promise<unknown>; }
export async function getReturns(user: User) { return returnSchema.array().parse(await request(user, "/api/v2/returns")); }
export async function cancelCustomerOrder(user: User, orderId: string, input: CancelOrder, idempotencyKey: string) { return request(user, `/api/v2/orders/${orderId}/cancel`, { method: "POST", headers: { "Idempotency-Key": idempotencyKey }, body: JSON.stringify(input) }); }
export async function createCustomerReturn(user: User, input: CreateReturn, idempotencyKey: string) { return returnSchema.parse(await request(user, "/api/v2/returns", { method: "POST", headers: { "Idempotency-Key": idempotencyKey }, body: JSON.stringify(input) })); }
export async function respondToVendorReturn(user: User, id: string, input: SellerReturnResponse) { return returnSchema.parse(await request(user, `/api/v2/vendor/returns/${id}/response`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify(input) })); }
export async function confirmVendorReturnReceipt(user: User, id: string, input: SellerReturnReceipt) { return returnSchema.parse(await request(user, `/api/v2/vendor/returns/${id}/receipt`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify(input) })); }
export async function getVendorFinance(user: User) { return vendorFinanceSchema.parse(await request(user, "/api/v2/vendor/finance")); }
export type AdminReturnSummary = { id: string; orderId: string; status: string; reasonCode: string; requestedAmount: { amountMinor: string; currency: string }; version: number; createdAt: string; items: Array<{ id: string }> };
export async function getAdminReturns(user: User) { return request(user, "/api/v2/admin/returns") as Promise<AdminReturnSummary[]>; }
export type AdminPayoutSummary = { id: string; vendorId: string; vendor: { legalName: string; displayName: string }; bankAccount: { provider: string; accountName: string; accountNumberMasked: string } | null; amount: { amountMinor: string; currency: string }; status: string; version: number; requestedAt: string; reviewedAt: string | null; rejectionReason: string | null; payouts: Array<{ id: string; provider: string; providerRef: string | null; amount: { amountMinor: string; currency: string }; status: string; paidAt: string | null }> };
export async function getAdminPayouts(user: User) { return request(user, "/api/v2/admin/payouts") as Promise<AdminPayoutSummary[]>; }
export async function getAdminQueues(user: User) { const safe = (path: string) => request(user, path).catch(() => []); const [returns, payouts, audit] = await Promise.all([safe("/api/v2/admin/returns"), safe("/api/v2/admin/payouts"), safe("/api/v2/admin/audit")]); return { returns: returns as AdminReturnSummary[], payouts: payouts as Array<{ id: string; status: string; version: number; requestedAt: string; amount: { amountMinor: string; currency: string }; vendor: { legalName: string; displayName: string }; bankAccount?: { accountNumberMasked: string } }>, audit: audit as Array<{ id: string; action: string; resourceType: string; createdAt: string }> }; }
export type AdminReturnDetail = { id: string; orderId: string; orderNumber: string; vendorOrderId: string; status: string; reasonCode: string; reasonDetail: string | null; requestedAmount: { amountMinor: string; currency: string }; approvedAmount: { amountMinor: string; currency: string } | null; version: number; createdAt: string; customer: { name: string; email: string | null; phone: string | null }; vendor: { name: string; legalName: string; shop: string }; items: Array<{ id: string; name: string; sku: string; quantity: number; requestedAmount: { amountMinor: string; currency: string }; inspection: Record<string, unknown> | null }>; events: Array<{ id: string; fromStatus: string | null; toStatus: string; actorType: string; note: string | null; createdAt: string }>; refunds: Array<{ id: string; status: string; amount: { amountMinor: string; currency: string }; providerRefundId: string | null; reason: string; createdAt: string; completedAt: string | null }> };
export async function getAdminReturnDetail(user: User, id: string) { return request(user, `/api/v2/admin/returns/${id}`) as Promise<AdminReturnDetail>; }
export async function reviewAdminPayout(user: User, id: string, expectedVersion: number, action: "APPROVE" | "REJECT") { return request(user, `/api/v2/admin/payouts/${id}/review`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify({ expectedVersion, action, reason: action === "REJECT" ? "Rejected after finance review" : null }) }); }
export async function reviewAdminPayoutCase(user: User, id: string, input: { expectedVersion: number; action: "APPROVE" | "REJECT"; reason?: string | null }) { return request(user, `/api/v2/admin/payouts/${id}/review`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify(input) }); }
export type AdminReturnStatus = "REVIEWING" | "APPROVED" | "REJECTED" | "PICKUP_SCHEDULED" | "RECEIVED" | "INSPECTED" | "REFUND_PENDING" | "CLOSED";
export async function transitionAdminReturn(user: User, id: string, expectedVersion: number, status: AdminReturnStatus, approvedAmountMinor: string) { return request(user, `/api/v2/admin/returns/${id}/transitions`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify({ expectedVersion, status, note: `Moved to ${status.toLowerCase()} by admin`, ...(status === "APPROVED" ? { approvedAmountMinor } : {}) }) }); }
export async function transitionAdminReturnCase(user: User, id: string, input: { expectedVersion: number; status: AdminReturnStatus; note?: string | null; approvedAmountMinor?: string }) { return request(user, `/api/v2/admin/returns/${id}/transitions`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify(input) }); }
export async function completeAdminRefund(user: User, id: string) { return request(user, `/api/v2/admin/returns/${id}/refund-completion`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify({ providerRefundId: `ADMIN-${Date.now()}` }) }); }
export async function completeAdminRefundCase(user: User, id: string, providerRefundId: string) { return request(user, `/api/v2/admin/returns/${id}/refund-completion`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify({ providerRefundId }) }); }
export async function completeAdminPayout(user: User, id: string) { return request(user, `/api/v2/admin/payouts/${id}/completion`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify({ provider: "manual_admin", providerRef: `ADMIN-${Date.now()}` }) }); }
export async function completeAdminPayoutCase(user: User, id: string, provider: string, providerRef: string) { return request(user, `/api/v2/admin/payouts/${id}/completion`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify({ provider, providerRef }) }); }
export async function createCodReconciliation(user: User, periodStart: string, periodEnd: string) { return request(user, "/api/v2/admin/cod/reconciliations", { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify({ periodStart, periodEnd }) }); }
export async function getAdminCodWorkspace(user: User) { return adminCodWorkspaceSchema.parse(await request(user, "/api/v2/admin/cod")); }
export async function markAdminCodDelivered(user: User, orderId: string, input: AdminCodDeliveryInput) { return request(user, `/api/v2/admin/cod/orders/${orderId}/delivered`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify(input) }); }
export async function confirmAdminCodPayment(user: User, orderId: string, input: AdminCodConfirmationInput) { return request(user, `/api/v2/admin/cod/orders/${orderId}/confirm`, { method: "POST", headers: { "Idempotency-Key": Crypto.randomUUID() }, body: JSON.stringify(input) }); }
export type { AdminCodConfirmationInput, AdminCodDeliveryInput, AdminCodWorkspaceDto } from "@amiyo/contracts";
export async function getDeliveryQueue(user: User) { return deliveryQueueItemSchema.array().parse(await request(user, "/api/v2/admin/delivery-queue")); }
export async function retryDelivery(user: User, id: string, input: DeliveryRetryInput, idempotencyKey: string) { return deliveryRetryResultSchema.parse(await request(user, `/api/v2/admin/delivery-queue/${id}/retry`, { method: "POST", headers: { "Idempotency-Key": idempotencyKey }, body: JSON.stringify(input) })); }
