import { Ionicons } from "@expo/vector-icons";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { AccountState } from "../account/components/AccountState";
import { firebaseAuth } from "../auth/firebase";
import { getReturns } from "./operations.api";

const money = (minor: string) => `৳${(Number(minor) / 100).toLocaleString("en-BD")}`;
const label = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());

export function ReturnsScreen() {
  const router = useRouter();
  const user = firebaseAuth?.currentUser ?? null;
  const query = useQuery({ queryKey: ["returns"], queryFn: () => getReturns(user!), enabled: Boolean(user) });
  if (!user) return <AccountState icon="return-down-back-outline" title="Returns and refunds" copy="Sign in to track return, inspection and refund progress." action="Sign in" onPress={() => router.replace("/auth")} />;
  if (query.isLoading) return <AccountState loading icon="return-down-back-outline" title="Loading returns" copy="Checking your current return requests." />;
  if (query.error) return <AccountState icon="alert-circle-outline" title="Could not load returns" copy={query.error.message} action="Try again" onPress={() => query.refetch()} />;

  const open = query.data?.filter((item) => !["REFUNDED", "CLOSED", "REJECTED"].includes(item.status)).length ?? 0;
  return <Screen eyebrow="AFTER SALES" title="Returns & refunds" description="Track review, pickup, inspection and refund progress."><View style={styles.summary}><View style={styles.summaryIcon}><Ionicons color={colors.surface} name="return-down-back" size={25} /></View><View style={styles.flex}><Text accessibilityRole="header" style={styles.summaryTitle}>{open} open request{open === 1 ? "" : "s"}</Text><Text style={styles.summaryCopy}>{query.data?.length ?? 0} total return request{query.data?.length === 1 ? "" : "s"}</Text></View></View>{query.data?.length ? <View style={styles.list}>{query.data.map((item) => <View key={item.id} style={styles.card}><View style={styles.cardHeader}><View><Text style={styles.returnNumber}>Return #{item.id.slice(0, 8).toUpperCase()}</Text><Text style={styles.muted}>{new Date(item.createdAt).toLocaleDateString("en-BD", { day: "numeric", month: "short", year: "numeric" })}</Text></View><Text style={styles.status}>{label(item.status)}</Text></View><View style={styles.reason}><Ionicons color={colors.primary} name="information-circle-outline" size={19} /><View style={styles.flex}><Text style={styles.reasonTitle}>{label(item.reasonCode)}</Text>{item.reasonDetail ? <Text style={styles.muted}>{item.reasonDetail}</Text> : null}</View></View><View style={styles.amountRow}><View><Text style={styles.amountLabel}>Requested</Text><Text style={styles.amount}>{money(item.requestedAmount.amountMinor)}</Text></View>{item.approvedAmount ? <View><Text style={styles.amountLabel}>Approved</Text><Text style={styles.approved}>{money(item.approvedAmount.amountMinor)}</Text></View> : null}<View><Text style={styles.amountLabel}>Items</Text><Text style={styles.itemCount}>{item.items.reduce((sum, row) => sum + row.quantity, 0)}</Text></View></View></View>)}</View> : <View style={styles.empty}><Ionicons color={colors.primary} name="checkmark-circle-outline" size={52} /><Text style={styles.emptyTitle}>No returns</Text><Text style={styles.muted}>Your return requests will appear here.</Text><Pressable onPress={() => router.push("/orders")} style={styles.primary}><Text style={styles.primaryText}>View my orders</Text></Pressable></View>}</Screen>;
}

const styles = StyleSheet.create({ flex: { flex: 1 }, summary: { alignItems: "center", backgroundColor: colors.navy, borderRadius: radius.lg, flexDirection: "row", gap: spacing.md, padding: spacing.lg }, summaryIcon: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, height: 48, justifyContent: "center", width: 48 }, summaryTitle: { color: colors.surface, fontSize: 20, fontWeight: "900" }, summaryCopy: { color: "#cbd5e1", marginTop: 3 }, list: { gap: spacing.md }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, gap: spacing.md, padding: spacing.lg }, cardHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, returnNumber: { color: colors.text, fontWeight: "900" }, muted: { color: colors.muted, lineHeight: 19, marginTop: 3 }, status: { backgroundColor: colors.primarySoft, borderRadius: radius.pill, color: colors.primary, fontSize: 9, fontWeight: "900", overflow: "hidden", paddingHorizontal: 9, paddingVertical: 6 }, reason: { alignItems: "flex-start", backgroundColor: colors.background, borderRadius: radius.md, flexDirection: "row", gap: spacing.sm, padding: spacing.md }, reasonTitle: { color: colors.text, fontWeight: "900" }, amountRow: { borderTopColor: colors.border, borderTopWidth: 1, flexDirection: "row", flexWrap: "wrap", gap: spacing.xl, paddingTop: spacing.md }, amountLabel: { color: colors.muted, fontSize: 10 }, amount: { color: colors.accent, fontSize: 18, fontWeight: "900", marginTop: 3 }, approved: { color: colors.success, fontSize: 18, fontWeight: "900", marginTop: 3 }, itemCount: { color: colors.text, fontSize: 18, fontWeight: "900", marginTop: 3 }, empty: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.xl, borderStyle: "dashed", borderWidth: 1, gap: spacing.md, padding: 44 }, emptyTitle: { color: colors.text, fontSize: 22, fontWeight: "900" }, primary: { backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: spacing.lg, paddingVertical: 13 }, primaryText: { color: colors.surface, fontWeight: "900" } });
