import { Ionicons } from "@expo/vector-icons";
import { useQuery } from "@tanstack/react-query";
import { StyleSheet, Text, View } from "react-native";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getVendorFinance } from "./operations.api";

const money = (minor: string) => `৳${(Number(minor) / 100).toLocaleString("en-BD")}`;
const label = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());

export function VendorFinanceScreen() {
  const user = firebaseAuth?.currentUser ?? null;
  const query = useQuery({ queryKey: ["vendor-finance"], queryFn: () => getVendorFinance(user!), enabled: Boolean(user) });
  if (query.isLoading) return <Screen eyebrow="SELLER CENTER" title="Loading finance" description="Calculating your current ledger balance."><View style={styles.empty}><Ionicons color={colors.primary} name="wallet-outline" size={48} /></View></Screen>;
  if (query.error || !query.data) return <Screen eyebrow="SELLER CENTER" title="Finance unavailable" description={query.error instanceof Error ? query.error.message : "Sign in with a vendor account to continue."}><View style={styles.empty}><Ionicons color={colors.primary} name="alert-circle-outline" size={48} /></View></Screen>;
  const credits = query.data.entries.filter((entry) => entry.direction === "CREDIT").reduce((sum, entry) => sum + Number(entry.amount.amountMinor), 0);
  return <Screen eyebrow="SELLER CENTER" title="Vendor finance" description="Balance and activity derived from the append-only vendor ledger."><View style={styles.balance}><View><Text style={styles.kicker}>AVAILABLE BALANCE</Text><Text accessibilityRole="header" style={styles.balanceValue}>{money(query.data.balance.amountMinor)}</Text><Text style={styles.balanceCopy}>Ready after payout reservations</Text></View><View style={styles.wallet}><Ionicons color={colors.surface} name="wallet" size={30} /></View></View><View style={styles.stats}><Stat label="Lifetime credits" value={money(String(credits))} /><Stat label="Ledger entries" value={String(query.data.entries.length)} /><Stat label="Payout requests" value={String(query.data.payoutRequests.length)} /></View><Text style={styles.heading}>Ledger activity</Text>{query.data.entries.length ? <View style={styles.list}>{query.data.entries.map((entry) => { const credit = entry.direction === "CREDIT"; return <View key={entry.id} style={styles.row}><View style={[styles.entryIcon, !credit && styles.debitIcon]}><Ionicons color={credit ? colors.success : colors.accent} name={credit ? "arrow-down" : "arrow-up"} size={18} /></View><View style={styles.flex}><Text style={styles.entryTitle}>{label(entry.entryType)}</Text><Text style={styles.muted}>{new Date(entry.createdAt).toLocaleString("en-BD")}</Text></View><Text style={[styles.amount, !credit && styles.debit]}>{credit ? "+" : "-"}{money(entry.amount.amountMinor)}</Text></View>; })}</View> : <View style={styles.empty}><Text style={styles.muted}>No ledger activity yet.</Text></View>}</Screen>;
}

function Stat({ label: statLabel, value }: { label: string; value: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{statLabel}</Text></View>; }
const styles = StyleSheet.create({ flex: { flex: 1 }, balance: { alignItems: "center", backgroundColor: colors.navy, borderRadius: radius.xl, flexDirection: "row", justifyContent: "space-between", padding: spacing.xl }, kicker: { color: "#7dd3fc", fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, balanceValue: { color: colors.surface, fontSize: 38, fontWeight: "900", marginTop: 5 }, balanceCopy: { color: "#cbd5e1", marginTop: 3 }, wallet: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.lg, height: 58, justifyContent: "center", width: 58 }, stats: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md }, stat: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, flexGrow: 1, minWidth: 160, padding: spacing.lg }, statValue: { color: colors.text, fontSize: 21, fontWeight: "900" }, statLabel: { color: colors.muted, fontSize: 11, marginTop: 4 }, heading: { color: colors.text, fontSize: 20, fontWeight: "900" }, list: { gap: spacing.sm }, row: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, flexDirection: "row", gap: spacing.md, padding: spacing.md }, entryIcon: { alignItems: "center", backgroundColor: "#ecfdf5", borderRadius: radius.pill, height: 40, justifyContent: "center", width: 40 }, debitIcon: { backgroundColor: "#fff7ed" }, entryTitle: { color: colors.text, fontWeight: "900" }, muted: { color: colors.muted, marginTop: 3 }, amount: { color: colors.success, fontSize: 17, fontWeight: "900" }, debit: { color: colors.accent }, empty: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.xl, borderStyle: "dashed", borderWidth: 1, gap: spacing.md, padding: 40 } });
