import assert from "node:assert/strict";
import test from "node:test";
import { adminAnalyticsQuerySchema, adminAuditQuerySchema, adminBannerInputSchema, adminCampaignInputSchema, adminCategoryAttributesInputSchema, adminCategoryInputSchema, adminCategoryRequestReviewSchema, adminChatThreadSchema, adminCouponInputSchema, adminFlashSaleInputSchema, adminKycReviewInputSchema, adminUserRolesInputSchema, adminUserStatusInputSchema, adminVoucherInputSchema, paymentVerificationReviewSchema, platformSettingsInputSchema, trustCaseActionInputSchema } from "./admin.js";

test("admin user status mutations require an operational reason", () => {
  assert.equal(adminUserStatusInputSchema.parse({ status: "SUSPENDED", reason: "Fraud review" }).status, "SUSPENDED");
  assert.throws(() => adminUserStatusInputSchema.parse({ status: "SUSPENDED", reason: "no" }));
});

test("platform staff roles are bounded and unique", () => {
  assert.deepEqual(adminUserRolesInputSchema.parse({ roles: ["SUPPORT_AGENT", "FINANCE_ADMIN"], reason: "Operations staffing change" }).roles, ["SUPPORT_AGENT", "FINANCE_ADMIN"]);
  assert.throws(() => adminUserRolesInputSchema.parse({ roles: ["CUSTOMER"], reason: "Operations staffing change" }));
  assert.throws(() => adminUserRolesInputSchema.parse({ roles: ["SUPPORT_AGENT", "SUPPORT_AGENT"], reason: "Operations staffing change" }));
});

test("KYC rejection cannot omit its reason", () => {
  assert.throws(() => adminKycReviewInputSchema.parse({ status: "REJECTED" }));
  assert.equal(adminKycReviewInputSchema.parse({ status: "APPROVED" }).status, "APPROVED");
});

test("trust actions use a bounded workflow", () => {
  assert.equal(trustCaseActionInputSchema.parse({ action: "RESOLVE", reason: "Evidence reviewed" }).action, "RESOLVE");
  assert.throws(() => trustCaseActionInputSchema.parse({ action: "DELETE", reason: "Evidence reviewed" }));
});
test("payment rejection requires a review reason", () => { assert.equal(paymentVerificationReviewSchema.parse({ status: "approved", reason: "Evidence verified" }).status, "approved"); assert.throws(() => paymentVerificationReviewSchema.parse({ status: "rejected", reason: "no" })); });
test("admin category slugs remain URL safe", () => { assert.equal(adminCategoryInputSchema.parse({ name: "Home Appliances", slug: "home-appliances" }).displayOrder, 0); assert.throws(() => adminCategoryInputSchema.parse({ name: "Home Appliances", slug: "Home Appliances" })); });
test("dynamic category attributes reject ambiguous configurations", () => {
  assert.equal(adminCategoryAttributesInputSchema.safeParse({ attributes: [{ key: "size", label: "Size", dataType: "select", options: ["Small", "Large"] }] }).success, true);
  assert.equal(adminCategoryAttributesInputSchema.safeParse({ attributes: [{ key: "size", label: "Size", dataType: "select", options: [] }] }).success, false);
  assert.equal(adminCategoryAttributesInputSchema.safeParse({ attributes: [{ key: "size", label: "Size", dataType: "text" }, { key: "size", label: "Other size", dataType: "text" }] }).success, false);
});
test("admin analytics uses bounded reporting windows", () => { assert.equal(adminAnalyticsQuerySchema.parse({}).range, "30d"); assert.equal(adminAnalyticsQuerySchema.parse({ range: "90d" }).range, "90d"); assert.throws(() => adminAnalyticsQuerySchema.parse({ range: "all" })); });
test("category request reviews use final bounded decisions", () => { assert.equal(adminCategoryRequestReviewSchema.safeParse({ status: "approved", reason: "Catalog verified" }).success, true); assert.equal(adminCategoryRequestReviewSchema.safeParse({ status: "pending", reason: "Wait" }).success, false); });
test("banner schedules and destinations remain valid", () => { const valid = { title: "Eid offers", placement: "home_hero", storageKey: "https://example.com/banner.jpg", targetType: "route", targetValue: "/search", startsAt: "2026-08-05T00:00:00.000Z", endsAt: "2026-08-20T00:00:00.000Z" }; assert.equal(adminBannerInputSchema.safeParse(valid).success, true); assert.equal(adminBannerInputSchema.safeParse({ ...valid, endsAt: valid.startsAt }).success, false); assert.equal(adminBannerInputSchema.safeParse({ ...valid, targetValue: null }).success, false); });
test("admin marketing rules enforce safe discounts and unique flash products", () => { const startsAt = "2026-08-15T00:00:00.000Z"; const endsAt = "2026-08-20T00:00:00.000Z"; assert.equal(adminVoucherInputSchema.safeParse({ code: " amiyo20 ", discountType: "PERCENT", value: 20, startsAt, endsAt }).success, true); assert.equal(adminVoucherInputSchema.safeParse({ code: "BAD200", discountType: "PERCENT", value: 200, startsAt, endsAt }).success, false); const product = { productId: "00000000-0000-4000-8000-000000000401", priceMinor: "199000", quantityLimit: 25 }; assert.equal(adminFlashSaleInputSchema.safeParse({ name: "Mega flash", startsAt, endsAt, products: [product] }).success, true); assert.equal(adminFlashSaleInputSchema.safeParse({ name: "Mega flash", startsAt, endsAt, products: [product, product] }).success, false); });
test("admin audit queries bound pagination and date windows", () => { assert.equal(adminAuditQuerySchema.parse({ page: "2", limit: "25" }).page, 2); assert.equal(adminAuditQuerySchema.safeParse({ limit: 101 }).success, false); assert.equal(adminAuditQuerySchema.safeParse({ from: "2026-08-20", to: "2026-08-10" }).success, false); });
test("platform settings enforce safe operational bounds", () => { const valid = { expectedVersion: 1, featureFlags: { sellerRegistration: true, reviews: true, questions: true, flashSales: true, loyalty: true, voiceSearch: true, googleLogin: true }, paymentMethods: { cod: { enabled: true }, sslcommerz: { enabled: true }, bkashManual: { enabled: true } }, maintenanceMode: { enabled: false, message: "Scheduled maintenance notice" }, returnPolicy: { windowDays: 7, restockingFeePercent: 0, requireEvidence: true }, tax: { enabled: false, rateBps: 0, pricesIncludeTax: true }, seo: { title: "Amiyo-Go", description: "Trusted marketplace in Bangladesh" }, notificationControls: { orderUpdates: true, promotions: true, sellerAlerts: true, adminAlerts: true } }; assert.equal(platformSettingsInputSchema.safeParse(valid).success, true); assert.equal(platformSettingsInputSchema.safeParse({ ...valid, returnPolicy: { ...valid.returnPolicy, windowDays: 365 } }).success, false); });
test("admin coupons enforce discount and redemption limits", () => { const valid = { code: " amiyo25 ", discountType: "PERCENT" as const, value: 25, maxDiscountMinor: "50000", minimumSpendMinor: "100000", usageLimit: 100, perUserLimit: 2, startsAt: "2026-08-15T00:00:00.000Z", endsAt: "2026-08-30T00:00:00.000Z", active: true }; assert.equal(adminCouponInputSchema.parse(valid).code, "AMIYO25"); assert.equal(adminCouponInputSchema.safeParse({ ...valid, value: 101 }).success, false); assert.equal(adminCouponInputSchema.safeParse({ ...valid, usageLimit: 1, perUserLimit: 2 }).success, false); assert.equal(adminCouponInputSchema.safeParse({ ...valid, endsAt: valid.startsAt }).success, false); });
test("admin campaigns validate storefront actions and targeting", () => { const productId = "00000000-0000-4000-8000-000000000401"; const valid = { name: "Eid marketplace sale", slug: "eid-marketplace-sale", description: "Save across selected marketplace products.", discountType: "PERCENT" as const, discountValue: 20, startsAt: "2026-08-15T00:00:00.000Z", endsAt: "2026-08-30T00:00:00.000Z", productIds: [productId], buttonText: "Shop now", buttonLink: "/products" }; assert.equal(adminCampaignInputSchema.safeParse(valid).success, true); assert.equal(adminCampaignInputSchema.safeParse({ ...valid, discountValue: 120 }).success, false); assert.equal(adminCampaignInputSchema.safeParse({ ...valid, productIds: [productId, productId] }).success, false); assert.equal(adminCampaignInputSchema.safeParse({ ...valid, buttonLink: "https://evil.example" }).success, false); });
test("admin chat threads preserve sender and participant evidence", () => { const thread = { id: "00000000-0000-4000-8000-000000000901", vendorId: "00000000-0000-4000-8000-000000000101", vendorName: "Demo seller", vendorStatus: "APPROVED", subject: "Shop support", status: "open", participants: [{ userId: "00000000-0000-4000-8000-000000000001", role: "vendor", displayName: "Seller" }], messages: [{ id: "00000000-0000-4000-8000-000000000902", senderId: "00000000-0000-4000-8000-000000000001", senderName: "Seller", senderRole: "vendor", body: "Please review my shop.", attachments: null, createdAt: "2026-08-14T10:00:00.000Z" }], createdAt: "2026-08-14T09:00:00.000Z", updatedAt: "2026-08-14T10:00:00.000Z" }; assert.equal(adminChatThreadSchema.parse(thread).messages[0]?.senderRole, "vendor"); assert.equal(adminChatThreadSchema.safeParse({ ...thread, messages: [{ ...thread.messages[0], body: 42 }] }).success, false); });
