import { Ionicons } from "@expo/vector-icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { pickAndUploadDocument } from "../media/media.api";
import { createTicket, getMyTickets } from "./support.api";

const categories = ["ORDER", "DELIVERY", "PAYMENT", "RETURN", "ACCOUNT", "PRODUCT", "OTHER"] as const;
type Attachment = { storageKey: string; name: string; mimeType: "image/jpeg" | "image/png" | "image/webp" | "application/pdf" };
export function SupportScreen() {
  const router = useRouter(); const cache = useQueryClient(); const user = firebaseAuth?.currentUser ?? null;
  const [subject, setSubject] = useState(""); const [message, setMessage] = useState(""); const [category, setCategory] = useState<(typeof categories)[number]>("ORDER"); const [files, setFiles] = useState<Attachment[]>([]); const [uploading, setUploading] = useState(false);
  const tickets = useQuery({ queryKey: ["support", "mine"], queryFn: () => getMyTickets(user!), enabled: Boolean(user) });
  const create = useMutation({ mutationFn: () => createTicket(user!, { subject, message, category, priority: "normal", attachments: files }), onSuccess: async (ticket) => { setSubject(""); setMessage(""); setFiles([]); await cache.invalidateQueries({ queryKey: ["support", "mine"] }); router.push(`/support/${ticket.id}` as never); } });
  const addFile = async () => { setUploading(true); try { const result = await pickAndUploadDocument(user!, "support"); if (result) setFiles((current) => current.length < 5 ? [...current, { storageKey: result.storageKey, name: result.originalName, mimeType: result.mimeType as Attachment["mimeType"] }] : current); } finally { setUploading(false); } };
  if (!user) return <Screen title="Customer support" description="Sign in to create and track support requests."><Pressable onPress={() => router.push("/auth")} style={styles.primary}><Text style={styles.primaryText}>Sign in</Text></Pressable></Screen>;
  return <Screen eyebrow="HELP CENTER" title="How can we help?" description="Create a ticket and keep the full conversation and evidence in one place.">
    <View style={styles.stats}><Stat label="Open" value={tickets.data?.filter((item) => ["open", "in_progress"].includes(item.status)).length ?? 0} /><Stat label="Resolved" value={tickets.data?.filter((item) => ["resolved", "closed"].includes(item.status)).length ?? 0} /></View>
    <ModuleCard title="Create support ticket" meta="Our support team will reply in this protected thread."><View style={styles.categories}>{categories.map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.chip, category === item && styles.chipActive]}><Text style={[styles.chipText, category === item && styles.chipTextActive]}>{item}</Text></Pressable>)}</View><TextInput onChangeText={setSubject} placeholder="What do you need help with?" placeholderTextColor={colors.muted} style={styles.input} value={subject} /><TextInput multiline onChangeText={setMessage} placeholder="Describe the issue in detail" placeholderTextColor={colors.muted} style={[styles.input, styles.textarea]} value={message} /><View style={styles.attachmentHeader}><Text style={styles.label}>Attachments ({files.length}/5)</Text><Pressable disabled={uploading || files.length >= 5} onPress={() => void addFile()} style={styles.attach}>{uploading ? <ActivityIndicator color={colors.primary} /> : <Text style={styles.attachText}>Add image or PDF</Text>}</Pressable></View>{files.map((file) => <AttachmentRow file={file} key={file.storageKey} remove={() => setFiles((current) => current.filter((item) => item.storageKey !== file.storageKey))} />)}{create.error ? <Text style={styles.error}>{create.error.message}</Text> : null}<Pressable disabled={create.isPending || subject.trim().length < 3 || message.trim().length < 5} onPress={() => create.mutate()} style={[styles.primary, create.isPending && styles.disabled]}>{create.isPending ? <ActivityIndicator color="#fff" /> : <Text style={styles.primaryText}>Submit ticket</Text>}</Pressable></ModuleCard>
    <Text style={styles.heading}>My tickets</Text>{tickets.isLoading ? <ActivityIndicator color={colors.primary} /> : null}{tickets.data?.map((ticket) => <ModuleCard key={ticket.id} title={ticket.subject} meta={`${ticket.category} · ${new Date(ticket.updatedAt).toLocaleString("en-BD")}`}><View style={styles.ticketTop}><Text style={styles.status}>{ticket.status.replaceAll("_", " ").toUpperCase()}</Text><Text style={styles.ticketId}>#{ticket.id.slice(0, 8)}</Text></View><Text style={styles.preview}>{ticket.messages.at(-1)?.body}</Text>{ticket.messages.at(-1)?.attachments.map((file) => <View key={file.storageKey} style={styles.inlineFile}><Ionicons color={colors.primary} name="document-outline" size={15} /><Text numberOfLines={1} style={styles.inlineText}>{file.name}</Text></View>)}<Pressable onPress={() => router.push(`/support/${ticket.id}` as never)} style={styles.primary}><Text style={styles.primaryText}>Open full conversation</Text></Pressable></ModuleCard>)}{tickets.data?.length === 0 ? <ModuleCard title="No support tickets" meta="Your new requests and replies will appear here." /> : null}
  </Screen>;
}
function AttachmentRow({ file, remove }: { file: Attachment; remove(): void }) { return <View style={styles.file}><Ionicons color={colors.primary} name="document-attach-outline" size={18} /><Text numberOfLines={1} style={styles.fileName}>{file.name}</Text><Pressable onPress={remove}><Ionicons color={colors.danger} name="close-circle" size={20} /></Pressable></View>; }
function Stat({ label, value }: { label: string; value: number }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.muted}>{label}</Text></View>; }
const styles = StyleSheet.create({ stats: { flexDirection: "row", gap: spacing.md }, stat: { backgroundColor: colors.primarySoft, borderRadius: radius.lg, flex: 1, padding: spacing.md }, statValue: { color: colors.primary, fontSize: 26, fontWeight: "700" }, muted: { color: colors.muted, fontSize: 11 }, categories: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, chip: { borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8 }, chipActive: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.muted, fontSize: 11, fontWeight: "600" }, chipTextActive: { color: "#fff" }, input: { backgroundColor: "#f8fafc", borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, minHeight: 46, paddingHorizontal: 13, paddingVertical: 10 }, textarea: { minHeight: 110, textAlignVertical: "top" }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, justifyContent: "center", minHeight: 46, paddingHorizontal: spacing.lg }, primaryText: { color: "#fff", fontWeight: "700" }, disabled: { opacity: .55 }, error: { color: colors.danger }, heading: { color: colors.text, fontSize: 22, fontWeight: "700" }, attachmentHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, label: { color: colors.text, fontSize: 12, fontWeight: "700" }, attach: { borderColor: colors.primary, borderRadius: radius.md, borderWidth: 1, minHeight: 38, justifyContent: "center", paddingHorizontal: spacing.md }, attachText: { color: colors.primary, fontWeight: "700" }, file: { alignItems: "center", backgroundColor: "#f8fafc", borderRadius: radius.md, flexDirection: "row", gap: spacing.sm, padding: spacing.sm }, fileName: { color: colors.text, flex: 1 }, ticketTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, status: { backgroundColor: colors.accentSoft, borderRadius: radius.pill, color: colors.accent, fontSize: 10, fontWeight: "700", overflow: "hidden", paddingHorizontal: 9, paddingVertical: 5 }, ticketId: { color: colors.muted, fontSize: 11 }, preview: { color: colors.text, lineHeight: 20 }, inlineFile: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: radius.sm, flexDirection: "row", gap: 5, padding: 7 }, inlineText: { color: colors.primaryDark, flex: 1, fontSize: 11, fontWeight: "600" } });
