import { Ionicons } from "@expo/vector-icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getMyTickets, replyToTicket } from "./support.api";

export function SupportThreadScreen({ id }: { id: string }) {
  const router = useRouter(); const cache = useQueryClient(); const user = firebaseAuth?.currentUser ?? null; const [body, setBody] = useState("");
  const tickets = useQuery({ queryKey: ["support", "mine"], queryFn: () => getMyTickets(user!), enabled: Boolean(user) });
  const ticket = tickets.data?.find((item) => item.id === id);
  const reply = useMutation({ mutationFn: () => replyToTicket(user!, id, body.trim()), onSuccess: async () => { setBody(""); await cache.invalidateQueries({ queryKey: ["support", "mine"] }); } });
  if (tickets.isLoading) return <Screen title="Support conversation"><ActivityIndicator color={colors.primary} /></Screen>;
  if (!ticket) return <Screen title="Ticket unavailable" description="This support request could not be found."><Pressable onPress={() => router.replace("/support")} style={styles.primary}><Text style={styles.primaryText}>Back to support</Text></Pressable></Screen>;
  return <Screen eyebrow="SUPPORT THREAD" title={ticket.subject} description={`${ticket.category} · Ticket #${ticket.id.slice(0, 8).toUpperCase()}`}><View style={styles.header}><Pressable onPress={() => router.replace("/support")} style={styles.back}><Ionicons color={colors.primary} name="arrow-back" size={18} /><Text style={styles.backText}>All tickets</Text></Pressable><Text style={styles.status}>{ticket.status.replaceAll("_", " ").toUpperCase()}</Text></View><View style={styles.thread}>{ticket.messages.map((message, index) => <View key={message.id} style={[styles.message, index === 0 && styles.opening]}><Text style={styles.sender}>{index === 0 ? "Request opened" : "Conversation update"}</Text><Text style={styles.body}>{message.body}</Text><Text style={styles.date}>{new Date(message.createdAt).toLocaleString("en-BD")}</Text></View>)}</View>{ticket.status !== "closed" ? <View style={styles.composer}><TextInput multiline onChangeText={setBody} placeholder="Write a reply" placeholderTextColor={colors.muted} style={styles.input} value={body} /><Pressable disabled={reply.isPending || !body.trim()} onPress={() => reply.mutate()} style={[styles.primary, (reply.isPending || !body.trim()) && styles.disabled]}>{reply.isPending ? <ActivityIndicator color="#fff" /> : <Text style={styles.primaryText}>Send reply</Text>}</Pressable></View> : <Text style={styles.closed}>This ticket is closed. Create a new ticket if you need more help.</Text>}{reply.error ? <Text style={styles.error}>{reply.error.message}</Text> : null}</Screen>;
}

const styles = StyleSheet.create({ header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, back: { alignItems: "center", flexDirection: "row", gap: 6 }, backText: { color: colors.primary, fontWeight: "900" }, status: { backgroundColor: colors.primarySoft, borderRadius: radius.pill, color: colors.primary, fontSize: 9, fontWeight: "900", overflow: "hidden", paddingHorizontal: 10, paddingVertical: 6 }, thread: { gap: spacing.md }, message: { alignSelf: "flex-end", backgroundColor: colors.primarySoft, borderRadius: radius.lg, gap: 6, maxWidth: 720, padding: spacing.md, width: "88%" }, opening: { alignSelf: "flex-start", backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1 }, sender: { color: colors.primary, fontSize: 9, fontWeight: "900" }, body: { color: colors.text, lineHeight: 21 }, date: { color: colors.muted, fontSize: 9 }, composer: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, gap: spacing.sm, padding: spacing.md }, input: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, minHeight: 100, padding: spacing.md, textAlignVertical: "top" }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, minHeight: 46, justifyContent: "center", paddingHorizontal: spacing.lg }, primaryText: { color: "#fff", fontWeight: "900" }, disabled: { opacity: .5 }, closed: { backgroundColor: "#f8fafc", borderRadius: radius.md, color: colors.muted, padding: spacing.md }, error: { color: colors.danger } });
