import type { AdminBannerDto, AdminBannerInput } from "@amiyo/contracts";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { ActivityIndicator, Alert, Image, Pressable, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { createAdminBanner, deleteAdminBanner, getAdminPlatform, toggleAdminResource, updateAdminBanner } from "./admin.api";

const placements = ["home_hero", "home_secondary", "category_banner", "shop_directory", "checkout_trust"] as const;
type Form = { title: string; subtitle: string; placement: typeof placements[number]; storageKey: string; mobileStorageKey: string; ctaLabel: string; badgeText: string; targetValue: string; startsAt: string; endsAt: string; displayOrder: string; active: boolean };
const initialForm = (): Form => ({ title: "", subtitle: "", placement: "home_hero", storageKey: "", mobileStorageKey: "", ctaLabel: "Shop now", badgeText: "MARKETPLACE PICKS", targetValue: "/search", startsAt: new Date().toISOString(), endsAt: new Date(Date.now() + 30 * 86_400_000).toISOString(), displayOrder: "0", active: true });
const payload = (form: Form): AdminBannerInput => ({ title: form.title, subtitle: form.subtitle || null, placement: form.placement, storageKey: form.storageKey, mobileStorageKey: form.mobileStorageKey || null, ctaLabel: form.ctaLabel || null, badgeText: form.badgeText || null, targetType: form.targetValue ? (form.targetValue.startsWith("/") ? "route" : "url") : null, targetValue: form.targetValue || null, startsAt: new Date(form.startsAt).toISOString(), endsAt: new Date(form.endsAt).toISOString(), active: form.active, displayOrder: Number(form.displayOrder || 0) });

export function AdminBannersScreen() {
  const user = firebaseAuth?.currentUser ?? null;
  const cache = useQueryClient();
  const query = useQuery({ queryKey: ["admin", "platform"], queryFn: () => getAdminPlatform(user!), enabled: Boolean(user) });
  const [form, setForm] = useState<Form>(initialForm);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [filter, setFilter] = useState<"all" | Form["placement"]>("all");
  const refresh = () => cache.invalidateQueries({ queryKey: ["admin", "platform"] });
  const save = useMutation({ mutationFn: () => editingId ? updateAdminBanner(user!, editingId, payload(form)) : createAdminBanner(user!, payload(form)), onSuccess: async () => { setEditingId(null); setForm(initialForm()); await refresh(); } });
  const toggle = useMutation({ mutationFn: (banner: AdminBannerDto) => toggleAdminResource(user!, "banners", banner.id, !banner.active), onSuccess: refresh });
  const remove = useMutation({ mutationFn: (id: string) => deleteAdminBanner(user!, id), onSuccess: refresh });
  const banners = useMemo(() => (query.data?.banners || []).filter((banner) => filter === "all" || banner.placement === filter), [filter, query.data?.banners]);
  const edit = (banner: AdminBannerDto) => { setEditingId(banner.id); setForm({ title: banner.title || "", subtitle: banner.subtitle || "", placement: banner.placement, storageKey: banner.storageKey, mobileStorageKey: banner.mobileStorageKey || "", ctaLabel: banner.ctaLabel || "", badgeText: banner.badgeText || "", targetValue: banner.targetValue || "", startsAt: banner.startsAt, endsAt: banner.endsAt, displayOrder: String(banner.displayOrder), active: banner.active }); };
  const confirmDelete = (banner: AdminBannerDto) => Alert.alert("Delete banner?", banner.title || banner.placement, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => remove.mutate(banner.id) }]);
  if (query.isLoading) return <Screen title="Banner management"><ActivityIndicator color={colors.primary} /></Screen>;
  const error = query.error || save.error || toggle.error || remove.error;
  return <Screen eyebrow="MARKETING CONTROL" title="Banner management" description="Create, schedule and publish storefront banners from one responsive workspace.">
    {error ? <Text style={styles.error}>{error.message}</Text> : null}
    <View style={styles.stats}><Stat label="Total" value={query.data?.banners.length || 0} /><Stat label="Live" value={query.data?.banners.filter((item) => item.status === "active").length || 0} /><Stat label="Scheduled" value={query.data?.banners.filter((item) => item.status === "scheduled").length || 0} /></View>
    <ModuleCard title={editingId ? "Edit banner" : "Create banner"} meta="Use a public image URL or an object-storage key">
      <View style={styles.grid}><Field label="Title" value={form.title} onChangeText={(title) => setForm({ ...form, title })} /><Field label="Subtitle" value={form.subtitle} onChangeText={(subtitle) => setForm({ ...form, subtitle })} /><Field label="Desktop image URL / key" value={form.storageKey} onChangeText={(storageKey) => setForm({ ...form, storageKey })} /><Field label="Mobile image URL / key" value={form.mobileStorageKey} onChangeText={(mobileStorageKey) => setForm({ ...form, mobileStorageKey })} /><Field label="CTA label" value={form.ctaLabel} onChangeText={(ctaLabel) => setForm({ ...form, ctaLabel })} /><Field label="Badge text" value={form.badgeText} onChangeText={(badgeText) => setForm({ ...form, badgeText })} /><Field label="App route or URL" value={form.targetValue} onChangeText={(targetValue) => setForm({ ...form, targetValue })} /><Field label="Display order" keyboardType="numeric" value={form.displayOrder} onChangeText={(displayOrder) => setForm({ ...form, displayOrder })} /><Field label="Starts at (ISO date)" value={form.startsAt} onChangeText={(startsAt) => setForm({ ...form, startsAt })} /><Field label="Ends at (ISO date)" value={form.endsAt} onChangeText={(endsAt) => setForm({ ...form, endsAt })} /></View>
      <Text style={styles.label}>Placement</Text><View style={styles.chips}>{placements.map((placement) => <Chip key={placement} active={form.placement === placement} label={placement.replaceAll("_", " ")} onPress={() => setForm({ ...form, placement })} />)}</View>
      <View style={styles.switchRow}><Text style={styles.label}>Published</Text><Switch value={form.active} onValueChange={(active) => setForm({ ...form, active })} /></View>
      <View style={styles.actions}><Button disabled={save.isPending || !form.title.trim() || !form.storageKey.trim()} label={save.isPending ? "Saving..." : editingId ? "Update banner" : "Create banner"} onPress={() => save.mutate()} />{editingId ? <Button label="Cancel edit" secondary onPress={() => { setEditingId(null); setForm(initialForm()); }} /> : null}</View>
    </ModuleCard>
    <View style={styles.chips}><Chip active={filter === "all"} label="all" onPress={() => setFilter("all")} />{placements.map((placement) => <Chip key={placement} active={filter === placement} label={placement.replaceAll("_", " ")} onPress={() => setFilter(placement)} />)}</View>
    {banners.map((banner) => <ModuleCard key={banner.id} title={banner.title || banner.placement} meta={`${banner.placement.replaceAll("_", " ")} · position ${banner.displayOrder}`}>
      {banner.imageUrl ? <Image source={{ uri: banner.imageUrl }} style={styles.preview} /> : <View style={[styles.preview, styles.missing]}><Text style={styles.muted}>Set OBJECT_STORAGE_PUBLIC_URL to preview storage keys.</Text></View>}
      <View style={styles.statusRow}><View style={[styles.badge, styles[`status_${banner.status}`]]}><Text style={styles.badgeLabel}>{banner.status.toUpperCase()}</Text></View><Switch value={banner.active} onValueChange={() => toggle.mutate(banner)} /></View>
      {banner.subtitle ? <Text style={styles.muted}>{banner.subtitle}</Text> : null}<Text style={styles.muted}>{new Date(banner.startsAt).toLocaleString()} — {new Date(banner.endsAt).toLocaleString()}</Text>
      <View style={styles.actions}><Button label="Edit" secondary onPress={() => edit(banner)} /><Button danger label="Delete" onPress={() => confirmDelete(banner)} /></View>
    </ModuleCard>)}
    {!banners.length ? <Text style={styles.empty}>No banners found for this placement.</Text> : null}
  </Screen>;
}

function Field({ label, ...props }: React.ComponentProps<typeof TextInput> & { label: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput autoCapitalize="none" placeholderTextColor={colors.muted} style={styles.input} {...props} /></View>; }
function Chip({ active, label, onPress }: { active: boolean; label: string; onPress(): void }) { return <Pressable onPress={onPress} style={[styles.chip, active && styles.activeChip]}><Text style={[styles.chipText, active && styles.activeChipText]}>{label}</Text></Pressable>; }
function Button({ danger, disabled, label, onPress, secondary }: { danger?: boolean; disabled?: boolean; label: string; onPress(): void; secondary?: boolean }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, secondary && styles.secondaryButton, danger && styles.dangerButton, disabled && styles.disabled]}><Text style={[styles.buttonText, secondary && styles.secondaryButtonText]}>{label}</Text></Pressable>; }
function Stat({ label, value }: { label: string; value: number }) { return <View style={styles.stat}><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ stats: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, stat: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flex: 1, minWidth: 110, padding: spacing.md }, statLabel: { color: colors.muted, fontSize: 11, fontWeight: "800", textTransform: "uppercase" }, statValue: { color: colors.text, fontSize: 26, fontWeight: "900", marginTop: 4 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, field: { flex: 1, minWidth: 230 }, label: { color: colors.text, fontSize: 12, fontWeight: "800", marginBottom: spacing.xs, marginTop: spacing.xs }, input: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, padding: spacing.md }, chips: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs }, chip: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8 }, activeChip: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.muted, fontSize: 11, fontWeight: "800", textTransform: "capitalize" }, activeChipText: { color: colors.surface }, switchRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: spacing.sm }, actions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.md }, button: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, minWidth: 120, paddingHorizontal: 16, paddingVertical: 12 }, secondaryButton: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1 }, dangerButton: { backgroundColor: colors.danger }, buttonText: { color: colors.surface, fontWeight: "900" }, secondaryButtonText: { color: colors.text }, disabled: { opacity: 0.45 }, preview: { aspectRatio: 3, backgroundColor: colors.background, borderRadius: radius.md, marginBottom: spacing.sm, width: "100%" }, missing: { alignItems: "center", justifyContent: "center", padding: spacing.md }, muted: { color: colors.muted, fontSize: 12, lineHeight: 18 }, statusRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, badge: { backgroundColor: colors.border, borderRadius: radius.pill, paddingHorizontal: 10, paddingVertical: 5 }, status_active: { backgroundColor: "#dcfce7" }, status_scheduled: { backgroundColor: "#e0f2fe" }, status_inactive: { backgroundColor: "#f1f5f9" }, status_expired: { backgroundColor: "#fee2e2" }, badgeLabel: { color: colors.text, fontSize: 10, fontWeight: "900" }, empty: { color: colors.muted, padding: spacing.lg, textAlign: "center" }, error: { color: colors.danger } });
