import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Image, Pressable, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { createAdminCampaign, getAdminCampaigns, updateAdminCampaign, type AdminCampaignInput } from "./admin.api";

type OfferForm = { name: string; slug: string; description: string; discountType: "PERCENT" | "FIXED"; discountValue: string; imageUrl: string; startsAt: string; endsAt: string; status: "draft" | "active" | "paused"; showAsPopup: boolean; priority: string; couponCode: string; productIds: string[]; buttonText: string; buttonLink: string };
const defaults = (): OfferForm => ({ name: "", slug: "", description: "", discountType: "PERCENT", discountValue: "10", imageUrl: "", startsAt: new Date().toISOString(), endsAt: new Date(Date.now() + 30 * 86_400_000).toISOString(), status: "draft", showAsPopup: true, priority: "0", couponCode: "", productIds: [], buttonText: "Shop now", buttonLink: "/products" });

export function AdminOfferFormScreen({ id }: { id?: string }) {
  const user = firebaseAuth?.currentUser ?? null;
  const router = useRouter();
  const cache = useQueryClient();
  const workspace = useQuery({ queryKey: ["admin", "campaigns"], queryFn: () => getAdminCampaigns(user!), enabled: Boolean(user) });
  const campaign = workspace.data?.campaigns.find((item) => item.id === id);
  const [form, setForm] = useState<OfferForm>(defaults);
  const [productSearch, setProductSearch] = useState("");
  useEffect(() => { if (campaign) setForm({ name: campaign.name, slug: campaign.slug, description: campaign.description, discountType: campaign.discountType, discountValue: String(campaign.discountValue), imageUrl: campaign.imageUrl || "", startsAt: campaign.startsAt, endsAt: campaign.endsAt, status: campaign.status, showAsPopup: campaign.showAsPopup, priority: String(campaign.priority), couponCode: campaign.couponCode || "", productIds: campaign.products.map((item) => item.id), buttonText: campaign.buttonText, buttonLink: campaign.buttonLink }); }, [campaign]);
  const generatedSlug = form.name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
  const payload = (): AdminCampaignInput => ({ name: form.name.trim(), slug: form.slug.trim() || generatedSlug, description: form.description.trim(), discountType: form.discountType, discountValue: Number(form.discountValue), imageUrl: form.imageUrl.trim() || null, startsAt: new Date(form.startsAt).toISOString(), endsAt: new Date(form.endsAt).toISOString(), status: form.status, showAsPopup: form.showAsPopup, priority: Number(form.priority), couponCode: form.couponCode.trim() || null, productIds: form.productIds, buttonText: form.buttonText.trim(), buttonLink: form.buttonLink.trim() });
  const submit = useMutation({ mutationFn: () => id && campaign ? updateAdminCampaign(user!, id, { ...payload(), expectedVersion: campaign.version }) : createAdminCampaign(user!, payload()), onSuccess: async () => { await cache.invalidateQueries({ queryKey: ["admin", "campaigns"] }); router.replace("/admin/offers"); } });
  const availableProducts = useMemo(() => (workspace.data?.products || []).filter((item) => `${item.name} ${item.slug}`.toLowerCase().includes(productSearch.toLowerCase())).slice(0, 100), [workspace.data, productSearch]);
  const valid = Boolean(user && form.name.trim().length >= 3 && (form.slug.trim() || generatedSlug).length >= 3 && form.description.trim().length >= 10 && Number(form.discountValue) > 0 && (form.discountType !== "PERCENT" || Number(form.discountValue) <= 100) && Number(form.priority) >= 0 && Date.parse(form.startsAt) < Date.parse(form.endsAt) && form.buttonText.trim().length >= 2 && form.buttonLink.startsWith("/") && (!form.imageUrl || /^https?:\/\//.test(form.imageUrl)));
  if (workspace.isLoading) return <Screen title={id ? "Edit offer" : "Create offer"}><ActivityIndicator color={colors.primary} /></Screen>;
  return <Screen eyebrow="MARKETING" title={id ? "Edit promotional offer" : "Create promotional offer"} description="Build a scheduled storefront campaign with discount messaging, popup placement and targeted products.">
    {id && !campaign ? <Text style={styles.error}>Offer not found.</Text> : null}
    {(!id || campaign) ? <><ModuleCard title="Basic information" meta="Customer-facing campaign identity and message"><View style={styles.grid}><Field label="Offer title" value={form.name} onChangeText={(name) => setForm({ ...form, name })} /><Field label="URL slug" value={form.slug} placeholder={generatedSlug || "summer-sale"} onChangeText={(slug) => setForm({ ...form, slug: slug.toLowerCase().replace(/[^a-z0-9-]/g, "") })} /></View><Field label="Description" multiline numberOfLines={4} value={form.description} onChangeText={(description) => setForm({ ...form, description })} /><View style={styles.grid}><Field keyboardType="numeric" label={form.discountType === "PERCENT" ? "Discount value (%)" : "Discount value (৳)"} value={form.discountValue} onChangeText={(discountValue) => setForm({ ...form, discountValue })} /><Field keyboardType="numeric" label="Display priority" value={form.priority} onChangeText={(priority) => setForm({ ...form, priority })} /></View><Text style={styles.label}>Discount type</Text><View style={styles.chips}>{(["PERCENT", "FIXED"] as const).map((type) => <Chip key={type} active={form.discountType === type} label={type === "PERCENT" ? "Percentage" : "Fixed amount"} onPress={() => setForm({ ...form, discountType: type })} />)}</View></ModuleCard>
      <ModuleCard title="Media and action" meta="Use a secure public image URL from the media library"><Field label="Offer image URL" value={form.imageUrl} placeholder="https://..." onChangeText={(imageUrl) => setForm({ ...form, imageUrl })} />{form.imageUrl && /^https?:\/\//.test(form.imageUrl) ? <Image source={{ uri: form.imageUrl }} style={styles.preview} /> : null}<View style={styles.grid}><Field label="Button text" value={form.buttonText} onChangeText={(buttonText) => setForm({ ...form, buttonText })} /><Field label="Internal button link" value={form.buttonLink} onChangeText={(buttonLink) => setForm({ ...form, buttonLink })} /></View></ModuleCard>
      <ModuleCard title="Schedule and publishing" meta="Control when and where the offer appears"><View style={styles.grid}><Field label="Starts at (ISO date)" value={form.startsAt} onChangeText={(startsAt) => setForm({ ...form, startsAt })} /><Field label="Ends at (ISO date)" value={form.endsAt} onChangeText={(endsAt) => setForm({ ...form, endsAt })} /><Field label="Coupon code (optional)" value={form.couponCode} onChangeText={(couponCode) => setForm({ ...form, couponCode: couponCode.toUpperCase().replace(/[^A-Z0-9_-]/g, "") })} /></View>{workspace.data?.coupons.length ? <View style={styles.chips}>{workspace.data.coupons.map((coupon) => <Chip key={coupon.code} active={form.couponCode === coupon.code} label={`${coupon.code}${coupon.active ? "" : " (disabled)"}`} onPress={() => setForm({ ...form, couponCode: form.couponCode === coupon.code ? "" : coupon.code })} />)}</View> : null}<Text style={styles.label}>Publication state</Text><View style={styles.chips}>{(["draft", "active", "paused"] as const).map((status) => <Chip key={status} active={form.status === status} label={status} onPress={() => setForm({ ...form, status })} />)}</View><View style={styles.switchRow}><View><Text style={styles.label}>Show as popup</Text><Text style={styles.muted}>Display this offer in the promotional popup placement.</Text></View><Switch value={form.showAsPopup} onValueChange={(showAsPopup) => setForm({ ...form, showAsPopup })} /></View></ModuleCard>
      <ModuleCard title="Target products" meta={`${form.productIds.length} products selected`}><TextInput value={productSearch} onChangeText={setProductSearch} placeholder="Search published products" placeholderTextColor={colors.muted} style={styles.search} /><View style={styles.products}>{availableProducts.map((product) => { const selected = form.productIds.includes(product.id); return <Pressable key={product.id} onPress={() => setForm({ ...form, productIds: selected ? form.productIds.filter((id) => id !== product.id) : [...form.productIds, product.id] })} style={[styles.product, selected && styles.selectedProduct]}>{product.imageUrl ? <Image source={{ uri: product.imageUrl }} style={styles.productImage} /> : null}<View style={styles.productText}><Text style={styles.productName}>{product.name}</Text><Text style={styles.muted}>৳{(Number(product.priceMinor) / 100).toLocaleString("en-BD")}</Text></View><Text style={[styles.selectText, selected && styles.selectedText]}>{selected ? "Selected" : "Add"}</Text></Pressable>; })}</View></ModuleCard>
      {submit.error ? <Text style={styles.error}>{submit.error.message}</Text> : null}<View style={styles.footer}><Pressable onPress={() => router.back()} style={styles.secondary}><Text style={styles.secondaryText}>Cancel</Text></Pressable><Pressable disabled={!valid || submit.isPending} onPress={() => submit.mutate()} style={[styles.primary, (!valid || submit.isPending) && styles.disabled]}><Text style={styles.primaryText}>{submit.isPending ? "Saving..." : id ? "Save offer" : "Create offer"}</Text></Pressable></View></> : null}
  </Screen>;
}
function Field({ label, ...props }: React.ComponentProps<typeof TextInput> & { label: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} placeholderTextColor={colors.muted} style={[styles.input, props.multiline && styles.textarea]} /></View>; }
function Chip({ active, label, onPress }: { active: boolean; label: string; onPress(): void }) { return <Pressable onPress={onPress} style={[styles.chip, active && styles.activeChip]}><Text style={[styles.chipText, active && styles.activeChipText]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md }, field: { flex: 1, gap: 6, minWidth: 220 }, label: { color: colors.text, fontSize: 11, fontWeight: "900", marginTop: spacing.xs }, input: { backgroundColor: colors.background, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, minHeight: 46, paddingHorizontal: 12, paddingVertical: 10 }, textarea: { minHeight: 105, textAlignVertical: "top" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs, marginTop: spacing.sm }, chip: { borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 8 }, activeChip: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.muted, fontSize: 11, fontWeight: "800", textTransform: "capitalize" }, activeChipText: { color: colors.surface }, preview: { borderRadius: radius.md, height: 220, marginTop: spacing.md, width: "100%" }, switchRow: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: spacing.md, justifyContent: "space-between", marginTop: spacing.md }, muted: { color: colors.muted, fontSize: 12, lineHeight: 18 }, search: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, minHeight: 46, paddingHorizontal: spacing.md }, products: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, marginTop: spacing.md }, product: { alignItems: "center", borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flexDirection: "row", gap: spacing.sm, minWidth: 250, padding: spacing.sm }, selectedProduct: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, productImage: { borderRadius: radius.sm, height: 44, width: 44 }, productText: { flex: 1, minWidth: 110 }, productName: { color: colors.text, fontSize: 12, fontWeight: "900" }, selectText: { color: colors.primary, fontSize: 11, fontWeight: "900" }, selectedText: { color: colors.success }, footer: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, justifyContent: "flex-end" }, primary: { backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: spacing.lg, paddingVertical: 13 }, primaryText: { color: colors.surface, fontWeight: "900" }, secondary: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, paddingHorizontal: spacing.lg, paddingVertical: 13 }, secondaryText: { color: colors.text, fontWeight: "900" }, disabled: { opacity: .45 }, error: { color: colors.danger, fontWeight: "700" } });
