import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getAdminCommerce } from "./admin.api";

const taka = (minor: string | number) => `৳${(Number(minor) / 100).toLocaleString("en-BD")}`;
type Range = "7d" | "30d" | "90d";
export function AdminVendorActivityScreen() {
  const user = firebaseAuth?.currentUser ?? null; const router = useRouter(); const [range, setRange] = useState<Range>("30d"); const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL");
  const query = useQuery({ queryKey: ["admin", "commerce"], queryFn: () => getAdminCommerce(user!), enabled: Boolean(user), refetchInterval: 30_000, staleTime: 15_000 });
  const cutoff = Date.now() - Number(range.slice(0, -1)) * 86_400_000;
  const orders = (query.data?.orders ?? []).filter((item) => new Date(item.createdAt).getTime() >= cutoff);
  const vendors = useMemo(() => (query.data?.vendorActivity ?? []).filter((item) => status === "ALL" || item.status === status).filter((item) => `${item.vendor} ${item.status}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => Number(b.gmvMinor) - Number(a.gmvMinor)), [query.data, search, status]);
  const gmv = orders.reduce((sum, item) => sum + Number(item.totalMinor), 0); const active = (query.data?.vendorActivity ?? []).filter((item) => item.status === "APPROVED").length; const aov = orders.length ? gmv / orders.length : 0;
  const exportCsv = () => { if (Platform.OS !== "web") return; const rows = [["Vendor", "Status", "GMV minor", "Commission minor", "Products", "Orders", "Chats", "Payout requests"], ...vendors.map((item) => [item.vendor, item.status, item.gmvMinor, item.commissionMinor, item.products, item.orders, item.chats, item.payoutRequests])]; const body = rows.map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([body], { type: "text/csv" })); link.download = `amiyo-vendor-activity-${range}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  return <Screen eyebrow="SELLER OPERATIONS" title="Vendor Activity Center" description="Real-time seller performance, marketplace activity and operational health monitoring.">
    {query.error ? <Text style={styles.error}>{query.error.message}</Text> : null}
    <View style={styles.controls}><View style={styles.pills}>{(["7d", "30d", "90d"] as Range[]).map((item) => <Pressable key={item} onPress={() => setRange(item)} style={[styles.pill, range === item && styles.active]}><Text style={[styles.pillText, range === item && styles.activeText]}>{item}</Text></Pressable>)}</View><Pressable onPress={() => query.refetch()} style={styles.button}><Text style={styles.buttonText}>Refresh</Text></Pressable>{Platform.OS === "web" ? <Pressable onPress={exportCsv} style={styles.button}><Text style={styles.buttonText}>Export CSV</Text></Pressable> : null}</View>
    <View style={styles.metrics}><Metric label="Total revenue" value={taka(gmv)} /><Metric label="Total orders" value={orders.length} /><Metric label="Active vendors" value={active} /><Metric label="Average order" value={taka(aov)} /><Metric label="Pending payouts" value={(query.data?.vendorActivity ?? []).reduce((sum, item) => sum + item.payoutRequests, 0)} /><Metric label="Seller chats" value={(query.data?.vendorActivity ?? []).reduce((sum, item) => sum + item.chats, 0)} /></View>
    <View style={styles.filters}><TextInput value={search} onChangeText={setSearch} placeholder="Search vendor" placeholderTextColor={colors.muted} style={styles.input} />{["ALL", "APPROVED", "PENDING", "SUSPENDED", "REJECTED"].map((item) => <Pressable key={item} onPress={() => setStatus(item)} style={[styles.pill, status === item && styles.active]}><Text style={[styles.pillText, status === item && styles.activeText]}>{item}</Text></Pressable>)}</View>
    <ModuleCard title="Seller performance ranking" meta={`${vendors.length} vendors · ranked by marketplace GMV`}>{vendors.map((item, index) => <Pressable key={item.id} onPress={() => router.push(`/admin/vendors/${item.id}` as never)} style={styles.row}><Text style={styles.rank}>#{index + 1}</Text><View style={styles.flex}><Text style={styles.strong}>{item.vendor}</Text><Text style={styles.muted}>{item.products} products · {item.orders} orders · {item.chats} chats · {item.payoutRequests} payout requests</Text></View><View style={styles.right}><Text style={styles.amount}>{taka(item.gmvMinor)}</Text><Text style={styles.commission}>{taka(item.commissionMinor)} commission</Text><Status value={item.status} /></View></Pressable>)}{!query.isLoading && !vendors.length ? <Text style={styles.muted}>No vendors match this filter.</Text> : null}</ModuleCard>
    <View style={styles.columns}><ModuleCard title="Latest order activity" meta={`${orders.length} orders in selected period`}>{orders.slice(0, 10).map((item) => <Pressable key={item.id} onPress={() => router.push(`/admin/orders/${item.id}` as never)} style={styles.activity}><View style={styles.flex}><Text style={styles.strong}>{item.orderNumber}</Text><Text style={styles.muted}>{item.customer} · {item.vendorCount} vendors · {new Date(item.createdAt).toLocaleString()}</Text></View><Text style={styles.amount}>{taka(item.totalMinor)}</Text></Pressable>)}</ModuleCard><ModuleCard title="Latest seller conversations" meta="Support and operational signals">{(query.data?.chats ?? []).slice(0, 10).map((item) => <Pressable key={item.id} onPress={() => router.push(`/admin/chats/${item.id}` as never)} style={styles.activity}><View style={styles.flex}><Text style={styles.strong}>{item.vendor}</Text><Text style={styles.muted}>{item.subject} · {item.lastMessage || "No message"}</Text></View><Status value={item.status} /></Pressable>)}</ModuleCard></View>
  </Screen>;
}
function Metric({ label, value }: { label: string; value: number | string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
function Status({ value }: { value: string }) { return <Text style={styles.status}>{value.replaceAll("_", " ").toUpperCase()}</Text>; }
const styles = StyleSheet.create({ error: { color: colors.danger }, controls: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, justifyContent: "space-between" }, pills: { flexDirection: "row", gap: spacing.xs }, pill: { borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 7 }, active: { backgroundColor: colors.primary, borderColor: colors.primary }, pillText: { color: colors.muted, fontSize: 9, fontWeight: "900" }, activeText: { color: colors.surface }, button: { backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: 14, paddingVertical: 10 }, buttonText: { color: colors.surface, fontSize: 10, fontWeight: "900" }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, metric: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flex: 1, minWidth: 140, padding: spacing.md }, metricLabel: { color: colors.muted, fontSize: 10, fontWeight: "900", textTransform: "uppercase" }, metricValue: { color: colors.text, fontSize: 22, fontWeight: "900", marginTop: 4 }, filters: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: spacing.xs }, input: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, flex: 1, minHeight: 42, minWidth: 220, paddingHorizontal: 12 }, row: { alignItems: "center", borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, paddingVertical: 12 }, rank: { color: colors.primary, fontSize: 15, fontWeight: "900", width: 34 }, flex: { flex: 1, minWidth: 180 }, strong: { color: colors.text, fontSize: 12, fontWeight: "900" }, muted: { color: colors.muted, fontSize: 10, lineHeight: 17 }, right: { alignItems: "flex-end", gap: 3 }, amount: { color: colors.text, fontSize: 14, fontWeight: "900" }, commission: { color: colors.muted, fontSize: 9 }, status: { backgroundColor: colors.primarySoft, borderRadius: radius.pill, color: colors.primary, fontSize: 8, fontWeight: "900", overflow: "hidden", paddingHorizontal: 8, paddingVertical: 4 }, columns: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md }, activity: { alignItems: "center", borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: "row", gap: spacing.sm, paddingVertical: spacing.sm } });
