import { Ionicons } from "@expo/vector-icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getPlatformSettings, updatePlatformSettings, type PlatformSettingsInput } from "./admin.api";

type FeatureKey = keyof PlatformSettingsInput["featureFlags"]; type PaymentKey = keyof PlatformSettingsInput["paymentMethods"]; type NotificationKey = keyof PlatformSettingsInput["notificationControls"];
const labels: Record<FeatureKey, string> = { sellerRegistration: "Seller registration", reviews: "Customer reviews", questions: "Product questions", flashSales: "Flash sales", loyalty: "Loyalty rewards", voiceSearch: "Voice search", googleLogin: "Google login" };
const paymentLabels: Record<PaymentKey, string> = { cod: "Cash on delivery", sslcommerz: "SSLCommerz", bkashManual: "Manual bKash verification" };
const notificationLabels: Record<NotificationKey, string> = { orderUpdates: "Order updates", promotions: "Promotional messages", sellerAlerts: "Seller alerts", adminAlerts: "Admin alerts" };

export function AdminSettingsScreen() {
  const user = firebaseAuth?.currentUser ?? null; const cache = useQueryClient(); const query = useQuery({ queryKey: ["admin", "settings"], queryFn: () => getPlatformSettings(user!), enabled: Boolean(user), staleTime: 15_000 }); const [form, setForm] = useState<PlatformSettingsInput | null>(null);
  useEffect(() => { if (query.data) setForm({ expectedVersion: query.data.version, featureFlags: query.data.featureFlags, paymentMethods: query.data.paymentMethods, maintenanceMode: query.data.maintenanceMode, returnPolicy: query.data.returnPolicy, tax: query.data.tax, seo: query.data.seo, notificationControls: query.data.notificationControls }); }, [query.data]);
  const save = useMutation({ mutationFn: () => updatePlatformSettings(user!, form!), onSuccess: async (data) => { setForm({ expectedVersion: data.version, featureFlags: data.featureFlags, paymentMethods: data.paymentMethods, maintenanceMode: data.maintenanceMode, returnPolicy: data.returnPolicy, tax: data.tax, seo: data.seo, notificationControls: data.notificationControls }); await Promise.all([cache.invalidateQueries({ queryKey: ["admin", "settings"] }), cache.invalidateQueries({ queryKey: ["admin", "audit"] })]); } });
  if (query.isLoading || !form) return <Screen title="Platform settings"><ActivityIndicator color={colors.primary} /></Screen>; const error = query.error || save.error;
  return <Screen eyebrow="PLATFORM CONTROL" title="Settings & health" description="Safely control marketplace availability, payments, policies, notifications and release health.">
    {error ? <Text style={styles.error}>{error.message}</Text> : null}<View style={styles.healthHead}><View><Text style={styles.sectionTitle}>Service health</Text><Text style={styles.muted}>Checked {query.data ? new Date(query.data.health.checkedAt).toLocaleString("en-BD") : "—"}</Text></View><Status value={query.data?.health.overall || "degraded"} /></View><View style={styles.healthGrid}>{query.data?.health.services.map((service) => <View key={service.key} style={styles.healthCard}><View style={styles.row}><Ionicons color={service.status === "healthy" ? colors.success : colors.warning} name={service.status === "healthy" ? "checkmark-circle" : "warning"} size={20} /><Text style={styles.healthName}>{service.label}</Text></View><Text style={styles.muted}>{service.detail}</Text></View>)}</View>
    <ModuleCard title="Maintenance mode" meta="Show a controlled service notice while critical work is in progress"><Toggle label="Maintenance enabled" value={form.maintenanceMode.enabled} onChange={(enabled) => setForm({ ...form, maintenanceMode: { ...form.maintenanceMode, enabled } })} /><Field label="Customer message" multiline value={form.maintenanceMode.message} onChangeText={(message) => setForm({ ...form, maintenanceMode: { ...form.maintenanceMode, message } })} /></ModuleCard>
    <ModuleCard title="Feature flags" meta="Release or pause customer and seller capabilities without a new app build"><View style={styles.toggleGrid}>{(Object.keys(form.featureFlags) as FeatureKey[]).map((key) => <Toggle key={key} label={labels[key]} value={form.featureFlags[key]} onChange={(value) => setForm({ ...form, featureFlags: { ...form.featureFlags, [key]: value } })} />)}</View></ModuleCard>
    <ModuleCard title="Payment methods" meta="Control methods presented at checkout"><View style={styles.toggleGrid}>{(Object.keys(form.paymentMethods) as PaymentKey[]).map((key) => <Toggle key={key} label={paymentLabels[key]} value={form.paymentMethods[key].enabled} onChange={(enabled) => setForm({ ...form, paymentMethods: { ...form.paymentMethods, [key]: { enabled } } })} />)}</View></ModuleCard>
    <ModuleCard title="Returns & tax" meta="Marketplace-wide policy defaults"><View style={styles.grid}><Field keyboardType="number-pad" label="Return window (days)" value={String(form.returnPolicy.windowDays)} onChangeText={(value) => setForm({ ...form, returnPolicy: { ...form.returnPolicy, windowDays: Number(value || 0) } })} /><Field keyboardType="numeric" label="Restocking fee (%)" value={String(form.returnPolicy.restockingFeePercent)} onChangeText={(value) => setForm({ ...form, returnPolicy: { ...form.returnPolicy, restockingFeePercent: Number(value || 0) } })} /><Field keyboardType="number-pad" label="Tax rate (basis points)" value={String(form.tax.rateBps)} onChangeText={(value) => setForm({ ...form, tax: { ...form.tax, rateBps: Number(value || 0) } })} /></View><View style={styles.toggleGrid}><Toggle label="Return evidence required" value={form.returnPolicy.requireEvidence} onChange={(requireEvidence) => setForm({ ...form, returnPolicy: { ...form.returnPolicy, requireEvidence } })} /><Toggle label="Tax enabled" value={form.tax.enabled} onChange={(enabled) => setForm({ ...form, tax: { ...form.tax, enabled } })} /><Toggle label="Prices include tax" value={form.tax.pricesIncludeTax} onChange={(pricesIncludeTax) => setForm({ ...form, tax: { ...form.tax, pricesIncludeTax } })} /></View></ModuleCard>
    <ModuleCard title="Storefront identity" meta="Default search and sharing metadata"><View style={styles.grid}><Field label="Marketplace title" value={form.seo.title} onChangeText={(title) => setForm({ ...form, seo: { ...form.seo, title } })} /><Field label="Marketplace description" multiline value={form.seo.description} onChangeText={(description) => setForm({ ...form, seo: { ...form.seo, description } })} /></View></ModuleCard>
    <ModuleCard title="Notification controls" meta="Pause message classes while preserving transactional safety"><View style={styles.toggleGrid}>{(Object.keys(form.notificationControls) as NotificationKey[]).map((key) => <Toggle key={key} label={notificationLabels[key]} value={form.notificationControls[key]} onChange={(value) => setForm({ ...form, notificationControls: { ...form.notificationControls, [key]: value } })} />)}</View></ModuleCard>
    <View style={styles.saveBar}><View><Text style={styles.version}>Configuration v{form.expectedVersion}</Text><Text style={styles.muted}>Every save creates an immutable audit event.</Text></View><Pressable disabled={save.isPending} onPress={() => save.mutate()} style={[styles.save, save.isPending && styles.disabled]}>{save.isPending ? <ActivityIndicator color="#fff" /> : <Text style={styles.saveText}>Save platform settings</Text>}</Pressable></View>
  </Screen>;
}
function Toggle({ label, onChange, value }: { label: string; onChange(value: boolean): void; value: boolean }) { return <View style={styles.toggle}><Text style={styles.toggleLabel}>{label}</Text><Switch onValueChange={onChange} trackColor={{ false: colors.border, true: colors.primarySoft }} thumbColor={value ? colors.primary : colors.muted} value={value} /></View>; } function Field({ label, ...props }: React.ComponentProps<typeof TextInput> & { label: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput placeholderTextColor={colors.muted} style={[styles.input, props.multiline && styles.textarea]} {...props} /></View>; } function Status({ value }: { value: "healthy" | "degraded" }) { return <Text style={[styles.status, value === "degraded" && styles.degraded]}>{value.toUpperCase()}</Text>; }
const styles = StyleSheet.create({ healthHead: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, sectionTitle: { color: colors.text, fontSize: 20, fontWeight: "700" }, healthGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, healthCard: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, flex: 1, gap: 7, minWidth: 180, padding: spacing.md }, row: { alignItems: "center", flexDirection: "row", gap: 8 }, healthName: { color: colors.text, fontSize: 13, fontWeight: "700" }, muted: { color: colors.muted, fontSize: 10, lineHeight: 16 }, status: { backgroundColor: "#dcfce7", borderRadius: radius.pill, color: "#166534", fontSize: 9, fontWeight: "700", overflow: "hidden", paddingHorizontal: 10, paddingVertical: 6 }, degraded: { backgroundColor: "#fef3c7", color: "#92400e" }, toggleGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, toggle: { alignItems: "center", backgroundColor: colors.background, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flex: 1, flexDirection: "row", justifyContent: "space-between", minWidth: 210, paddingHorizontal: 12, paddingVertical: 9 }, toggleLabel: { color: colors.text, flex: 1, fontSize: 11, fontWeight: "600" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, field: { flex: 1, minWidth: 220 }, label: { color: colors.text, fontSize: 11, fontWeight: "700", marginBottom: 5 }, input: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, minHeight: 44, outlineStyle: "none", paddingHorizontal: 12 } as never, textarea: { minHeight: 76, paddingVertical: 10, textAlignVertical: "top" }, saveBar: { alignItems: "center", backgroundColor: colors.navy, borderRadius: radius.lg, flexDirection: "row", flexWrap: "wrap", gap: spacing.md, justifyContent: "space-between", padding: spacing.md }, version: { color: "#fff", fontSize: 14, fontWeight: "700" }, save: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, minWidth: 190, paddingHorizontal: 18, paddingVertical: 13 }, saveText: { color: "#fff", fontSize: 11, fontWeight: "700" }, disabled: { opacity: .5 }, error: { color: colors.danger, fontWeight: "700" } });
