import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getAdminChat, readAdminChat, sendAdminChatMessage } from "./admin.api";

export function AdminChatDetailScreen({ threadId }: { threadId?: string }) { const user = firebaseAuth?.currentUser ?? null; const router = useRouter(); const cache = useQueryClient(); const [body, setBody] = useState(""); const query = useQuery({ queryKey: ["admin", "chat", threadId], queryFn: () => getAdminChat(user!, threadId!), enabled: Boolean(user && threadId), refetchInterval: 10_000 }); const markRead = useMutation({ mutationFn: () => readAdminChat(user!, threadId!), onSuccess: () => cache.invalidateQueries({ queryKey: ["admin", "chats"] }) }); useEffect(() => { if (query.data && !markRead.isSuccess && !markRead.isPending) markRead.mutate(); }, [query.data, markRead.isPending, markRead.isSuccess]); const send = useMutation({ mutationFn: () => sendAdminChatMessage(user!, threadId!, body.trim()), onSuccess: (data) => { setBody(""); cache.setQueryData(["admin", "chat", threadId], data); cache.invalidateQueries({ queryKey: ["admin", "chats"] }); } }); if (query.isLoading) return <Screen title="Vendor conversation"><ActivityIndicator color={colors.primary} /></Screen>; const thread = query.data; return <Screen eyebrow="SELLER SUPPORT" title={thread?.vendorName || "Vendor conversation"} description={`${thread?.subject || "Seller support"} · ${thread?.status || "open"}`}><View style={styles.header}><Pressable onPress={() => router.replace("/admin/chats")} style={styles.secondary}><Text style={styles.secondaryText}>← Inbox</Text></Pressable>{thread?.vendorId ? <Pressable onPress={() => router.push(`/admin/vendors/${thread.vendorId}`)} style={styles.secondary}><Text style={styles.secondaryText}>View vendor</Text></Pressable> : null}</View>{query.error || send.error ? <Text style={styles.error}>{(query.error || send.error)?.message}</Text> : null}<ScrollView contentContainerStyle={styles.messages}>{thread?.messages.map((message) => { const mine = message.senderId === user?.uid || message.senderRole === "admin"; return <View key={message.id} style={[styles.messageRow, mine && styles.mineRow]}><View style={[styles.bubble, mine && styles.mineBubble]}><Text style={[styles.sender, mine && styles.mineText]}>{mine ? "You (Admin)" : message.senderName}</Text><Text style={[styles.body, mine && styles.mineText]}>{message.body}</Text><Text style={[styles.time, mine && styles.mineTime]}>{new Date(message.createdAt).toLocaleString()}</Text></View></View>; })}{!thread?.messages.length ? <Text style={styles.empty}>No messages yet. Start the conversation with this seller.</Text> : null}</ScrollView><View style={styles.composer}><TextInput value={body} onChangeText={setBody} multiline placeholder="Write a message to this seller..." placeholderTextColor={colors.muted} style={styles.input} /><Pressable disabled={!body.trim() || send.isPending} onPress={() => send.mutate()} style={[styles.send, (!body.trim() || send.isPending) && styles.disabled]}><Text style={styles.sendText}>{send.isPending ? "Sending..." : "Send message"}</Text></Pressable></View></Screen>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, secondary: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, paddingHorizontal: 13, paddingVertical: 9 }, secondaryText: { color: colors.text, fontSize: 11, fontWeight: "900" }, messages: { backgroundColor: colors.background, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, gap: spacing.md, minHeight: 360, padding: spacing.md }, messageRow: { alignItems: "flex-start" }, mineRow: { alignItems: "flex-end" }, bubble: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, maxWidth: 560, padding: spacing.md, width: "85%" }, mineBubble: { backgroundColor: colors.primary, borderColor: colors.primary }, sender: { color: colors.primary, fontSize: 10, fontWeight: "900", marginBottom: spacing.xs }, body: { color: colors.text, fontSize: 14, lineHeight: 21 }, time: { color: colors.muted, fontSize: 9, marginTop: spacing.sm }, mineText: { color: colors.surface }, mineTime: { color: colors.primarySoft }, composer: { alignItems: "flex-end", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, flexDirection: "row", flexWrap: "wrap", gap: spacing.sm, padding: spacing.md }, input: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, flex: 1, minHeight: 78, minWidth: 220, padding: 12, textAlignVertical: "top" }, send: { backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: spacing.lg, paddingVertical: 13 }, sendText: { color: colors.surface, fontWeight: "900" }, disabled: { opacity: .45 }, error: { color: colors.danger }, empty: { color: colors.muted, padding: spacing.xl, textAlign: "center" } });
