import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { createNewsletterBroadcast, getNewsletterWorkspace, sendNewsletterBroadcast } from "../engagement/engagement.api";

export function AdminNewsletterScreen() {
  const user = firebaseAuth?.currentUser ?? null;
  const cache = useQueryClient();
  const workspace = useQuery({ queryKey: ["admin", "newsletter"], queryFn: () => getNewsletterWorkspace(user!), enabled: Boolean(user) });
  const [form, setForm] = useState({ subject: "", previewText: "", body: "", scheduledAt: "" });
  const create = useMutation({ mutationFn: () => createNewsletterBroadcast(user!, { subject: form.subject, previewText: form.previewText || null, body: form.body, scheduledAt: form.scheduledAt ? new Date(form.scheduledAt).toISOString() : null }), onSuccess: async () => { setForm({ subject: "", previewText: "", body: "", scheduledAt: "" }); await cache.invalidateQueries({ queryKey: ["admin", "newsletter"] }); } });
  const send = useMutation({ mutationFn: (id: string) => sendNewsletterBroadcast(user!, id), onSuccess: async () => { await cache.invalidateQueries({ queryKey: ["admin", "newsletter"] }); } });
  return <Screen eyebrow="ADMIN COMMUNICATIONS" title="Newsletter broadcasts" description="Manage subscribers and send reliable newsletter broadcasts.">{workspace.isLoading ? <ActivityIndicator color={colors.primary} /> : null}{workspace.error ? <Text style={styles.error}>{workspace.error.message}</Text> : null}<View style={styles.metrics}><Metric label="Active subscribers" value={workspace.data?.activeSubscriberCount ?? 0} /><Metric label="Broadcasts" value={workspace.data?.broadcasts.length ?? 0} /></View><ModuleCard title="Compose newsletter" meta="Scheduled messages enter the durable email delivery queue automatically."><Field label="Subject" value={form.subject} onChangeText={(subject) => setForm({ ...form, subject })} /><Field label="Preview text" value={form.previewText} onChangeText={(previewText) => setForm({ ...form, previewText })} /><Field label="Message" multiline value={form.body} onChangeText={(body) => setForm({ ...form, body })} /><Field label="Schedule (example: 2026-08-06 10:00)" value={form.scheduledAt} onChangeText={(scheduledAt) => setForm({ ...form, scheduledAt })} /><Pressable disabled={create.isPending || form.subject.trim().length < 2 || form.body.trim().length < 3} onPress={() => create.mutate()} style={styles.button}><Text style={styles.buttonText}>{create.isPending ? "Saving…" : form.scheduledAt ? "Schedule broadcast" : "Save draft"}</Text></Pressable>{create.error ? <Text style={styles.error}>{create.error.message}</Text> : null}</ModuleCard><Text style={styles.heading}>Broadcast history</Text>{workspace.data?.broadcasts.map((item) => <ModuleCard key={item.id} title={item.subject} meta={`${item.status.toUpperCase()} · ${item.sentCount}/${item.recipientCount} sent · ${item.failedCount} failed`}><Text style={styles.muted}>{item.previewText || item.body.slice(0, 140)}</Text><Text style={styles.muted}>{item.scheduledAt ? `Scheduled ${new Date(item.scheduledAt).toLocaleString()}` : `Created ${new Date(item.createdAt).toLocaleString()}`}</Text>{["draft", "scheduled"].includes(item.status) ? <Pressable disabled={send.isPending} onPress={() => send.mutate(item.id)} style={styles.button}><Text style={styles.buttonText}>{send.isPending ? "Queueing…" : "Send now"}</Text></Pressable> : null}</ModuleCard>)}{send.error ? <Text style={styles.error}>{send.error.message}</Text> : null}<Text style={styles.heading}>Subscribers</Text>{workspace.data?.subscribers.map((item) => <ModuleCard key={item.id} title={item.email} meta={`${item.active ? "ACTIVE" : "UNSUBSCRIBED"} · ${item.source}`}><Text style={styles.muted}>Joined {new Date(item.createdAt).toLocaleDateString()}</Text></ModuleCard>)}</Screen>;
}
function Field({ label, ...props }: React.ComponentProps<typeof TextInput> & { label: string }) { return <View><Text style={styles.label}>{label}</Text><TextInput placeholderTextColor={colors.muted} style={[styles.input, props.multiline && styles.multiline]} {...props} /></View>; }
function Metric({ label, value }: { label: string; value: number }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.muted}>{label}</Text></View>; }
const styles = StyleSheet.create({ metrics: { flexDirection: "row", gap: spacing.sm }, metric: { backgroundColor: colors.primarySoft, borderRadius: radius.lg, flex: 1, padding: spacing.md }, metricValue: { color: colors.primary, fontSize: 26, fontWeight: "700" }, heading: { color: colors.text, fontSize: 21, fontWeight: "700" }, label: { color: colors.text, fontSize: 12, fontWeight: "600", marginBottom: spacing.xs }, input: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, padding: spacing.md }, multiline: { minHeight: 120, textAlignVertical: "top" }, button: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, padding: 14 }, buttonText: { color: colors.surface, fontWeight: "700" }, muted: { color: colors.muted, lineHeight: 18 }, error: { color: colors.danger } });
