import { adminAnalyticsSchema, adminMarketingSchema, adminOrderDetailSchema, adminPlatformSchema, adminWorkspaceSchema, commissionRuleSchema, vendorCategoryRequestSchema, type AdminAnalyticsQuery, type AdminBannerInput, type AdminCategoryAttributesInput, type AdminCategoryInput, type AdminCategoryRequestReview, type AdminFlashSaleInput, type AdminKycReviewInput, type AdminMarketingDto, type AdminUserRolesInput, type AdminUserStatusInput, type AdminVendorStatusInput, type AdminVoucherInput, type CommissionRuleInput, type PaymentVerificationReview, type TrustCaseActionInput, type UpdateCommissionRule } from "@amiyo/contracts";
import type { User } from "firebase/auth";
const apiUrl = (process.env.EXPO_PUBLIC_API_URL || "http://localhost:4000").replace(/\/$/, "");
export type AdminCommerceDto = {
  orders: Array<{ id: string; orderNumber: string; customer: string; status: string; totalMinor: string; currency: string; itemCount: number; vendorCount: number; vendorOrders: Array<{ id: string; vendorId: string; vendor: string; shop: string; status: string; version: number }>; paymentMethod: string | null; paymentStatus: string | null; createdAt: string }>;
  inventory: Array<{ id: string; version: number; sku: string; variant: string; product: string; vendor: string; shop: string; onHand: number; reserved: number; available: number; reorderLevel: number; updatedAt: string }>;
  coupons: Array<{ id: string; code: string; discountType: string; value: number; minimumSpendMinor: string; usageLimit: number | null; redemptions: number; startsAt: string; endsAt: string; active: boolean; version: number }>;
  campaigns: Array<{ id: string; name: string; slug: string; status: string; startsAt: string; endsAt: string; productCount: number; eventCount: number; version: number }>;
  chats: Array<{ id: string; vendorId: string | null; vendor: string; subject: string; status: string; participants: number; messageCount: number; lastMessage: string | null; updatedAt: string }>;
  codCollections: Array<{ id: string; orderNumber: string; expectedMinor: string; collectedMinor: string; currency: string; collectorRef: string | null; collectedAt: string }>;
  codReconciliations: Array<{ id: string; periodStart: string; periodEnd: string; expectedMinor: string; receivedMinor: string; currency: string; status: string; itemCount: number; createdAt: string }>;
  vendorActivity: Array<{ id: string; vendor: string; status: string; products: number; orders: number; chats: number; payoutRequests: number; gmvMinor: string; commissionMinor: string; updatedAt: string }>;
};
async function request(user: User, path: string, init?: RequestInit) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) { const problem = await response.json().catch(() => null) as { title?: string; detail?: string } | null; throw new Error(problem?.detail || problem?.title || `Admin request failed (${response.status})`); } return adminWorkspaceSchema.parse(await response.json()); }
export async function getAdminWorkspace(user: User) { return request(user, "/api/v2/admin/workspace"); }
export type AdminCustomerDetail = { id: string; email: string | null; phone: string | null; status: string; roles: string[]; createdAt: string; lastLoginAt: string | null; profile: { firstName: string | null; lastName: string | null; displayName: string | null; locale: string; currency: string }; addresses: Array<{ id: string; label: string; recipientName: string; phone: string; line1: string; line2: string | null; division: string; district: string; upazila: string; unionName: string | null; postalCode: string | null; isDefault: boolean }>; orders: Array<{ id: string; orderNumber: string; status: string; total: { amountMinor: string; currency: string }; vendors: string[]; paymentStatus: string | null; createdAt: string }>; returns: Array<{ id: string; orderId: string; status: string; reasonCode: string; requested: { amountMinor: string; currency: string }; createdAt: string }>; support: Array<{ id: string; subject: string; category: string; priority: string; status: string; createdAt: string }>; reviews: Array<{ id: string; product: string; rating: number; status: string; body: string | null; createdAt: string }>; summary: { orders: number; spendMinor: string; returns: number; tickets: number; reviews: number } };
export async function getAdminCustomerDetail(user: User, id: string) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}/api/v2/admin/workspace/customers/${id}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(`Customer detail request failed (${response.status})`); return response.json() as Promise<AdminCustomerDetail>; }
async function commerceRequest(user: User, path = "", init?: RequestInit) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}/api/v2/admin/workspace${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) { const problem = await response.json().catch(() => null) as { title?: string; detail?: string } | null; throw new Error(problem?.detail || problem?.title || `Admin commerce request failed (${response.status})`); } return response.json() as Promise<AdminCommerceDto>; }
export async function getAdminCommerce(user: User) { return commerceRequest(user, "/commerce"); }
export async function getAdminOrderDetail(user: User, id: string) { return adminOrderDetailSchema.parse(await commerceRequest(user, `/orders/${id}`)); }
export async function updateAdminInventory(user: User, id: string, input: { expectedVersion: number; onHand: number; reorderLevel: number }) { return commerceRequest(user, `/inventory/${id}`, { method: "PATCH", body: JSON.stringify(input) }); }
export async function toggleAdminCoupon(user: User, id: string, active: boolean) { return commerceRequest(user, `/coupons/${id}`, { method: "PATCH", body: JSON.stringify({ active }) }); }
export async function createAdminCoupon(user: User, input: { code: string; discountType: "PERCENT" | "FIXED"; value: number; minimumSpendMinor: string; usageLimit: number | null; startsAt: string; endsAt: string }) { return commerceRequest(user, "/coupons", { method: "POST", body: JSON.stringify(input) }); }
export async function createAdminCampaign(user: User, input: { name: string; slug: string; startsAt: string; endsAt: string }) { return commerceRequest(user, "/campaigns", { method: "POST", body: JSON.stringify(input) }); }
export async function updateAdminCampaign(user: User, id: string, input: { name: string; slug: string; startsAt: string; endsAt: string }) { return commerceRequest(user, `/campaigns/${id}`, { method: "PUT", body: JSON.stringify(input) }); }
export async function toggleAdminCampaign(user: User, id: string, active: boolean) { return commerceRequest(user, `/campaigns/${id}`, { method: "PATCH", body: JSON.stringify({ active }) }); }
export async function sendAdminChatMessage(user: User, id: string, body: string) { return commerceRequest(user, `/chats/${id}/messages`, { method: "POST", body: JSON.stringify({ body }) }); }
async function commissionRequest(user: User, path = "", init?: RequestInit) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}/api/v2/admin/workspace/commission-rules${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) { const problem = await response.json().catch(() => null) as { title?: string; detail?: string } | null; throw new Error(problem?.detail || problem?.title || `Commission request failed (${response.status})`); } return response.json() as Promise<unknown>; }
export async function getCommissionRules(user: User) { return commissionRuleSchema.array().parse(await commissionRequest(user)); }
export async function createCommissionRule(user: User, input: CommissionRuleInput) { return commissionRuleSchema.parse(await commissionRequest(user, "", { method: "POST", body: JSON.stringify(input) })); }
export async function updateCommissionRule(user: User, id: string, input: UpdateCommissionRule) { return commissionRuleSchema.parse(await commissionRequest(user, `/${id}`, { method: "PUT", body: JSON.stringify(input) })); }
export async function endCommissionRule(user: User, id: string, expectedVersion: number) { return commissionRuleSchema.parse(await commissionRequest(user, `/${id}`, { method: "DELETE", body: JSON.stringify({ expectedVersion }) })); }
export async function updateAdminUser(user: User, id: string, input: AdminUserStatusInput) { return request(user, `/api/v2/admin/workspace/users/${id}/status`, { method: "PATCH", body: JSON.stringify(input) }); }
export async function updateAdminUserRoles(user: User, id: string, input: AdminUserRolesInput) { return request(user, `/api/v2/admin/workspace/users/${id}/roles`, { method: "PUT", body: JSON.stringify(input) }); }
export async function updateAdminVendor(user: User, id: string, input: AdminVendorStatusInput) { return request(user, `/api/v2/admin/workspace/vendors/${id}/status`, { method: "PATCH", body: JSON.stringify(input) }); }
export async function reviewAdminKyc(user: User, id: string, input: AdminKycReviewInput) { return request(user, `/api/v2/admin/workspace/kyc/${id}`, { method: "PATCH", body: JSON.stringify(input) }); }
export async function actOnTrustCase(user: User, id: string, input: TrustCaseActionInput) { return request(user, `/api/v2/admin/workspace/trust-cases/${id}/actions`, { method: "POST", body: JSON.stringify(input) }); }
async function platformRequest(user: User, path: string, init?: RequestInit) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) { const problem = await response.json().catch(() => null) as { title?: string; detail?: string } | null; throw new Error(problem?.detail || problem?.title || `Admin platform request failed (${response.status})`); } return adminPlatformSchema.parse(await response.json()); }
export async function getAdminPlatform(user: User) { return platformRequest(user, "/api/v2/admin/workspace/platform"); }
export type { AdminFlashSaleInput, AdminMarketingDto, AdminVoucherInput } from "@amiyo/contracts";
async function marketingRequest(user: User, path: string, init?: RequestInit) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}/api/v2/admin/workspace${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) { const problem = await response.json().catch(() => null) as { title?: string; detail?: string } | null; throw new Error(problem?.detail || problem?.title || `Marketing request failed (${response.status})`); } return adminMarketingSchema.parse(await response.json()); }
export async function getAdminMarketing(user: User) { return marketingRequest(user, "/marketing"); }
export async function createAdminVoucher(user: User, input: AdminVoucherInput) { return marketingRequest(user, "/vouchers", { method: "POST", body: JSON.stringify(input) }); }
export async function updateAdminVoucher(user: User, id: string, input: AdminVoucherInput) { return marketingRequest(user, `/vouchers/${id}`, { method: "PUT", body: JSON.stringify(input) }); }
export async function deleteAdminVoucher(user: User, id: string) { return marketingRequest(user, `/vouchers/${id}`, { method: "DELETE" }); }
export async function createAdminFlashSale(user: User, input: AdminFlashSaleInput) { return marketingRequest(user, "/flash-sales", { method: "POST", body: JSON.stringify(input) }); }
export async function updateAdminFlashSale(user: User, id: string, input: AdminFlashSaleInput) { return marketingRequest(user, `/flash-sales/${id}`, { method: "PUT", body: JSON.stringify(input) }); }
export async function deleteAdminFlashSale(user: User, id: string) { return marketingRequest(user, `/flash-sales/${id}`, { method: "DELETE" }); }
export async function reviewPaymentVerification(user: User, id: string, input: PaymentVerificationReview) { return platformRequest(user, `/api/v2/admin/workspace/payment-verifications/${id}`, { method: "PATCH", body: JSON.stringify(input) }); }
export type AdminPaymentVerification = { id: string; paymentId: string; orderId: string; orderNumber: string; customer: string; provider: string; method: string; amount: { amountMinor: string; currency: string }; paymentStatus: string; status: string; transactionRef: string; senderMasked: string | null; evidenceStorageKey: string | null; reviewedAt: string | null; createdAt: string };
export async function getAdminPaymentVerifications(user: User) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}/api/v2/admin/workspace/payment-verifications`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(`Payment verification request failed (${response.status})`); return response.json() as Promise<AdminPaymentVerification[]>; }
export async function createAdminCategory(user: User, input: AdminCategoryInput) { return platformRequest(user, "/api/v2/admin/workspace/categories", { method: "POST", body: JSON.stringify(input) }); }
export async function updateAdminCategory(user: User, id: string, input: { status?: "active" | "inactive"; displayOrder?: number }) { return platformRequest(user, `/api/v2/admin/workspace/categories/${id}`, { method: "PATCH", body: JSON.stringify(input) }); }
export async function replaceAdminCategoryAttributes(user: User, id: string, input: AdminCategoryAttributesInput) { return platformRequest(user, `/api/v2/admin/workspace/categories/${id}/attributes`, { method: "PUT", body: JSON.stringify(input) }); }
export async function toggleAdminResource(user: User, type: "banners" | "vouchers" | "flash-sales", id: string, active: boolean) { return platformRequest(user, `/api/v2/admin/workspace/${type}/${id}`, { method: "PATCH", body: JSON.stringify({ active }) }); }
export async function createAdminBanner(user: User, input: AdminBannerInput) { return platformRequest(user, "/api/v2/admin/workspace/banners", { method: "POST", body: JSON.stringify(input) }); }
export async function updateAdminBanner(user: User, id: string, input: AdminBannerInput) { return platformRequest(user, `/api/v2/admin/workspace/banners/${id}`, { method: "PUT", body: JSON.stringify(input) }); }
export async function deleteAdminBanner(user: User, id: string) { return platformRequest(user, `/api/v2/admin/workspace/banners/${id}`, { method: "DELETE" }); }
export async function getAdminAnalytics(user: User, range: AdminAnalyticsQuery["range"]) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}/api/v2/admin/workspace/analytics?range=${range}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) throw new Error(`Admin analytics request failed (${response.status})`); return adminAnalyticsSchema.parse(await response.json()); }
async function categoryRequest(user: User, path: string, init?: RequestInit) { const token = await user.getIdToken(); const response = await fetch(`${apiUrl}${path}`, { ...init, headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" } }); if (!response.ok) throw new Error(`Category request operation failed (${response.status})`); return vendorCategoryRequestSchema.array().parse(await response.json()); }
export async function getAdminCategoryRequests(user: User) { return categoryRequest(user, "/api/v2/admin/workspace/category-requests"); }
export async function reviewAdminCategoryRequest(user: User, id: string, input: AdminCategoryRequestReview) { return categoryRequest(user, `/api/v2/admin/workspace/category-requests/${id}`, { method: "PATCH", body: JSON.stringify(input) }); }
