import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { createAdminCategory, getAdminPlatform, reviewPaymentVerification, toggleAdminResource, updateAdminCategory } from "./admin.api";

export function AdminPlatformScreen() {
  const user = firebaseAuth?.currentUser ?? null;
  const queryClient = useQueryClient();
  const platform = useQuery({ queryKey: ["admin", "platform"], queryFn: () => getAdminPlatform(user!), enabled: Boolean(user) });
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["admin", "platform"] });
  const payment = useMutation({ mutationFn: ({ id, status }: { id: string; status: "approved" | "rejected" }) => reviewPaymentVerification(user!, id, { status, reason: status === "approved" ? "Payment evidence verified" : "Payment evidence could not be verified" }), onSuccess: refresh });
  const toggle = useMutation({ mutationFn: ({ type, id, active }: { type: "banners" | "vouchers" | "flash-sales"; id: string; active: boolean }) => toggleAdminResource(user!, type, id, active), onSuccess: refresh });
  const [category, setCategory] = useState<{ name: string; slug: string; parentId: string | null }>({ name: "", slug: "", parentId: null });
  const createCategory = useMutation({ mutationFn: () => createAdminCategory(user!, { parentId: category.parentId, name: category.name, slug: category.slug, displayOrder: platform.data?.categories.length ?? 0 }), onSuccess: () => { setCategory({ name: "", slug: "", parentId: null }); return refresh(); } });
  const controlCategory = useMutation({ mutationFn: ({ id, status, displayOrder }: { id: string; status?: "active" | "inactive"; displayOrder?: number }) => updateAdminCategory(user!, id, { status, displayOrder }), onSuccess: refresh });
  if (platform.isLoading) return <Screen title="Platform operations"><ActivityIndicator color={colors.primary} /></Screen>;
  const error = platform.error || payment.error || toggle.error || createCategory.error || controlCategory.error;
  return <Screen eyebrow="ADMIN" title="Platform operations" description="Payments, taxonomy, marketing visibility and immutable platform activity.">
    {error ? <Text style={styles.error}>{error.message}</Text> : null}
    <Text style={styles.heading}>Payment verification</Text>
    {platform.data?.paymentVerifications.filter((item) => item.status === "pending").map((item) => <ModuleCard key={item.id} title={item.orderNumber} meta={`${item.provider} · ${item.transactionRef}`}><Text style={styles.amount}>৳{(Number(item.amountMinor) / 100).toLocaleString("en-BD")}</Text><Text style={styles.muted}>Sender: {item.senderMasked || "Not supplied"}</Text><View style={styles.row}><Action label="Approve" tone="success" onPress={() => payment.mutate({ id: item.id, status: "approved" })} /><Action label="Reject" tone="danger" onPress={() => payment.mutate({ id: item.id, status: "rejected" })} /></View></ModuleCard>)}
    <Text style={styles.heading}>Categories</Text>
    <ModuleCard title="Create category" meta={category.parentId ? "Creating a subcategory" : "Creating a main category"}><View style={styles.parentChoices}><Choice active={category.parentId === null} label="Main category" onPress={() => setCategory({ ...category, parentId: null })} />{platform.data?.categories.filter((item) => item.parentId === null).map((item) => <Choice active={category.parentId === item.id} key={item.id} label={`Under ${item.name}`} onPress={() => setCategory({ ...category, parentId: item.id })} />)}</View><TextInput onChangeText={(name) => setCategory({ ...category, name, slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") })} placeholder="Category name" placeholderTextColor={colors.muted} style={styles.input} value={category.name} /><Text style={styles.muted}>Slug: {category.slug || "—"}</Text><Action label={createCategory.isPending ? "Creating…" : "Create category"} onPress={() => createCategory.mutate()} /></ModuleCard>
    {platform.data?.categories.map((item) => <ModuleCard key={item.id} title={item.name} meta={`${item.parentId ? "SUBCATEGORY" : "MAIN CATEGORY"} · ${item.status} · ${item.productCount} products`}><Text style={styles.muted}>/{item.slug} · position {item.displayOrder}</Text><View style={styles.row}><Action label={item.status === "active" ? "Disable" : "Enable"} tone={item.status === "active" ? "danger" : "success"} onPress={() => controlCategory.mutate({ id: item.id, status: item.status === "active" ? "inactive" : "active" })} /><Action label="Move up" onPress={() => controlCategory.mutate({ id: item.id, displayOrder: Math.max(0, item.displayOrder - 1) })} /><Action label="Move down" onPress={() => controlCategory.mutate({ id: item.id, displayOrder: item.displayOrder + 1 })} /></View></ModuleCard>)}
    <Text style={styles.heading}>Marketing controls</Text>
    {platform.data?.banners.map((item) => <ToggleCard key={item.id} title={item.title || item.placement} meta={`Banner · ${item.placement}`} active={item.active} onPress={() => toggle.mutate({ type: "banners", id: item.id, active: !item.active })} />)}
    {platform.data?.vouchers.map((item) => <ToggleCard key={item.id} title={item.code} meta={`Voucher · ${item.ownerType}`} active={item.active} onPress={() => toggle.mutate({ type: "vouchers", id: item.id, active: !item.active })} />)}
    {platform.data?.flashSales.map((item) => <ToggleCard key={item.id} title={item.name} meta={`Flash sale · ${item.productCount} products`} active={item.status === "active"} onPress={() => toggle.mutate({ type: "flash-sales", id: item.id, active: item.status !== "active" })} />)}
    <Text style={styles.heading}>Audit activity</Text>
    {platform.data?.audit.map((item) => <ModuleCard key={item.id} title={item.action} meta={`${item.actorType} · ${new Date(item.createdAt).toLocaleString()}`}><Text style={styles.muted}>{item.resourceType} #{item.resourceId.slice(0, 10)}</Text></ModuleCard>)}
  </Screen>;
}

function Action({ label, onPress, tone = "primary" }: { label: string; onPress(): void; tone?: "primary" | "success" | "danger" }) { return <Pressable onPress={onPress} style={[styles.button, tone === "success" && styles.success, tone === "danger" && styles.danger]}><Text style={styles.buttonText}>{label}</Text></Pressable>; }
function Choice({ active, label, onPress }: { active: boolean; label: string; onPress(): void }) { return <Pressable onPress={onPress} style={[styles.choice, active && styles.choiceActive]}><Text style={[styles.choiceText, active && styles.choiceTextActive]}>{label}</Text></Pressable>; }
function ToggleCard({ title, meta, active, onPress }: { title: string; meta: string; active: boolean; onPress(): void }) { return <ModuleCard title={title} meta={meta}><Pressable onPress={onPress} style={[styles.toggle, active && styles.toggleActive]}><Text style={[styles.toggleText, active && styles.toggleTextActive]}>{active ? "ACTIVE · Tap to pause" : "INACTIVE · Tap to activate"}</Text></Pressable></ModuleCard>; }
const styles = StyleSheet.create({ heading: { color: colors.text, fontSize: 21, fontWeight: "700" }, error: { color: colors.danger }, amount: { color: colors.text, fontSize: 22, fontWeight: "700" }, muted: { color: colors.muted, fontSize: 12 }, row: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, parentChoices: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, choice: { borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 8 }, choiceActive: { backgroundColor: colors.primary, borderColor: colors.primary }, choiceText: { color: colors.text, fontSize: 11, fontWeight: "600" }, choiceTextActive: { color: "#fff" }, input: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, minHeight: 46, paddingHorizontal: 12 }, button: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, flex: 1, justifyContent: "center", minHeight: 44, minWidth: 110, paddingHorizontal: spacing.md }, success: { backgroundColor: colors.success }, danger: { backgroundColor: colors.danger }, buttonText: { color: "#fff", fontWeight: "700" }, toggle: { alignItems: "center", borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, padding: spacing.sm }, toggleActive: { backgroundColor: colors.primarySoft, borderColor: colors.primary }, toggleText: { color: colors.muted, fontWeight: "700" }, toggleTextActive: { color: colors.primary } });
