import { useQuery } from "@tanstack/react-query";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { Platform, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getAdminCommerce, type AdminCommerceDto } from "./admin.api";

type Order = AdminCommerceDto["orders"][number];
const taka = (minor: string | number) => `৳${(Number(minor) / 100).toLocaleString("en-BD")}`;
const fulfillment = ["CONFIRMED", "PROCESSING", "PACKED", "READY_TO_SHIP", "SHIPPED"];
export function AdminOrdersScreen() {
  const user = firebaseAuth?.currentUser ?? null; const router = useRouter(); const params = useLocalSearchParams<{ search?: string }>();
  const query = useQuery({ queryKey: ["admin", "commerce"], queryFn: () => getAdminCommerce(user!), enabled: Boolean(user), refetchInterval: 15_000, staleTime: 8_000 });
  const [search, setSearch] = useState(params.search ?? ""); const [status, setStatus] = useState("ALL"); const [payment, setPayment] = useState("ALL"); const [vendor, setVendor] = useState("ALL"); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const all = query.data?.orders ?? []; const statuses = ["ALL", ...Array.from(new Set(all.map((item) => item.status)))]; const payments = ["ALL", ...Array.from(new Set(all.map((item) => item.paymentMethod || "UNSET")))]; const vendors = Array.from(new Map(all.flatMap((item) => item.vendorOrders.map((row) => [row.vendorId, row.vendor] as const))).entries());
  const rows = useMemo(() => all.filter((item) => status === "ALL" || item.status === status).filter((item) => payment === "ALL" || (item.paymentMethod || "UNSET") === payment).filter((item) => vendor === "ALL" || item.vendorOrders.some((row) => row.vendorId === vendor)).filter((item) => !from || new Date(item.createdAt) >= new Date(`${from}T00:00:00`)).filter((item) => !to || new Date(item.createdAt) <= new Date(`${to}T23:59:59`)).filter((item) => `${item.orderNumber} ${item.customer} ${item.vendorOrders.map((row) => `${row.vendor} ${row.shop}`).join(" ")}`.toLowerCase().includes(search.trim().toLowerCase())), [all, from, payment, search, status, to, vendor]);
  const revenue = rows.filter((item) => item.status !== "CANCELLED").reduce((sum, item) => sum + Number(item.totalMinor), 0); const pending = rows.filter((item) => ["PENDING_PAYMENT", "CONFIRMED"].includes(item.status)).length; const processing = rows.filter((item) => fulfillment.includes(item.status)).length; const issues = rows.filter((item) => ["CANCELLED", "RETURN_REQUESTED", "RETURNED", "REFUNDED"].includes(item.status)).length;
  const exportCsv = () => { if (Platform.OS !== "web") return; const data = [["Order", "Created", "Customer", "Vendors", "Items", "Payment method", "Payment status", "Total minor", "Currency", "Status"], ...rows.map((item) => [item.orderNumber, item.createdAt, item.customer, item.vendorOrders.map((row) => row.vendor).join("; "), item.itemCount, item.paymentMethod || "", item.paymentStatus || "", item.totalMinor, item.currency, item.status])].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([data], { type: "text/csv" })); link.download = `amiyo-orders-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  const reset = () => { setSearch(""); setStatus("ALL"); setPayment("ALL"); setVendor("ALL"); setFrom(""); setTo(""); };
  return <Screen eyebrow="ORDER OPERATIONS" title="Marketplace orders" description="Global operations across sellers, payment, fulfillment, delivery and customer service.">
    {query.error ? <Text style={styles.error}>{query.error.message}</Text> : null}
    <View style={styles.metrics}><Metric label="Filtered orders" value={rows.length} /><Metric label="Revenue" value={taka(revenue)} /><Metric label="Pending" value={pending} warning /><Metric label="In fulfillment" value={processing} /><Metric label="Issues / returns" value={issues} danger /></View>
    <ModuleCard title="Operational filters" meta="Search short order codes, customers, sellers and shops."><TextInput value={search} onChangeText={setSearch} placeholder="Search order, customer, vendor or shop" placeholderTextColor={colors.muted} style={styles.input} /><View style={styles.filterRows}><Filter label="Status" options={statuses.map((value) => [value, value])} value={status} onChange={setStatus} /><Filter label="Payment" options={payments.map((value) => [value, value])} value={payment} onChange={setPayment} /><Filter label="Vendor" options={[["ALL", "All vendors"], ...vendors]} value={vendor} onChange={setVendor} /></View><View style={styles.filterRows}><Field label="From (YYYY-MM-DD)" value={from} onChangeText={setFrom} /><Field label="To (YYYY-MM-DD)" value={to} onChangeText={setTo} /></View><View style={styles.actions}><Button label="Refresh" onPress={() => query.refetch()} /><Button secondary label="Reset filters" onPress={reset} />{Platform.OS === "web" ? <Button secondary label="Export CSV" onPress={exportCsv} /> : null}</View></ModuleCard>
    <View style={styles.statusTabs}>{statuses.map((value) => <Pressable key={value} onPress={() => setStatus(value)} style={[styles.tab, status === value && styles.tabActive]}><Text style={[styles.tabText, status === value && styles.tabTextActive]}>{value.replaceAll("_", " ")} · {value === "ALL" ? all.length : all.filter((item) => item.status === value).length}</Text></Pressable>)}</View>
    {query.isLoading ? <Text style={styles.muted}>Loading marketplace orders...</Text> : null}{rows.map((item) => <OrderCard key={item.id} item={item} open={() => router.push(`/admin/orders/${item.id}` as never)} invoice={() => router.push(`/admin/orders/${item.id}/invoice` as never)} />)}{!query.isLoading && !rows.length ? <Text style={styles.empty}>No orders match these operational filters.</Text> : null}
  </Screen>;
}
function OrderCard({ invoice, item, open }: { invoice(): void; item: Order; open(): void }) { return <ModuleCard title={item.orderNumber} meta={`${new Date(item.createdAt).toLocaleString("en-BD")} · ${item.itemCount} items · ${item.vendorCount} sellers`}><View style={styles.orderTop}><View style={styles.flex}><Text style={styles.strong}>{item.customer}</Text><Text style={styles.muted}>{item.vendorOrders.map((row) => `${row.vendor} · ${row.shop}`).join(", ")}</Text></View><View style={styles.right}><Text style={styles.amount}>{taka(item.totalMinor)}</Text><Status value={item.status} /></View></View><View style={styles.details}><Detail label="Payment" value={`${item.paymentMethod || "Not set"} · ${item.paymentStatus || "unpaid"}`} /><Detail label="Fulfillment" value={item.vendorOrders.map((row) => `${row.vendor}: ${row.status.replaceAll("_", " ")}`).join(" · ")} /><Detail label="Currency" value={item.currency} /></View><View style={styles.actions}><Button label="Manage order" onPress={open} /><Button secondary label="Print invoice" onPress={invoice} /></View></ModuleCard>; }
function Metric({ danger, label, value, warning }: { danger?: boolean; label: string; value: number | string; warning?: boolean }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue, warning && styles.warning, danger && styles.danger]}>{value}</Text></View>; }
function Filter({ label, onChange, options, value }: { label: string; onChange(value: string): void; options: ReadonlyArray<readonly [string, string]>; value: string }) { return <View style={styles.filter}><Text style={styles.label}>{label}</Text><View style={styles.pills}>{options.map(([id, name]) => <Pressable key={id} onPress={() => onChange(id)} style={[styles.pill, value === id && styles.pillActive]}><Text style={[styles.pillText, value === id && styles.pillTextActive]}>{name.replaceAll("_", " ")}</Text></Pressable>)}</View></View>; }
function Field({ label, ...props }: React.ComponentProps<typeof TextInput> & { label: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} placeholderTextColor={colors.muted} style={styles.input} /></View>; }
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.muted}>{label}</Text><Text style={styles.strong}>{value || "—"}</Text></View>; }
function Status({ value }: { value: string }) { const good = value === "DELIVERED"; const bad = ["CANCELLED", "RETURNED", "REFUNDED"].includes(value); return <Text style={[styles.status, good && styles.statusGood, bad && styles.statusBad]}>{value.replaceAll("_", " ")}</Text>; }
function Button({ label, onPress, secondary }: { label: string; onPress(): void; secondary?: boolean }) { return <Pressable onPress={onPress} style={[styles.button, secondary && styles.secondary]}><Text style={[styles.buttonText, secondary && styles.secondaryText]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ error: { color: colors.danger }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, metric: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flex: 1, minWidth: 140, padding: spacing.md }, metricLabel: { color: colors.muted, fontSize: 9, fontWeight: "900", textTransform: "uppercase" }, metricValue: { color: colors.text, fontSize: 21, fontWeight: "900", marginTop: 4 }, warning: { color: colors.warning }, danger: { color: colors.danger }, input: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, minHeight: 43, paddingHorizontal: 12 }, filterRows: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, filter: { flex: 1, minWidth: 220 }, field: { flex: 1, minWidth: 210 }, label: { color: colors.text, fontSize: 10, fontWeight: "900", marginBottom: 5 }, pills: { flexDirection: "row", flexWrap: "wrap", gap: 5 }, pill: { borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 6 }, pillActive: { backgroundColor: colors.primary, borderColor: colors.primary }, pillText: { color: colors.muted, fontSize: 8, fontWeight: "900", textTransform: "capitalize" }, pillTextActive: { color: colors.surface }, actions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, button: { backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: 13, paddingVertical: 10 }, secondary: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1 }, buttonText: { color: colors.surface, fontSize: 10, fontWeight: "900" }, secondaryText: { color: colors.text }, statusTabs: { flexDirection: "row", flexWrap: "wrap", gap: 4 }, tab: { borderBottomColor: "transparent", borderBottomWidth: 3, padding: 9 }, tabActive: { borderBottomColor: colors.primary }, tabText: { color: colors.muted, fontSize: 9, fontWeight: "900" }, tabTextActive: { color: colors.primary }, muted: { color: colors.muted, flexShrink: 1, fontSize: 10, lineHeight: 17 }, orderTop: { alignItems: "flex-start", flexDirection: "row", flexWrap: "wrap", gap: spacing.md }, flex: { flex: 1, minWidth: 200 }, strong: { color: colors.text, flexShrink: 1, fontSize: 11, fontWeight: "900" }, right: { alignItems: "flex-end", gap: 4 }, amount: { color: colors.text, fontSize: 18, fontWeight: "900" }, status: { backgroundColor: "#fff7ed", borderRadius: radius.pill, color: colors.warning, fontSize: 8, fontWeight: "900", overflow: "hidden", paddingHorizontal: 8, paddingVertical: 5 }, statusGood: { backgroundColor: "#ecfdf5", color: colors.success }, statusBad: { backgroundColor: "#fef2f2", color: colors.danger }, details: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, detail: { backgroundColor: colors.background, borderRadius: radius.md, flex: 1, minWidth: 150, padding: spacing.sm }, empty: { color: colors.muted, padding: spacing.xl, textAlign: "center" } });
