import { randomUUID } from "expo-crypto";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocalSearchParams } from "expo-router";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getVendorOrders, transitionVendorOrder } from "../orders/orders.api";

const nextStatuses: Record<string, string[]> = { PLACED: ["ACCEPTED", "REJECTED", "CANCELLED"], ACCEPTED: ["PROCESSING", "CANCELLED"], PROCESSING: ["READY_TO_SHIP", "CANCELLED"], READY_TO_SHIP: ["PICKED_UP"], PICKED_UP: ["IN_TRANSIT"], IN_TRANSIT: ["DELIVERED"] };
export function AdminOrderDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const user = firebaseAuth?.currentUser ?? null; const cache = useQueryClient();
  const orders = useQuery({ queryKey: ["admin", "vendor-orders"], queryFn: () => getVendorOrders(user!), enabled: Boolean(user && id) });
  const rows = orders.data?.filter((item) => item.orderId === id) ?? [];
  const transition = useMutation({ mutationFn: ({ vendorOrderId, status, version }: { vendorOrderId: string; status: string; version: number }) => transitionVendorOrder(user!, vendorOrderId, { status: status as never, expectedVersion: version, reason: `Status updated to ${status} by marketplace administrator` }, randomUUID()), onSuccess: async () => { await cache.invalidateQueries({ queryKey: ["admin", "vendor-orders"] }); await cache.invalidateQueries({ queryKey: ["admin", "commerce"] }); } });
  if (orders.isLoading) return <Screen title="Order detail"><ActivityIndicator color={colors.primary} /></Screen>;
  return <Screen eyebrow="GLOBAL ORDER" title={rows[0]?.orderNumber ?? "Order detail"} description="Manage each seller fulfillment, line items, shipment and dispatch state.">{orders.error || transition.error ? <Text style={styles.error}>{(orders.error || transition.error)?.message}</Text> : null}<View style={styles.summary}><Metric label="Seller fulfillments" value={rows.length} /><Metric label="Product lines" value={rows.reduce((sum, item) => sum + item.items.length, 0)} /><Metric label="Delivered" value={rows.filter((item) => item.status === "DELIVERED").length} /></View>{rows.map((order) => <ModuleCard key={order.id} title={order.shopName} meta={`${order.status.replaceAll("_", " ")} · Version ${order.version}`}><View style={styles.amountRow}><Text style={styles.label}>Fulfillment total</Text><Text style={styles.amount}>৳{(Number(order.total.amountMinor) / 100).toLocaleString("en-BD")}</Text></View>{order.items.map((item) => <View key={item.id} style={styles.item}><View style={styles.flex}><Text style={styles.itemTitle}>{item.productName}</Text><Text style={styles.muted}>{item.sku} · Qty {item.quantity}</Text></View><Text style={styles.itemTitle}>৳{(Number(item.lineTotal.amountMinor) / 100).toLocaleString("en-BD")}</Text></View>)}<View style={styles.meta}><Text style={styles.muted}>Shipment: {order.shipment?.status ?? "Not created"}</Text><Text style={styles.muted}>Dispatch: {order.dispatchStatus ?? "Not requested"}</Text></View>{nextStatuses[order.status]?.length ? <View style={styles.actions}>{nextStatuses[order.status].map((status) => <Pressable disabled={transition.isPending} key={status} onPress={() => transition.mutate({ vendorOrderId: order.id, status, version: order.version })} style={[styles.action, ["REJECTED", "CANCELLED"].includes(status) && styles.danger]}><Text style={[styles.actionText, ["REJECTED", "CANCELLED"].includes(status) && styles.dangerText]}>{status.replaceAll("_", " ")}</Text></Pressable>)}</View> : <Text style={styles.complete}>No further fulfillment action is available.</Text>}</ModuleCard>)}{!rows.length ? <ModuleCard title="Order not found" meta="This order is unavailable or has no seller fulfillments." /> : null}</Screen>;
}
function Metric({ label, value }: { label: string; value: number }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.muted}>{label}</Text></View>; }
const styles = StyleSheet.create({ flex: { flex: 1 }, error: { color: colors.danger }, summary: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, metric: { backgroundColor: colors.primarySoft, borderRadius: radius.lg, flex: 1, minWidth: 140, padding: spacing.md }, metricValue: { color: colors.primary, fontSize: 24, fontWeight: "900" }, amountRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, label: { color: colors.text, fontWeight: "800" }, amount: { color: colors.success, fontSize: 18, fontWeight: "900" }, item: { alignItems: "center", borderTopColor: colors.border, borderTopWidth: 1, flexDirection: "row", gap: spacing.sm, paddingTop: spacing.sm }, itemTitle: { color: colors.text, fontWeight: "800" }, muted: { color: colors.muted, fontSize: 11, marginTop: 3 }, meta: { backgroundColor: "#f8fafc", borderRadius: radius.md, gap: 4, padding: spacing.sm }, actions: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, action: { backgroundColor: colors.primarySoft, borderRadius: radius.sm, paddingHorizontal: 10, paddingVertical: 8 }, actionText: { color: colors.primary, fontSize: 10, fontWeight: "900" }, danger: { backgroundColor: "#fef2f2" }, dangerText: { color: colors.danger }, complete: { color: colors.success, fontSize: 11, fontWeight: "800" } });
