import type { AdminOrderDetail } from "@amiyo/contracts";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { correctAdminOrderAddress, overrideAdminOrderStatus, reassignAdminOrderCourier } from "./admin.api";

const statuses = ["CONFIRMED", "PROCESSING", "READY_TO_SHIP", "SHIPPED", "DELIVERED", "RETURN_REQUESTED", "RETURNED", "REFUNDED"] as const;
export function AdminOrderInterventions({ order }: { order: AdminOrderDetail }) {
  const user = firebaseAuth?.currentUser!; const cache = useQueryClient(); const address = order.deliveryAddress;
  const [status, setStatus] = useState<(typeof statuses)[number]>(statuses.includes(order.status as never) ? order.status as (typeof statuses)[number] : "PROCESSING"); const [statusReason, setStatusReason] = useState(""); const [addressReason, setAddressReason] = useState(""); const [addressForm, setAddressForm] = useState({ recipientName: address?.recipientName ?? "", phone: address?.phone ?? "", line1: address?.line1 ?? "", line2: address?.line2 ?? "", division: address?.division ?? "", district: address?.district ?? "", upazila: address?.upazila ?? "", unionName: address?.unionName ?? "", postalCode: address?.postalCode ?? "" }); const [vendorOrderId, setVendorOrderId] = useState(order.vendorOrders[0]?.id ?? ""); const selected = order.vendorOrders.find((item) => item.id === vendorOrderId); const [provider, setProvider] = useState(selected?.shipment?.provider ?? ""); const [tracking, setTracking] = useState(selected?.shipment?.trackingNumber ?? ""); const [courierReason, setCourierReason] = useState("");
  const refresh = () => Promise.all([cache.invalidateQueries({ queryKey: ["admin", "order", order.id] }), cache.invalidateQueries({ queryKey: ["admin", "commerce"] })]);
  const override = useMutation({ mutationFn: () => overrideAdminOrderStatus(user, order.id, { expectedVersion: order.version, status, reason: statusReason.trim() }), onSuccess: refresh });
  const correction = useMutation({ mutationFn: () => correctAdminOrderAddress(user, order.id, { ...addressForm, line2: addressForm.line2 || null, upazila: addressForm.upazila || null, unionName: addressForm.unionName || null, postalCode: addressForm.postalCode || null, reason: addressReason.trim() }), onSuccess: refresh });
  const courier = useMutation({ mutationFn: () => reassignAdminOrderCourier(user, order.id, { vendorOrderId, expectedVersion: selected!.version, provider: provider.trim(), trackingNumber: tracking.trim(), reason: courierReason.trim() }), onSuccess: refresh });
  const error = override.error || correction.error || courier.error;
  return <ModuleCard title="Administrative interventions" meta="Version-checked controls with immutable audit evidence.">{error ? <Text style={styles.error}>{error.message}</Text> : null}<Text style={styles.heading}>Status override</Text><View style={styles.actions}>{statuses.map((value) => <Chip active={status === value} key={value} label={value} onPress={() => setStatus(value)} />)}</View><Field label="Operational reason" value={statusReason} onChangeText={setStatusReason} /><Button disabled={status === order.status || statusReason.trim().length < 5 || override.isPending} label="Apply status override" onPress={() => override.mutate()} /><Text style={styles.heading}>Delivery address correction</Text><View style={styles.grid}>{Object.entries(addressForm).map(([key, value]) => <Field key={key} label={key.replace(/[A-Z]/g, (letter) => ` ${letter.toLowerCase()}`)} value={value} onChangeText={(next) => setAddressForm((current) => ({ ...current, [key]: next }))} />)}</View><Field label="Correction reason" value={addressReason} onChangeText={setAddressReason} /><Button disabled={!address || addressReason.trim().length < 5 || addressForm.line1.trim().length < 3 || correction.isPending} label="Save corrected address" onPress={() => correction.mutate()} /><Text style={styles.heading}>Courier reassignment</Text><View style={styles.actions}>{order.vendorOrders.map((item) => <Chip active={vendorOrderId === item.id} key={item.id} label={item.shopName} onPress={() => { setVendorOrderId(item.id); setProvider(item.shipment?.provider ?? ""); setTracking(item.shipment?.trackingNumber ?? ""); }} />)}</View><View style={styles.grid}><Field label="Courier provider" value={provider} onChangeText={setProvider} /><Field label="Tracking number" value={tracking} onChangeText={setTracking} /><Field label="Reassignment reason" value={courierReason} onChangeText={setCourierReason} /></View><Button disabled={!selected || provider.trim().length < 2 || tracking.trim().length < 2 || courierReason.trim().length < 5 || courier.isPending} label="Reassign courier" onPress={() => courier.mutate()} /></ModuleCard>;
}
function Field({ label, ...props }: React.ComponentProps<typeof TextInput> & { label: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput {...props} placeholderTextColor={colors.muted} style={styles.input} /></View>; }
function Chip({ active, label, onPress }: { active: boolean; label: string; onPress(): void }) { return <Pressable onPress={onPress} style={[styles.chip, active && styles.chipActive]}><Text style={[styles.chipText, active && styles.chipTextActive]}>{label.replaceAll("_", " ")}</Text></Pressable>; }
function Button({ disabled, label, onPress }: { disabled?: boolean; label: string; onPress(): void }) { return <Pressable disabled={disabled} onPress={onPress} style={[styles.button, disabled && styles.disabled]}><Text style={styles.buttonText}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ error: { color: colors.danger }, heading: { color: colors.text, fontSize: 14, fontWeight: "700", marginTop: spacing.sm }, actions: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, chip: { borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 7 }, chipActive: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.muted, fontSize: 9, fontWeight: "700" }, chipTextActive: { color: colors.surface }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, field: { flex: 1, minWidth: 210 }, label: { color: colors.text, fontSize: 10, fontWeight: "700", marginBottom: 5, textTransform: "capitalize" }, input: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, minHeight: 43, paddingHorizontal: 12 }, button: { alignSelf: "flex-start", backgroundColor: colors.primary, borderRadius: radius.md, paddingHorizontal: 14, paddingVertical: 11 }, buttonText: { color: colors.surface, fontSize: 10, fontWeight: "700" }, disabled: { opacity: .45 } });
