import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getAdminChats } from "./admin.api";

export function AdminChatsScreen() { const user = firebaseAuth?.currentUser ?? null; const router = useRouter(); const [search, setSearch] = useState(""); const [unreadOnly, setUnreadOnly] = useState(false); const query = useQuery({ queryKey: ["admin", "chats"], queryFn: () => getAdminChats(user!), enabled: Boolean(user), refetchInterval: 15_000 }); const threads = useMemo(() => (query.data?.threads || []).filter((item) => (!unreadOnly || item.unreadCount > 0) && `${item.vendorName} ${item.subject} ${item.lastMessage?.body || ""}`.toLowerCase().includes(search.toLowerCase())), [query.data, search, unreadOnly]); if (query.isLoading) return <Screen title="Vendor messages"><ActivityIndicator color={colors.primary} /></Screen>; return <Screen eyebrow="SELLER SUPPORT" title="Vendor messages" description="Read and respond to seller conversations from one operational inbox.">{query.error ? <Text style={styles.error}>{query.error.message}</Text> : null}<View style={styles.stats}><Stat label="Conversations" value={query.data?.summary.total || 0} /><Stat label="Needs reply" value={query.data?.summary.unread || 0} /><Stat label="Open" value={query.data?.summary.open || 0} /></View><View style={styles.toolbar}><TextInput value={search} onChangeText={setSearch} placeholder="Search seller conversations" placeholderTextColor={colors.muted} style={styles.search} /><Pressable onPress={() => setUnreadOnly(false)} style={[styles.filter, !unreadOnly && styles.activeFilter]}><Text style={[styles.filterText, !unreadOnly && styles.activeFilterText]}>All chats</Text></Pressable><Pressable onPress={() => setUnreadOnly(true)} style={[styles.filter, unreadOnly && styles.activeFilter]}><Text style={[styles.filterText, unreadOnly && styles.activeFilterText]}>Unread only</Text></Pressable></View>{threads.map((item) => <Pressable key={item.id} onPress={() => router.push(`/admin/chat/${item.id}`)}><ModuleCard title={item.vendorName} meta={`${item.subject} · ${item.messageCount} messages`}><View style={styles.row}><View style={styles.flex}>{item.lastMessage ? <><Text style={styles.sender}>{item.lastMessage.senderName}</Text><Text numberOfLines={2} style={styles.message}>{item.lastMessage.body}</Text></> : <Text style={styles.muted}>No messages yet</Text>}</View><View style={styles.right}>{item.unreadCount ? <Text style={styles.unread}>{item.unreadCount} NEW</Text> : <Text style={styles.read}>READ</Text>}<Text style={styles.muted}>{new Date(item.updatedAt).toLocaleString()}</Text></View></View></ModuleCard></Pressable>)}{!threads.length ? <Text style={styles.empty}>{unreadOnly ? "All caught up — no unread seller messages." : "No seller conversations found."}</Text> : null}</Screen>; }
function Stat({ label, value }: { label: string; value: number }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ stats: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, stat: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, flex: 1, minWidth: 120, padding: spacing.md }, statValue: { color: colors.text, fontSize: 24, fontWeight: "700" }, statLabel: { color: colors.muted, fontSize: 11 }, toolbar: { alignItems: "center", flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, search: { borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, color: colors.text, flex: 1, minHeight: 44, minWidth: 220, paddingHorizontal: spacing.md }, filter: { borderColor: colors.border, borderRadius: radius.pill, borderWidth: 1, paddingHorizontal: 13, paddingVertical: 9 }, activeFilter: { backgroundColor: colors.primary, borderColor: colors.primary }, filterText: { color: colors.muted, fontSize: 11, fontWeight: "700" }, activeFilterText: { color: colors.surface }, row: { alignItems: "flex-start", flexDirection: "row", flexWrap: "wrap", gap: spacing.md }, flex: { flex: 1, minWidth: 210 }, right: { alignItems: "flex-end", gap: spacing.xs }, sender: { color: colors.text, fontSize: 11, fontWeight: "700" }, message: { color: colors.text, fontSize: 13, lineHeight: 19, marginTop: 3 }, muted: { color: colors.muted, fontSize: 10 }, unread: { backgroundColor: colors.danger, borderRadius: radius.pill, color: colors.surface, fontSize: 9, fontWeight: "700", overflow: "hidden", paddingHorizontal: 8, paddingVertical: 5 }, read: { color: colors.success, fontSize: 9, fontWeight: "700" }, error: { color: colors.danger }, empty: { color: colors.muted, padding: spacing.xl, textAlign: "center" } });
