import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, useWindowDimensions, View } from "react-native";
import { colors, radius, spacing } from "../../ui/tokens";
import { StoreFooter } from "../home/components/StoreFooter";
import { StoreHeader } from "../home/components/StoreHeader";

export function ContactScreen() {
  const router = useRouter();
  const { width } = useWindowDimensions();
  return <SafeAreaView style={styles.safe}><ScrollView><StoreHeader desktop={width >= 900} viewportWidth={width} /><View style={styles.content}><Text style={styles.eyebrow}>HELP CENTER</Text><Text accessibilityRole="header" style={styles.title}>Contact Amiyo-Go</Text><Text style={styles.description}>Use a tracked support ticket for orders, payments, delivery, returns, seller operations, or account concerns.</Text><View style={styles.grid}><ContactCard icon="chatbubbles-outline" title="In-app support" body="Create a ticket, receive replies, and keep the full conversation attached to your account." action="Open support" onPress={() => router.push("/support")} /><ContactCard icon="mail-outline" title="Email" body="For general questions that are not linked to an existing order or account ticket." action="info@amiyo-go.com" onPress={() => Linking.openURL("mailto:info@amiyo-go.com")} /><ContactCard icon="time-outline" title="Tracked resolution" body="Ticket status and staff replies appear in the support center, so you do not lose the conversation." action="View my tickets" onPress={() => router.push("/support")} /></View><View style={styles.notice}><Ionicons color={colors.warning} name="shield-checkmark-outline" size={24} /><Text style={styles.noticeText}>Never share passwords, OTP codes, or complete payment credentials in a support message.</Text></View><StoreFooter /></View></ScrollView></SafeAreaView>;
}

function ContactCard({ action, body, icon, onPress, title }: { action: string; body: string; icon: string; onPress(): void; title: string }) { return <View style={styles.card}><View style={styles.icon}><Ionicons color={colors.primary} name={icon as never} size={25} /></View><Text style={styles.cardTitle}>{title}</Text><Text style={styles.cardBody}>{body}</Text><Pressable accessibilityRole="button" onPress={onPress} style={styles.action}><Text style={styles.actionText}>{action}</Text></Pressable></View>; }

const styles = StyleSheet.create({ safe: { backgroundColor: colors.background, flex: 1 }, content: { alignSelf: "center", maxWidth: 1000, padding: spacing.lg, width: "100%" }, eyebrow: { color: colors.primary, fontSize: 11, fontWeight: "900", letterSpacing: 1.2 }, title: { color: colors.text, fontSize: 34, fontWeight: "900", marginTop: spacing.sm }, description: { color: colors.muted, fontSize: 16, lineHeight: 25, marginTop: spacing.md, maxWidth: 680 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md, marginTop: spacing.xl }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.xl, borderWidth: 1, flex: 1, minWidth: 250, padding: spacing.lg }, icon: { alignItems: "center", backgroundColor: colors.primarySoft, borderRadius: radius.pill, height: 50, justifyContent: "center", width: 50 }, cardTitle: { color: colors.text, fontSize: 19, fontWeight: "900", marginTop: spacing.md }, cardBody: { color: colors.muted, lineHeight: 21, marginTop: spacing.sm, minHeight: 64 }, action: { alignItems: "center", borderColor: colors.primary, borderRadius: radius.md, borderWidth: 1, marginTop: spacing.md, padding: spacing.md }, actionText: { color: colors.primary, fontWeight: "900" }, notice: { alignItems: "center", backgroundColor: "#fffbeb", borderColor: "#fde68a", borderRadius: radius.lg, borderWidth: 1, flexDirection: "row", gap: spacing.md, marginTop: spacing.lg, padding: spacing.md }, noticeText: { color: "#92400e", flex: 1, lineHeight: 20 } });
