import assert from "node:assert/strict";
import test from "node:test";
import type { PrismaClient } from "@prisma/client";
import type { Session } from "@amiyo/contracts";
import { OperationsService } from "./operations.service.js";

const admin: Session = { principal: { userId: "00000000-0000-4000-8000-000000000003", roles: ["SUPER_ADMIN"], vendorIds: [] }, status: "ACTIVE", email: "admin@amiyo.test", phone: null, profile: { firstName: null, lastName: null, displayName: "Admin", avatarStorageKey: null, locale: "en", currency: "BDT" }, permissions: ["admin:read", "admin:manage", "finance:manage"], vendorMemberships: [] };

test("COD workspace derives delivery and cash discrepancy states", async () => { const now = new Date("2026-08-14T10:00:00.000Z"); const client = { payment: { findMany: async () => [{ id: "payment-1", method: "COD", status: "CAPTURED", amountMinor: 100000n, currency: "BDT", createdAt: now, codCollection: { id: "collection-1", collectedMinor: 98000n, collectorRef: "HANDOVER-1", collectedAt: now, reconciliationItems: [] }, order: { id: "order-1", orderNumber: "AGO-1", version: 2, createdAt: now, user: { normalizedPhone: "01700000000", profile: { displayName: "Customer" } }, addresses: [{ recipientName: "Customer", phone: "01700000000", upazila: "Dhanmondi", district: "Dhaka" }], vendorOrders: [{ status: "DELIVERED", vendor: { displayName: "Vendor" }, shipments: [{ status: "DELIVERED", provider: "Amiyo Delivery", assignment: null }] }] } }] }, codReconciliation: { findMany: async () => [] } } as unknown as PrismaClient; const result = await new OperationsService(client).codWorkspace(admin); assert.equal(result.orders[0]?.reconciliationStatus, "discrepancy"); assert.equal(result.orders[0]?.discrepancyMinor, "-2000"); assert.equal(result.summary.discrepancies, 1); });

test("COD cash cannot be confirmed before delivery", async () => { const transaction = { idempotencyRecord: { findUnique: async () => null }, order: { findUnique: async () => ({ id: "order-1", version: 1, payments: [{ id: "payment-1", amountMinor: 100000n, currency: "BDT", status: "AUTHORIZED", codCollection: null }], vendorOrders: [{ status: "IN_TRANSIT", shipments: [{ status: "IN_TRANSIT" }] }] }) } }; const client = { $transaction: async (operation: (client: typeof transaction) => unknown) => operation(transaction) } as unknown as PrismaClient; await assert.rejects(() => new OperationsService(client).confirmCodPayment(admin, "00000000-0000-4000-8000-000000000801", { expectedVersion: 1, collectedAmountMinor: "100000", reference: "HANDOVER-1", courierName: "Amiyo Delivery", note: null }, "00000000-0000-4000-8000-000000000999"), /Confirm delivery before receiving COD cash/); });
