import { Prisma, type PrismaClient, type ShipmentStatus } from "@prisma/client";
import type { CodRemittanceInput, CourierPartnerInput, DeliveryFeeRuleInput, FailedDeliveryReattempt, FailedDeliveryReturn, LogisticsAssignmentInput, LogisticsDeliveryAttempt, LogisticsShipmentTransition, LogisticsZoneInput, PickupStaffInput, Session } from "@amiyo/contracts";
import { ApiProblem } from "../../middleware/api-problem.js";

const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
const operatorRoles = new Set(["OPERATIONS_ADMIN", "SUPER_ADMIN"]);
const transitions: Record<ShipmentStatus, ShipmentStatus[]> = {
  PENDING: ["READY_TO_SHIP", "CANCELLED"], READY_TO_SHIP: ["PICKED_UP", "FAILED", "CANCELLED"], PICKED_UP: ["IN_TRANSIT", "FAILED"],
  IN_TRANSIT: ["DELIVERED", "FAILED"], DELIVERED: [], FAILED: ["READY_TO_SHIP", "CANCELLED"], CANCELLED: []
};

function requireOperator(session: Session, manage = false) {
  const permission = manage ? "admin:manage" : "admin:read";
  if (session.status !== "ACTIVE" || !session.permissions.includes(permission) || !session.principal.roles.some((role) => operatorRoles.has(role))) {
    throw new ApiProblem(403, "LOGISTICS_FORBIDDEN", `Logistics ${manage ? "management" : "access"} requires operations administrator access`);
  }
}

const shipmentInclude = {
  vendorOrder: { include: { order: { include: { addresses: true, payments: { orderBy: { createdAt: "desc" as const }, take: 1 } } }, vendor: true, shop: true } },
  assignment: { include: { courierPartner: true, pickupStaff: true } }, failedDelivery: true
};
type ShipmentRow = Prisma.ShipmentGetPayload<{ include: typeof shipmentInclude }>;

function shipmentDto(row: ShipmentRow) {
  const delivery = row.vendorOrder.order.addresses.find((address) => address.type === "delivery");
  const payment = row.vendorOrder.order.payments[0];
  return {
    id: row.id, vendorOrderId: row.vendorOrderId, orderId: row.vendorOrder.orderId, orderNumber: row.vendorOrder.order.orderNumber,
    vendorId: row.vendorOrder.vendorId, vendorName: row.vendorOrder.vendor.displayName, shopName: row.vendorOrder.shop.name, status: row.status,
    provider: row.provider, trackingNumber: row.trackingNumber, totalMinor: row.vendorOrder.totalMinor.toString(), currency: row.vendorOrder.order.currency,
    paymentMethod: payment?.method ?? null, codAmountMinor: payment?.method === "COD" ? row.vendorOrder.totalMinor.toString() : "0",
    deliveryAddress: delivery ? { recipientName: delivery.recipientName, phone: delivery.phone, line1: delivery.line1, line2: delivery.line2, division: delivery.division, district: delivery.district, upazila: delivery.upazila, unionName: delivery.unionName, postalCode: delivery.postalCode } : null,
    assignment: row.assignment ? { ...row.assignment, pickupDate: row.assignment.pickupDate?.toISOString() ?? null, estimatedDeliveryDate: row.assignment.estimatedDeliveryDate?.toISOString() ?? null, createdAt: row.assignment.createdAt.toISOString(), updatedAt: row.assignment.updatedAt.toISOString() } : null,
    failedDelivery: row.failedDelivery ? { ...row.failedDelivery, redeliveryFeeMinor: row.failedDelivery.redeliveryFeeMinor.toString(), returnFeeMinor: row.failedDelivery.returnFeeMinor.toString(), nextAttemptAt: row.failedDelivery.nextAttemptAt?.toISOString() ?? null, createdAt: row.failedDelivery.createdAt.toISOString(), updatedAt: row.failedDelivery.updatedAt.toISOString() } : null,
    shippedAt: row.shippedAt?.toISOString() ?? null, deliveredAt: row.deliveredAt?.toISOString() ?? null, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString()
  };
}

export class LogisticsService {
  constructor(private readonly client: PrismaClient) {}

  private async audit(session: Session, action: string, resourceType: string, resourceId: string, before: unknown, after: unknown) {
    await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action, resourceType, resourceId, before: json(before), after: json(after) } });
  }

  async overview(session: Session) {
    requireOperator(session);
    const [zones, couriers, pickupStaff, feeRules, shipments, remittances] = await Promise.all([
      this.client.logisticsZone.findMany({ orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }), this.client.courierPartner.findMany({ orderBy: { name: "asc" } }),
      this.client.pickupStaff.findMany({ orderBy: { name: "asc" } }), this.client.deliveryFeeRule.findMany({ orderBy: [{ priority: "asc" }, { name: "asc" }] }),
      this.client.shipment.findMany({ include: shipmentInclude, orderBy: { updatedAt: "desc" }, take: 250 }), this.client.codRemittance.findMany({ include: { courierPartner: true }, orderBy: { createdAt: "desc" }, take: 100 })
    ]);
    const shipmentRows = shipments.map(shipmentDto);
    return { zones, couriers: couriers.map((row) => ({ ...row, baseDeliveryCostMinor: row.baseDeliveryCostMinor.toString(), codCollectionFeeMinor: row.codCollectionFeeMinor.toString() })), pickupStaff, feeRules: feeRules.map((row) => this.feeRuleDto(row)), shipments: shipmentRows, remittances: remittances.map((row) => this.remittanceDto(row)), summary: { totalShipments: shipmentRows.length, readyToShip: shipmentRows.filter((row) => row.status === "READY_TO_SHIP").length, activeParcels: shipmentRows.filter((row) => ["PICKED_UP", "IN_TRANSIT"].includes(row.status)).length, failedDeliveries: shipmentRows.filter((row) => row.status === "FAILED").length, codOutstandingMinor: remittances.reduce((sum, row) => sum + (row.collectedAmountMinor - row.remittedAmountMinor), 0n).toString() } };
  }

  async shipments(session: Session) { requireOperator(session); return (await this.client.shipment.findMany({ include: shipmentInclude, orderBy: { updatedAt: "desc" }, take: 250 })).map(shipmentDto); }
  async zones(session: Session) { requireOperator(session); return this.client.logisticsZone.findMany({ orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }); }
  async couriers(session: Session) { requireOperator(session); return (await this.client.courierPartner.findMany({ orderBy: { name: "asc" } })).map((row) => ({ ...row, baseDeliveryCostMinor: row.baseDeliveryCostMinor.toString(), codCollectionFeeMinor: row.codCollectionFeeMinor.toString() })); }
  async staff(session: Session) { requireOperator(session); return this.client.pickupStaff.findMany({ orderBy: { name: "asc" } }); }
  async feeRules(session: Session) { requireOperator(session); return (await this.client.deliveryFeeRule.findMany({ orderBy: [{ priority: "asc" }, { name: "asc" }] })).map((row) => this.feeRuleDto(row)); }
  async failedDeliveries(session: Session) { requireOperator(session); return (await this.client.shipment.findMany({ where: { status: "FAILED" }, include: shipmentInclude, orderBy: { updatedAt: "desc" } })).map(shipmentDto); }

  async saveZone(session: Session, input: LogisticsZoneInput, id?: string) { requireOperator(session, true); const before = id ? await this.client.logisticsZone.findUnique({ where: { id } }) : null; const data = { ...input, districts: json(input.districts), courierPartnerIds: json(input.courierPartnerIds) }; const row = id ? await this.client.logisticsZone.update({ where: { id }, data }) : await this.client.logisticsZone.create({ data }); await this.audit(session, id ? "logistics.zone.updated" : "logistics.zone.created", "logistics_zone", row.id, before, row); return row; }
  async saveCourier(session: Session, input: CourierPartnerInput, id?: string) { requireOperator(session, true); const before = id ? await this.client.courierPartner.findUnique({ where: { id } }) : null; const data = { ...input, serviceZones: json(input.serviceZones), baseDeliveryCostMinor: BigInt(input.baseDeliveryCostMinor), codCollectionFeeMinor: BigInt(input.codCollectionFeeMinor) }; const row = id ? await this.client.courierPartner.update({ where: { id }, data }) : await this.client.courierPartner.create({ data }); await this.audit(session, id ? "logistics.courier.updated" : "logistics.courier.created", "courier_partner", row.id, before, row); return { ...row, baseDeliveryCostMinor: row.baseDeliveryCostMinor.toString(), codCollectionFeeMinor: row.codCollectionFeeMinor.toString() }; }
  async saveStaff(session: Session, input: PickupStaffInput, id?: string) { requireOperator(session, true); const before = id ? await this.client.pickupStaff.findUnique({ where: { id } }) : null; const data = { ...input, assignedZones: json(input.assignedZones), assignedLocations: json(input.assignedLocations), assignedVendorIds: json(input.assignedVendorIds) }; const row = id ? await this.client.pickupStaff.update({ where: { id }, data }) : await this.client.pickupStaff.create({ data }); await this.audit(session, id ? "logistics.pickup_staff.updated" : "logistics.pickup_staff.created", "pickup_staff", row.id, before, row); return row; }
  async saveFeeRule(session: Session, input: DeliveryFeeRuleInput, id?: string) { requireOperator(session, true); const before = id ? await this.client.deliveryFeeRule.findUnique({ where: { id } }) : null; const { freeShippingThresholdMinor, ...rest } = input; const data = { ...rest, minOrderAmountMinor: BigInt(input.minOrderAmountMinor), maxOrderAmountMinor: BigInt(input.maxOrderAmountMinor), baseFeeMinor: BigInt(input.baseFeeMinor), perItemFeeMinor: BigInt(input.perItemFeeMinor), feePerKgMinor: BigInt(input.feePerKgMinor), codFeeMinor: BigInt(input.codFeeMinor), redeliveryFeeMinor: BigInt(input.redeliveryFeeMinor), freeShippingThreshold: BigInt(freeShippingThresholdMinor), paymentMethods: json(input.paymentMethods) }; const row = id ? await this.client.deliveryFeeRule.update({ where: { id }, data }) : await this.client.deliveryFeeRule.create({ data }); await this.audit(session, id ? "logistics.fee_rule.updated" : "logistics.fee_rule.created", "delivery_fee_rule", row.id, before, row); return this.feeRuleDto(row); }

  async assignShipment(session: Session, shipmentId: string, input: LogisticsAssignmentInput) { requireOperator(session, true); const shipment = await this.client.shipment.findUnique({ where: { id: shipmentId }, include: { assignment: true } }); if (!shipment) throw new ApiProblem(404, "SHIPMENT_NOT_FOUND", "Shipment not found"); if (input.expectedVersion && shipment.assignment?.version !== input.expectedVersion) throw new ApiProblem(409, "ASSIGNMENT_VERSION_CONFLICT", "Parcel assignment changed; refresh and retry"); const data = { courierPartnerId: input.courierPartnerId, pickupStaffId: input.pickupStaffId, bookingMode: input.bookingMode, trackingNumber: input.trackingNumber, pickupDate: input.pickupDate ? new Date(input.pickupDate) : null, pickupWindow: input.pickupWindow, estimatedDeliveryDate: input.estimatedDeliveryDate ? new Date(input.estimatedDeliveryDate) : null, note: input.note }; const assignment = await this.client.logisticsAssignment.upsert({ where: { shipmentId }, create: { shipmentId, ...data }, update: { ...data, version: { increment: 1 } }, include: { courierPartner: true, pickupStaff: true } }); await this.client.shipment.update({ where: { id: shipmentId }, data: { provider: assignment.courierPartner?.provider ?? shipment.provider, trackingNumber: input.trackingNumber ?? shipment.trackingNumber } }); await this.audit(session, "logistics.shipment.assigned", "shipment", shipmentId, shipment.assignment, assignment); return assignment; }
  async transitionShipment(session: Session, shipmentId: string, input: LogisticsShipmentTransition) { requireOperator(session, true); const shipment = await this.client.shipment.findUnique({ where: { id: shipmentId } }); if (!shipment) throw new ApiProblem(404, "SHIPMENT_NOT_FOUND", "Shipment not found"); if (!transitions[shipment.status].includes(input.status)) throw new ApiProblem(409, "SHIPMENT_TRANSITION_INVALID", `Cannot move ${shipment.status} to ${input.status}`); const row = await this.client.shipment.update({ where: { id: shipmentId }, data: { status: input.status, ...(input.status === "PICKED_UP" ? { shippedAt: new Date() } : {}), ...(input.status === "DELIVERED" ? { deliveredAt: new Date() } : {}), events: { create: { status: input.status, description: input.note, occurredAt: new Date() } } } }); await this.audit(session, "logistics.shipment.transitioned", "shipment", shipmentId, { status: shipment.status }, { status: row.status, note: input.note }); return row; }
  async recordDeliveryAttempt(session: Session, shipmentId: string, input: LogisticsDeliveryAttempt) { requireOperator(session, true); const status: ShipmentStatus = input.outcome === "delivered" ? "DELIVERED" : "FAILED"; const shipment = await this.client.shipment.findUnique({ where: { id: shipmentId }, include: { failedDelivery: true, assignment: { include: { courierPartner: true } } } }); if (!shipment) throw new ApiProblem(404, "SHIPMENT_NOT_FOUND", "Shipment not found"); const row = await this.client.shipment.update({ where: { id: shipmentId }, data: { status, ...(status === "DELIVERED" ? { deliveredAt: new Date() } : {}), events: { create: { status, description: input.reason || input.notes || `Delivery ${input.outcome}`, providerPayload: json({ receiverName: input.receiverName, codCollected: input.codCollected }), occurredAt: new Date() } } } }); if (status === "FAILED") await this.client.failedDeliveryRecord.upsert({ where: { shipmentId }, create: { shipmentId, courierName: shipment.assignment?.courierPartner?.name ?? shipment.provider, reason: input.reason || "Delivery attempt failed", note: input.notes }, update: { reason: input.reason || "Delivery attempt failed", note: input.notes, attemptCount: { increment: 1 }, resolution: "pending" } }); else if (shipment.failedDelivery) await this.client.failedDeliveryRecord.update({ where: { shipmentId }, data: { resolution: "delivered" } }); await this.audit(session, `logistics.delivery.${input.outcome}`, "shipment", shipmentId, { status: shipment.status }, { status, ...input }); return row; }

  async recordCodRemittance(session: Session, input: CodRemittanceInput) { requireOperator(session, true); const row = await this.client.codRemittance.create({ data: { courierPartnerId: input.courierPartnerId, courierName: input.courierName, collectedAmountMinor: BigInt(input.collectedAmountMinor), remittedAmountMinor: BigInt(input.remittedAmountMinor), forwardedToVendorMinor: BigInt(input.forwardedToVendorMinor), reference: input.reference, notes: input.notes, orderIds: json(input.orderIds), createdBy: session.principal.userId } }); await this.audit(session, "logistics.cod_remittance.recorded", "cod_remittance", row.id, null, row); return this.remittanceDto(row); }
  async scheduleReattempt(session: Session, shipmentId: string, input: FailedDeliveryReattempt) { requireOperator(session, true); const row = await this.client.failedDeliveryRecord.update({ where: { shipmentId }, data: { nextAttemptAt: new Date(input.nextAttemptAt), redeliveryFeeMinor: BigInt(input.redeliveryFeeMinor), reason: input.reason, note: input.note, resolution: "reattempt_scheduled" } }); await this.client.shipment.update({ where: { id: shipmentId }, data: { status: "READY_TO_SHIP", events: { create: { status: "READY_TO_SHIP", description: input.reason, occurredAt: new Date() } } } }); await this.audit(session, "logistics.failed_delivery.reattempt_scheduled", "shipment", shipmentId, null, row); return row; }
  async returnToSeller(session: Session, shipmentId: string, input: FailedDeliveryReturn) { requireOperator(session, true); const row = await this.client.failedDeliveryRecord.update({ where: { shipmentId }, data: { returnFeeMinor: BigInt(input.returnFeeMinor), reason: input.reason, note: input.note, resolution: "return_to_seller" } }); await this.client.shipment.update({ where: { id: shipmentId }, data: { status: "CANCELLED", events: { create: { status: "CANCELLED", description: input.reason, occurredAt: new Date() } } } }); await this.audit(session, "logistics.failed_delivery.return_to_seller", "shipment", shipmentId, null, row); return row; }

  private feeRuleDto(row: Awaited<ReturnType<PrismaClient["deliveryFeeRule"]["findFirstOrThrow"]>>) { return { ...row, minOrderAmountMinor: row.minOrderAmountMinor.toString(), maxOrderAmountMinor: row.maxOrderAmountMinor.toString(), baseFeeMinor: row.baseFeeMinor.toString(), perItemFeeMinor: row.perItemFeeMinor.toString(), feePerKgMinor: row.feePerKgMinor.toString(), codFeeMinor: row.codFeeMinor.toString(), redeliveryFeeMinor: row.redeliveryFeeMinor.toString(), freeShippingThreshold: row.freeShippingThreshold.toString() }; }
  private remittanceDto(row: { id: string; courierPartnerId: string | null; courierName: string; collectedAmountMinor: bigint; remittedAmountMinor: bigint; forwardedToVendorMinor: bigint; reference: string | null; notes: string | null; orderIds: Prisma.JsonValue; createdBy: string; createdAt: Date; courierPartner?: unknown }) { return { ...row, collectedAmountMinor: row.collectedAmountMinor.toString(), remittedAmountMinor: row.remittedAmountMinor.toString(), forwardedToVendorMinor: row.forwardedToVendorMinor.toString(), createdAt: row.createdAt.toISOString() }; }
}
