import { Prisma, type PrismaClient, type ReturnStatus, type ShipmentStatus } from "@prisma/client";
import type { CodRemittanceInput, CourierPartnerInput, DeliveryFeeRuleInput, FailedDeliveryReattempt, FailedDeliveryReturn, LogisticsAssignmentInput, LogisticsCodStateInput, LogisticsDeliveryAttempt, LogisticsManifestPickup, LogisticsNote, LogisticsReturnAction, LogisticsShipmentTransition, LogisticsTrackingEvent, LogisticsZoneInput, PickupStaffInput, Session } from "@amiyo/contracts";
import { ApiProblem } from "../../middleware/api-problem.js";

const json = (value: unknown) => JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
const operatorRoles = new Set(["OPERATIONS_ADMIN", "SUPER_ADMIN"]);
const transitions: Record<ShipmentStatus, ShipmentStatus[]> = {
  PENDING: ["READY_TO_SHIP", "CANCELLED"], READY_TO_SHIP: ["PICKED_UP", "FAILED", "CANCELLED"], PICKED_UP: ["IN_TRANSIT", "FAILED"],
  IN_TRANSIT: ["DELIVERED", "FAILED"], DELIVERED: [], FAILED: ["READY_TO_SHIP", "CANCELLED"], CANCELLED: []
};
const reverseTransitions: Record<string, { allowed: ReturnStatus[]; status: ReturnStatus }> = {
  generate_label: { allowed: ["APPROVED", "PICKUP_SCHEDULED"], status: "APPROVED" },
  schedule_pickup: { allowed: ["APPROVED"], status: "PICKUP_SCHEDULED" },
  picked_up: { allowed: ["PICKUP_SCHEDULED"], status: "PICKUP_SCHEDULED" },
  in_transit: { allowed: ["PICKUP_SCHEDULED"], status: "PICKUP_SCHEDULED" },
  received: { allowed: ["PICKUP_SCHEDULED"], status: "RECEIVED" },
  inspected: { allowed: ["RECEIVED"], status: "INSPECTED" },
  restocked: { allowed: ["INSPECTED"], status: "CLOSED" },
  disposed: { allowed: ["INSPECTED"], status: "CLOSED" },
  refurbished: { allowed: ["INSPECTED"], status: "CLOSED" }
};
const codTransitions: Record<string, string[]> = { cod_pending: ["cod_collected", "cod_failed", "cod_disputed"], cod_collected: ["cod_remitted", "cod_disputed"], cod_disputed: ["cod_collected", "cod_failed"], cod_failed: [], cod_remitted: [] };

function requireOperator(session: Session, manage = false) {
  const permission = manage ? "admin:manage" : "admin:read";
  if (session.status !== "ACTIVE" || !session.permissions.includes(permission) || !session.principal.roles.some((role) => operatorRoles.has(role))) {
    throw new ApiProblem(403, "LOGISTICS_FORBIDDEN", `Logistics ${manage ? "management" : "access"} requires operations administrator access`);
  }
}

const shipmentInclude = {
  vendorOrder: { include: { order: { include: { addresses: true, payments: { orderBy: { createdAt: "desc" as const }, take: 1 } } }, vendor: true, shop: true } },
  assignment: { include: { courierPartner: true, pickupStaff: true } }, failedDelivery: true
};
type ShipmentRow = Prisma.ShipmentGetPayload<{ include: typeof shipmentInclude }>;

function shipmentDto(row: ShipmentRow) {
  const delivery = row.vendorOrder.order.addresses.find((address) => address.type === "delivery");
  const payment = row.vendorOrder.order.payments[0];
  return {
    id: row.id, vendorOrderId: row.vendorOrderId, orderId: row.vendorOrder.orderId, orderNumber: row.vendorOrder.order.orderNumber,
    vendorId: row.vendorOrder.vendorId, vendorName: row.vendorOrder.vendor.displayName, shopName: row.vendorOrder.shop.name, status: row.status,
    provider: row.provider, trackingNumber: row.trackingNumber, codState: row.codState, codRemittanceReference: row.codRemittanceReference, codDisputeReason: row.codDisputeReason, rtoReceivedAt: row.rtoReceivedAt?.toISOString() ?? null, totalMinor: row.vendorOrder.totalMinor.toString(), currency: row.vendorOrder.order.currency,
    paymentMethod: payment?.method ?? null, codAmountMinor: payment?.method === "COD" ? row.vendorOrder.totalMinor.toString() : "0",
    deliveryAddress: delivery ? { recipientName: delivery.recipientName, phone: delivery.phone, line1: delivery.line1, line2: delivery.line2, division: delivery.division, district: delivery.district, upazila: delivery.upazila, unionName: delivery.unionName, postalCode: delivery.postalCode } : null,
    assignment: row.assignment ? { ...row.assignment, pickupDate: row.assignment.pickupDate?.toISOString() ?? null, estimatedDeliveryDate: row.assignment.estimatedDeliveryDate?.toISOString() ?? null, createdAt: row.assignment.createdAt.toISOString(), updatedAt: row.assignment.updatedAt.toISOString() } : null,
    failedDelivery: row.failedDelivery ? { ...row.failedDelivery, redeliveryFeeMinor: row.failedDelivery.redeliveryFeeMinor.toString(), returnFeeMinor: row.failedDelivery.returnFeeMinor.toString(), nextAttemptAt: row.failedDelivery.nextAttemptAt?.toISOString() ?? null, createdAt: row.failedDelivery.createdAt.toISOString(), updatedAt: row.failedDelivery.updatedAt.toISOString() } : null,
    shippedAt: row.shippedAt?.toISOString() ?? null, deliveredAt: row.deliveredAt?.toISOString() ?? null, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString()
  };
}

export class LogisticsService {
  constructor(private readonly client: PrismaClient) {}

  private async audit(session: Session, action: string, resourceType: string, resourceId: string, before: unknown, after: unknown) {
    await this.client.auditLog.create({ data: { actorUserId: session.principal.userId, actorType: "admin", action, resourceType, resourceId, before: json(before), after: json(after) } });
  }

  async overview(session: Session) {
    requireOperator(session);
    const [zones, couriers, pickupStaff, feeRules, shipments, remittances] = await Promise.all([
      this.client.logisticsZone.findMany({ orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }), this.client.courierPartner.findMany({ orderBy: { name: "asc" } }),
      this.client.pickupStaff.findMany({ orderBy: { name: "asc" } }), this.client.deliveryFeeRule.findMany({ orderBy: [{ priority: "asc" }, { name: "asc" }] }),
      this.client.shipment.findMany({ include: shipmentInclude, orderBy: { updatedAt: "desc" }, take: 250 }), this.client.codRemittance.findMany({ include: { courierPartner: true }, orderBy: { createdAt: "desc" }, take: 100 })
    ]);
    const shipmentRows = shipments.map(shipmentDto);
    return { zones, couriers: couriers.map((row) => ({ ...row, baseDeliveryCostMinor: row.baseDeliveryCostMinor.toString(), codCollectionFeeMinor: row.codCollectionFeeMinor.toString() })), pickupStaff, feeRules: feeRules.map((row) => this.feeRuleDto(row)), shipments: shipmentRows, remittances: remittances.map((row) => this.remittanceDto(row)), summary: { totalShipments: shipmentRows.length, readyToShip: shipmentRows.filter((row) => row.status === "READY_TO_SHIP").length, activeParcels: shipmentRows.filter((row) => ["PICKED_UP", "IN_TRANSIT"].includes(row.status)).length, failedDeliveries: shipmentRows.filter((row) => row.status === "FAILED").length, codOutstandingMinor: remittances.reduce((sum, row) => sum + (row.collectedAmountMinor - row.remittedAmountMinor), 0n).toString() } };
  }

  async shipments(session: Session) { requireOperator(session); return (await this.client.shipment.findMany({ include: shipmentInclude, orderBy: { updatedAt: "desc" }, take: 250 })).map(shipmentDto); }
  async dashboard(session: Session) { return this.overview(session); }
  async stateMachine(session: Session) { requireOperator(session); return { forward: transitions, reverse: reverseTransitions, cod: codTransitions }; }
  async courierReadiness(session: Session) { requireOperator(session); return ["pathao", "steadfast", "redx"].map((provider) => ({ provider, configured: Boolean(process.env[`${provider.toUpperCase()}_API_KEY`]), mode: process.env.NODE_ENV === "production" ? "live" : "sandbox" })); }
  async auditLog(session: Session) { requireOperator(session); return this.client.auditLog.findMany({ where: { action: { startsWith: "logistics." } }, orderBy: { createdAt: "desc" }, take: 250 }); }
  async zones(session: Session) { requireOperator(session); return this.client.logisticsZone.findMany({ orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }); }
  async couriers(session: Session) { requireOperator(session); return (await this.client.courierPartner.findMany({ orderBy: { name: "asc" } })).map((row) => ({ ...row, baseDeliveryCostMinor: row.baseDeliveryCostMinor.toString(), codCollectionFeeMinor: row.codCollectionFeeMinor.toString() })); }
  async staff(session: Session) { requireOperator(session); return this.client.pickupStaff.findMany({ orderBy: { name: "asc" } }); }
  async feeRules(session: Session) { requireOperator(session); return (await this.client.deliveryFeeRule.findMany({ orderBy: [{ priority: "asc" }, { name: "asc" }] })).map((row) => this.feeRuleDto(row)); }
  async failedDeliveries(session: Session) { requireOperator(session); return (await this.client.shipment.findMany({ where: { status: "FAILED" }, include: shipmentInclude, orderBy: { updatedAt: "desc" } })).map(shipmentDto); }

  async saveZone(session: Session, input: LogisticsZoneInput, id?: string) { requireOperator(session, true); const before = id ? await this.client.logisticsZone.findUnique({ where: { id } }) : null; const data = { ...input, districts: json(input.districts), courierPartnerIds: json(input.courierPartnerIds) }; const row = id ? await this.client.logisticsZone.update({ where: { id }, data }) : await this.client.logisticsZone.create({ data }); await this.audit(session, id ? "logistics.zone.updated" : "logistics.zone.created", "logistics_zone", row.id, before, row); return row; }
  async saveCourier(session: Session, input: CourierPartnerInput, id?: string) { requireOperator(session, true); const before = id ? await this.client.courierPartner.findUnique({ where: { id } }) : null; const data = { ...input, serviceZones: json(input.serviceZones), baseDeliveryCostMinor: BigInt(input.baseDeliveryCostMinor), codCollectionFeeMinor: BigInt(input.codCollectionFeeMinor) }; const row = id ? await this.client.courierPartner.update({ where: { id }, data }) : await this.client.courierPartner.create({ data }); await this.audit(session, id ? "logistics.courier.updated" : "logistics.courier.created", "courier_partner", row.id, before, row); return { ...row, baseDeliveryCostMinor: row.baseDeliveryCostMinor.toString(), codCollectionFeeMinor: row.codCollectionFeeMinor.toString() }; }
  async saveStaff(session: Session, input: PickupStaffInput, id?: string) { requireOperator(session, true); const before = id ? await this.client.pickupStaff.findUnique({ where: { id } }) : null; const data = { ...input, assignedZones: json(input.assignedZones), assignedLocations: json(input.assignedLocations), assignedVendorIds: json(input.assignedVendorIds) }; const row = id ? await this.client.pickupStaff.update({ where: { id }, data }) : await this.client.pickupStaff.create({ data }); await this.audit(session, id ? "logistics.pickup_staff.updated" : "logistics.pickup_staff.created", "pickup_staff", row.id, before, row); return row; }
  async saveFeeRule(session: Session, input: DeliveryFeeRuleInput, id?: string) { requireOperator(session, true); const before = id ? await this.client.deliveryFeeRule.findUnique({ where: { id } }) : null; const { freeShippingThresholdMinor, ...rest } = input; const data = { ...rest, minOrderAmountMinor: BigInt(input.minOrderAmountMinor), maxOrderAmountMinor: BigInt(input.maxOrderAmountMinor), baseFeeMinor: BigInt(input.baseFeeMinor), perItemFeeMinor: BigInt(input.perItemFeeMinor), feePerKgMinor: BigInt(input.feePerKgMinor), codFeeMinor: BigInt(input.codFeeMinor), redeliveryFeeMinor: BigInt(input.redeliveryFeeMinor), freeShippingThreshold: BigInt(freeShippingThresholdMinor), paymentMethods: json(input.paymentMethods) }; const row = id ? await this.client.deliveryFeeRule.update({ where: { id }, data }) : await this.client.deliveryFeeRule.create({ data }); await this.audit(session, id ? "logistics.fee_rule.updated" : "logistics.fee_rule.created", "delivery_fee_rule", row.id, before, row); return this.feeRuleDto(row); }

  async assignShipment(session: Session, shipmentId: string, input: LogisticsAssignmentInput) { requireOperator(session, true); const shipment = await this.client.shipment.findUnique({ where: { id: shipmentId }, include: { assignment: true } }); if (!shipment) throw new ApiProblem(404, "SHIPMENT_NOT_FOUND", "Shipment not found"); if (input.expectedVersion && shipment.assignment?.version !== input.expectedVersion) throw new ApiProblem(409, "ASSIGNMENT_VERSION_CONFLICT", "Parcel assignment changed; refresh and retry"); const data = { courierPartnerId: input.courierPartnerId, pickupStaffId: input.pickupStaffId, bookingMode: input.bookingMode, trackingNumber: input.trackingNumber, pickupDate: input.pickupDate ? new Date(input.pickupDate) : null, pickupWindow: input.pickupWindow, estimatedDeliveryDate: input.estimatedDeliveryDate ? new Date(input.estimatedDeliveryDate) : null, note: input.note }; const assignment = await this.client.logisticsAssignment.upsert({ where: { shipmentId }, create: { shipmentId, ...data }, update: { ...data, version: { increment: 1 } }, include: { courierPartner: true, pickupStaff: true } }); await this.client.shipment.update({ where: { id: shipmentId }, data: { provider: assignment.courierPartner?.provider ?? shipment.provider, trackingNumber: input.trackingNumber ?? shipment.trackingNumber } }); await this.audit(session, "logistics.shipment.assigned", "shipment", shipmentId, shipment.assignment, assignment); return assignment; }
  async syncTrackingEvent(session: Session, input: LogisticsTrackingEvent) { requireOperator(session, true); const shipment = await this.client.shipment.findUnique({ where: { id: input.shipmentId } }); if (!shipment) throw new ApiProblem(404, "SHIPMENT_NOT_FOUND", "Shipment not found"); if (input.status !== shipment.status && !transitions[shipment.status].includes(input.status)) throw new ApiProblem(409, "SHIPMENT_TRANSITION_INVALID", `Cannot move ${shipment.status} to ${input.status}`); const row = await this.client.shipment.update({ where: { id: input.shipmentId }, data: { status: input.status, ...(input.status === "PICKED_UP" ? { shippedAt: new Date(input.occurredAt) } : {}), ...(input.status === "DELIVERED" ? { deliveredAt: new Date(input.occurredAt) } : {}), events: { create: { status: input.status, description: input.description, location: input.location, providerPayload: json({ providerEventId: input.providerEventId }), occurredAt: new Date(input.occurredAt) } } } }); await this.audit(session, "logistics.tracking.synced", "shipment", input.shipmentId, { status: shipment.status }, input); return row; }
  async transitionShipment(session: Session, shipmentId: string, input: LogisticsShipmentTransition) { requireOperator(session, true); const shipment = await this.client.shipment.findUnique({ where: { id: shipmentId } }); if (!shipment) throw new ApiProblem(404, "SHIPMENT_NOT_FOUND", "Shipment not found"); if (!transitions[shipment.status].includes(input.status)) throw new ApiProblem(409, "SHIPMENT_TRANSITION_INVALID", `Cannot move ${shipment.status} to ${input.status}`); const row = await this.client.shipment.update({ where: { id: shipmentId }, data: { status: input.status, ...(input.status === "PICKED_UP" ? { shippedAt: new Date() } : {}), ...(input.status === "DELIVERED" ? { deliveredAt: new Date() } : {}), events: { create: { status: input.status, description: input.note, occurredAt: new Date() } } } }); await this.audit(session, "logistics.shipment.transitioned", "shipment", shipmentId, { status: shipment.status }, { status: row.status, note: input.note }); return row; }
  async recordDeliveryAttempt(session: Session, shipmentId: string, input: LogisticsDeliveryAttempt) { requireOperator(session, true); const status: ShipmentStatus = input.outcome === "delivered" ? "DELIVERED" : "FAILED"; const shipment = await this.client.shipment.findUnique({ where: { id: shipmentId }, include: { failedDelivery: true, assignment: { include: { courierPartner: true } } } }); if (!shipment) throw new ApiProblem(404, "SHIPMENT_NOT_FOUND", "Shipment not found"); const row = await this.client.shipment.update({ where: { id: shipmentId }, data: { status, ...(status === "DELIVERED" ? { deliveredAt: new Date() } : {}), events: { create: { status, description: input.reason || input.notes || `Delivery ${input.outcome}`, providerPayload: json({ receiverName: input.receiverName, codCollected: input.codCollected }), occurredAt: new Date() } } } }); if (status === "FAILED") await this.client.failedDeliveryRecord.upsert({ where: { shipmentId }, create: { shipmentId, courierName: shipment.assignment?.courierPartner?.name ?? shipment.provider, reason: input.reason || "Delivery attempt failed", note: input.notes }, update: { reason: input.reason || "Delivery attempt failed", note: input.notes, attemptCount: { increment: 1 }, resolution: "pending" } }); else if (shipment.failedDelivery) await this.client.failedDeliveryRecord.update({ where: { shipmentId }, data: { resolution: "delivered" } }); await this.audit(session, `logistics.delivery.${input.outcome}`, "shipment", shipmentId, { status: shipment.status }, { status, ...input }); return row; }
  async markRto(session: Session, shipmentId: string, input: LogisticsNote) { requireOperator(session, true); const shipment = await this.client.shipment.findUnique({ where: { id: shipmentId }, include: { assignment: { include: { courierPartner: true } } } }); if (!shipment) throw new ApiProblem(404, "SHIPMENT_NOT_FOUND", "Shipment not found"); if (!["READY_TO_SHIP", "PICKED_UP", "IN_TRANSIT", "FAILED"].includes(shipment.status)) throw new ApiProblem(409, "RTO_NOT_ALLOWED", `Cannot mark ${shipment.status} as RTO`); const row = await this.client.shipment.update({ where: { id: shipmentId }, data: { status: "CANCELLED", events: { create: { status: "CANCELLED", description: input.note, providerPayload: json({ logisticsState: "rto_in_transit" }), occurredAt: new Date() } } } }); await this.client.failedDeliveryRecord.upsert({ where: { shipmentId }, create: { shipmentId, courierName: shipment.assignment?.courierPartner?.name ?? shipment.provider, reason: input.note, resolution: "rto_in_transit" }, update: { reason: input.note, resolution: "rto_in_transit" } }); await this.audit(session, "logistics.rto.marked", "shipment", shipmentId, { status: shipment.status }, { status: "CANCELLED", resolution: "rto_in_transit", note: input.note }); return row; }
  async confirmRtoReceived(session: Session, shipmentId: string, input: LogisticsNote) { requireOperator(session, true); const shipment = await this.client.shipment.findUnique({ where: { id: shipmentId }, include: { failedDelivery: true } }); if (!shipment) throw new ApiProblem(404, "SHIPMENT_NOT_FOUND", "Shipment not found"); if (shipment.status !== "CANCELLED" || shipment.failedDelivery?.resolution !== "rto_in_transit") throw new ApiProblem(409, "RTO_NOT_IN_TRANSIT", "Shipment is not awaiting RTO receipt"); const record = await this.client.failedDeliveryRecord.update({ where: { shipmentId }, data: { resolution: "rto_received", note: input.note } }); await this.client.shipment.update({ where: { id: shipmentId }, data: { rtoReceivedAt: new Date(), events: { create: { status: "CANCELLED", description: input.note, providerPayload: json({ logisticsState: "rto_received" }), occurredAt: new Date() } } } }); await this.audit(session, "logistics.rto.received", "shipment", shipmentId, { resolution: "rto_in_transit" }, { resolution: "rto_received", note: input.note }); return record; }

  async updateCodState(session: Session, shipmentId: string, targetState: string, input: LogisticsCodStateInput) { requireOperator(session, true); const shipment = await this.client.shipment.findUnique({ where: { id: shipmentId } }); if (!shipment) throw new ApiProblem(404, "SHIPMENT_NOT_FOUND", "Shipment not found"); if (!codTransitions[shipment.codState]?.includes(targetState)) throw new ApiProblem(409, "COD_TRANSITION_INVALID", `Cannot move ${shipment.codState} to ${targetState}`); if (targetState === "cod_remitted" && !input.reference) throw new ApiProblem(400, "COD_REMITTANCE_REFERENCE_REQUIRED", "A remittance reference is required"); if (["cod_failed", "cod_disputed"].includes(targetState) && !input.reason) throw new ApiProblem(400, "COD_REASON_REQUIRED", "A failure or dispute reason is required"); const row = await this.client.shipment.update({ where: { id: shipmentId }, data: { codState: targetState, codRemittanceReference: targetState === "cod_remitted" ? input.reference : shipment.codRemittanceReference, codDisputeReason: targetState === "cod_disputed" ? input.reason : null, events: { create: { status: shipment.status, description: input.note, providerPayload: json({ codState: targetState, reference: input.reference, reason: input.reason }), occurredAt: new Date() } } } }); await this.audit(session, `logistics.${targetState.replace("cod_", "cod.")}`, "shipment", shipmentId, { codState: shipment.codState }, { codState: targetState, ...input }); return row; }

  async shipmentLabel(session: Session, shipmentId: string, recordGeneration = false) { requireOperator(session, recordGeneration); const row = await this.client.shipment.findUnique({ where: { id: shipmentId }, include: shipmentInclude }); if (!row) throw new ApiProblem(404, "SHIPMENT_NOT_FOUND", "Shipment not found"); const shipment = shipmentDto(row); const label = { labelId: `LBL-${row.id.slice(0, 8).toUpperCase()}`, generatedAt: new Date().toISOString(), parcelId: `AG-${shipment.orderNumber}-${row.id.slice(-6).toUpperCase()}`, shipment }; if (recordGeneration) { await this.client.shipmentEvent.create({ data: { shipmentId, status: row.status, description: "Parcel label generated", providerPayload: json({ labelId: label.labelId }), occurredAt: new Date() } }); await this.audit(session, "logistics.label.generated", "shipment", shipmentId, null, { labelId: label.labelId }); } return label; }

  async dispatchManifest(session: Session) { requireOperator(session); const shipments = (await this.client.shipment.findMany({ where: { status: { in: ["READY_TO_SHIP", "PICKED_UP"] } }, include: shipmentInclude, orderBy: { updatedAt: "desc" }, take: 500 })).map(shipmentDto); const groups = new Map<string, typeof shipments>(); for (const shipment of shipments) { const courier = shipment.assignment?.courierPartner?.name ?? shipment.provider ?? "Unassigned"; groups.set(courier, [...(groups.get(courier) ?? []), shipment]); } return { generatedAt: new Date().toISOString(), totalShipments: shipments.length, totalCodMinor: shipments.reduce((sum, row) => sum + BigInt(row.codAmountMinor), 0n).toString(), groups: [...groups].map(([courierName, rows], index) => ({ id: `manifest-${index + 1}`, courierName, shipmentIds: rows.map((row) => row.id), shipmentCount: rows.length, codAmountMinor: rows.reduce((sum, row) => sum + BigInt(row.codAmountMinor), 0n).toString(), shipments: rows })) }; }
  async confirmManifestPickup(session: Session, manifestId: string, input: LogisticsManifestPickup) { requireOperator(session, true); const shipments = await this.client.shipment.findMany({ where: { id: { in: input.shipmentIds } } }); if (shipments.length !== input.shipmentIds.length) throw new ApiProblem(404, "MANIFEST_SHIPMENT_NOT_FOUND", "One or more manifest shipments were not found"); if (shipments.some((row) => row.status !== "READY_TO_SHIP")) throw new ApiProblem(409, "MANIFEST_PICKUP_INVALID", "Every manifest parcel must be ready to ship"); await this.client.shipment.updateMany({ where: { id: { in: input.shipmentIds }, status: "READY_TO_SHIP" }, data: { status: "PICKED_UP", shippedAt: new Date() } }); await this.client.shipmentEvent.createMany({ data: input.shipmentIds.map((shipmentId) => ({ shipmentId, status: "PICKED_UP" as const, description: input.note, providerPayload: json({ manifestId }), occurredAt: new Date() })) }); await this.audit(session, "logistics.manifest.pickup_confirmed", "dispatch_manifest", manifestId, null, input); return { manifestId, status: "PICKED_UP", shipmentCount: input.shipmentIds.length }; }

  async reverseReturnAction(session: Session, returnId: string, action: string, input: LogisticsReturnAction) { requireOperator(session, true); const rule = reverseTransitions[action]; if (!rule) throw new ApiProblem(400, "RETURN_LOGISTICS_ACTION_INVALID", "Unsupported reverse logistics action"); const current = await this.client.return.findUnique({ where: { id: returnId } }); if (!current) throw new ApiProblem(404, "RETURN_NOT_FOUND", "Return not found"); if (!rule.allowed.includes(current.status)) throw new ApiProblem(409, "RETURN_LOGISTICS_TRANSITION_INVALID", `Cannot apply ${action} while return is ${current.status}`); const metadata = json({ logisticsState: action, trackingNumber: input.trackingNumber, pickupAt: input.pickupAt, inspection: input.inspection }); const row = await this.client.return.update({ where: { id: returnId }, data: { status: rule.status, version: { increment: 1 }, events: { create: { fromStatus: current.status, toStatus: rule.status, actorType: "admin", actorId: session.principal.userId, note: input.note, metadata } } } }); await this.audit(session, `logistics.return.${action}`, "return", returnId, { status: current.status }, { status: rule.status, ...input }); return { ...row, requestedMinor: row.requestedMinor.toString(), approvedMinor: row.approvedMinor?.toString() ?? null, createdAt: row.createdAt.toISOString(), updatedAt: row.updatedAt.toISOString() }; }

  async recordCodRemittance(session: Session, input: CodRemittanceInput) { requireOperator(session, true); const row = await this.client.codRemittance.create({ data: { courierPartnerId: input.courierPartnerId, courierName: input.courierName, collectedAmountMinor: BigInt(input.collectedAmountMinor), remittedAmountMinor: BigInt(input.remittedAmountMinor), forwardedToVendorMinor: BigInt(input.forwardedToVendorMinor), reference: input.reference, notes: input.notes, orderIds: json(input.orderIds), createdBy: session.principal.userId } }); await this.audit(session, "logistics.cod_remittance.recorded", "cod_remittance", row.id, null, row); return this.remittanceDto(row); }
  async scheduleReattempt(session: Session, shipmentId: string, input: FailedDeliveryReattempt) { requireOperator(session, true); const row = await this.client.failedDeliveryRecord.update({ where: { shipmentId }, data: { nextAttemptAt: new Date(input.nextAttemptAt), redeliveryFeeMinor: BigInt(input.redeliveryFeeMinor), reason: input.reason, note: input.note, resolution: "reattempt_scheduled" } }); await this.client.shipment.update({ where: { id: shipmentId }, data: { status: "READY_TO_SHIP", events: { create: { status: "READY_TO_SHIP", description: input.reason, occurredAt: new Date() } } } }); await this.audit(session, "logistics.failed_delivery.reattempt_scheduled", "shipment", shipmentId, null, row); return row; }
  async returnToSeller(session: Session, shipmentId: string, input: FailedDeliveryReturn) { requireOperator(session, true); const row = await this.client.failedDeliveryRecord.update({ where: { shipmentId }, data: { returnFeeMinor: BigInt(input.returnFeeMinor), reason: input.reason, note: input.note, resolution: "return_to_seller" } }); await this.client.shipment.update({ where: { id: shipmentId }, data: { status: "CANCELLED", events: { create: { status: "CANCELLED", description: input.reason, occurredAt: new Date() } } } }); await this.audit(session, "logistics.failed_delivery.return_to_seller", "shipment", shipmentId, null, row); return row; }

  private feeRuleDto(row: Awaited<ReturnType<PrismaClient["deliveryFeeRule"]["findFirstOrThrow"]>>) { return { ...row, minOrderAmountMinor: row.minOrderAmountMinor.toString(), maxOrderAmountMinor: row.maxOrderAmountMinor.toString(), baseFeeMinor: row.baseFeeMinor.toString(), perItemFeeMinor: row.perItemFeeMinor.toString(), feePerKgMinor: row.feePerKgMinor.toString(), codFeeMinor: row.codFeeMinor.toString(), redeliveryFeeMinor: row.redeliveryFeeMinor.toString(), freeShippingThreshold: row.freeShippingThreshold.toString() }; }
  private remittanceDto(row: { id: string; courierPartnerId: string | null; courierName: string; collectedAmountMinor: bigint; remittedAmountMinor: bigint; forwardedToVendorMinor: bigint; reference: string | null; notes: string | null; orderIds: Prisma.JsonValue; createdBy: string; createdAt: Date; courierPartner?: unknown }) { return { ...row, collectedAmountMinor: row.collectedAmountMinor.toString(), remittedAmountMinor: row.remittedAmountMinor.toString(), forwardedToVendorMinor: row.forwardedToVendorMinor.toString(), createdAt: row.createdAt.toISOString() }; }
}
