import type { LegacyDocument, TargetRow } from "./types.js";
import { dateString, decimalToMinor, deterministicUuid, legacyId, optionalString, requiredString, slug } from "./normalization.js";

const now = new Date("2000-01-01T00:00:00.000Z");
const id = (collection: string, value: unknown, suffix = "") => deterministicUuid(collection, legacyId(value), suffix);
const legacyTables = new Set(["users", "categories", "vendors", "vendor_shops", "products", "orders", "returns"]);
const row = (sourceCollection: string, sourceId: string, targetTable: string, targetId: string, data: Record<string, unknown>): TargetRow => ({ sourceCollection, legacyId: sourceId, targetTable, targetId, data: { id: targetId, ...(legacyTables.has(targetTable) ? { legacyId: sourceId } : {}), ...data } });
const userStatus = (value: unknown) => ({ active: "ACTIVE", suspended: "SUSPENDED", deactivated: "DEACTIVATED", anonymized: "ANONYMIZED" })[String(value || "active").toLowerCase()] || "ACTIVE";
const vendorStatus = (value: unknown) => ({ pending: "PENDING", approved: "APPROVED", rejected: "REJECTED", suspended: "SUSPENDED" })[String(value || "pending").toLowerCase()] || "PENDING";
const orderStatus = (value: unknown) => ({ pending: "PENDING_PAYMENT", processing: "PROCESSING", packed: "PROCESSING", ready_to_ship: "READY_TO_SHIP", shipped: "SHIPPED", delivered: "DELIVERED", cancelled: "CANCELLED", returned: "RETURNED", refunded: "REFUNDED" })[String(value || "pending").toLowerCase()] || "PENDING_PAYMENT";
const paymentStatus = (value: unknown) => ({ pending: "INITIATED", processing: "REQUIRES_ACTION", pending_verification: "REQUIRES_ACTION", completed: "CAPTURED", captured: "CAPTURED", failed: "FAILED", refunded: "REFUNDED", cancelled: "CANCELLED" })[String(value || "pending").toLowerCase()] || "INITIATED";
const roleName = (value: unknown) => ({ customer: "CUSTOMER", vendor: "VENDOR_OWNER", vendor_owner: "VENDOR_OWNER", vendor_manager: "VENDOR_MANAGER", vendor_staff: "VENDOR_STAFF", support: "SUPPORT_AGENT", support_agent: "SUPPORT_AGENT", finance_admin: "FINANCE_ADMIN", operations_admin: "OPERATIONS_ADMIN", admin: "SUPER_ADMIN", super_admin: "SUPER_ADMIN" })[String(value || "customer").toLowerCase()] || "CUSTOMER";

export const migrationOrder = ["users", "categories", "vendors", "products", "orders", "payments"] as const;

export function mapDocument(collection: string, document: LegacyDocument): TargetRow[] {
  const sourceId = legacyId(document._id); const createdAt = dateString(document.createdAt, now); const updatedAt = dateString(document.updatedAt, new Date(createdAt));
  if (collection === "users") { const userId = id(collection, document._id); const profile = document.profile && typeof document.profile === "object" && !Array.isArray(document.profile) ? document.profile as LegacyDocument : {}; return [row(collection, sourceId, "users", userId, { providerSubject: requiredString(document.firebaseUid, "firebaseUid"), normalizedEmail: optionalString(document.email)?.toLowerCase() ?? null, normalizedPhone: optionalString(profile.phone), status: userStatus(document.status), createdAt, updatedAt }), { sourceCollection: collection, legacyId: sourceId, targetTable: "user_profiles", targetId: userId, data: { userId, firstName: optionalString(profile.firstName), lastName: optionalString(profile.lastName), displayName: optionalString(document.displayName), locale: "en", currency: "BDT", createdAt, updatedAt } }, { sourceCollection: collection, legacyId: sourceId, targetTable: "user_roles", targetId: deterministicUuid(collection, sourceId, "role"), data: { userId, roleName: roleName(document.role), assignedAt: createdAt } }]; }
  if (collection === "categories") { return [row(collection, sourceId, "categories", id(collection, document._id), { parentId: document.parentId ? id(collection, document.parentId) : null, name: requiredString(document.name, "name"), slug: slug(document.slug, requiredString(document.name, "name")), status: document.isActive === false ? "inactive" : "active", displayOrder: Number(document.displayOrder || 0), commissionRateBps: Math.round(Number(document.commissionRate || 0) * 100), createdAt, updatedAt })]; }
  if (collection === "vendors") { const vendorId = id(collection, document._id); const owner = id("users", document.ownerUserId); const shopId = deterministicUuid(collection, sourceId, "shop"); const name = requiredString(document.shopName || document.businessName, "shopName/businessName"); return [row(collection, sourceId, "vendors", vendorId, { legalName: requiredString(document.businessName || name, "businessName"), displayName: name, status: vendorStatus(document.status), createdAt, updatedAt }), { sourceCollection: collection, legacyId: sourceId, targetTable: "vendor_members", targetId: deterministicUuid(collection, sourceId, "owner"), data: { id: deterministicUuid(collection, sourceId, "owner"), vendorId, userId: owner, role: "VENDOR_OWNER", status: "active", createdAt } }, { sourceCollection: collection, legacyId: sourceId, targetTable: "vendor_shops", targetId: shopId, data: { id: shopId, legacyId: sourceId, vendorId, name, slug: slug(document.slug, name), status: vendorStatus(document.status) === "APPROVED" ? "ACTIVE" : "DRAFT", description: optionalString(document.description), createdAt, updatedAt } }]; }
  if (collection === "products") { const productId = id(collection, document._id); const vendorId = id("vendors", document.vendorId); const categoryId = id("categories", document.categoryId); const shopId = deterministicUuid("vendors", legacyId(document.vendorId), "shop"); const variantId = deterministicUuid(collection, sourceId, "default-variant"); const priceMinor = decimalToMinor(document.price, "price"); const stock = Number(document.stock || 0); if (!Number.isInteger(stock) || stock < 0) throw new Error("Invalid stock"); return [row(collection, sourceId, "products", productId, { vendorId, shopId, categoryId, name: requiredString(document.title || document.name, "title/name"), slug: slug(document.slug, `${document.title || document.name}-${sourceId}`), description: optionalString(document.description), brand: optionalString(document.brand), status: String(document.approvalStatus || "approved").toLowerCase() === "approved" && document.isActive !== false ? "APPROVED" : "DRAFT", createdAt, updatedAt }), { sourceCollection: collection, legacyId: sourceId, targetTable: "product_variants", targetId: variantId, data: { id: variantId, productId, sku: requiredString(document.sku || `LEGACY-${sourceId}`, "sku"), title: "Default", priceMinor, currency: "BDT", active: document.isActive !== false, createdAt, updatedAt } }, { sourceCollection: collection, legacyId: sourceId, targetTable: "inventory_items", targetId: deterministicUuid(collection, sourceId, "inventory"), data: { id: deterministicUuid(collection, sourceId, "inventory"), variantId, onHand: stock, reserved: 0, version: 1, updatedAt } }]; }
  if (collection === "orders") { const orderId = id(collection, document._id); const totalMinor = decimalToMinor(document.total, "total"); const subtotalMinor = decimalToMinor(document.subtotal ?? document.total, "subtotal"); const products = Array.isArray(document.products) ? document.products as LegacyDocument[] : []; if (!products.length) throw new Error("Order has no products"); const vendorIds = [...new Set(products.map((product) => legacyId(product.vendorId)))]; const rows: TargetRow[] = [row(collection, sourceId, "orders", orderId, { orderNumber: requiredString(document.orderNumber || sourceId, "orderNumber"), userId: document.userId ? id("users", document.userId) : null, status: orderStatus(document.status), currency: "BDT", subtotalMinor, discountMinor: decimalToMinor(document.discount || 0, "discount"), deliveryMinor: decimalToMinor(document.deliveryFee || 0, "deliveryFee"), taxMinor: decimalToMinor(document.tax || 0, "tax"), totalMinor, placedAt: createdAt, createdAt, updatedAt })]; for (const vendorLegacyId of vendorIds) { const vendorOrderId = deterministicUuid(collection, sourceId, `vendor:${vendorLegacyId}`); const vendorProducts = products.filter((product) => legacyId(product.vendorId) === vendorLegacyId); const vendorSubtotal = vendorProducts.reduce((sum, product) => sum + BigInt(decimalToMinor(product.price, "product price")) * BigInt(Number(product.quantity || 1)), 0n); rows.push({ sourceCollection: collection, legacyId: sourceId, targetTable: "vendor_orders", targetId: vendorOrderId, data: { id: vendorOrderId, orderId, vendorId: id("vendors", vendorLegacyId), shopId: deterministicUuid("vendors", vendorLegacyId, "shop"), status: orderStatus(document.status) === "DELIVERED" ? "DELIVERED" : "PLACED", subtotalMinor: vendorSubtotal.toString(), totalMinor: vendorSubtotal.toString(), createdAt, updatedAt } }); for (const [index, product] of vendorProducts.entries()) { const productLegacyId = legacyId(product.productId || product._id); const quantity = Number(product.quantity || 1); if (!Number.isInteger(quantity) || quantity <= 0) throw new Error("Invalid product quantity"); const unitPriceMinor = decimalToMinor(product.price, "product price"); rows.push({ sourceCollection: collection, legacyId: sourceId, targetTable: "order_items", targetId: deterministicUuid(collection, sourceId, `item:${vendorLegacyId}:${index}`), data: { id: deterministicUuid(collection, sourceId, `item:${vendorLegacyId}:${index}`), orderId, vendorOrderId, productId: id("products", productLegacyId), variantId: deterministicUuid("products", productLegacyId, "default-variant"), productNameSnapshot: requiredString(product.title || product.name, "product title"), skuSnapshot: requiredString(product.sku || `LEGACY-${productLegacyId}`, "sku"), quantity, unitPriceMinor, lineTotalMinor: (BigInt(unitPriceMinor) * BigInt(quantity)).toString(), currency: "BDT" } }); } } return rows; }
  if (collection === "payments") { const amountMinor = decimalToMinor(document.amount, "amount"); return [row(collection, sourceId, "payments", id(collection, document._id), { orderId: id("orders", document.orderId), provider: String(document.provider || document.paymentMethod || "legacy").toLowerCase(), method: String(document.paymentMethod || "manual").toUpperCase(), status: paymentStatus(document.status), amountMinor, refundedMinor: decimalToMinor(document.refundedAmount || 0, "refundedAmount"), currency: String(document.currency || "BDT").toUpperCase(), providerTransactionId: optionalString(document.transactionId || document.stripePaymentId), createdAt, updatedAt })]; }
  throw new Error(`Unsupported collection ${collection}`);
}
