import { Ionicons } from "@expo/vector-icons";
import { useQuery } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { getGrowthFeed } from "./engagement.api";

const money = (minor: string) => `৳${(Number(minor) / 100).toLocaleString("en-BD")}`;

export function CampaignScreen({ slug }: { slug: string }) {
  const router = useRouter();
  const query = useQuery({ queryKey: ["growth", "feed"], queryFn: getGrowthFeed });
  const item = query.data?.campaigns.find((campaign) => campaign.slug === slug);
  if (query.isLoading) return <OfferLoading title="Loading campaign" />;
  if (query.error || !item) return <OfferMissing copy={query.error instanceof Error ? query.error.message : "This campaign is no longer available."} onPress={() => router.replace("/")} />;
  return <Screen eyebrow="LIMITED CAMPAIGN" title={item.name} description="Explore the live marketplace selection included in this campaign."><View style={styles.hero}><View style={styles.heroIcon}><Ionicons color={colors.surface} name="megaphone" size={29} /></View><View style={styles.flex}><Text accessibilityRole="header" style={styles.heroTitle}>Campaign is live</Text><Text style={styles.heroCopy}>Available until {new Date(item.endsAt).toLocaleString("en-BD")}</Text></View></View><View style={styles.info}><Info icon="calendar-outline" label="Started" value={new Date(item.startsAt).toLocaleDateString("en-BD")} /><Info icon="time-outline" label="Ends" value={new Date(item.endsAt).toLocaleDateString("en-BD")} /></View><Pressable accessibilityRole="link" onPress={() => router.push(item.href as never)} style={styles.primary}><Text style={styles.primaryText}>Explore campaign products</Text><Ionicons color={colors.surface} name="arrow-forward" size={18} /></Pressable></Screen>;
}

export function FlashSaleScreen({ id }: { id: string }) {
  const router = useRouter();
  const query = useQuery({ queryKey: ["growth", "feed"], queryFn: getGrowthFeed });
  const item = query.data?.flashSales.find((sale) => sale.id === id);
  if (query.isLoading) return <OfferLoading title="Loading flash sale" />;
  if (query.error || !item) return <OfferMissing copy={query.error instanceof Error ? query.error.message : "This flash sale has ended or is unavailable."} onPress={() => router.replace("/")} />;
  return <Screen eyebrow="FLASH SALE" title={item.name} description={`Live offer ends ${new Date(item.endsAt).toLocaleString("en-BD")}.`}><View style={styles.heroSale}><View style={styles.heroIconSale}><Ionicons color={colors.surface} name="flash" size={29} /></View><View style={styles.flex}><Text accessibilityRole="header" style={styles.heroTitle}>Limited-time prices</Text><Text style={styles.heroCopy}>{item.products.length} product{item.products.length === 1 ? "" : "s"} currently included</Text></View></View>{item.products.length ? <View style={styles.grid}>{item.products.map((product) => <View key={product.productId} style={styles.card}><View style={styles.productIcon}><Ionicons color={colors.accent} name="flash-outline" size={26} /></View><Text style={styles.cardLabel}>FLASH PRICE</Text><Text style={styles.price}>{money(product.price.amountMinor)}</Text><Text style={styles.stock}>{product.quantityRemaining === null ? "Available while stocks last" : `${product.quantityRemaining} remaining`}</Text><Pressable accessibilityRole="link" onPress={() => router.push(`/product/${product.productId}` as never)} style={styles.cardButton}><Text style={styles.cardButtonText}>View deal</Text><Ionicons color={colors.primary} name="arrow-forward" size={16} /></Pressable></View>)}</View> : <View style={styles.empty}><Ionicons color={colors.primary} name="hourglass-outline" size={45} /><Text style={styles.emptyTitle}>Deals are being prepared</Text></View>}</Screen>;
}

function Info({ icon, label, value }: { icon: string; label: string; value: string }) { return <View style={styles.infoCard}><Ionicons color={colors.primary} name={icon as never} size={22} /><View><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View></View>; }
function OfferLoading({ title }: { title: string }) { return <Screen eyebrow="SPECIAL OFFER" title={title} description="Fetching live offer availability."><View style={styles.empty}><ActivityIndicator color={colors.primary} size="large" /></View></Screen>; }
function OfferMissing({ copy, onPress }: { copy: string; onPress: () => void }) { return <Screen eyebrow="SPECIAL OFFER" title="Offer unavailable" description={copy}><View style={styles.empty}><Ionicons color={colors.primary} name="pricetag-outline" size={48} /><Pressable onPress={onPress} style={styles.primary}><Text style={styles.primaryText}>Browse current offers</Text></Pressable></View></Screen>; }

const styles = StyleSheet.create({ flex: { flex: 1 }, hero: { alignItems: "center", backgroundColor: colors.navy, borderRadius: radius.xl, flexDirection: "row", gap: spacing.md, padding: spacing.xl }, heroSale: { alignItems: "center", backgroundColor: "#7c2d12", borderRadius: radius.xl, flexDirection: "row", gap: spacing.md, padding: spacing.xl }, heroIcon: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.lg, height: 58, justifyContent: "center", width: 58 }, heroIconSale: { alignItems: "center", backgroundColor: colors.accent, borderRadius: radius.lg, height: 58, justifyContent: "center", width: 58 }, heroTitle: { color: colors.surface, fontSize: 22, fontWeight: "700" }, heroCopy: { color: "#e2e8f0", marginTop: 4 }, info: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md }, infoCard: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, flexDirection: "row", flexGrow: 1, gap: spacing.md, minWidth: 220, padding: spacing.lg }, infoLabel: { color: colors.muted, fontSize: 11 }, infoValue: { color: colors.text, fontWeight: "700", marginTop: 3 }, primary: { alignItems: "center", alignSelf: "flex-start", backgroundColor: colors.primary, borderRadius: radius.md, flexDirection: "row", gap: spacing.sm, minHeight: 48, paddingHorizontal: spacing.lg }, primaryText: { color: colors.surface, fontWeight: "700" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.md }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.lg, borderWidth: 1, flexGrow: 1, gap: spacing.sm, maxWidth: 330, minWidth: 230, padding: spacing.lg }, productIcon: { alignItems: "center", backgroundColor: "#fff7ed", borderRadius: radius.md, height: 50, justifyContent: "center", width: 50 }, cardLabel: { color: colors.accent, fontSize: 10, fontWeight: "700", letterSpacing: 1 }, price: { color: colors.text, fontSize: 26, fontWeight: "700" }, stock: { color: colors.muted }, cardButton: { alignItems: "center", borderTopColor: colors.border, borderTopWidth: 1, flexDirection: "row", gap: 6, justifyContent: "space-between", marginTop: spacing.sm, paddingTop: spacing.md }, cardButtonText: { color: colors.primary, fontWeight: "700" }, empty: { alignItems: "center", backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.xl, borderStyle: "dashed", borderWidth: 1, gap: spacing.lg, padding: 44 }, emptyTitle: { color: colors.text, fontSize: 20, fontWeight: "700" } });
