import { Ionicons } from "@expo/vector-icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useRouter } from "expo-router";
import { ActivityIndicator, Pressable, Share, StyleSheet, Text, View } from "react-native";
import { ModuleCard } from "../../ui/ModuleCard";
import { Screen } from "../../ui/Screen";
import { colors, radius, spacing } from "../../ui/tokens";
import { firebaseAuth } from "../auth/firebase";
import { getWishlist, removeWishlistItem, shareWishlist, unshareWishlist } from "./engagement.api";

const money = (minor: string) => `৳${(Number(minor) / 100).toLocaleString("en-BD")}`;

export function WishlistScreen() {
  const router = useRouter(); const cache = useQueryClient(); const user = firebaseAuth?.currentUser;
  const query = useQuery({ queryKey: ["wishlist"], queryFn: () => getWishlist(user!), enabled: Boolean(user) });
  const updateShare = useMutation({ mutationFn: () => query.data?.shareUrl ? unshareWishlist(user!) : shareWishlist(user!), onSuccess: (data) => cache.setQueryData(["wishlist"], data) });
  const remove = useMutation({ mutationFn: (productId: string) => removeWishlistItem(user!, productId), onSuccess: (data) => cache.setQueryData(["wishlist"], data) });
  async function openShare() { if (!query.data?.shareUrl) return; await Share.share({ title: "My Amiyo-Go wishlist", message: `See my Amiyo-Go wishlist: ${query.data.shareUrl}`, url: query.data.shareUrl }); }
  return <Screen eyebrow="SAVED ITEMS" title="My wishlist" description="Save products, create a private 30-day link, and revoke access whenever you want.">{query.isLoading ? <ActivityIndicator color={colors.primary} /> : null}{query.error ? <Text style={styles.error}>{query.error.message}</Text> : null}{query.data ? <><View style={styles.shareCard}><View style={styles.shareHeading}><Ionicons color={colors.primary} name={query.data.shareUrl ? "globe-outline" : "lock-closed-outline"} size={25} /><View style={styles.flex}><Text style={styles.shareTitle}>{query.data.shareUrl ? "Sharing is active" : "Wishlist is private"}</Text><Text style={styles.muted}>{query.data.shareUrl ? "Anyone with the current link can view it for up to 30 days." : "Generate a link only when you are ready to share."}</Text></View></View>{query.data.shareUrl ? <Text selectable style={styles.url}>{query.data.shareUrl}</Text> : null}<View style={styles.actions}>{query.data.shareUrl ? <Pressable onPress={openShare} style={styles.primary}><Ionicons color="#fff" name="share-social-outline" size={18} /><Text style={styles.primaryText}>Share link</Text></Pressable> : null}<Pressable disabled={updateShare.isPending} onPress={() => updateShare.mutate()} style={styles.secondary}><Text style={styles.secondaryText}>{query.data.shareUrl ? "Revoke link" : "Generate share link"}</Text></Pressable></View>{updateShare.error ? <Text style={styles.error}>{updateShare.error.message}</Text> : null}</View>{query.data.items.map((item) => <ModuleCard key={item.productId} title={item.name} meta={item.price ? money(item.price.amountMinor) : "Unavailable"}><View style={styles.actions}><Pressable accessibilityRole="link" onPress={() => router.push(`/product/${item.slug}` as never)} style={styles.primary}><Text style={styles.primaryText}>View product</Text></Pressable><Pressable accessibilityRole="button" disabled={remove.isPending} onPress={() => remove.mutate(item.productId)} style={styles.secondary}><Text style={styles.dangerText}>Remove</Text></Pressable></View></ModuleCard>)}{query.data.items.length === 0 ? <ModuleCard title="Your wishlist is empty" meta="Save products from any product detail page." /> : null}</> : null}</Screen>;
}

const styles = StyleSheet.create({ shareCard: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.xl, borderWidth: 1, gap: spacing.md, padding: spacing.lg }, shareHeading: { alignItems: "flex-start", flexDirection: "row", gap: spacing.md }, flex: { flex: 1 }, shareTitle: { color: colors.text, fontSize: 18, fontWeight: "900" }, muted: { color: colors.muted, lineHeight: 20, marginTop: 3 }, url: { backgroundColor: colors.primarySoft, borderRadius: radius.md, color: colors.primaryDark, fontSize: 12, padding: spacing.md }, actions: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: radius.md, flexDirection: "row", gap: 6, justifyContent: "center", minHeight: 42, paddingHorizontal: spacing.md }, primaryText: { color: "#fff", fontWeight: "900" }, secondary: { alignItems: "center", borderColor: colors.border, borderRadius: radius.md, borderWidth: 1, justifyContent: "center", minHeight: 42, paddingHorizontal: spacing.md }, secondaryText: { color: colors.text, fontWeight: "900" }, dangerText: { color: colors.danger, fontWeight: "900" }, error: { color: colors.danger } });
